import OAI.AlgebraicTopology.IntegralHomology.Subdivision
import Mathlib.Algebra.Homology.QuasiIso

namespace OAI

noncomputable section

namespace Kaplansky

/-! Eventual smallness of generators and chains and comparison on homology. -/

section
open CategoryTheory Limits AlgebraicTopology Simplicial

section
variable {X : Type} [TopologicalSpace X] (U V : Set X)

/-- Every actual singular simplex becomes a chain of small simplices after
sufficiently many applications of the constructed subdivision operator. -/
theorem singularGen_eventually_small (hU : IsOpen U) (hV : IsOpen V)
    (hUV : U ∪ V = Set.univ) {n : ℕ}
    (σ : (TopCat.toSSet.obj (TopCat.of X)) _⦋n⦌) :
    ∃ N : ℕ, ∀ k ≥ N, (singularSubdivisionMap (TopCat.of X) n)^[k]
      (singularGen σ (1 : ℤ)) ∈ LinearMap.range ((smallSingularChainInclusion U V).f n).hom := by
  let c : ℝ := (n : ℝ)/(n+1)
  obtain ⟨N, hN⟩ := finite_continuousMaps_eventually_small ({()} : Finset Unit)
    (fun _ : Unit => TopCat.toSSetObjEquiv (TopCat.of X) _ σ)
    U V hU hV hUV 1 c (by positivity) (simplexMeshFactor_lt_one n)
  refine ⟨N, fun k hk => ?_⟩
  rw [singularSubdivision_iterate_gen]
  let L := (simplexAffineChains n).f n ≫ (integralSingularChains.map (singularSimplexTopMap σ)).f n
  have hspan : tupleMeshSpan n (c^k) ≤
      (LinearMap.range ((smallSingularChainInclusion U V).f n).hom).comap L.hom := by
    apply Submodule.span_le.mpr
    rintro a ⟨v, hv, rfl⟩
    change L.hom (tupleGen v (1 : ℤ)) ∈ LinearMap.range ((smallSingularChainInclusion U V).f n).hom
    dsimp only [L]
    change (tupleGen v ≫ (simplexAffineChains n).f n ≫
      (integralSingularChains.map (singularSimplexTopMap σ)).f n) (1 : ℤ) ∈ LinearMap.range ((smallSingularChainInclusion U V).f n).hom
    rw [tupleGen_affine_assoc, singularGen_map]
    apply small_singularGen_mem_range
    rw [mem_smallSingularSet_iff]
    have hmesh : ∀ a ∈ Set.range (simplexCombination v), ∀ b ∈ Set.range (simplexCombination v),
        dist a b ≤ 1 * c^k := by
      rintro _ ⟨s, rfl⟩ _ ⟨t, rfl⟩
      simpa only [one_mul] using simplexCombination_pair_dist_le v s t (c^k) hv
    have h := hN k hk () (Finset.mem_singleton_self ()) _ hmesh
    rcases h with h | h
    · left
      intro p
      exact h _ ⟨p.down, rfl⟩
    · right
      intro p
      exact h _ ⟨p.down, rfl⟩
  exact hspan (universalTupleSubdivision_mesh n k)

end

/-- Every singular chain is generated by finitely many integral simplex generators.
This uses the actual coproduct universal property, with no support premise. -/
theorem singularChain_submodule_eq_top {X : TopCat.{0}} (n : ℕ)
    (S : Submodule ℤ ((integralSingularChains.obj X).X n))
    (hS : ∀ σ : (TopCat.toSSet.obj X) _⦋n⦌, singularGen σ (1 : ℤ) ∈ S) : S = ⊤ := by
  let : Module ℤ (((integralSingularChains.obj X).X n) ⧸ S) := Submodule.Quotient.module S
  let q : (integralSingularChains.obj X).X n ⟶ ModuleCat.of ℤ (((integralSingularChains.obj X).X n) ⧸ S) := ModuleCat.ofHom S.mkQ
  have hq : q = 0 := by
    apply SSet.chainComplex_hom_ext
    intro σ
    apply ModuleCat.hom_ext
    apply LinearMap.ext_ring
    change S.mkQ (singularGen σ (1 : ℤ)) = 0
    exact (Submodule.Quotient.mk_eq_zero S).mpr (hS σ)
  apply top_unique
  intro a ha
  apply (Submodule.Quotient.mk_eq_zero S).mp
  exact ConcreteCategory.congr_hom hq a

variable {X : Type} [TopologicalSpace X] (U V : Set X)

/-- Chains whose iterated subdivisions eventually lie in the actual image
of the small-chain inclusion. -/
def eventuallySmallChains (n : ℕ) : Submodule ℤ ((integralSingularChains.obj (TopCat.of X)).X n) where
  carrier := {a | ∃ N : ℕ, ∀ k ≥ N, (singularSubdivisionMap (TopCat.of X) n)^[k] a ∈
    LinearMap.range ((smallSingularChainInclusion U V).f n).hom}
  zero_mem' := by
    refine ⟨0, fun k hk => ?_⟩
    rw [← Module.End.pow_apply ((singularSubdivisionMap (TopCat.of X) n).hom)]
    rw [map_zero]
    exact Submodule.zero_mem _
  add_mem' := by
    rintro a b ⟨N, hN⟩ ⟨M, hM⟩
    refine ⟨max N M, fun k hk => ?_⟩
    rw [← Module.End.pow_apply ((singularSubdivisionMap (TopCat.of X) n).hom)]
    rw [map_add]
    simp only [Module.End.pow_apply]
    exact Submodule.add_mem _ (hN k ((le_max_left N M).trans hk)) (hM k ((le_max_right N M).trans hk))
  smul_mem' := by
    rintro r a ⟨N, hN⟩
    refine ⟨N, fun k hk => ?_⟩
    rw [← Module.End.pow_apply ((singularSubdivisionMap (TopCat.of X) n).hom)]
    rw [((singularSubdivisionMap (TopCat.of X) n).hom ^ k).map_smul]
    simp only [Module.End.pow_apply]
    exact Submodule.smul_mem _ r (hN k hk)

/-- The actual open-cover smallness theorem for every finite singular chain. -/
theorem singularChain_eventually_small (hU : IsOpen U) (hV : IsOpen V)
    (hUV : U ∪ V = Set.univ) (n : ℕ)
    (a : (integralSingularChains.obj (TopCat.of X)).X n) :
    ∃ N : ℕ, ∀ k ≥ N, (singularSubdivisionMap (TopCat.of X) n)^[k] a ∈
      LinearMap.range ((smallSingularChainInclusion U V).f n).hom := by
  have h : eventuallySmallChains U V n = ⊤ :=
    singularChain_submodule_eq_top n _ (fun σ => singularGen_eventually_small U V hU hV hUV σ)
  change a ∈ eventuallySmallChains U V n
  rw [h]
  trivial

end

section
open CategoryTheory Limits HomologicalComplex

theorem chainNext_nat (n : ℕ) : (ComplexShape.down ℕ).next n = n-1 := by
  cases n <;> simp only [ChainComplex.next_nat_zero, ChainComplex.next_nat_succ, Nat.zero_sub, Nat.add_sub_cancel]

/-- An actual cycle represented by its underlying chain. -/
def chainCycle (K : ChainComplex (ModuleCat.{0} ℤ) ℕ) (n : ℕ)
    (a : K.X n) (ha : K.d n (n-1) a = 0) : K.cycles n :=
  (K.sc n).moduleCatCyclesIso.inv ⟨a, by
    change K.d n ((ComplexShape.down ℕ).next n) a = 0
    rwa [chainNext_nat]⟩

@[simp]
theorem chainCycle_i (K : ChainComplex (ModuleCat.{0} ℤ) ℕ) (n : ℕ)
    (a : K.X n) (ha : K.d n (n-1) a = 0) :
    K.iCycles n (chainCycle K n a ha) = a := by
  exact (K.sc n).moduleCatCyclesIso_inv_iCycles_apply ⟨a, by
    change K.d n ((ComplexShape.down ℕ).next n) a = 0
    rwa [chainNext_nat]⟩

theorem chain_cycle_boundary_zero (K : ChainComplex (ModuleCat.{0} ℤ) ℕ) (n : ℕ)
    (z : K.cycles n) : K.d n (n-1) (K.iCycles n z) = 0 :=
  ConcreteCategory.congr_hom (K.iCycles_d n (n-1)) z

/-- A homology class is zero exactly when its representative cycle is a boundary. -/
theorem chain_homologyπ_eq_zero_iff (K : ChainComplex (ModuleCat.{0} ℤ) ℕ) (n : ℕ)
    (z : K.cycles n) : K.homologyπ n z = 0 ↔
      ∃ b : K.X (n+1), K.d (n+1) n b = K.iCycles n z := by
  have hi := (ModuleCat.mono_iff_injective (K.homologyι n)).mp inferInstance
  rw [← hi.eq_iff, map_zero]
  change ((K.homologyπ n ≫ K.homologyι n) z = 0) ↔ _
  rw [K.homology_π_ι]
  have h := (K.sc n).moduleCat_pOpcycles_eq_zero_iff (K.iCycles n z)
  change (K.pOpcycles n (K.iCycles n z) = 0) ↔
    ∃ b : K.X ((ComplexShape.down ℕ).prev n), K.d _ n b = K.iCycles n z at h
  rw [ChainComplex.prev ℕ n] at h
  exact h

@[simp]
theorem chain_cyclesMap_i {P Q : ChainComplex (ModuleCat.{0} ℤ) ℕ} (f : P ⟶ Q)
    (n : ℕ) (z : P.cycles n) :
    Q.iCycles n (cyclesMap f n z) = f.f n (P.iCycles n z) :=
  ConcreteCategory.congr_hom (cyclesMap_i f n) z

@[simp]
theorem chain_homologyMap_π {P Q : ChainComplex (ModuleCat.{0} ℤ) ℕ} (f : P ⟶ Q)
    (n : ℕ) (z : P.cycles n) :
    homologyMap f n (P.homologyπ n z) = Q.homologyπ n (cyclesMap f n z) :=
  ConcreteCategory.congr_hom (homologyπ_naturality f n) z

/-- Iterates of an actual chain endomorphism. -/
def chainIterate {K : ChainComplex (ModuleCat.{0} ℤ) ℕ} (s : K ⟶ K) : ℕ → (K ⟶ K)
  | 0 => 𝟙 _
  | k+1 => chainIterate s k ≫ s

@[simp]
theorem chainIterate_f_apply {K : ChainComplex (ModuleCat.{0} ℤ) ℕ} (s : K ⟶ K)
    (k n : ℕ) (a : K.X n) : (chainIterate s k).f n a = (s.f n)^[k] a := by
  induction k with
  | zero => rfl
  | succ k ih =>
    change s.f n ((chainIterate s k).f n a) = _
    rw [ih, Function.iterate_succ_apply']

theorem chainIterate_homologyMap {K : ChainComplex (ModuleCat.{0} ℤ) ℕ} (s : K ⟶ K)
    (hs : ∀ n, homologyMap s n = 𝟙 _) (k n : ℕ) :
    homologyMap (chainIterate s k) n = 𝟙 _ := by
  induction k with
  | zero => exact homologyMap_id K n
  | succ k ih => rw [chainIterate, homologyMap_comp, ih, hs, Category.id_comp]

theorem chainIterate_commute {P Q : ChainComplex (ModuleCat.{0} ℤ) ℕ}
    (f : P ⟶ Q) (s : P ⟶ P) (t : Q ⟶ Q) (h : s ≫ f = f ≫ t) (k : ℕ) :
    chainIterate s k ≫ f = f ≫ chainIterate t k := by
  induction k with
  | zero => simp only [chainIterate, Category.id_comp, Category.comp_id]
  | succ k ih => rw [chainIterate, chainIterate, Category.assoc, h, ← Category.assoc, ih, Category.assoc]

end

open CategoryTheory Limits HomologicalComplex
section

/-- A monomorphic chain comparison is a quasi-isomorphism if compatible
endomorphisms induce the identity on homology and eventually carry every
chain into its image. All premises are discharged by subdivision below. -/
theorem quasiIso_of_eventual_image
    {P Q : ChainComplex (ModuleCat.{0} ℤ) ℕ} (f : P ⟶ Q) [Mono f]
    (s : P ⟶ P) (t : Q ⟶ Q) (hcomm : s ≫ f = f ≫ t)
    (hs : ∀ n, homologyMap s n = 𝟙 _) (ht : ∀ n, homologyMap t n = 𝟙 _)
    (hevent : ∀ n (a : Q.X n), ∃ k, (chainIterate t k).f n a ∈ LinearMap.range (f.f n).hom) :
    QuasiIso f := by
  constructor
  intro n
  rw [quasiIsoAt_iff_isIso_homologyMap]
  apply (ConcreteCategory.isIso_iff_bijective _).mpr
  constructor
  · apply LinearMap.ker_eq_bot.mp
    apply LinearMap.ker_eq_bot'.mpr
    intro y hy
    obtain ⟨z, rfl⟩ := (ModuleCat.epi_iff_surjective (P.homologyπ n)).mp inferInstance y
    rw [chain_homologyMap_π] at hy
    obtain ⟨b, hb⟩ := (chain_homologyπ_eq_zero_iff Q n (cyclesMap f n z)).mp hy
    rw [chain_cyclesMap_i] at hb
    obtain ⟨k, w, hw⟩ := hevent (n+1) b
    have ha : P.d (n+1) n w = (chainIterate s k).f n (P.iCycles n z) := by
      apply (ModuleCat.mono_iff_injective (f.f n)).mp inferInstance
      have hc := ConcreteCategory.congr_hom (congrArg (fun g => g.f n)
        (chainIterate_commute f s t hcomm k)) (P.iCycles n z)
      change f.f n ((chainIterate s k).f n (P.iCycles n z)) =
        (chainIterate t k).f n (f.f n (P.iCycles n z)) at hc
      rw [hc, ← hb]
      rw [← ModuleCat.comp_apply, ← f.comm, ModuleCat.comp_apply, hw,
        ← ModuleCat.comp_apply, (chainIterate t k).comm, ModuleCat.comp_apply]
    have hz : P.homologyπ n (cyclesMap (chainIterate s k) n z) = 0 :=
      (chain_homologyπ_eq_zero_iff P n _).mpr ⟨w, by simpa using ha⟩
    rw [← chain_homologyMap_π, chainIterate_homologyMap s hs] at hz
    exact hz
  · intro y
    obtain ⟨z, rfl⟩ := (ModuleCat.epi_iff_surjective (Q.homologyπ n)).mp inferInstance y
    obtain ⟨k, a, ha⟩ := hevent n (Q.iCycles n z)
    have hda : P.d n (n-1) a = 0 := by
      apply (ModuleCat.mono_iff_injective (f.f (n-1))).mp inferInstance
      rw [map_zero, ← ModuleCat.comp_apply, ← f.comm, ModuleCat.comp_apply, ha]
      rw [← chain_cyclesMap_i]
      exact chain_cycle_boundary_zero Q n _
    let w := chainCycle P n a hda
    have hw : cyclesMap f n w = cyclesMap (chainIterate t k) n z := by
      apply (ModuleCat.mono_iff_injective (Q.iCycles n)).mp inferInstance
      rw [chain_cyclesMap_i, chain_cyclesMap_i, chainCycle_i, ha]
    refine ⟨P.homologyπ n w, ?_⟩
    rw [chain_homologyMap_π, hw, ← chain_homologyMap_π, chainIterate_homologyMap t ht]
    rfl

/-- The two-set open-cover theorem for the actual integral singular chain
complex: the inclusion of small chains is a quasi-isomorphism. -/
theorem smallSingularChainInclusion_quasiIso {X : Type} [TopologicalSpace X]
    (U V : Set X) (hU : IsOpen U) (hV : IsOpen V) (hUV : U ∪ V = Set.univ) :
    QuasiIso (smallSingularChainInclusion U V) := by
  apply quasiIso_of_eventual_image (smallSingularChainInclusion U V)
    (smallSubdivision U V) (singularSubdivision (TopCat.of X))
    (smallSubdivision_inclusion U V) (smallSubdivision_homologyMap U V)
    (singularSubdivision_homologyMap (TopCat.of X))
  intro n a
  obtain ⟨N, hN⟩ := singularChain_eventually_small U V hU hV hUV n a
  refine ⟨N, ?_⟩
  rw [chainIterate_f_apply]
  exact hN N le_rfl

end

end Kaplansky

end

end OAI
