import OAI.Geometry.RCD.Transport.LocalFeatureConvexImage
import OAI.Geometry.RCD.Sobolev.ConvexDifferenceSpace

namespace OAI

/-! # The vector space generated by local squared-distance coordinates -/

open Set Metric
noncomputable section
namespace RegularPointCoordinates.LocalQuadraticMidpointGeometry
variable {Y : Type*} [MetricSpace Y] [ProperSpace Y] {q : Y}
  (G : LocalQuadraticMidpointGeometry q)

omit [ProperSpace Y] in
private theorem zero_in_image : (0 : ball q (1:ℝ) → ℝ) ∈
    localDistanceFeature q '' closedBall q (1/4:ℝ) := by
  refine ⟨q,by simp,?_⟩
  funext z
  exact congrFun (quadraticDistanceFeature_self q) z

def localFeatureSpace : Submodule ℝ (ball q (1:ℝ) → ℝ) :=
  convexDifferenceSpace (localDistanceFeature q '' closedBall q (1/4:ℝ))
    (G.convex_local_feature_image (by norm_num) (by norm_num)) zero_in_image

structure FeatureRepresentation (u : G.localFeatureSpace) where
  scale : ℝ
  nonneg : 0 ≤ scale
  first : closedBall q (1/4:ℝ)
  second : closedBall q (1/4:ℝ)
  eq_feature : (u : ball q (1:ℝ) → ℝ) =
    scale • (localDistanceFeature q first-localDistanceFeature q second)

theorem exists_featureRepresentation (u : G.localFeatureSpace) :
    Nonempty (G.FeatureRepresentation u) := by
  obtain ⟨a,ha,f,hf,g,hg,he⟩ := u.property
  obtain ⟨x,hx,rfl⟩ := hf
  obtain ⟨y,hy,rfl⟩ := hg
  exact ⟨⟨a,ha,⟨x,hx⟩,⟨y,hy⟩,he⟩⟩

def featureRepresentation (u : G.localFeatureSpace) : G.FeatureRepresentation u :=
  Classical.choice (G.exists_featureRepresentation u)

omit G in
def featureTestPoint (x : closedBall q (1/4:ℝ)) : ball q (1:ℝ) :=
  ⟨x,x.property.trans_lt (by norm_num : (1/4:ℝ)<1)⟩

theorem representation_eval (u : G.localFeatureSpace) (z : ball q (1:ℝ)) :
    (u : ball q (1:ℝ) → ℝ) z =
      (G.featureRepresentation u).scale *
        (quadraticDistanceFeature q (G.featureRepresentation u).first z-
          quadraticDistanceFeature q (G.featureRepresentation u).second z) := by
  have hh := congrFun (G.featureRepresentation u).eq_feature z
  exact hh

def localInner (u v : G.localFeatureSpace) : ℝ :=
  (G.featureRepresentation v).scale *
    ((u : ball q (1:ℝ) → ℝ) (featureTestPoint (G.featureRepresentation v).first)-
      (u : ball q (1:ℝ) → ℝ) (featureTestPoint (G.featureRepresentation v).second))

theorem localInner_symm (u v : G.localFeatureSpace) : G.localInner u v = G.localInner v u := by
  dsimp only [localInner]
  rw [G.representation_eval,G.representation_eval,G.representation_eval,G.representation_eval]
  dsimp only [featureTestPoint]
  rw [quadraticDistanceFeature_symm q (G.featureRepresentation u).first (G.featureRepresentation v).first,
    quadraticDistanceFeature_symm q (G.featureRepresentation u).second (G.featureRepresentation v).first,
    quadraticDistanceFeature_symm q (G.featureRepresentation u).first (G.featureRepresentation v).second,
    quadraticDistanceFeature_symm q (G.featureRepresentation u).second (G.featureRepresentation v).second]
  ring

theorem localInner_self (u : G.localFeatureSpace) : G.localInner u u =
    (G.featureRepresentation u).scale^2 *
      dist ((G.featureRepresentation u).first:Y) ((G.featureRepresentation u).second:Y)^2 := by
  dsimp only [localInner]
  rw [G.representation_eval,G.representation_eval]
  dsimp only [featureTestPoint,quadraticDistanceFeature]
  rw [dist_self,dist_self,dist_comm ((G.featureRepresentation u).second:Y)
    ((G.featureRepresentation u).first:Y)]
  ring

end RegularPointCoordinates.LocalQuadraticMidpointGeometry

end

end OAI
