import OAI.GroupTheory.PolycyclicRecognition.Geometry.ComplexAdjointWeights
import Mathlib.Algebra.Lie.Weights.Cartan

namespace OAI

/-! # The real form inside a complexified Lie algebra

Real and imaginary tensor coordinates detect membership in a complexified
subalgebra. In particular the complexification of the chosen real Cartan
subalgebra is again Cartan; it is preserved by the canonical conjugation.
-/

noncomputable section
namespace PolycyclicRecognition

open Module LieAlgebra
open scoped TensorProduct

variable (L : Type*) [LieRing L] [LieAlgebra ℝ L]

def complexificationRealPart : (ℂ ⊗[ℝ] L) →ₗ[ℝ] L :=
  (TensorProduct.lid ℝ L).toLinearMap.comp
    (TensorProduct.map Complex.reLm (LinearMap.id : L →ₗ[ℝ] L))

def complexificationImagPart : (ℂ ⊗[ℝ] L) →ₗ[ℝ] L :=
  (TensorProduct.lid ℝ L).toLinearMap.comp
    (TensorProduct.map Complex.imLm (LinearMap.id : L →ₗ[ℝ] L))

@[simp] theorem complexificationRealPart_tmul (z : ℂ) (x : L) :
    complexificationRealPart L (z ⊗ₜ[ℝ] x) = z.re • x := rfl

@[simp] theorem complexificationImagPart_tmul (z : ℂ) (x : L) :
    complexificationImagPart L (z ⊗ₜ[ℝ] x) = z.im • x := rfl

theorem complexification_decompose (x : ℂ ⊗[ℝ] L) :
    x = (1 : ℂ) ⊗ₜ[ℝ] complexificationRealPart L x +
      Complex.I ⊗ₜ[ℝ] complexificationImagPart L x := by
  induction x using TensorProduct.inductionOn with
  | tmul z x =>
    simp only [complexificationRealPart_tmul, complexificationImagPart_tmul]
    rw [← TensorProduct.smul_tmul, ← TensorProduct.smul_tmul, ← TensorProduct.add_tmul]
    congr 1
    simp
  | add x y hx hy =>
    simp only [map_add, TensorProduct.tmul_add]
    conv_lhs => rw [hx, hy]
    abel

/-- Conjugation on the complexification as a real Lie automorphism. -/
def complexificationConjugation : (ℂ ⊗[ℝ] L) ≃ₗ⁅ℝ⁆ (ℂ ⊗[ℝ] L) := by
  let f := LieAlgebra.ExtendScalars.map Complex.conjAe.toAlgHom (LieHom.id : L →ₗ⁅ℝ⁆ L)
  have hi : Function.Involutive f := by
    intro x
    induction x using TensorProduct.inductionOn with
    | tmul z x => simp [f]
    | add x y hx hy => simpa only [map_add] using congrArg₂ (· + ·) hx hy
  exact { f with invFun := f, left_inv := hi, right_inv := hi }

@[simp] theorem complexificationConjugation_tmul (z : ℂ) (x : L) :
    complexificationConjugation L (z ⊗ₜ[ℝ] x) = star z ⊗ₜ[ℝ] x := rfl

theorem complexification_conjugation_fixed_iff (x : ℂ ⊗[ℝ] L) :
    complexificationConjugation L x = x ↔
      ∃ y : L, x = (1 : ℂ) ⊗ₜ[ℝ] y := by
  constructor
  · intro hx
    have hi : complexificationImagPart L x = 0 := by
      have he := congrArg (complexificationImagPart L) hx
      have hc : complexificationImagPart L (complexificationConjugation L x) =
          -complexificationImagPart L x := by
        clear hx he
        induction x using TensorProduct.inductionOn with
        | tmul z y => simp
        | add x y hx hy => simp [hx, hy, add_comm]
      rw [hc] at he
      have ht : (2 : ℝ) • complexificationImagPart L x = 0 := by
        simpa only [two_smul, ← neg_eq_iff_add_eq_zero] using he
      exact (smul_eq_zero.mp ht).resolve_left (by norm_num)
    exact ⟨complexificationRealPart L x, by simpa [hi] using complexification_decompose L x⟩
  · rintro ⟨y, rfl⟩
    simp

/-- Complexification of the inclusion of a real Lie subalgebra. -/
def complexifiedInclusion (H : LieSubalgebra ℝ L) :
    (ℂ ⊗[ℝ] H) →ₗ⁅ℂ⁆ (ℂ ⊗[ℝ] L) where
  __ := H.incl.toLinearMap.baseChange ℂ
  map_lie' := fun {x y} =>
    (LieAlgebra.ExtendScalars.map (AlgHom.id ℝ ℂ) H.incl).map_lie x y

@[simp] theorem complexifiedInclusion_tmul (H : LieSubalgebra ℝ L) (z : ℂ) (h : H) :
    complexifiedInclusion L H (z ⊗ₜ[ℝ] h) = z ⊗ₜ[ℝ] (h : L) := rfl

/-- The actual complex Lie subalgebra generated by the real subalgebra. -/
def complexifiedSubalgebra (H : LieSubalgebra ℝ L) : LieSubalgebra ℂ (ℂ ⊗[ℝ] L) :=
  (complexifiedInclusion L H).range

theorem mem_complexifiedSubalgebra_iff (H : LieSubalgebra ℝ L) (x : ℂ ⊗[ℝ] L) :
    x ∈ complexifiedSubalgebra L H ↔
      complexificationRealPart L x ∈ H ∧ complexificationImagPart L x ∈ H := by
  constructor
  · rintro ⟨y, rfl⟩
    change complexificationRealPart L (complexifiedInclusion L H y) ∈ H ∧
      complexificationImagPart L (complexifiedInclusion L H y) ∈ H
    induction y using TensorProduct.inductionOn with
    | tmul z h =>
      simp only [complexifiedInclusion_tmul, complexificationRealPart_tmul,
        complexificationImagPart_tmul]
      exact ⟨H.smul_mem _ h.property, H.smul_mem _ h.property⟩
    | add x y hx hy =>
      simp only [map_add]
      exact ⟨H.add_mem hx.1 hy.1, H.add_mem hx.2 hy.2⟩
  · rintro ⟨hr, hi⟩
    refine ⟨1 ⊗ₜ[ℝ] (⟨complexificationRealPart L x, hr⟩ : H) +
      Complex.I ⊗ₜ[ℝ] (⟨complexificationImagPart L x, hi⟩ : H), ?_⟩
    change complexifiedInclusion L H
      (1 ⊗ₜ[ℝ] (⟨complexificationRealPart L x, hr⟩ : H) +
      Complex.I ⊗ₜ[ℝ] (⟨complexificationImagPart L x, hi⟩ : H)) = x
    simpa only [map_add, complexifiedInclusion_tmul] using (complexification_decompose L x).symm

/-- Scalar conjugation is the only failure of complex linearity. -/
theorem complexificationConjugation_smul (z : ℂ) (x : ℂ ⊗[ℝ] L) :
    complexificationConjugation L (z • x) = star z • complexificationConjugation L x := by
  induction x using TensorProduct.inductionOn with
  | tmul w x => simp [TensorProduct.smul_tmul']
  | add x y hx hy => simp only [smul_add, map_add, hx, hy]

theorem complexificationConjugation_involutive (x : ℂ ⊗[ℝ] L) :
    complexificationConjugation L (complexificationConjugation L x) = x :=
  (complexificationConjugation L).left_inv x

theorem complexificationConjugation_inclusion (H : LieSubalgebra ℝ L) (x : ℂ ⊗[ℝ] H) :
    complexificationConjugation L (complexifiedInclusion L H x) =
      complexifiedInclusion L H (complexificationConjugation H x) := by
  induction x using TensorProduct.inductionOn with
  | tmul z h => simp
  | add x y hx hy => simp only [map_add, hx, hy]

theorem complexifiedSubalgebra_conjugation (H : LieSubalgebra ℝ L)
    {x : ℂ ⊗[ℝ] L} (hx : x ∈ complexifiedSubalgebra L H) :
    complexificationConjugation L x ∈ complexifiedSubalgebra L H := by
  obtain ⟨y, rfl⟩ := hx
  exact ⟨complexificationConjugation H y, (complexificationConjugation_inclusion L H y).symm⟩

end PolycyclicRecognition

end

end OAI
