import OAI.GroupTheory.PolycyclicRecognition.Algebra.EnvelopingDerivation
import OAI.GroupTheory.PolycyclicRecognition.Algebra.BoundedWordAlgebra
import Mathlib.RingTheory.TwoSidedIdeal.Operations

namespace OAI

/-! # The finite word truncation of an enveloping algebra

The ideal is generated by all sufficiently long products of Lie generators.
It is invariant under every extended Lie derivation.
-/

noncomputable section
namespace PolycyclicRecognition

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

local notation "U" => UniversalEnvelopingAlgebra R L
local notation "η" => UniversalEnvelopingAlgebra.ι R (L := L)

def envelopingLongWords (c : ℕ) : Set U :=
  {u | ∃ l : List L, c ≤ l.length ∧ (l.map η).prod = u}

def envelopingTruncationIdeal (c : ℕ) : TwoSidedIdeal U :=
  TwoSidedIdeal.span (envelopingLongWords (R := R) (L := L) c)

theorem longWord_mem_envelopingTruncationIdeal (c : ℕ) (l : List L)
    (hl : c ≤ l.length) : (l.map η).prod ∈ envelopingTruncationIdeal (R := R) c :=
  TwoSidedIdeal.subset_span ⟨l, hl, rfl⟩

theorem word_derivation_mem_truncation (D : LieDerivation R L L) (c : ℕ)
    (p l : List L) (h : c ≤ p.length + l.length) :
    (p.map η).prod * envelopingDerivation D (l.map η).prod ∈
      envelopingTruncationIdeal (R := R) c := by
  induction l generalizing p with
  | nil =>
    have hzero : envelopingDerivation D (1 : U) = 0 := by
      simpa using envelopingDerivation_scalar D (1 : R)
    simpa only [List.map_nil, List.prod_nil, hzero, mul_zero] using
      (envelopingTruncationIdeal (R := R) (L := L) c).zero_mem
  | cons x l ih =>
    simp only [List.map_cons, List.prod_cons, envelopingDerivation_mul,
      envelopingDerivation_generator, mul_add]
    apply TwoSidedIdeal.add_mem
    · have hp : c ≤ (p ++ [x]).length + l.length := by
        simpa only [List.length_append, List.length_singleton, List.length_cons,
          List.length_nil, zero_add, Nat.add_assoc, Nat.add_comm 1] using h
      simpa only [List.map_append, List.prod_append, List.map_singleton,
        List.prod_singleton, mul_assoc] using ih (p ++ [x]) hp
    · have hp : c ≤ (p ++ D x :: l).length := by
        simpa only [List.length_append, List.length_cons] using h
      simpa only [List.map_append, List.prod_append, List.map_cons,
        List.prod_cons] using longWord_mem_envelopingTruncationIdeal c (p ++ D x :: l) hp

theorem envelopingDerivation_preserves_truncation (D : LieDerivation R L L)
    (c : ℕ) {u : U} (hu : u ∈ envelopingTruncationIdeal (R := R) c) :
    envelopingDerivation D u ∈ envelopingTruncationIdeal (R := R) c := by
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
    obtain ⟨l, hl, rfl⟩ := hu
    simpa using word_derivation_mem_truncation D c [] l (by simpa using hl)
  | zero => simpa only [map_zero] using (envelopingTruncationIdeal (R := R) (L := L) c).zero_mem
  | add a b _ _ ha hb =>
    rw [map_add]
    exact TwoSidedIdeal.add_mem _ ha hb
  | neg a _ ha =>
    rw [map_neg]
    exact TwoSidedIdeal.neg_mem _ ha
  | left_absorb a b hb hDb =>
    rw [envelopingDerivation_mul]
    exact TwoSidedIdeal.add_mem _
      (TwoSidedIdeal.mul_mem_left _ _ _ hDb)
      (TwoSidedIdeal.mul_mem_left _ _ _ hb)
  | right_absorb b a ha hDa =>
    rw [envelopingDerivation_mul]
    exact TwoSidedIdeal.add_mem _
      (TwoSidedIdeal.mul_mem_right _ _ _ ha)
      (TwoSidedIdeal.mul_mem_right _ _ _ hDa)

end PolycyclicRecognition

end

end OAI
