import OAI.GroupTheory.PolycyclicRecognition.Algebra.VandermondeSubmoduleInterpolation
import Mathlib.LinearAlgebra.Lagrange
import Mathlib.Algebra.Polynomial.Lifts
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis

namespace OAI

/-! # Independent coordinates detected by finitely many shifted products

The polynomial ring in n variables is integral over the algebra generated by
n+1 distinct scalar evaluations of its monic root polynomial. Interpolation
recovers the coefficients; every coordinate is a root of that polynomial.
-/

noncomputable section
namespace PolycyclicRecognition
open scoped Polynomial Cardinal
variable (K : Type) [Field K]

def shiftProduct (n : ℕ) (c : K) : MvPolynomial (Fin n) K :=
  ∏ i : Fin n, (MvPolynomial.C c - MvPolynomial.X i)

def shiftProductAlgebra (n : ℕ) (c : Fin (n + 1) → K) :
    Subalgebra K (MvPolynomial (Fin n) K) :=
  Algebra.adjoin K (Set.range (fun i => shiftProduct K n (c i)))

theorem rootPolynomial_coeff_mem_shiftProductAlgebra (n : ℕ) (c : Fin (n + 1) → K)
    (hc : Function.Injective c) (k : ℕ) :
    (Lagrange.nodal Finset.univ (fun i : Fin n => (MvPolynomial.X i : MvPolynomial (Fin n) K))).coeff k ∈
      shiftProductAlgebra K n c := by
  let P := Lagrange.nodal Finset.univ (fun i : Fin n => (MvPolynomial.X i : MvPolynomial (Fin n) K))
  have hd : P.natDegree = n := by simp [P]
  by_cases hk : k < n + 1
  · apply polynomial_coeff_mem_of_evaluations P (by omega) c hc
      (shiftProductAlgebra K n c).toSubmodule (i := ⟨k, hk⟩)
    intro i
    change P.eval (MvPolynomial.C (c i)) ∈ shiftProductAlgebra K n c
    rw [show P.eval (MvPolynomial.C (c i)) = shiftProduct K n (c i) by
      simp only [P, Lagrange.eval_nodal, shiftProduct]]
    exact Algebra.subset_adjoin (Set.mem_range_self i)
  · have hz : P.coeff k = 0 := Polynomial.coeff_eq_zero_of_natDegree_lt (by omega)
    exact hz ▸ (shiftProductAlgebra K n c).zero_mem

theorem coordinate_integral_shiftProductAlgebra (n : ℕ) (c : Fin (n + 1) → K)
    (hc : Function.Injective c) (i : Fin n) :
    IsIntegral (shiftProductAlgebra K n c) (MvPolynomial.X i : MvPolynomial (Fin n) K) := by
  let P := Lagrange.nodal Finset.univ (fun j : Fin n => (MvPolynomial.X j : MvPolynomial (Fin n) K))
  let B := shiftProductAlgebra K n c
  have hcoeff : P ∈ Polynomial.lifts B.val.toRingHom := by
    apply (Polynomial.lifts_iff_coeff_lifts P).mpr
    intro k
    exact ⟨⟨P.coeff k, rootPolynomial_coeff_mem_shiftProductAlgebra K n c hc k⟩, rfl⟩
  obtain ⟨q, hq⟩ := (Polynomial.mem_lifts P).mp hcoeff
  refine ⟨q, Polynomial.monic_of_injective (f := B.val.toRingHom) Subtype.val_injective ?_, ?_⟩
  · rw [hq]
    exact Lagrange.nodal_monic
  · change q.eval₂ B.val.toRingHom (MvPolynomial.X i) = 0
    rw [← Polynomial.eval_map, hq]
    exact Lagrange.eval_nodal_at_node (Finset.mem_univ i)

theorem shiftProductAlgebra_integral (n : ℕ) (c : Fin (n + 1) → K)
    (hc : Function.Injective c) :
    Algebra.IsIntegral (shiftProductAlgebra K n c) (MvPolynomial (Fin n) K) := by
  let B := shiftProductAlgebra K n c
  refine ⟨fun p => ?_⟩
  induction p using MvPolynomial.induction_on with
  | C a =>
    change IsIntegral B (algebraMap B (MvPolynomial (Fin n) K)
      ⟨MvPolynomial.C a, B.algebraMap_mem a⟩)
    exact isIntegral_algebraMap
  | add p q hp hq => exact hp.add hq
  | mul_X p i hp => exact hp.mul (coordinate_integral_shiftProductAlgebra K n c hc i)

theorem shiftProductAlgebra_trdeg (n : ℕ) (c : Fin (n + 1) → K)
    (hc : Function.Injective c) :
    Algebra.trdeg K (shiftProductAlgebra K n c) = n := by
  let B := shiftProductAlgebra K n c
  let := shiftProductAlgebra_integral K n c hc
  have ht := trdeg_add_eq K B (A := MvPolynomial (Fin n) K)
  rw [trdeg_eq_zero (R := B) (A := MvPolynomial (Fin n) K), add_zero,
    MvPolynomial.trdeg_of_isDomain] at ht
  simpa using ht

theorem shiftProductAlgebra_independent (n : ℕ) (c : Fin (n + 1) → K)
    (hc : Function.Injective c) :
    ∃ x : Fin n → shiftProductAlgebra K n c, AlgebraicIndependent K x := by
  obtain ⟨s, hs⟩ := exists_isTranscendenceBasis K (shiftProductAlgebra K n c)
  have he : Cardinal.mk s = Cardinal.mk (Fin n) := by
    rw [hs.cardinalMk_eq_trdeg, shiftProductAlgebra_trdeg K n c hc]
    simp
  obtain ⟨e⟩ := Cardinal.eq.mp he
  exact ⟨fun i => (e.symm i).val, hs.1.comp e.symm e.symm.injective⟩

end PolycyclicRecognition

end

end OAI
