import OAI.GroupTheory.PolycyclicRecognition.Algebra.BracketWords
import Mathlib.Algebra.Lie.Quotient

namespace OAI

/-! # The mixed-word ideal used by the cone quotients -/

noncomputable section
namespace PolycyclicRecognition

open Set

variable {I L : Type*} [LieRing L] [LieAlgebra ℝ L]

/-- A bracket word is mixed when at least one of its letters is outside the
chosen cone. No property of that cone is needed for the ideal calculation. -/
def IsMixedWord (outside : I → Prop) : FreeMagma I → Prop
  | .of i => outside i
  | .mul u v => IsMixedWord outside u ∨ IsMixedWord outside v

def mixedWordSpan (X : I → L) (outside : I → Prop) : Submodule ℝ L :=
  Submodule.span ℝ (evalBracketWord X '' {w | IsMixedWord outside w})

theorem eval_mixed_mem_span (X : I → L) (outside : I → Prop)
    {w : FreeMagma I} (hw : IsMixedWord outside w) :
    evalBracketWord X w ∈ mixedWordSpan X outside :=
  Submodule.subset_span ⟨w, hw, rfl⟩

/-- Bracketing a mixed word with an arbitrary word still gives a mixed word;
linearity extends this to the full generated algebra. -/
theorem mixedWordSpan_lie (X : I → L) (outside : I → Prop)
    (hgen : LieSubalgebra.lieSpan ℝ L (range X) = ⊤)
    (x y : L) (hy : y ∈ mixedWordSpan X outside) :
    ⁅x, y⁆ ∈ mixedWordSpan X outside := by
  have hx : x ∈ Submodule.span ℝ (range (evalBracketWord X)) := by
    rw [span_evalBracketWord, hgen]
    trivial
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨u, rfl⟩ := hx
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨v, hv, rfl⟩ := hy
      exact eval_mixed_mem_span X outside (w := u * v) (Or.inr hv)
    | zero => simpa only [lie_zero] using (mixedWordSpan X outside).zero_mem
    | add y z _ _ hy hz =>
      simpa only [lie_add] using (mixedWordSpan X outside).add_mem hy hz
    | smul r y _ hy =>
      simpa only [lie_smul] using (mixedWordSpan X outside).smul_mem r hy
  | zero => simpa only [zero_lie] using (mixedWordSpan X outside).zero_mem
  | add x z _ _ hx hz =>
    simpa only [add_lie] using (mixedWordSpan X outside).add_mem hx hz
  | smul r x _ hx =>
    simpa only [smul_lie] using (mixedWordSpan X outside).smul_mem r hx

/-- The span of mixed words is an actual Lie ideal, rather than an assumed
quotient datum. -/
def mixedWordIdeal (X : I → L) (outside : I → Prop)
    (hgen : LieSubalgebra.lieSpan ℝ L (range X) = ⊤) : LieIdeal ℝ L :=
  { mixedWordSpan X outside with
    lie_mem := fun {x y} hy => mixedWordSpan_lie X outside hgen x y hy }

/-- Every ideal containing the outside letters contains every mixed word. -/
theorem eval_mixed_mem_ideal (X : I → L) (outside : I → Prop)
    (J : LieIdeal ℝ L) (hJ : ∀ i, outside i → X i ∈ J)
    (w : FreeMagma I) (hw : IsMixedWord outside w) : evalBracketWord X w ∈ J := by
  induction w using FreeMagma.rec with
  | of i => exact hJ i hw
  | mul u v hu hv =>
    rcases hw with hw | hw
    · exact lie_mem_left ℝ L J _ _ (hu hw)
    · exact J.lie_mem (hv hw)

/-- This is precisely the ideal generated by the outside letters. -/
theorem mixedWordIdeal_le_iff (X : I → L) (outside : I → Prop)
    (hgen : LieSubalgebra.lieSpan ℝ L (range X) = ⊤) (J : LieIdeal ℝ L) :
    mixedWordIdeal X outside hgen ≤ J ↔ ∀ i, outside i → X i ∈ J := by
  constructor
  · intro h i hi
    exact h (eval_mixed_mem_span X outside (w := .of i) hi)
  · intro h
    apply Submodule.span_le.mpr
    rintro _ ⟨w, hw, rfl⟩
    exact eval_mixed_mem_ideal X outside J h w hw

/-- The quotient by the mixed-word ideal is spanned by pure words. -/
theorem quotient_mixedWordIdeal_span_pure (X : I → L) (outside : I → Prop)
    (hgen : LieSubalgebra.lieSpan ℝ L (range X) = ⊤) :
    let J := (mixedWordIdeal X outside hgen).toSubmodule
    Submodule.span ℝ (J.mkQ '' (evalBracketWord X '' {w | ¬IsMixedWord outside w})) = ⊤ := by
  dsimp only
  let J := (mixedWordIdeal X outside hgen).toSubmodule
  let P := Submodule.span ℝ (J.mkQ '' (evalBracketWord X '' {w | ¬IsMixedWord outside w}))
  apply top_unique
  intro q hq
  clear hq
  obtain ⟨x, rfl⟩ := J.mkQ_surjective q
  have hx : x ∈ Submodule.span ℝ (range (evalBracketWord X)) := by
    rw [span_evalBracketWord, hgen]
    trivial
  change J.mkQ x ∈ P
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w, rfl⟩ := hx
    by_cases hw : IsMixedWord outside w
    · have hz : J.mkQ (evalBracketWord X w) = 0 :=
        (Submodule.Quotient.mk_eq_zero J).mpr (eval_mixed_mem_span X outside hw)
      rw [hz]
      exact P.zero_mem
    · exact Submodule.subset_span ⟨_, ⟨w, hw, rfl⟩, rfl⟩
  | zero => simpa only [map_zero] using P.zero_mem
  | add x y _ _ hx hy => simpa only [map_add] using P.add_mem hx hy
  | smul r x _ hx => simpa only [map_smul] using P.smul_mem r hx

/-- In the abelianization, the mixed-word ideal is exactly the span of the
outside generator images. Higher bracket words contribute zero. -/
theorem map_mixedWordSpan_of_kills_brackets
    {V : Type*} [AddCommGroup V] [Module ℝ V]
    (X : I → L) (outside : I → Prop) (q : L →ₗ[ℝ] V)
    (hq : ∀ x y : L, q ⁅x, y⁆ = 0) :
    (mixedWordSpan X outside).map q = Submodule.span ℝ (q '' (X '' {i | outside i})) := by
  rw [mixedWordSpan, Submodule.map_span]
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨w, hw, rfl⟩, rfl⟩
    cases w with
    | of i => exact Submodule.subset_span ⟨X i, ⟨i, hw, rfl⟩, rfl⟩
    | mul u v =>
      change q ⁅evalBracketWord X u, evalBracketWord X v⁆ ∈ _
      rw [hq]
      exact Submodule.zero_mem _
  · apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨i, hi, rfl⟩, rfl⟩
    exact Submodule.subset_span ⟨_, ⟨FreeMagma.of i, hi, rfl⟩, rfl⟩

/-- A derivation preserves the mixed-word ideal as soon as it sends each
outside generator into that ideal. This is the Cartan-invariance reduction. -/
theorem derivation_preserves_mixedWordIdeal
    (X : I → L) (outside : I → Prop)
    (hgen : LieSubalgebra.lieSpan ℝ L (range X) = ⊤)
    (D : L →ₗ[ℝ] L)
    (hD : ∀ x y, D ⁅x, y⁆ = ⁅D x, y⁆ + ⁅x, D y⁆)
    (hout : ∀ i, outside i → D (X i) ∈ mixedWordIdeal X outside hgen)
    (v : L) (hv : v ∈ mixedWordIdeal X outside hgen) :
    D v ∈ mixedWordIdeal X outside hgen := by
  let J := mixedWordIdeal X outside hgen
  change D v ∈ J.toSubmodule
  have hw (w : FreeMagma I) (hm : IsMixedWord outside w) : D (evalBracketWord X w) ∈ J := by
    induction w using FreeMagma.rec with
    | of i => exact hout i hm
    | mul u v hu hv =>
      change D ⁅evalBracketWord X u, evalBracketWord X v⁆ ∈ J
      rw [hD]
      rcases hm with hm | hm
      · exact J.add_mem (lie_mem_left ℝ L J _ _ (hu hm))
          (lie_mem_left ℝ L J _ _ (eval_mixed_mem_span X outside hm))
      · exact J.add_mem (J.lie_mem (eval_mixed_mem_span X outside hm))
          (J.lie_mem (hv hm))
  change v ∈ mixedWordSpan X outside at hv
  induction hv using Submodule.span_induction with
  | mem v hv =>
    obtain ⟨w, hw', rfl⟩ := hv
    exact hw w hw'
  | zero => simpa only [map_zero] using J.toSubmodule.zero_mem
  | add x y _ _ hx hy => simpa only [map_add] using J.add_mem hx hy
  | smul r x _ hx => simpa only [map_smul] using J.smul_mem r hx

end PolycyclicRecognition

end

end OAI
