import OAI.GroupTheory.PolycyclicRecognition.Algebra.UnitaryCocycle
import Mathlib.Topology.Algebra.Group.Subgroup

namespace OAI

/-! # Fixed vectors and contracted elements

The fixed-vector case of Cornulier--Tessera, Lemma 5.2. The proof uses only
strong continuity and the isometry identity, with explicit contracting
sequences. The closed subgroup generated by these elements then has the
same fixed vectors as the contracting subgroup.
-/

noncomputable section

namespace PolycyclicRecognition

open Filter Set
open scoped Topology

variable {G E : Type*} [Group G] [TopologicalSpace G]
  [NormedAddCommGroup E] [NormedSpace ℝ E]
  (ρ : G →* (E ≃ₗᵢ[ℝ] E))

def unitaryStabilizer (v : E) : Subgroup G where
  carrier := {g | ρ g v = v}
  one_mem' := by change ρ 1 v = v; rw [ρ.map_one]; rfl
  mul_mem' := by
    intro g h hg hh
    change ρ (g * h) v = v
    rw [ρ.map_mul]
    change ρ g (ρ h v) = v
    rw [hh, hg]
  inv_mem' := by
    intro g hg
    have he := congrArg (fun w => ρ g⁻¹ w) hg
    have hi : ρ g⁻¹ * ρ g = 1 := by rw [← ρ.map_mul, inv_mul_cancel, ρ.map_one]
    change (ρ g⁻¹ * ρ g) v = ρ g⁻¹ v at he
    rw [hi] at he
    exact he.symm

theorem isClosed_unitaryStabilizer (hρ : ∀ v, Continuous (fun g => ρ g v)) (v : E) :
    IsClosed (unitaryStabilizer ρ v : Set G) :=
  isClosed_eq (hρ v) continuous_const

def contractedBy (H : Subgroup G) : Set G :=
  {u | ∃ a : ℕ → H, Tendsto (fun n => (a n : G)⁻¹ * u * a n) atTop (𝓝 1)}

theorem unitary_fixed_of_contracted
    (hρ : ∀ v, Continuous (fun g => ρ g v)) (H : Subgroup G)
    (v : E) (hv : ∀ h : H, ρ h v = v) {u : G} (hu : u ∈ contractedBy H) :
    ρ u v = v := by
  obtain ⟨a, ha⟩ := hu
  have ht := ((hρ v).tendsto 1).comp ha
  rw [ρ.map_one] at ht
  change Tendsto (fun n => ρ ((a n : G)⁻¹ * u * a n) v) atTop (𝓝 v) at ht
  have hn : Tendsto (fun n => ‖ρ ((a n : G)⁻¹ * u * a n) v - v‖) atTop (𝓝 0) := by
    simpa only [sub_self, norm_zero] using
      (ht.sub (tendsto_const_nhds : Tendsto (fun _ : ℕ => v) atTop (𝓝 v))).norm
  have he (n : ℕ) : ‖ρ ((a n : G)⁻¹ * u * a n) v - v‖ = ‖ρ u v - v‖ := by
    have hia : ρ ((a n : G)⁻¹) v = v :=
      (unitaryStabilizer ρ v).inv_mem (hv (a n))
    rw [ρ.map_mul, ρ.map_mul]
    change ‖ρ ((a n : G)⁻¹) (ρ u (ρ (a n : G) v)) - v‖ = _
    rw [hv (a n)]
    calc
      ‖ρ ((a n : G)⁻¹) (ρ u v) - v‖ =
          ‖ρ ((a n : G)⁻¹) (ρ u v) - ρ ((a n : G)⁻¹) v‖ := by rw [hia]
      _ = ‖ρ u v - v‖ := by rw [← map_sub]; exact (ρ ((a n : G)⁻¹)).norm_map _
  have htzero : Tendsto (fun _ : ℕ => ‖ρ u v - v‖) atTop (𝓝 0) := by
    simpa only [Function.comp_apply, sub_self, norm_zero, he] using hn
  exact sub_eq_zero.mp (norm_eq_zero.mp (tendsto_nhds_unique tendsto_const_nhds htzero))

variable [IsTopologicalGroup G]

theorem unitary_fixed_of_contracted_generation
    (hρ : ∀ v, Continuous (fun g => ρ g v)) (H : Subgroup G)
    (hgen : (Subgroup.closure ((H : Set G) ∪ contractedBy H)).topologicalClosure = ⊤)
    (v : E) (hv : ∀ h : H, ρ h v = v) : ∀ g, ρ g v = v := by
  have hle : Subgroup.closure ((H : Set G) ∪ contractedBy H) ≤ unitaryStabilizer ρ v := by
    apply (Subgroup.closure_le _).2
    intro g hg
    rcases hg with hg | hg
    · exact hv ⟨g, hg⟩
    · exact unitary_fixed_of_contracted ρ hρ H v hv hg
  have hc := (Subgroup.closure ((H : Set G) ∪ contractedBy H)).topologicalClosure_minimal
    hle (isClosed_unitaryStabilizer ρ hρ v)
  rw [hgen] at hc
  exact fun g => hc (Subgroup.mem_top g)

theorem unitary_no_fixed_on_contracting_subgroup
    (hρ : ∀ v, Continuous (fun g => ρ g v))
    (hfix : ∀ v, (∀ g, ρ g v = v) → v = 0) (H : Subgroup G)
    (hgen : (Subgroup.closure ((H : Set G) ∪ contractedBy H)).topologicalClosure = ⊤) :
    ∀ v, (∀ h : H, ρ h v = v) → v = 0 :=
  fun v hv => hfix v (unitary_fixed_of_contracted_generation ρ hρ H hgen v hv)

end PolycyclicRecognition

end

end OAI
