import OAI.MathematicalPhysics.ContinuumCoulomb.Nuclei.MoserEndpoint
import Mathlib.Topology.MetricSpace.Antilipschitz

namespace OAI

/-! Backward stability gives the separation bound required for mapped
quadrature nodes. Compactly supported motion also preserves the enclosing slab. -/

noncomputable section
open scoped Topology NNReal
namespace ContinuumCoulomb

theorem moser_trajectory_backward_bound {rho : ℝ} (hrho : 0 < rho)
    (V : Position → ℝ) (hV : ContDiff ℝ 6 V) (hc : HasCompactSupport V)
    (hbound : ∀ x, |manufacturedCharge V x| ≤ rho / 2) :
    ∃ K : ℝ≥0, ∀ (α β : ℝ → Position),
      (∀ t ∈ Set.Icc (0 : ℝ) 1,
        HasDerivWithinAt α (moserVelocity rho V t (α t)) (Set.Icc (0 : ℝ) 1) t) →
      (∀ t ∈ Set.Icc (0 : ℝ) 1,
        HasDerivWithinAt β (moserVelocity rho V t (β t)) (Set.Icc (0 : ℝ) 1) t) →
      dist (α 0) (β 0) ≤ Real.exp (K : ℝ) * dist (α 1) (β 1) := by
  obtain ⟨L, K, hL, hK, ht⟩ := moserVelocity_uniform_bounds hrho V hV hc hbound
  refine ⟨K, fun α β hα hβ => ?_⟩
  let v : ℝ → Position → Position := fun s x => -(moserVelocity rho V (-s) x)
  have hmap : Set.MapsTo (Neg.neg : ℝ → ℝ) (Set.Icc (-1 : ℝ) 0) (Set.Icc (0 : ℝ) 1) := by
    intro s hs
    constructor <;> linarith [hs.1, hs.2]
  have hd (γ : ℝ → Position)
      (hγ : ∀ t ∈ Set.Icc (0 : ℝ) 1,
        HasDerivWithinAt γ (moserVelocity rho V t (γ t)) (Set.Icc (0 : ℝ) 1) t)
      (s : ℝ) (hs : s ∈ Set.Ico (-1 : ℝ) 0) :
      HasDerivWithinAt (γ ∘ Neg.neg) (v s ((γ ∘ Neg.neg) s)) (Set.Ici s) s := by
    have hmem : -s ∈ Set.Ioc (0 : ℝ) 1 := by constructor <;> linarith [hs.1, hs.2]
    have hdγ : HasDerivWithinAt γ (moserVelocity rho V (-s) (γ (-s))) (Set.Iic (-s)) (-s) := by
      apply (hγ (-s) ⟨hmem.1.le, hmem.2⟩).mono_of_mem_nhdsWithin
      apply Filter.mem_of_superset (Icc_mem_nhdsLE hmem.1)
      exact Set.Icc_subset_Icc_right hmem.2
    have hm : Set.MapsTo (Neg.neg : ℝ → ℝ) (Set.Ici s) (Set.Iic (-s)) :=
      fun _ ht => neg_le_neg (Set.mem_Ici.mp ht)
    convert! HasFDerivWithinAt.comp_hasDerivWithinAt s hdγ
      (hasDerivAt_neg s).hasDerivWithinAt hm using 1
    simp [v]
  have hv (s : ℝ) (hs : s ∈ Set.Ico (-1 : ℝ) 0) :
      LipschitzOnWith K (v s) (Set.univ : Set Position) := by
    have hm : -s ∈ Set.Icc (0 : ℝ) 1 := hmap ⟨hs.1, hs.2.le⟩
    exact (hK (-s) hm).neg.lipschitzOnWith
  have h := dist_le_of_trajectories_ODE_of_mem (v := v) (s := fun _ => Set.univ) hv
    ((HasDerivWithinAt.continuousOn hα).comp continuous_neg.continuousOn hmap)
    (hd α hα) (fun _ _ => Set.mem_univ _)
    ((HasDerivWithinAt.continuousOn hβ).comp continuous_neg.continuousOn hmap)
    (hd β hβ) (fun _ _ => Set.mem_univ _)
    (le_refl (dist ((α ∘ Neg.neg) (-1)) ((β ∘ Neg.neg) (-1))))
    0 (show (0 : ℝ) ∈ Set.Icc (-1 : ℝ) 0 by constructor <;> norm_num)
  simpa only [Function.comp_apply, neg_zero, neg_neg, sub_neg_eq_add, zero_add, mul_one,
    mul_comm] using h

/-- Both Lipschitz bounds refer to the actual map generated by the ODE. -/
theorem moser_bilipschitz_time_one_exists {rho : ℝ} (hrho : 0 < rho)
    (V : Position → ℝ) (hV : ContDiff ℝ 6 V) (hc : HasCompactSupport V)
    (hbound : ∀ x, |manufacturedCharge V x| ≤ rho / 2) :
    ∃ (G : Position → ℝ → Position) (C Cinv : ℝ≥0),
      (∀ x, G x 0 = x) ∧
      (∀ x, ∀ t ∈ Set.Icc (0 : ℝ) 1,
        HasDerivWithinAt (G x) (moserVelocity rho V t (G x t)) (Set.Icc (0 : ℝ) 1) t) ∧
      Function.Bijective (fun x => G x 1) ∧
      LipschitzWith C (fun x => G x 1) ∧
      AntilipschitzWith Cinv (fun x => G x 1) ∧
      (∀ x, x ∉ tsupport V → G x 1 = x) := by
  obtain ⟨G, hG0, hG, hbij, ⟨C, hC⟩, hfix⟩ := moser_time_one_exists hrho V hV hc hbound
  obtain ⟨K, hK⟩ := moser_trajectory_backward_bound hrho V hV hc hbound
  refine ⟨G, C, ⟨Real.exp (K : ℝ), (Real.exp_pos _).le⟩,
    hG0, hG, hbij, hC, AntilipschitzWith.of_le_mul_dist ?_, hfix⟩
  intro x y
  change dist x y ≤ Real.exp (K : ℝ) * dist (G x 1) (G y 1)
  simpa only [hG0] using hK (G x) (G y) (hG x) (hG y)

theorem moser_time_one_preserves_slab (V : Position → ℝ) {H S : ℝ}
    (hsupport : tsupport V ⊆ slabDomain H S) (G : Position → Position)
    (hbij : Function.Bijective G) (hfix : ∀ x, x ∉ tsupport V → G x = x) :
    G '' slabDomain H S = slabDomain H S := by
  apply Set.Subset.antisymm
  · rintro y ⟨x, hx, rfl⟩
    by_contra hy
    have hn : G x ∉ tsupport V := fun h => hy (hsupport h)
    have heq : x = G x := hbij.1 (hfix (G x) hn).symm
    exact hy (heq ▸ hx)
  · intro y hy
    obtain ⟨x, rfl⟩ := hbij.2 y
    refine ⟨x, ?_, rfl⟩
    by_contra hx
    have hn : x ∉ tsupport V := fun h => hx (hsupport h)
    exact hx ((hfix x hn) ▸ hy)

end ContinuumCoulomb

end

end OAI
