import OAI.MathematicalPhysics.Elasticity.Bessel
import OAI.MathematicalPhysics.Elasticity.Augmented

namespace OAI

noncomputable section

open MeasureTheory Complex SchwartzMap
open scoped BigOperators FourierTransform SchwartzMap LineDeriv ENNReal
namespace ElasticityPhysicalEstimate
open ElasticityBessel ElasticitySchwartzCarleman ElasticityNegativeOrder
abbrev X := ElasticityBessel.X

lemma J_sum {ι : Type*} (T : Finset ι) (h s : ℝ) (f : ι → S) :
    J h s (∑ i ∈ T, f i) = ∑ i ∈ T, J h s (f i) := by
  simp only [J, FourierTransform.fourier_sum, map_sum, FourierTransform.fourierInv_sum]

lemma negNorm_sum_le {ι : Type*} (T : Finset ι) (h : ℝ) (f : ι → S) :
    norm2 (J h (-1) (∑ i ∈ T, f i)) ≤ ∑ i ∈ T, norm2 (J h (-1) (f i)) := by
  rw [J_sum]
  exact norm2_sum_le _ _

lemma sumNorm_three_le (h s : ℝ) (U : Fin 3 → S) :
    sumNorm h s U ≤ 2*sobNorm h s U := by
  have hn : 0 ≤ ∑ i, norm2 (J h s (U i))^2 := Finset.sum_nonneg (fun _ _ => sq_nonneg _)
  have hs := Real.sq_sqrt hn
  have ht := sq_sum_le_card_mul_sum_sq
    (s := Finset.univ) (f := fun i => norm2 (J h s (U i)))
  norm_num only [Finset.card_univ, Fintype.card_fin, Nat.cast_ofNat] at ht
  dsimp only [sobNorm, sumNorm]
  nlinarith only [hs, ht, hn, Real.sqrt_nonneg (∑ i, norm2 (J h s (U i))^2)]

lemma dirDeriv_negNorm (h : ℝ) (hh : 0 ≤ h) (α β : X) (i : Fin 3) (f : S) :
    norm2 (J h (-1) (dirDeriv h α β i f)) ≤
      h*(1+‖((α i : ℂ)+Complex.I*(β i : ℂ))‖)*norm2 f := by
  have hd := semideriv_bound h 0 hh i f
  norm_num only [zero_sub, J_zero] at hd
  have hz := norm2_J_nonpos h (-1) (by norm_num) f
  have hn := norm2_nonneg f
  simp only [dirDeriv, J_add, J_smul]
  calc
    _ ≤ norm2 (((h^2 : ℝ) : ℂ) • J h (-1) (d (e i) f)) +
        norm2 (((h : ℂ)*((α i : ℂ)+Complex.I*(β i : ℂ))) • J h (-1) f) := norm2_add_le _ _
    _ = h^2*norm2 (J h (-1) (d (e i) f)) +
        (h*‖((α i : ℂ)+Complex.I*(β i : ℂ))‖)*norm2 (J h (-1) f) := by
      simp only [norm2_const_smul, norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_nonneg hh, abs_of_nonneg (sq_nonneg h)]
    _ ≤ h*norm2 f+(h*‖((α i : ℂ)+Complex.I*(β i : ℂ))‖)*norm2 f := by
      have hd' := mul_le_mul_of_nonneg_left hd hh
      have hz' := mul_le_mul_of_nonneg_left hz (mul_nonneg hh (norm_nonneg ((α i : ℂ)+Complex.I*(β i : ℂ))))
      nlinarith only [hd', hz']
    _ = _ := by ring

/-- The actual normalized forcing generated by a physical forcing F.
Here n=1/μ, o=1/(λ+2μ), and c_i=-2(∂ᵢμ)/μ.
The scalar entry contains the conjugated divergence. -/
def augmentedForcing (h : ℝ) (α β : X) (n o : X → ℂ) (c : Fin 3 → X → ℂ)
    (F : Fin 3 → S) : Fin 4 → S :=
  Fin.cons (mult o (∑ i, (dirDeriv h α β i (F i) + ((h^2 : ℝ) : ℂ) • mult (c i) (F i))))
    (fun i => ((h^2 : ℝ) : ℂ) • mult n (F i))

lemma forcing_bound (h : ℝ) (hh : 0 ≤ h) (hh1 : h ≤ 1) (α β : X)
    (n o : X → ℂ) (c : Fin 3 → X → ℂ)
    (hn : n.HasTemperateGrowth) (ho : o.HasTemperateGrowth)
    (hc : ∀ i, (c i).HasTemperateGrowth)
    (A D Z : ℝ) (hA : 0 ≤ A) (hD : 0 ≤ D) (hZ : 0 ≤ Z)
    (hnA : ∀ x, ‖n x‖ ≤ A) (hoA : ∀ x, ‖o x‖ ≤ A)
    (hcA : ∀ i x, ‖c i x‖ ≤ A)
    (hod : ∀ x i, h*‖fderiv ℝ o x (e i)‖ ≤ D)
    (hz : ∀ i, ‖((α i : ℂ)+Complex.I*(β i : ℂ))‖ ≤ Z)
    (F : Fin 3 → S) :
    sobNorm h (-1) (augmentedForcing h α β n o c F) ≤
      2*(A+3*(A+D)*(1+Z+A))*h*sobNorm h 0 F := by
  have hM : 0 ≤ 3*(A+D) := by positivity
  have hm (i : Fin 3) : norm2 (J h (-1) (((h^2 : ℝ) : ℂ) • mult (c i) (F i))) ≤
      h*A*norm2 (F i) := by
    rw [J_smul, norm2_const_smul, Complex.norm_real, Real.norm_eq_abs,
      abs_of_nonneg (sq_nonneg h)]
    calc
      _ ≤ h^2*norm2 (mult (c i) (F i)) :=
        mul_le_mul_of_nonneg_left (norm2_J_nonpos _ _ (by norm_num) _) (sq_nonneg h)
      _ ≤ h^2*(A*norm2 (F i)) :=
        mul_le_mul_of_nonneg_left (norm2_mult _ (hc i) A (hcA i) _) (sq_nonneg h)
      _ ≤ h*A*norm2 (F i) := by
        have ht : h^2 ≤ h := by nlinarith only [hh, hh1]
        nlinarith [mul_le_mul_of_nonneg_right ht (mul_nonneg hA (norm2_nonneg (F i)))]
  have hd (i : Fin 3) : norm2 (J h (-1) (dirDeriv h α β i (F i))) ≤
      h*(1+Z)*norm2 (F i) := by
    exact (dirDeriv_negNorm h hh α β i _).trans
      (mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_left (show 1+‖((α i : ℂ)+Complex.I*(β i : ℂ))‖ ≤ 1+Z by linarith [hz i]) hh)
        (norm2_nonneg (F i)))
  have hs : norm2 (J h (-1) (augmentedForcing h α β n o c F 0)) ≤
      3*(A+D)*h*(1+Z+A)*sumNorm h 0 F := by
    change norm2 (J h (-1) (mult o _)) ≤ _
    calc
      _ ≤ 3*(A+D)*norm2 (J h (-1) (∑ i, (dirDeriv h α β i (F i) +
          ((h^2 : ℝ) : ℂ) • mult (c i) (F i)))) := mult_Hneg1 h hh o ho A D hA hD hoA hod _
      _ ≤ 3*(A+D)*(∑ i, norm2 (J h (-1) (dirDeriv h α β i (F i) +
          ((h^2 : ℝ) : ℂ) • mult (c i) (F i)))) :=
        mul_le_mul_of_nonneg_left (negNorm_sum_le Finset.univ h _) hM
      _ ≤ 3*(A+D)*(∑ i, h*(1+Z+A)*norm2 (F i)) := by
        gcongr with i
        rw [J_add]
        exact (norm2_add_le _ _).trans (by nlinarith only [hd i, hm i])
      _ = _ := by simp only [sumNorm, J_zero, ← Finset.mul_sum]; ring
  have ht (i : Fin 3) : norm2 (J h (-1) (augmentedForcing h α β n o c F i.succ)) ≤
      h*A*norm2 (F i) := by
    change norm2 (J h (-1) (((h^2 : ℝ) : ℂ) • mult n (F i))) ≤ _
    rw [J_smul, norm2_const_smul, Complex.norm_real, Real.norm_eq_abs,
      abs_of_nonneg (sq_nonneg h)]
    calc
      _ ≤ h^2*norm2 (mult n (F i)) :=
        mul_le_mul_of_nonneg_left (norm2_J_nonpos _ _ (by norm_num) _) (sq_nonneg h)
      _ ≤ h^2*(A*norm2 (F i)) :=
        mul_le_mul_of_nonneg_left (norm2_mult _ hn A hnA _) (sq_nonneg h)
      _ ≤ h*A*norm2 (F i) := by
        have ht : h^2 ≤ h := by nlinarith only [hh, hh1]
        nlinarith [mul_le_mul_of_nonneg_right ht (mul_nonneg hA (norm2_nonneg (F i)))]
  calc
    _ ≤ sumNorm h (-1) (augmentedForcing h α β n o c F) := sobNorm_le_sumNorm _ _ _
    _ ≤ (A+3*(A+D)*(1+Z+A))*h*sumNorm h 0 F := by
      rw [sumNorm, Fin.sum_univ_succ]
      have hts := Finset.sum_le_sum (fun i (_ : i ∈ Finset.univ) => ht i)
      simp only [← Finset.mul_sum] at hts
      have hsum : (∑ i, norm2 (F i)) = sumNorm h 0 F := by simp only [sumNorm, J_zero]
      rw [hsum] at hts
      nlinarith only [hs, hts]
    _ ≤ (A+3*(A+D)*(1+Z+A))*h*(2*sobNorm h 0 F) := by
      gcongr
      exact sumNorm_three_le _ _ _
    _ = _ := by ring

lemma dirDeriv_norm (h : ℝ) (hh : 0 ≤ h) (α β : X) (i : Fin 3) (f : S) :
    norm2 (dirDeriv h α β i f) ≤
      h*(1+‖((α i : ℂ)+Complex.I*(β i : ℂ))‖)*norm2 (J h 1 f) := by
  have hd := semideriv_bound h 1 hh i f
  norm_num only [sub_self, J_zero] at hd
  have hz := norm2_J_one_ge h f
  simp only [dirDeriv]
  calc
    _ ≤ norm2 (((h^2 : ℝ) : ℂ) • d (e i) f) +
        norm2 (((h : ℂ)*((α i : ℂ)+Complex.I*(β i : ℂ))) • f) := norm2_add_le _ _
    _ = h^2*norm2 (d (e i) f) +
        (h*‖((α i : ℂ)+Complex.I*(β i : ℂ))‖)*norm2 f := by
      simp only [norm2_const_smul, norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_nonneg hh, abs_of_nonneg (sq_nonneg h)]
    _ ≤ h*norm2 (J h 1 f)+(h*‖((α i : ℂ)+Complex.I*(β i : ℂ))‖)*norm2 (J h 1 f) := by
      have hd' := mul_le_mul_of_nonneg_left hd hh
      have hz' := mul_le_mul_of_nonneg_left hz (mul_nonneg hh (norm_nonneg ((α i : ℂ)+Complex.I*(β i : ℂ))))
      nlinarith only [hd', hz']
    _ = _ := by ring

lemma lowerDir_norm (h : ℝ) (hh : 0 ≤ h) (hh1 : h ≤ 1) (α β : X)
    (a : Fin 3 → X → ℂ) (v : X → ℂ)
    (ha : ∀ i,(a i).HasTemperateGrowth) (hv : v.HasTemperateGrowth)
    (A V Z : ℝ) (hA : 0≤A) (hV : 0≤V)
    (haA : ∀ i x,‖a i x‖≤A) (hvV : ∀ x,‖v x‖≤V)
    (hz : ∀ i,‖((α i : ℂ)+Complex.I*(β i : ℂ))‖≤Z) (f : S) :
    norm2 (lowerDir h α β a v f) ≤ (3*A*(1+Z)+V)*h*norm2 (J h 1 f) := by
  have hd (i : Fin 3) : norm2 (mult (a i) (dirDeriv h α β i f)) ≤
      A*(h*(1+Z)*norm2 (J h 1 f)) := by
    apply (norm2_mult (a i) (ha i) A (haA i) _).trans
    apply mul_le_mul_of_nonneg_left _ hA
    apply (dirDeriv_norm h hh α β i f).trans
    exact mul_le_mul_of_nonneg_right
      (mul_le_mul_of_nonneg_left (add_le_add_right (hz i) 1) hh) (norm2_nonneg _)
  have hs := norm2_sum_le Finset.univ (fun i : Fin 3 => mult (a i) (dirDeriv h α β i f))
  have hs' := Finset.sum_le_sum (s := Finset.univ) (fun i _ => hd i)
  norm_num only [Finset.sum_const,Finset.card_univ,Fintype.card_fin,nsmul_eq_mul] at hs'
  have hv' := norm2_mult v hv V hvV f
  have hn := norm2_J_one_ge h f
  have hsq : h^2≤h := by nlinarith
  have hv'' : h^2*norm2 (mult v f) ≤ h*V*norm2 (J h 1 f) := by
    calc
      _ ≤ h^2*(V*norm2 f) := mul_le_mul_of_nonneg_left hv' (sq_nonneg h)
      _ ≤ h*(V*norm2 (J h 1 f)) :=
        (mul_le_mul_of_nonneg_right hsq (mul_nonneg hV (norm2_nonneg _))).trans
          (mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_left hn hV) hh)
      _ = _ := by ring
  have ht := norm2_add_le (∑ i : Fin 3,mult (a i) (dirDeriv h α β i f))
    (((h^2 : ℝ) : ℂ) • mult v f)
  rw [norm2_const_smul,Complex.norm_real,Real.norm_eq_abs,abs_of_nonneg (sq_nonneg h)] at ht
  change norm2 ((∑ i : Fin 3,mult (a i) (dirDeriv h α β i f))+
    (((h^2 : ℝ) : ℂ) • mult v f))≤_
  nlinarith only [ht,hs,hs',hv'']

lemma system_difference_bound (h : ℝ) (hh : 0≤h) (hh1 : h≤1) (α β : X)
    (a b : Fin 3 → Fin 4 → Fin 4 → X → ℂ) (v w : Fin 4 → Fin 4 → X → ℂ)
    (ha : ∀ k i j,(a k i j).HasTemperateGrowth) (hb : ∀ k i j,(b k i j).HasTemperateGrowth)
    (hv : ∀ i j,(v i j).HasTemperateGrowth) (hw : ∀ i j,(w i j).HasTemperateGrowth)
    (A V Z : ℝ) (hA : 0≤A) (hV : 0≤V) (hZ : 0≤Z)
    (haA : ∀ k i j x,‖a k i j x‖≤A) (hbA : ∀ k i j x,‖b k i j x‖≤A)
    (hvV : ∀ i j x,‖v i j x‖≤V) (hwV : ∀ i j x,‖w i j x‖≤V)
    (hz : ∀ i,‖((α i : ℂ)+Complex.I*(β i : ℂ))‖≤Z) (U : Fin 4 → S) :
    sobNorm h (-1) (dirSystem h α β a v U-dirSystem h α β b w U) ≤
      16*(3*A*(1+Z)+V)*h*sobNorm h 1 U := by
  let K := (3*A*(1+Z)+V)*h
  have hK : 0≤K := by dsimp [K]; positivity
  have hi (i : Fin 4) : norm2 ((dirSystem h α β a v U-dirSystem h α β b w U) i) ≤
      2*K*sumNorm h 1 U := by
    have he : (dirSystem h α β a v U-dirSystem h α β b w U) i =
        (∑ j,lowerDir h α β (fun k => a k i j) (v i j) (U j))-
        (∑ j,lowerDir h α β (fun k => b k i j) (w i j) (U j)) := by
      simp only [Pi.sub_apply,dirSystem]; abel
    rw [he]
    have hn : ∀ f : S,norm2 (-f)=norm2 f := by intro f; simp only [norm2,map_neg,norm_neg]
    rw [sub_eq_add_neg]
    apply (norm2_add_le _ _).trans
    rw [hn]
    have h1 := (norm2_sum_le Finset.univ (fun j => lowerDir h α β (fun k => a k i j) (v i j) (U j))).trans
      (Finset.sum_le_sum (fun j _ => lowerDir_norm h hh hh1 α β (fun k => a k i j) (v i j)
        (fun k => ha k i j) (hv i j) A V Z hA hV (fun k => haA k i j) (hvV i j) hz (U j)))
    have h2 := (norm2_sum_le Finset.univ (fun j => lowerDir h α β (fun k => b k i j) (w i j) (U j))).trans
      (Finset.sum_le_sum (fun j _ => lowerDir_norm h hh hh1 α β (fun k => b k i j) (w i j)
        (fun k => hb k i j) (hw i j) A V Z hA hV (fun k => hbA k i j) (hwV i j) hz (U j)))
    simp only [← Finset.mul_sum] at h1 h2
    change _≤2*K*(∑ j,norm2 (J h 1 (U j)))
    dsimp [K]
    linarith only [h1,h2]
  have hn := Finset.sum_le_sum (s := Finset.univ) (fun i _ =>
    (norm2_J_nonpos h (-1) (by norm_num) _).trans (hi i))
  norm_num only [Finset.sum_const,Finset.card_univ,Fintype.card_fin,nsmul_eq_mul] at hn
  apply (sobNorm_le_sumNorm h (-1) _).trans
  change sumNorm h (-1) _≤_
  apply hn.trans
  have hf := mul_le_mul_of_nonneg_left (sumNorm_four_le h 1 U) (by positivity : 0≤4*(2*K))
  dsimp [K] at hf
  nlinarith only [hf]

/-- The exact compact comparison estimate: the common second-order principal
part cancels, and the h factor in its actual lower-order forcing cancels the
Carleman 1/h loss. This dependency does not assert that the physical DN transfer
has already supplied the forcing identity. -/
theorem compact_comparison_estimate (R : ℝ) (hR : 1≤R) (α β : X) (hα : α≠0)
    (a b : Fin 3 → Fin 4 → Fin 4 → X → ℂ) (v w : Fin 4 → Fin 4 → X → ℂ)
    (ha : ∀ k i j,(a k i j).HasTemperateGrowth) (hb : ∀ k i j,(b k i j).HasTemperateGrowth)
    (hv : ∀ i j,(v i j).HasTemperateGrowth) (hw : ∀ i j,(w i j).HasTemperateGrowth)
    (A V Z : ℝ) (hA : 0≤A) (hV : 0≤V) (hZ : 0≤Z)
    (haA : ∀ k i j x,‖a k i j x‖≤A) (hbA : ∀ k i j x,‖b k i j x‖≤A)
    (hvV : ∀ i j x,‖v i j x‖≤V) (hwV : ∀ i j x,‖w i j x‖≤V)
    (hz : ∀ i,‖((α i : ℂ)+Complex.I*(β i : ℂ))‖≤Z) :
    ∃ C h₀ : ℝ,0<C ∧ 0<h₀ ∧ ∀ h : ℝ,0<h → h≤h₀ →
      ∀ U W : Fin 4 → S,(∀ i,BallSupported R (W i)) →
      dirSystem h α β b w W=dirSystem h α β a v U-dirSystem h α β b w U →
      sobNorm h 1 W≤C*sobNorm h 1 U := by
  obtain ⟨C,h₀,hC,hh₀,hest⟩ := system_four_direction R hR α β hα b w hb hw A V hA hV hbA hwV
  let B := 16*(3*A*(1+Z)+V)
  have hB : 0≤B := by dsimp [B]; positivity
  refine ⟨C*(1+B),min h₀ 1,by positivity,lt_min hh₀ zero_lt_one,fun h hh hsmall U W hW he => ?_⟩
  have h1 := hest h hh (hsmall.trans (min_le_left _ _)) W hW
  rw [he] at h1
  have h2 := system_difference_bound h hh.le (hsmall.trans (min_le_right _ _)) α β a b v w ha hb hv hw
    A V Z hA hV hZ haA hbA hvV hwV hz U
  calc
    _ ≤ (C/h)*sobNorm h (-1) (dirSystem h α β a v U-dirSystem h α β b w U) := h1
    _ ≤ (C/h)*(B*h*sobNorm h 1 U) := mul_le_mul_of_nonneg_left h2 (by positivity)
    _ = C*B*sobNorm h 1 U := by field_simp
    _ ≤ C*(1+B)*sobNorm h 1 U := by
      apply mul_le_mul_of_nonneg_right _ (Real.sqrt_nonneg _)
      gcongr
      linarith
end ElasticityPhysicalEstimate

namespace ElasticityPhysicalAlgebra
open ElasticityBessel ElasticitySchwartzCarleman ElasticityNegativeOrder
abbrev X := ElasticityBessel.X
abbrev Smooth := ElasticityAugmented.Smooth

lemma temperate_fderiv (a : X → ℂ) (ha : a.HasTemperateGrowth) :
    (fderiv ℝ a).HasTemperateGrowth := by
  refine ⟨ha.1.fderiv_right (by simp), fun N => ?_⟩
  obtain ⟨k, C, h⟩ := ha.2 (N+1)
  refine ⟨k, C, fun x => ?_⟩
  simpa only [iteratedFDeriv_succ_eq_comp_right, Function.comp_apply, LinearIsometryEquiv.norm_map] using h x

lemma temperate_partial (a : X → ℂ) (ha : a.HasTemperateGrowth) (v : X) :
    (fun x => fderiv ℝ a x v).HasTemperateGrowth := by
  exact (ContinuousLinearMap.apply ℝ ℂ v).hasTemperateGrowth.comp (temperate_fderiv a ha)

/-- The genuine embedding of Schwartz functions into the smooth differential algebra. -/
def toSmooth : S →ₗ[ℂ] Smooth where
  toFun f := ⟨f, f.smooth (⊤ : ℕ∞)⟩
  map_add' f g := by apply Subtype.ext; rfl
  map_smul' a f := by apply Subtype.ext; rfl

@[simp] lemma toSmooth_apply (f : S) (x : X) : (toSmooth f : X → ℂ) x = f x := rfl

lemma toSmooth_injective : Function.Injective toSmooth := by
  intro f g h
  ext x
  exact congrArg (fun a : Smooth => (a : X → ℂ) x) h

lemma toSmooth_d (f : S) (i : Fin 3) :
    toSmooth (d (e i) f) = ElasticityAugmented.coord i (toSmooth f) := by
  apply Subtype.ext
  rfl

lemma toSmooth_mult (a : Smooth) (ha : (a : X → ℂ).HasTemperateGrowth) (f : S) :
    toSmooth (mult a f) = a*toSmooth f := by
  apply Subtype.ext
  funext x
  exact mult_apply a ha f x

/-- Constant complex phase shift, still an actual differential operator on Schwartz maps. -/
def shiftD (z : Fin 3 → ℂ) (i : Fin 3) : S →ₗ[ℂ] S := d (e i) + z i • LinearMap.id

lemma shiftD_apply (z : Fin 3 → ℂ) (i : Fin 3) (f : S) :
    shiftD z i f = d (e i) f + z i • f := rfl

lemma toSmooth_shiftD (z : Fin 3 → ℂ) (i : Fin 3) (f : S) :
    toSmooth (shiftD z i f) = ElasticityAugmented.shifted ElasticityAugmented.coord z i (toSmooth f) := by
  simp only [shiftD_apply, map_add, map_smul, toSmooth_d, ElasticityAugmented.shifted_apply]

/-- The conjugated physical stress-divergence, without treating its shifted derivatives as derivations. -/
def physical (z : Fin 3 → ℂ) (lam m : X → ℂ) (u : Fin 3 → S) (i : Fin 3) : S :=
  shiftD z i (mult lam (∑ j, shiftD z j (u j))) +
    ∑ j, shiftD z j (mult m (shiftD z j (u i) + shiftD z i (u j)))

lemma toSmooth_physical (z : Fin 3 → ℂ) (lam m : Smooth)
    (hl : (lam : X → ℂ).HasTemperateGrowth) (hm : (m : X → ℂ).HasTemperateGrowth)
    (u : Fin 3 → S) (i : Fin 3) :
    toSmooth (physical z lam m u i) =
      ElasticityAugmented.LT (ElasticityAugmented.shifted ElasticityAugmented.coord z)
        lam m (fun j => toSmooth (u j)) i := by
  simp only [physical, ElasticityAugmented.LT, ElasticityAugmented.divT, map_add, map_sum,
    toSmooth_shiftD, toSmooth_mult lam hl, toSmooth_mult m hm,
    Finset.mul_sum, mul_add]

def phase (h : ℝ) (α β : X) (i : Fin 3) : ℂ :=
  ((α i : ℂ)+Complex.I*(β i : ℂ))/(h : ℂ)

lemma dirDeriv_eq_shiftD (h : ℝ) (hh : h ≠ 0) (α β : X) (i : Fin 3) (f : S) :
    dirDeriv h α β i f = ((h^2 : ℝ) : ℂ) • shiftD (phase h α β) i f := by
  rw [dirDeriv, shiftD_apply, smul_add, smul_smul]
  congr 1
  congr 1
  simp only [phase]
  have hc : (h : ℂ) ≠ 0 := by exact_mod_cast hh
  push_cast
  field_simp [hc]

def lapShift (z : Fin 3 → ℂ) (f : S) : S := ∑ i, shiftD z i (shiftD z i f)

def divShift (z : Fin 3 → ℂ) (u : Fin 3 → S) : S := ∑ i, shiftD z i (u i)

lemma toSmooth_lapShift (z : Fin 3 → ℂ) (f : S) :
    toSmooth (lapShift z f) =
      ElasticityAugmented.lapT (ElasticityAugmented.shifted ElasticityAugmented.coord z) (toSmooth f) := by
  simp only [lapShift, ElasticityAugmented.lapT, map_sum, toSmooth_shiftD]

lemma toSmooth_divShift (z : Fin 3 → ℂ) (u : Fin 3 → S) :
    toSmooth (divShift z u) =
      ElasticityAugmented.divT (ElasticityAugmented.shifted ElasticityAugmented.coord z) (fun i => toSmooth (u i)) := by
  simp only [divShift, ElasticityAugmented.divT, map_sum, toSmooth_shiftD]

lemma Pdir_eq_lapShift (h : ℝ) (hh : h ≠ 0) (α β : X) (f : S) :
    Pdir h α β f = -((h^2 : ℝ) : ℂ) • lapShift (phase h α β) f := by
  ext x
  simp only [Pdir, lapShift, shiftD_apply, map_add, map_smul, lap_apply,
    d_sum_basis α f, d_sum_basis β f,
    EuclideanSpace.real_norm_sq_eq, PiLp.inner_apply, RCLike.inner_apply,
    conj_trivial, Fin.sum_univ_three, add_apply, sub_apply,
    smul_apply, smul_eq_mul, phase]
  have hc : (h : ℂ) ≠ 0 := by exact_mod_cast hh
  push_cast
  field_simp [hc]
  ring_nf
  simp only [Complex.I_sq]
  ring

lemma shiftD_supported (z : Fin 3 → ℂ) (i : Fin 3) {R : ℝ} {f : S}
    (hf : BallSupported R f) : BallSupported R (shiftD z i f) :=
  (hf.d _).add (hf.smul _)

lemma divShift_supported (z : Fin 3 → ℂ) {R : ℝ} (u : Fin 3 → S)
    (hu : ∀ i, BallSupported R (u i)) : BallSupported R (divShift z u) := by
  exact BallSupported.sum _ _ (fun i _ => shiftD_supported z i (hu i))

end ElasticityPhysicalAlgebra

open scoped BigOperators
namespace ElasticityAugmented
variable {A : Type*} [CommRing A] [Algebra ℂ A]
variable (D : Fin 3 → Derivation ℂ A A) (T : Fin 3 → A →ₗ[ℂ] A)

def coeffA (lam m n o : A) (k : Fin 3) : Fin 4 → Fin 4 → A :=
  Fin.cons
    (Fin.cons (2*o*(D k (lam+m)-(lam+m)*n*D k m))
      (fun j => 2*o*(D k (D j m)-2*n*D k m*D j m)))
    (fun i => Fin.cons (if k=i then (lam+m)*n else 0)
      (fun j => (if j=i then n*D k m else 0) + (if k=i then n*D j m else 0)))

def coeffV (lam m n o : A) : Fin 4 → Fin 4 → A :=
  Fin.cons
    (Fin.cons (o*(lap D lam-2*n*(∑ i, D i m*D i lam))) (fun _ => 0))
    (fun i => Fin.cons (n*D i lam) (fun _ => 0))

def normalizedPair (lam m n o : A) (u : Fin 3 → A) (b : A) : Fin 4 → A :=
  Fin.cons (o*(ST D T lam m u b-2*n*(∑ i, D i m*RT D T lam m u b i)))
    (fun i => n*RT D T lam m u b i)

lemma normalizedPair_matrix (lam m n o : A) (hn : n*m=1) (ho : o*(lam+m+m)=1)
    (U : Fin 4 → A) (i : Fin 4) :
    normalizedPair D T lam m n o (fun j => U j.succ) (U 0) i =
      lapT T (U i) + (∑ k, ∑ j, coeffA D lam m n o k i j * T k (U j)) +
        (∑ j, coeffV D lam m n o i j*U j) := by
  refine Fin.cases ?_ (fun i => ?_) i
  · change o*(ST D T lam m _ _-2*n*(∑ i, D i m*RT D T lam m _ _ i)) = _
    rw [normalized_scalar D T lam m n o hn ho]
    simp only [coeffA, coeffV, Fin.sum_univ_succ, Fin.cons_zero, Fin.cons_succ,
      zero_mul, Finset.sum_const_zero, add_zero, Finset.sum_add_distrib]
    ring
  · change n*RT D T lam m _ _ i = _
    rw [normalized_vector D T lam m n hn]
    simp only [coeffA, coeffV, Fin.sum_univ_succ, Fin.cons_zero, Fin.cons_succ,
      zero_mul, Finset.sum_const_zero, add_zero, add_mul, ite_mul,
      Finset.sum_add_distrib, Finset.sum_ite_eq', Finset.mem_univ, ite_true]
    ring

end ElasticityAugmented

open MeasureTheory Complex SchwartzMap
open scoped BigOperators FourierTransform SchwartzMap LineDeriv ENNReal
open Set MeasureTheory SchwartzMap
open scoped BigOperators SchwartzMap Topology
namespace ElasticityPhysicalEstimate

section
open ElasticityBessel ElasticitySchwartzCarleman ElasticityNegativeOrder ElasticityPhysicalAlgebra
open ElasticityAugmented (coord coeffA coeffV normalizedPair shifted)

/-- The actual normalized matrix coefficients, with the sign of the Carleman operator. -/
def aPhys (lam m n o : Smooth) (k : Fin 3) (i j : Fin 4) : X → ℂ :=
  -((coeffA coord lam m n o k i j : Smooth) : X → ℂ)
def vPhys (lam m n o : Smooth) (i j : Fin 4) : X → ℂ :=
  -((coeffV coord lam m n o i j : Smooth) : X → ℂ)
def cPhys (m n : Smooth) (i : Fin 3) : X → ℂ := (-2*n*coord i m : Smooth)

lemma aPhys_growth (lam m n o : Smooth)
    (ha : ∀ k i j, ((coeffA coord lam m n o k i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (k : Fin 3) (i j : Fin 4) : (aPhys lam m n o k i j).HasTemperateGrowth :=
  (ha k i j).neg
lemma vPhys_growth (lam m n o : Smooth)
    (hv : ∀ i j, ((coeffV coord lam m n o i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (i j : Fin 4) : (vPhys lam m n o i j).HasTemperateGrowth :=
  (hv i j).neg

lemma toSmooth_aPhys (lam m n o : Smooth)
    (ha : ∀ k i j, ((coeffA coord lam m n o k i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (k : Fin 3) (i j : Fin 4) (f : S) :
    toSmooth (mult (aPhys lam m n o k i j) f) = -coeffA coord lam m n o k i j*toSmooth f := by
  exact toSmooth_mult (-coeffA coord lam m n o k i j) ((ha k i j).neg) f
lemma toSmooth_vPhys (lam m n o : Smooth)
    (hv : ∀ i j, ((coeffV coord lam m n o i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (i j : Fin 4) (f : S) :
    toSmooth (mult (vPhys lam m n o i j) f) = -coeffV coord lam m n o i j*toSmooth f := by
  exact toSmooth_mult (-coeffV coord lam m n o i j) ((hv i j).neg) f

lemma toSmooth_dirSystem (h : ℝ) (hh : h ≠ 0) (α β : X)
    (lam m n o : Smooth) (hn : n*m=1) (ho : o*(lam+m+m)=1)
    (ha : ∀ k i j, ((coeffA coord lam m n o k i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hv : ∀ i j, ((coeffV coord lam m n o i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (U : Fin 4 → S) (i : Fin 4) :
    toSmooth (dirSystem h α β (aPhys lam m n o) (vPhys lam m n o) U i) =
      -((h^2 : ℝ) : ℂ) • normalizedPair coord (shifted coord (phase h α β)) lam m n o
        (fun j => toSmooth (U j.succ)) (toSmooth (U 0)) i := by
  rw [ElasticityAugmented.normalizedPair_matrix coord _ lam m n o hn ho (fun j => toSmooth (U j)) i]
  simp only [dirSystem, lowerDir, Pdir_eq_lapShift h hh, dirDeriv_eq_shiftD h hh,
    map_add, map_sum, map_smul, toSmooth_shiftD,
    toSmooth_aPhys lam m n o ha, toSmooth_vPhys lam m n o hv,
    smul_add, Finset.smul_sum, neg_smul]
  simp only [map_neg, map_smul, toSmooth_lapShift, Fin.sum_univ_succ,
    Algebra.smul_def]
  ring

lemma toSmooth_forcing (h : ℝ) (hh : h ≠ 0) (α β : X)
    (m n o : Smooth)
    (hn : (n : X → ℂ).HasTemperateGrowth) (ho : (o : X → ℂ).HasTemperateGrowth)
    (hc : ∀ i, (cPhys m n i).HasTemperateGrowth)
    (F : Fin 3 → S) (i : Fin 4) :
    toSmooth (augmentedForcing h α β n o (cPhys m n) F i) =
      ((h^2 : ℝ) : ℂ) • Fin.cons (α := fun _ : Fin 4 => Smooth)
        (o*(ElasticityAugmented.divT (shifted coord (phase h α β)) (fun j => toSmooth (F j)) -
          2*n*(∑ j, coord j m*toSmooth (F j))))
        (fun j => n*toSmooth (F j)) i := by
  refine Fin.cases ?_ (fun i => ?_) i
  · simp only [augmentedForcing, Fin.cons_zero, map_sum, map_add, map_smul,
      dirDeriv_eq_shiftD h hh, toSmooth_mult o ho, toSmooth_shiftD]
    have hcm (j : Fin 3) : toSmooth (mult (cPhys m n j) (F j)) =
        (-2*n*coord j m)*toSmooth (F j) := toSmooth_mult _ (hc j) _
    simp only [hcm, ElasticityAugmented.divT, Fin.sum_univ_three, Algebra.smul_def]
    ring
  · simp only [augmentedForcing, Fin.cons_succ, map_smul, toSmooth_mult n hn]

lemma physical_system_identity (h : ℝ) (hh : h ≠ 0) (α β : X)
    (lam m n o : Smooth) (hinv : n*m=1) (hoinv : o*(lam+m+m)=1)
    (hl : (lam : X → ℂ).HasTemperateGrowth) (hm : (m : X → ℂ).HasTemperateGrowth)
    (hn : (n : X → ℂ).HasTemperateGrowth) (ho : (o : X → ℂ).HasTemperateGrowth)
    (ha : ∀ k i j, ((coeffA coord lam m n o k i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hv : ∀ i j, ((coeffV coord lam m n o i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hc : ∀ i, (cPhys m n i).HasTemperateGrowth)
    (u : Fin 3 → S) :
    dirSystem h α β (aPhys lam m n o) (vPhys lam m n o)
        (Fin.cons (divShift (phase h α β) u) u) =
      fun i => -augmentedForcing h α β n o (cPhys m n) (physical (phase h α β) lam m u) i := by
  funext i
  apply toSmooth_injective
  rw [map_neg, toSmooth_dirSystem h hh α β lam m n o hinv hoinv ha hv,
    toSmooth_forcing h hh α β m n o hn ho hc]
  simp only [Fin.cons_zero, Fin.cons_succ, toSmooth_divShift,
    toSmooth_physical _ lam m hl hm, neg_smul]
  congr 1
  refine Fin.cases ?_ (fun i => ?_) i
  · simp only [normalizedPair, Fin.cons_zero]
    rw [ElasticityAugmented.shifted_physical_divergence coord _ _ _ _ ElasticityAugmented.coord_commute]
    simp only [ElasticityAugmented.shifted_physical_expansion coord _ _ _ _ ElasticityAugmented.coord_commute]
  · simp only [normalizedPair, Fin.cons_succ,
      ElasticityAugmented.shifted_physical_expansion coord _ _ _ _ ElasticityAugmented.coord_commute]

lemma norm_tail_le (h : ℝ) (b : S) (u : Fin 3 → S) :
    sobNorm h 0 u ≤ sobNorm h 1 (Fin.cons b u) := by
  unfold sobNorm
  apply Real.sqrt_le_sqrt
  rw [Fin.sum_univ_succ]
  simp only [J_zero]
  exact (Finset.sum_le_sum (fun i (_ : i ∈ Finset.univ) =>
    pow_le_pow_left₀ (norm2_nonneg (u i)) (norm2_J_one_ge h (u i)) 2)).trans
      (le_add_of_nonneg_left (sq_nonneg _))

/-- The physical adjoint-test estimate obtained from the actual scalar-principal
augmented operator. All coefficients and forcing terms are explicit. -/
theorem physical_test_estimate (R : ℝ) (hR : 1 ≤ R) (α β : X) (hα : α ≠ 0)
    (lam m n o : Smooth) (hinv : n*m=1) (hoinv : o*(lam+m+m)=1)
    (hl : (lam : X → ℂ).HasTemperateGrowth) (hm : (m : X → ℂ).HasTemperateGrowth)
    (hn : (n : X → ℂ).HasTemperateGrowth) (ho : (o : X → ℂ).HasTemperateGrowth)
    (ha : ∀ k i j, ((coeffA coord lam m n o k i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hv : ∀ i j, ((coeffV coord lam m n o i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hc : ∀ i, (cPhys m n i).HasTemperateGrowth)
    (M V A D Z : ℝ) (hM : 0 ≤ M) (hV : 0 ≤ V) (hA : 0 ≤ A) (hD : 0 ≤ D) (hZ : 0 ≤ Z)
    (haM : ∀ k i j x, ‖aPhys lam m n o k i j x‖ ≤ M)
    (hvV : ∀ i j x, ‖vPhys lam m n o i j x‖ ≤ V)
    (hnA : ∀ x, ‖(n : X → ℂ) x‖ ≤ A) (hoA : ∀ x, ‖(o : X → ℂ) x‖ ≤ A)
    (hcA : ∀ i x, ‖cPhys m n i x‖ ≤ A)
    (hod : ∀ x i, ‖fderiv ℝ (o : X → ℂ) x (e i)‖ ≤ D)
    (hz : ∀ i, ‖((α i : ℂ)+Complex.I*(β i : ℂ))‖ ≤ Z) :
    ∃ C h₀ : ℝ, 0 < C ∧ 0 < h₀ ∧ ∀ h : ℝ, 0 < h → h ≤ h₀ →
      ∀ u : Fin 3 → S, (∀ i, BallSupported R (u i)) →
        sobNorm h 0 u ≤ C*sobNorm h 0 (physical (phase h α β) lam m u) := by
  obtain ⟨C, h₀, hC, hh₀, hest⟩ := system_four_direction R hR α β hα
    (aPhys lam m n o) (vPhys lam m n o) (aPhys_growth lam m n o ha)
    (vPhys_growth lam m n o hv) M V hM hV haM hvV
  let K := 2*(A+3*(A+D)*(1+Z+A))
  have hK : 0 ≤ K := by dsimp [K]; positivity
  refine ⟨C*(1+K), min h₀ 1, mul_pos hC (by positivity), lt_min hh₀ zero_lt_one, ?_⟩
  intro h hh hsmall u hu
  have hs0 := (le_min_iff.mp hsmall).1
  have hs1 := (le_min_iff.mp hsmall).2
  let F := physical (phase h α β) lam m u
  have hb := forcing_bound h hh.le hs1 α β n o (cPhys m n) hn ho hc A D Z hA hD hZ hnA hoA hcA
    (fun x i => (mul_le_mul_of_nonneg_right hs1 (norm_nonneg _)).trans (by simpa using hod x i)) hz F
  have hu' : ∀ i, BallSupported R (Fin.cons (α := fun _ : Fin 4 => S) (divShift (phase h α β) u) u i) := by
    intro i
    exact Fin.cases (divShift_supported _ u hu) hu i
  have huest := hest h hh hs0 (Fin.cons (divShift (phase h α β) u) u) hu'
  rw [physical_system_identity h hh.ne' α β lam m n o hinv hoinv hl hm hn ho ha hv hc u] at huest
  have hneg : sobNorm h (-1) (fun i => -augmentedForcing h α β n o (cPhys m n) F i) =
      sobNorm h (-1) (augmentedForcing h α β n o (cPhys m n) F) := by
    simpa only [neg_one_smul, norm_neg, norm_one, one_mul] using
      sobNorm_smul h (-1) (-1 : ℂ) (augmentedForcing h α β n o (cPhys m n) F)
  change sobNorm h 1 (Fin.cons (divShift (phase h α β) u) u) ≤
    (C/h)*sobNorm h (-1) (fun i => -augmentedForcing h α β n o (cPhys m n) F i) at huest
  rw [hneg] at huest
  calc
    _ ≤ sobNorm h 1 (Fin.cons (divShift (phase h α β) u) u) := norm_tail_le h _ u
    _ ≤ (C/h)*sobNorm h (-1) (augmentedForcing h α β n o (cPhys m n) F) := huest
    _ ≤ (C/h)*(K*h*sobNorm h 0 F) := mul_le_mul_of_nonneg_left hb (div_nonneg hC.le hh.le)
    _ = C*K*sobNorm h 0 F := by field_simp
    _ ≤ C*(1+K)*sobNorm h 0 F :=
      mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_left (by linarith : K ≤ 1+K) hC.le)
        (Real.sqrt_nonneg _)

end

open ElasticityBessel ElasticitySchwartzCarleman ElasticityNegativeOrder ElasticityPhysicalAlgebra
open ElasticityAugmented (coord coeffA coeffV)

lemma deriv_zero_on {B : Set X} (hB : IsOpen B) (f : S) (hf : EqOn (f : X → ℂ) 0 B)
    (v : X) : EqOn (d v f : X → ℂ) 0 B := by
  intro x hx
  have he : (f : X → ℂ)=ᶠ[𝓝 x] 0 := by
    filter_upwards [hB.mem_nhds hx] with y hy using hf hy
  change fderiv ℝ (f : X → ℂ) x v=0
  rw [he.fderiv_eq]
  simp only [fderiv_zero]
  rfl

lemma dirDeriv_zero_on {B : Set X} (hB : IsOpen B) (h : ℝ) (α β : X)
    (f : S) (hf : EqOn (f : X → ℂ) 0 B) (i : Fin 3) :
    EqOn (dirDeriv h α β i f : X → ℂ) 0 B := by
  intro x hx
  simp only [dirDeriv,add_apply,smul_apply,deriv_zero_on hB f hf (e i) hx,hf hx,
    smul_zero,add_zero,Pi.zero_apply]

/-- A local physical solution satisfies the actual normalized four-system,
including its scalar row, on the same open set. -/
theorem physical_dirSystem_on {B : Set X} (hB : IsOpen B)
    (h : ℝ) (hh : h≠0) (α β : X)
    (lam m n o : Smooth) (hinv : n*m=1) (hoinv : o*(lam+m+m)=1)
    (hl : (lam : X → ℂ).HasTemperateGrowth) (hm : (m : X → ℂ).HasTemperateGrowth)
    (hn : (n : X → ℂ).HasTemperateGrowth) (ho : (o : X → ℂ).HasTemperateGrowth)
    (ha : ∀ k i j,((coeffA coord lam m n o k i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hv : ∀ i j,((coeffV coord lam m n o i j : Smooth) : X → ℂ).HasTemperateGrowth)
    (hc : ∀ i,(cPhys m n i).HasTemperateGrowth)
    (u : Fin 3 → S) (hu : ∀ i,EqOn (physical (phase h α β) lam m u i : X → ℂ) 0 B) :
    ∀ i,EqOn (dirSystem h α β (aPhys lam m n o) (vPhys lam m n o)
      (Fin.cons (divShift (phase h α β) u) u) i : X → ℂ) 0 B := by
  rw [physical_system_identity h hh α β lam m n o hinv hoinv hl hm hn ho ha hv hc u]
  intro i x hx
  refine Fin.cases ?_ (fun i => ?_) i
  · simp only [augmentedForcing,Fin.cons_zero,neg_apply,mult_apply _ ho,
      sum_apply,add_apply,smul_apply,mult_apply _ (hc _),
      dirDeriv_zero_on hB h α β _ (hu _) _ hx,hu _ hx,Pi.zero_apply,
      smul_zero,mul_zero,add_zero,Finset.sum_const_zero,neg_zero]
  · simp only [augmentedForcing,Fin.cons_succ,neg_apply,smul_apply,
      mult_apply _ hn,hu _ hx,Pi.zero_apply,mul_zero,smul_zero,neg_zero]

lemma dirSystem_sub (h : ℝ) (α β : X)
    (a : Fin 3 → Fin 4 → Fin 4 → X → ℂ) (v : Fin 4 → Fin 4 → X → ℂ)
    (U W : Fin 4 → S) :
    dirSystem h α β a v (U-W)=dirSystem h α β a v U-dirSystem h α β a v W := by
  have hd (i : Fin 3) (f g : S) : dirDeriv h α β i (f-g)=dirDeriv h α β i f-dirDeriv h α β i g := by
    simp only [dirDeriv,map_sub,smul_sub]
    module
  have hl (a : Fin 3 → X → ℂ) (v : X → ℂ) (f g : S) :
      lowerDir h α β a v (f-g)=lowerDir h α β a v f-lowerDir h α β a v g := by
    simp only [lowerDir,hd,map_sub,smul_sub,Finset.sum_sub_distrib]
    abel
  have hp (f g : S) : Pdir h α β (f-g)=Pdir h α β f-Pdir h α β g := by
    simp only [Pdir,map_sub,smul_sub]
    module
  funext i
  simp only [dirSystem,Pi.sub_apply,hp,hl,Finset.sum_sub_distrib]
  abel

lemma deriv_supported {K : Set X} (f : S) (hf : tsupport (f : X → ℂ)⊆K) (v : X) :
    tsupport (d v f : X → ℂ)⊆K :=
  (tsupport_fderiv_apply_subset ℝ v).trans hf

lemma dirSystem_zero_outside {K : Set X} (h : ℝ) (α β : X)
    (a : Fin 3 → Fin 4 → Fin 4 → X → ℂ) (v : Fin 4 → Fin 4 → X → ℂ)
    (ha : ∀ k i j,(a k i j).HasTemperateGrowth) (hv : ∀ i j,(v i j).HasTemperateGrowth)
    (W : Fin 4 → S) (hW : ∀ i,tsupport (W i : X → ℂ)⊆K) {x : X} (hx : x∉K) (i : Fin 4) :
    dirSystem h α β a v W i x=0 := by
  have hz (f : S) (hf : tsupport (f : X → ℂ)⊆K) : f x=0 :=
    image_eq_zero_of_notMem_tsupport (fun ht => hx (hf ht))
  have hd (i : Fin 4) (q : X) : d q (W i) x=0 := hz _ (deriv_supported _ (hW i) q)
  have hdd (i : Fin 4) (q r : X) : d q (d r (W i)) x=0 :=
    hz _ (deriv_supported _ (deriv_supported _ (hW i) r) q)
  simp only [dirSystem,Pdir,lowerDir,dirDeriv,lap_apply,
    add_apply,sub_apply,smul_apply,sum_apply,mult_apply _ (ha _ _ _),mult_apply _ (hv _ _),
    hd,hdd,hz _ (hW _),smul_zero,mul_zero,add_zero,sub_zero,Finset.sum_const_zero]

lemma dirSystem_difference_zero_outside {K : Set X} (h : ℝ) (α β : X)
    (a b : Fin 3 → Fin 4 → Fin 4 → X → ℂ) (v w : Fin 4 → Fin 4 → X → ℂ)
    (ha : ∀ k i j,(a k i j).HasTemperateGrowth) (hb : ∀ k i j,(b k i j).HasTemperateGrowth)
    (hv : ∀ i j,(v i j).HasTemperateGrowth) (hw : ∀ i j,(w i j).HasTemperateGrowth)
    (hea : ∀ k i j x,x∉K → a k i j x=b k i j x)
    (hev : ∀ i j x,x∉K → v i j x=w i j x)
    (U : Fin 4 → S) {x : X} (hx : x∉K) (i : Fin 4) :
    (dirSystem h α β a v U-dirSystem h α β b w U) i x=0 := by
  simp only [Pi.sub_apply,sub_apply,dirSystem,lowerDir,add_apply,sum_apply,smul_apply,
    mult_apply _ (ha _ _ _),mult_apply _ (hb _ _ _),mult_apply _ (hv _ _),mult_apply _ (hw _ _),
    hea _ _ _ x hx,hev _ _ x hx,sub_self]

/-- A genuine local pair of homogeneous normalized solutions with compact
supported difference has the global compact forcing identity used by Carleman.
Only equality of the lower-order coefficients off K is required; no artificial
second-order difference term is introduced. -/
theorem compact_forcing_identity {B K : Set X} (hKB : K⊆B) (h : ℝ) (α β : X)
    (a b : Fin 3 → Fin 4 → Fin 4 → X → ℂ) (v w : Fin 4 → Fin 4 → X → ℂ)
    (ha : ∀ k i j,(a k i j).HasTemperateGrowth) (hb : ∀ k i j,(b k i j).HasTemperateGrowth)
    (hv : ∀ i j,(v i j).HasTemperateGrowth) (hw : ∀ i j,(w i j).HasTemperateGrowth)
    (hea : ∀ k i j x,x∉K → a k i j x=b k i j x)
    (hev : ∀ i j x,x∉K → v i j x=w i j x)
    (U V : Fin 4 → S) (hs : ∀ i,tsupport ((V-U) i : X → ℂ)⊆K)
    (hU : ∀ i,EqOn (dirSystem h α β a v U i : X → ℂ) 0 B)
    (hV : ∀ i,EqOn (dirSystem h α β b w V i : X → ℂ) 0 B) :
    dirSystem h α β b w (V-U)=dirSystem h α β a v U-dirSystem h α β b w U := by
  funext i
  ext x
  by_cases hx : x∈K
  · rw [dirSystem_sub]
    simp only [Pi.sub_apply,sub_apply,hU i (hKB hx),hV i (hKB hx),Pi.zero_apply]
  · rw [dirSystem_zero_outside h α β b w hb hw (V-U) hs hx i,
      dirSystem_difference_zero_outside h α β a b v w ha hb hv hw hea hev U hx i]
end ElasticityPhysicalEstimate

end

end OAI
