import OAI.Algebra.AuslanderReiten.Algebras.TCoordinates

namespace OAI

namespace ArExplicit.CocycleData

structure MulMonomial where
  first : TIndex
  second : TIndex
  output : TIndex
  degree : ℕ
  deriving DecidableEq

structure TripleMonomial where
  first : TIndex
  second : TIndex
  third : TIndex
  output : TIndex
  degree : ℕ
  deriving DecidableEq

def multiplication : List MulMonomial := [
  ⟨(false, .e), (false, .e), (false, .e), 0⟩,
  ⟨(false, .e), (false, .x), (false, .x), 0⟩,
  ⟨(false, .x), (false, .e), (false, .x), 0⟩,
  ⟨(false, .e), (false, .y), (false, .y), 0⟩,
  ⟨(false, .y), (false, .e), (false, .y), 0⟩,
  ⟨(false, .e), (false, .z), (false, .z), 0⟩,
  ⟨(false, .z), (false, .e), (false, .z), 0⟩,
  ⟨(false, .e), (false, .u), (false, .u), 0⟩,
  ⟨(false, .u), (false, .f), (false, .u), 0⟩,
  ⟨(false, .e), (false, .v), (false, .v), 0⟩,
  ⟨(false, .v), (false, .f), (false, .v), 0⟩,
  ⟨(false, .f), (false, .t), (false, .t), 0⟩,
  ⟨(false, .t), (false, .e), (false, .t), 0⟩,
  ⟨(false, .f), (false, .j), (false, .j), 0⟩,
  ⟨(false, .j), (false, .e), (false, .j), 0⟩,
  ⟨(false, .f), (false, .f), (false, .f), 0⟩,
  ⟨(false, .f), (false, .n), (false, .n), 0⟩,
  ⟨(false, .n), (false, .f), (false, .n), 0⟩,
  ⟨(false, .x), (false, .y), (false, .z), 1⟩,
  ⟨(false, .y), (false, .x), (false, .z), 0⟩,
  ⟨(false, .x), (false, .u), (false, .v), 0⟩,
  ⟨(false, .y), (false, .u), (false, .v), 0⟩,
  ⟨(false, .t), (false, .x), (false, .j), 0⟩,
  ⟨(false, .t), (false, .y), (false, .j), 2⟩,
  ⟨(false, .u), (false, .t), (false, .y), 0⟩,
  ⟨(false, .u), (false, .t), (false, .x), 1⟩,
  ⟨(false, .v), (false, .t), (false, .z), 1⟩,
  ⟨(false, .u), (false, .j), (false, .z), 0⟩,
  ⟨(false, .t), (false, .u), (false, .n), 0⟩,
  ⟨(false, .t), (false, .u), (false, .n), 1⟩,
  ⟨(false, .n), (false, .t), (false, .j), 1⟩,
  ⟨(false, .u), (false, .n), (false, .v), 0⟩,
  ⟨(false, .e), (true, .e), (true, .e), 0⟩,
  ⟨(true, .e), (false, .e), (true, .e), 0⟩,
  ⟨(false, .e), (true, .x), (true, .x), 0⟩,
  ⟨(true, .x), (false, .e), (true, .x), 0⟩,
  ⟨(false, .e), (true, .y), (true, .y), 0⟩,
  ⟨(true, .y), (false, .e), (true, .y), 0⟩,
  ⟨(false, .e), (true, .z), (true, .z), 0⟩,
  ⟨(true, .z), (false, .e), (true, .z), 0⟩,
  ⟨(true, .u), (false, .e), (true, .u), 0⟩,
  ⟨(true, .v), (false, .e), (true, .v), 0⟩,
  ⟨(false, .e), (true, .t), (true, .t), 0⟩,
  ⟨(false, .e), (true, .j), (true, .j), 0⟩,
  ⟨(false, .x), (true, .x), (true, .e), 0⟩,
  ⟨(true, .x), (false, .x), (true, .e), 0⟩,
  ⟨(false, .x), (true, .z), (true, .y), 0⟩,
  ⟨(true, .z), (false, .x), (true, .y), 1⟩,
  ⟨(true, .v), (false, .x), (true, .u), 0⟩,
  ⟨(false, .x), (true, .j), (true, .t), 0⟩,
  ⟨(false, .y), (true, .y), (true, .e), 0⟩,
  ⟨(true, .y), (false, .y), (true, .e), 0⟩,
  ⟨(false, .y), (true, .z), (true, .x), 1⟩,
  ⟨(true, .z), (false, .y), (true, .x), 0⟩,
  ⟨(true, .v), (false, .y), (true, .u), 0⟩,
  ⟨(false, .y), (true, .j), (true, .t), 2⟩,
  ⟨(false, .z), (true, .z), (true, .e), 0⟩,
  ⟨(true, .z), (false, .z), (true, .e), 0⟩,
  ⟨(true, .x), (false, .u), (true, .t), 1⟩,
  ⟨(true, .y), (false, .u), (true, .t), 0⟩,
  ⟨(true, .z), (false, .u), (true, .j), 0⟩,
  ⟨(false, .u), (true, .u), (true, .e), 0⟩,
  ⟨(true, .u), (false, .u), (true, .f), 0⟩,
  ⟨(false, .u), (true, .v), (true, .x), 0⟩,
  ⟨(false, .u), (true, .v), (true, .y), 0⟩,
  ⟨(true, .v), (false, .u), (true, .n), 0⟩,
  ⟨(false, .u), (true, .n), (true, .t), 0⟩,
  ⟨(false, .u), (true, .n), (true, .t), 1⟩,
  ⟨(true, .z), (false, .v), (true, .t), 1⟩,
  ⟨(false, .v), (true, .v), (true, .e), 0⟩,
  ⟨(true, .v), (false, .v), (true, .f), 0⟩,
  ⟨(false, .t), (true, .x), (true, .u), 1⟩,
  ⟨(false, .t), (true, .y), (true, .u), 0⟩,
  ⟨(false, .t), (true, .z), (true, .v), 1⟩,
  ⟨(true, .t), (false, .t), (true, .e), 0⟩,
  ⟨(false, .t), (true, .t), (true, .f), 0⟩,
  ⟨(true, .j), (false, .t), (true, .x), 0⟩,
  ⟨(true, .j), (false, .t), (true, .y), 2⟩,
  ⟨(false, .t), (true, .j), (true, .n), 1⟩,
  ⟨(true, .n), (false, .t), (true, .u), 0⟩,
  ⟨(true, .n), (false, .t), (true, .u), 1⟩,
  ⟨(false, .j), (true, .z), (true, .u), 0⟩,
  ⟨(true, .j), (false, .j), (true, .e), 0⟩,
  ⟨(false, .j), (true, .j), (true, .f), 0⟩,
  ⟨(false, .f), (true, .u), (true, .u), 0⟩,
  ⟨(false, .f), (true, .v), (true, .v), 0⟩,
  ⟨(true, .t), (false, .f), (true, .t), 0⟩,
  ⟨(true, .j), (false, .f), (true, .j), 0⟩,
  ⟨(false, .f), (true, .f), (true, .f), 0⟩,
  ⟨(true, .f), (false, .f), (true, .f), 0⟩,
  ⟨(false, .f), (true, .n), (true, .n), 0⟩,
  ⟨(true, .n), (false, .f), (true, .n), 0⟩,
  ⟨(false, .n), (true, .v), (true, .u), 0⟩,
  ⟨(true, .j), (false, .n), (true, .t), 1⟩,
  ⟨(false, .n), (true, .n), (true, .f), 0⟩,
  ⟨(true, .n), (false, .n), (true, .f), 0⟩]

def cochain : List TripleMonomial := [
  ⟨(true, .e), (false, .u), (true, .n), (true, .t), 2⟩,
  ⟨(true, .e), (false, .y), (true, .z), (true, .x), 2⟩,
  ⟨(true, .f), (true, .n), (false, .t), (true, .u), 2⟩,
  ⟨(true, .j), (false, .t), (true, .x), (true, .z), 2⟩,
  ⟨(true, .n), (false, .t), (true, .e), (true, .u), 2⟩,
  ⟨(true, .n), (false, .t), (true, .x), (true, .v), 2⟩,
  ⟨(true, .x), (false, .z), (true, .j), (true, .t), 2⟩,
  ⟨(true, .z), (false, .x), (true, .e), (true, .y), 2⟩,
  ⟨(false, .t), (true, .e), (false, .u), (false, .n), 2⟩,
  ⟨(false, .t), (true, .x), (false, .u), (false, .f), 2⟩,
  ⟨(false, .t), (true, .x), (false, .v), (false, .n), 2⟩,
  ⟨(false, .t), (true, .x), (false, .z), (false, .j), 2⟩,
  ⟨(false, .t), (false, .u), (true, .f), (false, .n), 2⟩,
  ⟨(false, .t), (false, .u), (true, .n), (false, .f), 2⟩,
  ⟨(false, .t), (false, .v), (true, .n), (false, .n), 2⟩,
  ⟨(false, .u), (true, .f), (true, .n), (true, .t), 2⟩,
  ⟨(false, .v), (true, .n), (true, .n), (true, .t), 2⟩,
  ⟨(false, .v), (false, .t), (true, .j), (false, .u), 2⟩,
  ⟨(false, .x), (true, .e), (false, .y), (false, .z), 2⟩,
  ⟨(false, .z), (true, .j), (false, .t), (false, .x), 2⟩,
  ⟨(true, .e), (false, .u), (true, .u), (true, .e), 1⟩,
  ⟨(true, .e), (false, .u), (true, .v), (true, .x), 1⟩,
  ⟨(true, .e), (false, .v), (true, .v), (true, .e), 1⟩,
  ⟨(true, .e), (false, .x), (true, .x), (true, .e), 1⟩,
  ⟨(true, .e), (false, .y), (true, .y), (true, .e), 1⟩,
  ⟨(true, .e), (false, .z), (true, .z), (true, .e), 1⟩,
  ⟨(true, .f), (true, .n), (false, .n), (true, .f), 1⟩,
  ⟨(true, .f), (true, .v), (false, .v), (true, .f), 1⟩,
  ⟨(true, .f), (true, .v), (false, .x), (true, .u), 1⟩,
  ⟨(true, .f), (false, .t), (true, .t), (true, .f), 1⟩,
  ⟨(true, .f), (false, .t), (true, .y), (true, .u), 1⟩,
  ⟨(true, .f), (false, .t), (false, .u), (false, .n), 1⟩,
  ⟨(true, .f), (false, .t), (false, .x), (false, .j), 1⟩,
  ⟨(true, .j), (true, .f), (false, .t), (true, .x), 1⟩,
  ⟨(true, .j), (true, .n), (false, .t), (true, .z), 1⟩,
  ⟨(true, .j), (true, .u), (false, .y), (true, .x), 1⟩,
  ⟨(true, .j), (true, .v), (false, .y), (true, .z), 1⟩,
  ⟨(true, .j), (false, .j), (true, .e), (true, .e), 1⟩,
  ⟨(true, .j), (false, .j), (true, .t), (true, .t), 1⟩,
  ⟨(true, .j), (false, .j), (true, .x), (true, .x), 1⟩,
  ⟨(true, .n), (true, .f), (false, .t), (true, .u), 1⟩,
  ⟨(true, .n), (true, .n), (false, .t), (true, .v), 1⟩,
  ⟨(true, .n), (true, .u), (false, .y), (true, .u), 1⟩,
  ⟨(true, .n), (true, .v), (false, .y), (true, .v), 1⟩,
  ⟨(true, .n), (false, .j), (true, .j), (true, .n), 1⟩,
  ⟨(true, .n), (false, .j), (true, .z), (true, .v), 1⟩,
  ⟨(true, .n), (false, .n), (true, .n), (true, .n), 1⟩,
  ⟨(true, .n), (false, .n), (true, .v), (true, .v), 1⟩,
  ⟨(true, .n), (false, .t), (false, .u), (false, .f), 1⟩,
  ⟨(true, .n), (false, .t), (false, .v), (false, .n), 1⟩,
  ⟨(true, .n), (false, .t), (false, .z), (false, .j), 1⟩,
  ⟨(true, .t), (false, .t), (true, .e), (true, .e), 1⟩,
  ⟨(true, .t), (false, .t), (true, .x), (true, .x), 1⟩,
  ⟨(true, .u), (false, .u), (true, .f), (true, .f), 1⟩,
  ⟨(true, .u), (false, .u), (true, .u), (true, .u), 1⟩,
  ⟨(true, .u), (false, .v), (true, .n), (true, .f), 1⟩,
  ⟨(true, .u), (false, .v), (true, .v), (true, .u), 1⟩,
  ⟨(true, .u), (false, .x), (true, .x), (true, .u), 1⟩,
  ⟨(true, .u), (false, .y), (false, .u), (false, .n), 1⟩,
  ⟨(true, .u), (false, .y), (false, .x), (false, .j), 1⟩,
  ⟨(true, .u), (false, .z), (true, .z), (true, .u), 1⟩,
  ⟨(true, .v), (false, .v), (true, .n), (true, .n), 1⟩,
  ⟨(true, .v), (false, .v), (true, .v), (true, .v), 1⟩,
  ⟨(true, .v), (false, .x), (true, .e), (true, .u), 1⟩,
  ⟨(true, .v), (false, .x), (true, .x), (true, .v), 1⟩,
  ⟨(true, .v), (false, .y), (false, .u), (false, .f), 1⟩,
  ⟨(true, .v), (false, .y), (false, .v), (false, .n), 1⟩,
  ⟨(true, .v), (false, .y), (false, .z), (false, .j), 1⟩,
  ⟨(true, .v), (false, .z), (true, .z), (true, .v), 1⟩,
  ⟨(true, .x), (false, .x), (true, .e), (true, .e), 1⟩,
  ⟨(true, .x), (false, .x), (true, .x), (true, .x), 1⟩,
  ⟨(true, .y), (false, .u), (true, .f), (true, .t), 1⟩,
  ⟨(true, .y), (false, .u), (true, .u), (true, .y), 1⟩,
  ⟨(true, .y), (false, .v), (true, .n), (true, .t), 1⟩,
  ⟨(true, .y), (false, .v), (true, .v), (true, .y), 1⟩,
  ⟨(true, .y), (false, .x), (true, .x), (true, .y), 1⟩,
  ⟨(true, .y), (false, .y), (true, .e), (true, .e), 1⟩,
  ⟨(true, .y), (false, .y), (true, .j), (true, .j), 1⟩,
  ⟨(true, .y), (false, .y), (true, .t), (true, .t), 1⟩,
  ⟨(true, .y), (false, .y), (true, .x), (true, .x), 1⟩,
  ⟨(true, .y), (false, .y), (true, .y), (true, .y), 1⟩,
  ⟨(true, .y), (false, .y), (true, .z), (true, .z), 1⟩,
  ⟨(true, .y), (false, .z), (true, .z), (true, .y), 1⟩,
  ⟨(true, .z), (false, .x), (true, .x), (true, .z), 1⟩,
  ⟨(true, .z), (false, .z), (true, .e), (true, .e), 1⟩,
  ⟨(true, .z), (false, .z), (true, .j), (true, .j), 1⟩,
  ⟨(true, .z), (false, .z), (true, .t), (true, .t), 1⟩,
  ⟨(true, .z), (false, .z), (true, .x), (true, .x), 1⟩,
  ⟨(false, .j), (true, .j), (true, .f), (true, .f), 1⟩,
  ⟨(false, .j), (true, .j), (true, .u), (true, .u), 1⟩,
  ⟨(false, .j), (true, .j), (false, .j), (false, .j), 1⟩,
  ⟨(false, .j), (true, .j), (false, .n), (false, .n), 1⟩,
  ⟨(false, .j), (true, .y), (false, .y), (false, .j), 1⟩,
  ⟨(false, .j), (true, .z), (false, .v), (false, .n), 1⟩,
  ⟨(false, .j), (true, .z), (false, .z), (false, .j), 1⟩,
  ⟨(false, .n), (true, .n), (true, .f), (true, .f), 1⟩,
  ⟨(false, .n), (true, .n), (true, .u), (true, .u), 1⟩,
  ⟨(false, .n), (false, .t), (true, .t), (false, .n), 1⟩,
  ⟨(false, .t), (true, .j), (false, .j), (false, .t), 1⟩,
  ⟨(false, .t), (true, .t), (true, .n), (true, .n), 1⟩,
  ⟨(false, .t), (true, .t), (true, .v), (true, .v), 1⟩,
  ⟨(false, .t), (true, .t), (false, .t), (false, .t), 1⟩,
  ⟨(false, .t), (true, .y), (false, .y), (false, .t), 1⟩,
  ⟨(false, .t), (true, .z), (false, .z), (false, .t), 1⟩,
  ⟨(false, .t), (false, .z), (true, .j), (false, .n), 1⟩,
  ⟨(false, .u), (true, .f), (true, .v), (true, .x), 1⟩,
  ⟨(false, .u), (true, .f), (false, .t), (false, .y), 1⟩,
  ⟨(false, .u), (true, .n), (true, .f), (true, .t), 1⟩,
  ⟨(false, .u), (true, .n), (true, .u), (true, .y), 1⟩,
  ⟨(false, .u), (true, .n), (false, .t), (false, .e), 1⟩,
  ⟨(false, .u), (true, .u), (false, .y), (false, .y), 1⟩,
  ⟨(false, .u), (true, .v), (false, .y), (false, .e), 1⟩,
  ⟨(false, .u), (false, .j), (true, .j), (false, .u), 1⟩,
  ⟨(false, .v), (true, .n), (true, .u), (true, .e), 1⟩,
  ⟨(false, .v), (true, .n), (true, .v), (true, .x), 1⟩,
  ⟨(false, .v), (true, .n), (false, .t), (false, .y), 1⟩,
  ⟨(false, .v), (true, .v), (false, .y), (false, .y), 1⟩,
  ⟨(false, .v), (false, .t), (true, .t), (false, .v), 1⟩,
  ⟨(false, .x), (true, .e), (false, .u), (false, .v), 1⟩,
  ⟨(false, .x), (true, .j), (true, .f), (true, .t), 1⟩,
  ⟨(false, .x), (true, .j), (true, .u), (true, .y), 1⟩,
  ⟨(false, .x), (true, .j), (false, .j), (false, .x), 1⟩,
  ⟨(false, .x), (true, .j), (false, .t), (false, .e), 1⟩,
  ⟨(false, .x), (true, .t), (false, .t), (false, .x), 1⟩,
  ⟨(false, .x), (true, .x), (false, .u), (false, .u), 1⟩,
  ⟨(false, .x), (true, .x), (false, .v), (false, .v), 1⟩,
  ⟨(false, .x), (true, .x), (false, .y), (false, .y), 1⟩,
  ⟨(false, .x), (true, .x), (false, .z), (false, .z), 1⟩,
  ⟨(false, .x), (true, .y), (false, .y), (false, .x), 1⟩,
  ⟨(false, .x), (true, .z), (false, .y), (false, .e), 1⟩,
  ⟨(false, .x), (true, .z), (false, .z), (false, .x), 1⟩,
  ⟨(false, .x), (false, .u), (true, .f), (false, .v), 1⟩,
  ⟨(false, .x), (false, .u), (true, .n), (false, .u), 1⟩,
  ⟨(false, .x), (false, .v), (true, .n), (false, .v), 1⟩,
  ⟨(false, .y), (false, .x), (true, .j), (false, .u), 1⟩,
  ⟨(false, .y), (false, .z), (true, .j), (false, .v), 1⟩,
  ⟨(false, .z), (true, .j), (true, .n), (true, .t), 1⟩,
  ⟨(false, .z), (true, .j), (true, .v), (true, .y), 1⟩,
  ⟨(false, .z), (true, .y), (false, .y), (false, .z), 1⟩,
  ⟨(false, .z), (true, .z), (false, .u), (false, .u), 1⟩,
  ⟨(false, .z), (true, .z), (false, .v), (false, .v), 1⟩,
  ⟨(false, .z), (true, .z), (false, .y), (false, .y), 1⟩,
  ⟨(false, .z), (true, .z), (false, .z), (false, .z), 1⟩,
  ⟨(true, .e), (false, .y), (true, .j), (true, .t), 3⟩,
  ⟨(true, .j), (false, .t), (true, .e), (true, .y), 3⟩,
  ⟨(false, .t), (true, .e), (false, .y), (false, .j), 3⟩,
  ⟨(false, .t), (false, .y), (true, .j), (false, .f), 3⟩,
  ⟨(true, .j), (true, .n), (false, .j), (true, .x), 0⟩,
  ⟨(true, .j), (true, .v), (false, .z), (true, .x), 0⟩,
  ⟨(true, .n), (true, .n), (false, .j), (true, .u), 0⟩,
  ⟨(true, .n), (true, .v), (false, .z), (true, .u), 0⟩,
  ⟨(true, .n), (false, .j), (true, .y), (true, .u), 0⟩,
  ⟨(true, .n), (false, .j), (false, .u), (false, .n), 0⟩,
  ⟨(true, .n), (false, .j), (false, .x), (false, .j), 0⟩,
  ⟨(true, .n), (false, .t), (false, .x), (false, .t), 0⟩,
  ⟨(true, .t), (true, .n), (false, .t), (true, .x), 0⟩,
  ⟨(true, .t), (true, .v), (false, .y), (true, .x), 0⟩,
  ⟨(true, .v), (false, .y), (false, .x), (false, .t), 0⟩,
  ⟨(true, .v), (false, .z), (true, .y), (true, .u), 0⟩,
  ⟨(true, .v), (false, .z), (false, .u), (false, .n), 0⟩,
  ⟨(true, .v), (false, .z), (false, .x), (false, .j), 0⟩,
  ⟨(true, .y), (false, .u), (true, .n), (true, .j), 0⟩,
  ⟨(true, .y), (false, .u), (true, .v), (true, .z), 0⟩,
  ⟨(false, .j), (true, .y), (false, .u), (false, .n), 0⟩,
  ⟨(false, .j), (false, .u), (true, .n), (false, .n), 0⟩,
  ⟨(false, .j), (false, .x), (true, .j), (false, .n), 0⟩,
  ⟨(false, .t), (false, .x), (true, .t), (false, .n), 0⟩,
  ⟨(false, .u), (true, .n), (true, .n), (true, .j), 0⟩,
  ⟨(false, .u), (true, .n), (true, .v), (true, .z), 0⟩,
  ⟨(false, .u), (true, .n), (false, .j), (false, .y), 0⟩,
  ⟨(false, .u), (true, .v), (false, .z), (false, .y), 0⟩,
  ⟨(false, .x), (true, .j), (true, .n), (true, .j), 0⟩,
  ⟨(false, .x), (true, .j), (true, .v), (true, .z), 0⟩,
  ⟨(false, .x), (true, .t), (true, .n), (true, .t), 0⟩,
  ⟨(false, .x), (true, .t), (true, .v), (true, .y), 0⟩,
  ⟨(false, .y), (false, .x), (true, .t), (false, .v), 0⟩,
  ⟨(false, .z), (true, .y), (false, .u), (false, .v), 0⟩,
  ⟨(false, .z), (false, .u), (true, .n), (false, .v), 0⟩,
  ⟨(false, .z), (false, .x), (true, .j), (false, .v), 0⟩]

end ArExplicit.CocycleData

end OAI
