import OAI.Analysis.KadisonKastler.Amenable
import Mathlib.Algebra.Star.UnitaryStarAlgAut

namespace OAI

/-! # Moving an injective subalgebra into a nearby algebra

The published input is the one-sided assertion of Cameron--Christensen--
Sinclair--Smith--White--Wiggins, *Kadison--Kastler stable factors*, Duke
Math. J. 163 (2014), Theorem 3.3(i), arXiv:1209.4116v3, p. 13. Only
the inclusion and the displacement bound `150 * γ` are retained.
-/

namespace KadisonKastler

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Restricting the source preserves a near inclusion with the same bound. -/
theorem nearInclusion_mono_left {R M N : VonNeumannAlgebra H} {γ : ℝ}
    (hRM : R ≤ M) (hMN : NearInclusion M N γ) : NearInclusion R N γ := by
  obtain ⟨γ', hγ', happrox⟩ := hMN
  exact ⟨γ', hγ', fun x hx => happrox x ⟨hRM hx.1, hx.2⟩⟩

/-- The one-sided part of CCSSWW Theorem 3.3(i). The location of the
unitary in the algebra generated by the two inputs is not needed here. -/
def PublishedAmenableEmbedding : Prop :=
  ∀ (P B : VonNeumannAlgebra H) (γ : ℝ), IsInjective P →
    NearInclusion P B γ → γ < 1 / 100 →
    ∃ w : unitary (H →L[ℂ] H),
      (∀ x ∈ P, unitaryConj w x ∈ B) ∧ ‖(w : H →L[ℂ] H) - 1‖ ≤ 150 * γ

/-- A common injective subalgebra of the source can be moved into its
nearby neighbor by the published one-sided theorem. -/
theorem exists_amenable_embedding_of_kkDistance_lt
    (hpub : PublishedAmenableEmbedding (H := H))
    {R M N : VonNeumannAlgebra H} (hRM : R ≤ M) (hR : IsInjective R)
    {t : ℝ} (hgap : kkDistance M N < t) (ht : t < 1 / 100) :
    ∃ w : unitary (H →L[ℂ] H),
      (∀ x ∈ R, unitaryConj w x ∈ N) ∧ ‖(w : H →L[ℂ] H) - 1‖ ≤ 150 * t :=
  hpub R N t hR (nearInclusion_mono_left hRM (nearInclusion_of_kkDistance_lt hgap)) ht

private theorem centralizer_image_starAlgEquiv
    (e : (H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H)) (S : Set (H →L[ℂ] H)) :
    Set.centralizer (e '' S) = e '' Set.centralizer S := by
  ext x
  constructor
  · intro hx
    refine ⟨e.symm x, ?_, e.apply_symm_apply x⟩
    intro y hy
    apply e.injective
    rw [map_mul, map_mul]
    change e y * e (e.symm x) = e (e.symm x) * e y
    rw [e.apply_symm_apply]
    exact hx (e y) ⟨y, hy, rfl⟩
  · rintro ⟨y, hy, rfl⟩ z ⟨w, hw, rfl⟩
    simpa only [map_mul] using congrArg e (hy w hw)

/-- A concrete von Neumann algebra conjugated by an ambient unitary. -/
def unitaryConjugateAlgebra (w : unitary (H →L[ℂ] H)) (M : VonNeumannAlgebra H) :
    VonNeumannAlgebra H where
  toStarSubalgebra := M.toStarSubalgebra.map (Unitary.conjStarAlgAut ℂ _ w).toStarAlgHom
  centralizer_centralizer' := by
    let e := Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) w
    change Set.centralizer (Set.centralizer (e '' (M : Set (H →L[ℂ] H)))) =
      e '' (M : Set (H →L[ℂ] H))
    rw [centralizer_image_starAlgEquiv, centralizer_image_starAlgEquiv,
      M.centralizer_centralizer]

/-- The algebra just constructed is the exact unitary image. -/
theorem conjugates_unitaryConjugateAlgebra (w : unitary (H →L[ℂ] H))
    (M : VonNeumannAlgebra H) : Conjugates w M (unitaryConjugateAlgebra w M) := rfl

theorem le_unitaryConjugateAlgebra_star {R N : VonNeumannAlgebra H}
    (w : unitary (H →L[ℂ] H)) (hw : ∀ x ∈ R, unitaryConj w x ∈ N) :
    R ≤ unitaryConjugateAlgebra (star w) N := by
  intro x hx
  exact ⟨unitaryConj w x, hw x hx, unitaryConj_star_unitaryConj w x⟩

/-- Moving the neighbor back creates a literal common subalgebra. The
additional Kadison--Kastler error is at most twice the displacement. -/
theorem exists_common_amenable_neighbor_of_kkDistance_lt
    (hpub : PublishedAmenableEmbedding (H := H))
    {R M N : VonNeumannAlgebra H} (hRM : R ≤ M) (hR : IsInjective R)
    {t : ℝ} (hgap : kkDistance M N < t) (ht : t < 1 / 100) :
    ∃ w : unitary (H →L[ℂ] H),
      R ≤ unitaryConjugateAlgebra (star w) N ∧
      ‖(w : H →L[ℂ] H) - 1‖ ≤ 150 * t ∧
      kkDistance M (unitaryConjugateAlgebra (star w) N) ≤
        kkDistance M N + 2 * ‖(w : H →L[ℂ] H) - 1‖ := by
  obtain ⟨w, hw, hnorm⟩ := exists_amenable_embedding_of_kkDistance_lt hpub hRM hR hgap ht
  refine ⟨w, le_unitaryConjugateAlgebra_star w hw, hnorm, ?_⟩
  have hstar : ‖((star w : unitary (H →L[ℂ] H)) : H →L[ℂ] H) - 1‖ =
      ‖(w : H →L[ℂ] H) - 1‖ := by
    simpa only [Unitary.coe_star, star_sub, star_one] using
      norm_star ((w : H →L[ℂ] H) - 1)
  simpa only [hstar] using
    (kkDistance_conjugate_le (M := M) (conjugates_unitaryConjugateAlgebra (star w) N))

end

end KadisonKastler

end OAI
