import OAI.Analysis.KadisonKastler.ProjectionNormalWords
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.Tactic.LinearCombination

namespace OAI

/-! # Conditional expectation of the closed projection--Haar algebra -/

namespace KadisonKastler

noncomputable section

variable {B : Type*} [CStarAlgebra B]

/-- Continuity extends the algebraic normal-form conclusion to the closed
algebra generated by the projection and the Haar unitary. -/
theorem FreeHaarMoments.expectation_eq_affine_projection_of_mem_closure
    {τ : FaithfulTracialState B} {A : StarSubalgebra ℂ B} {v : unitary B}
    (h : FreeHaarMoments τ A v)
    (E : B →L[ℂ] B) (hE : ∀ x, E x ∈ A)
    (hpair : ∀ b ∈ A, ∀ x, τ.toLinearMap (b * E x) = τ.toLinearMap (b * x))
    {p x : B} (hp : IsStarProjection p) (hpA : p ∈ A)
    (hx : x ∈ closure (Algebra.adjoin ℂ (insert p (Set.range (haarPower v))) : Set B)) :
    ∃ α β : ℂ, E x = α • p + β • (1 : B) := by
  let V := Submodule.span ℂ ({p, (1 : B)} : Set B)
  let : FiniteDimensional ℂ V := FiniteDimensional.span_of_finite ℂ (Set.toFinite _)
  have hclosed : IsClosed {y : B | E y ∈ V} :=
    V.closed_of_finiteDimensional.preimage E.continuous
  have hall : (Algebra.adjoin ℂ (insert p (Set.range (haarPower v))) : Set B) ⊆
      {y : B | E y ∈ V} := by
    intro y hy
    obtain ⟨α, β, hαβ⟩ := h.expectation_eq_affine_projection E.toLinearMap hE hpair hp hpA hy
    exact Submodule.mem_span_pair.mpr ⟨α, β, hαβ.symm⟩
  have hEx : E x ∈ V := closure_minimal hall hclosed hx
  obtain ⟨α, β, hαβ⟩ := Submodule.mem_span_pair.mp hEx
  exact ⟨α, β, hαβ.symm⟩

/-- The two trace pairings determine the affine coefficients whenever
the projection has trace strictly between zero and one. -/
theorem affine_projection_coefficients_unique_between_traces
    {C : Type*} [CStarAlgebra C]
    (τ : FaithfulTracialState B) (σ : FaithfulTracialState C)
    {p : B} {q : C} (hp : IsStarProjection p) (hq : IsStarProjection q)
    {t α β γ δ : ℂ} (ht0 : t ≠ 0) (ht1 : t ≠ 1)
    (hpτ : τ.toLinearMap p = t) (hqσ : σ.toLinearMap q = t)
    (htrace : τ.toLinearMap (α • p + β • (1 : B)) =
      σ.toLinearMap (γ • q + δ • (1 : C)))
    (hptrace : τ.toLinearMap (p * (α • p + β • (1 : B))) =
      σ.toLinearMap (q * (γ • q + δ • (1 : C)))) :
    α = γ ∧ β = δ := by
  have h1 : α * t + β = γ * t + δ := by
    simpa only [map_add, map_smul, smul_eq_mul, hpτ, hqσ, τ.map_one, σ.map_one,
      mul_one] using htrace
  have h2 : α * t + β * t = γ * t + δ * t := by
    simpa only [mul_add, mul_smul_comm, mul_one, hp.isIdempotentElem.eq,
      hq.isIdempotentElem.eq, map_add, map_smul, smul_eq_mul, hpτ, hqσ] using hptrace
  have hz : (β - δ) * (t - 1) = 0 := by linear_combination h2 - h1
  have hβ : β = δ := sub_eq_zero.mp ((mul_eq_zero.mp hz).resolve_right (sub_ne_zero.mpr ht1))
  have hzα : (α - γ) * t = 0 := by rw [hβ] at h1; linear_combination h1
  exact ⟨sub_eq_zero.mp ((mul_eq_zero.mp hzα).resolve_right ht0), hβ⟩

end

end KadisonKastler

end OAI
