import OAI.Analysis.KadisonKastler.RegularCoreInjective
import OAI.Analysis.KadisonKastler.TypeIIIMatrixCorner
import OAI.Analysis.KadisonKastler.MatrixNearInclusion
import OAI.Analysis.KadisonKastler.AmenableEmbedding

namespace OAI

/-! # Preparing a common infinite matrix algebra

The actual countable matrix units lie in the injective algebra generated by
factorial matrix stages. Moving that algebra into the neighbor makes the
ordinary gap control every matrix size, with no linear selection of approximants.
-/

namespace KadisonKastler

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [TopologicalSpace.SeparableSpace H]

/-- One small correction makes the given countable matrix units common and
upgrades the original metric gap to two-sided matrix proximity. -/
theorem exists_common_matrix_preparation
    (hAFD : PublishedIncreasingMatrixInjectivity (H := H))
    (hEmbed : PublishedAmenableEmbedding (H := H))
    (M N : VonNeumannAlgebra H) (E : Submodule ℂ H) [CompleteSpace E]
    (F : FullMatrixCorner E) (hF : ∀ i j, F.entry i j ∈ M)
    {γ : ℝ} (hsmall : γ < 1 / 100) (hgap : kkDistance M N < γ) :
    ∃ a : unitary (H →L[ℂ] H),
      ‖(a : H →L[ℂ] H) - 1‖ ≤ 150 * γ ∧
      (∀ i j, F.entry i j ∈ unitaryConjugateAlgebra (star a) N) ∧
      kkDistance M (unitaryConjugateAlgebra (star a) N) < 301 * γ ∧
      MatrixNearInclusion M (unitaryConjugateAlgebra (star a) N) (301 * γ) ∧
      MatrixNearInclusion (unitaryConjugateAlgebra (star a) N) M (301 * γ) := by
  obtain ⟨S, hSM, hS, hFS⟩ := F.exists_injective_matrix_subalgebra hAFD M hF
  obtain ⟨a, haS, ha, hdist⟩ :=
    exists_common_amenable_neighbor_of_kkDistance_lt hEmbed hSM hS hgap hsmall
  have hFN : ∀ i j, F.entry i j ∈ unitaryConjugateAlgebra (star a) N :=
    fun i j => haS (hFS i j)
  have hd : kkDistance M (unitaryConjugateAlgebra (star a) N) < 301 * γ := by
    linarith
  refine ⟨a, ha, hFN, hd, ?_, ?_⟩
  · exact MatrixNearInclusion.of_common_matrix_units M _ E F hF hFN hd
  · exact MatrixNearInclusion.of_common_matrix_units _ M E F hFN hF
      (by simpa only [kkDistance_comm] using hd)

/-- In a type III factor, the published projection comparison supplies the
countable matrix units required by the preceding preparation theorem. -/
theorem exists_typeIII_matrix_preparation
    (hCompare : PublishedTypeIIIProjectionComparison.{u})
    (hAFD : PublishedIncreasingMatrixInjectivity (H := H))
    (hEmbed : PublishedAmenableEmbedding (H := H))
    (M N : VonNeumannAlgebra H) (hM : TypeIIIFactor M)
    {γ : ℝ} (hsmall : γ < 1 / 100) (hgap : kkDistance M N < γ) :
    ∃ a : unitary (H →L[ℂ] H),
      ‖(a : H →L[ℂ] H) - 1‖ ≤ 150 * γ ∧
      kkDistance M (unitaryConjugateAlgebra (star a) N) < 301 * γ ∧
      MatrixNearInclusion M (unitaryConjugateAlgebra (star a) N) (301 * γ) ∧
      MatrixNearInclusion (unitaryConjugateAlgebra (star a) N) M (301 * γ) := by
  obtain ⟨p, _hp, F, hF⟩ := hM.exists_fullMatrixCorner hCompare
  obtain ⟨a, ha, _hFN, hd, hMN, hNM⟩ :=
    exists_common_matrix_preparation hAFD hEmbed M N (typeIIIInitialSpace p) F hF hsmall hgap
  exact ⟨a, ha, hd, hMN, hNM⟩

end

end KadisonKastler

end OAI
