import OAI.Analysis.KadisonKastler.ConjugateRightIrreducibility

namespace OAI

/-! # Actual matrix stages in the conjugate right algebra

Conjugation changes the scalar coefficients by complex conjugation, while
the conjugated matrix-unit entries retain their usual product laws. Thus
the right algebra is generated by actual increasing full matrix stages.
This lets the same finite averaging argument transfer its irreducibility
to a nearby commutant.
-/

namespace KadisonKastler

open Generator
open scoped BigOperators

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

omit [CompleteSpace H] in
private theorem conjugationOperator_zero (J : H ≃ₗᵢ⋆[ℂ] H) :
    conjugationOperator J (0 : H →L[ℂ] H) = 0 := by
  ext ξ
  exact map_zero J

omit [CompleteSpace H] in
private theorem conjugationOperator_sum (J : H ≃ₗᵢ⋆[ℂ] H)
    {ι : Type*} (s : Finset ι) (f : ι → H →L[ℂ] H) :
    conjugationOperator J (∑ i ∈ s, f i) = ∑ i ∈ s, conjugationOperator J (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp only [Finset.sum_empty, conjugationOperator_zero]
  | @insert i s hi ih =>
      rw [Finset.sum_insert hi, Finset.sum_insert hi, conjugationOperator_add, ih]

/-- Actual full matrix units in the conjugate right algebra. -/
def conjugateMatrixUnits (J : H ≃ₗᵢ⋆[ℂ] H) (hJ : Function.Involutive J)
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (E : MatrixUnitSystem ι (H →L[ℂ] H)) : MatrixUnitSystem ι (H →L[ℂ] H) where
  entry i j := conjugationOperator J (E.entry i j)
  star_entry i j := by rw [← conjugationOperator_star J hJ, E.star_entry]
  mul_entry i j k l := by
    rw [← conjugationOperator_mul J hJ, E.mul_entry]
    split_ifs <;> simp only [conjugationOperator_zero]
  total := by
    rw [← conjugationOperator_sum, E.total, conjugationOperator_one J hJ]

@[simp]
theorem conjugateMatrixUnits_entry (J : H ≃ₗᵢ⋆[ℂ] H) (hJ : Function.Involutive J)
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (E : MatrixUnitSystem ι (H →L[ℂ] H)) (i j : ι) :
    (conjugateMatrixUnits J hJ E).entry i j = conjugationOperator J (E.entry i j) := rfl

theorem conjugateMatrixUnits_hom (J : H ≃ₗᵢ⋆[ℂ] H) (hJ : Function.Involutive J)
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (E : MatrixUnitSystem ι (H →L[ℂ] H)) (a : Matrix ι ι ℂ) :
    (conjugateMatrixUnits J hJ E).hom (fun i j => star (a i j)) =
      conjugationOperator J (E.hom a) := by
  change (∑ i, ∑ j, star (a i j) • conjugationOperator J (E.entry i j)) =
    conjugationOperator J (E.hom a)
  simp only [MatrixUnitSystem.hom_apply, conjugationOperator_sum,
    conjugationOperator_smul]

theorem conjugation_mem_conjugateMatrixUnits (J : H ≃ₗᵢ⋆[ℂ] H)
    (hJ : Function.Involutive J) {ι : Type*} [Fintype ι] [DecidableEq ι]
    (E : MatrixUnitSystem ι (H →L[ℂ] H)) {x : H →L[ℂ] H} (hx : x ∈ E.algebra) :
    conjugationOperator J x ∈ (conjugateMatrixUnits J hJ E).algebra := by
  obtain ⟨a, rfl⟩ := hx
  exact ⟨(fun i j => star (a i j)), conjugateMatrixUnits_hom J hJ E a⟩

theorem conjugateMatrixUnits_mono (J : H ≃ₗᵢ⋆[ℂ] H) (hJ : Function.Involutive J)
    (d : ℕ → ℕ) (E : ∀ n, MatrixUnitSystem (Fin (d n)) (H →L[ℂ] H))
    (hmono : Monotone (fun n => (E n).algebra)) :
    Monotone (fun n => (conjugateMatrixUnits J hJ (E n)).algebra) := by
  intro i j hij
  apply ((conjugateMatrixUnits J hJ (E i)).algebra_le_iff
    (conjugateMatrixUnits J hJ (E j)).algebra).mpr
  intro a b
  exact conjugation_mem_conjugateMatrixUnits J hJ (E j)
    (hmono hij ((E i).entry_mem a b))

/-- The weakly generated right algebra is exactly generated by the
conjugated finite matrix stages. -/
theorem conjugateRightAlgebra_generated_matrixStages
    (J : H ≃ₗᵢ⋆[ℂ] H) (hJ : Function.Involutive J)
    (d : ℕ → ℕ) (E : ∀ n, MatrixUnitSystem (Fin (d n)) (H →L[ℂ] H)) :
    conjugateRightAlgebra J hJ (generatedVonNeumannAlgebra (⨆ n, (E n).algebra)) =
      generatedVonNeumannAlgebra (⨆ n, (conjugateMatrixUnits J hJ (E n)).algebra) := by
  let R := generatedVonNeumannAlgebra (⨆ n, (E n).algebra)
  let S := generatedVonNeumannAlgebra (⨆ n, (conjugateMatrixUnits J hJ (E n)).algebra)
  have hRS : R ≤ conjugateRightAlgebra J hJ S := by
    apply generatedVonNeumannAlgebra_le_of_le
    apply iSup_le
    intro n
    apply ((E n).algebra_le_iff (conjugateRightAlgebra J hJ S).toStarSubalgebra).mpr
    intro i j
    refine ⟨(conjugateMatrixUnits J hJ (E n)).entry i j, ?_, ?_⟩
    · exact subset_generatedVonNeumannAlgebra _
        ((le_iSup (fun n => (conjugateMatrixUnits J hJ (E n)).algebra) n)
          ((conjugateMatrixUnits J hJ (E n)).entry_mem i j))
    · exact conjugationOperator_twice J hJ ((E n).entry i j)
  apply le_antisymm
  · rintro _ ⟨r, hr, rfl⟩
    obtain ⟨s, hs, he⟩ := hRS hr
    rw [← he, conjugationOperator_twice J hJ]
    exact hs
  · apply generatedVonNeumannAlgebra_le_of_le
    apply iSup_le
    intro n
    apply ((conjugateMatrixUnits J hJ (E n)).algebra_le_iff
      (conjugateRightAlgebra J hJ R).toStarSubalgebra).mpr
    intro i j
    exact ⟨(E n).entry i j,
      subset_generatedVonNeumannAlgebra _ ((le_iSup (fun n => (E n).algebra) n)
        ((E n).entry_mem i j)), rfl⟩

/-- Small gaps on both sides transfer the two relative irreducibility
statements. Together with the common left/right vector action this proves
cyclicity and separation in the actual neighboring representation. -/
theorem preparedRight_cyclic_separating_of_matrix_gaps
    (M N R : VonNeumannAlgebra H)
    (J : H ≃ₗᵢ⋆[ℂ] H) (hJ : Function.Involutive J)
    (hJM : conjugateRightAlgebra J hJ M = M.commutant)
    (d : ℕ → ℕ) (E : ∀ n, MatrixUnitSystem (Fin (d n)) (H →L[ℂ] H))
    (hmono : Monotone (fun n => (E n).algebra))
    (hR : R = generatedVonNeumannAlgebra (⨆ n, (E n).algebra))
    (hRM : R ≤ M) (hRN : R ≤ N)
    (hSN : conjugateRightAlgebra J hJ R ≤ N.commutant)
    (hirr : ∀ T ∈ M, (∀ r ∈ R, r * T = T * r) →
      ∃ z : ℂ, T = z • (1 : H →L[ℂ] H))
    (hgap : kkDistance M N < 1 / 2)
    (hgap' : kkDistance M.commutant N.commutant < 1 / 2)
    (Ω : H) (hΩ : Ω ≠ 0)
    (hvector : ∀ r ∈ R, conjugationOperator J (star r) Ω = r Ω) :
    DenseRange (fun x : Algebra N => x.val Ω) ∧
      DenseRange (fun x : Algebra N.commutant => x.val Ω) ∧
      (∀ a : Algebra N, a.val Ω = 0 → a = 0) ∧
      (∀ a : Algebra N.commutant, a.val Ω = 0 → a = 0) := by
  have hEM (n : ℕ) : (E n).algebra ≤ M.toStarSubalgebra := by
    intro x hx
    apply hRM
    rw [hR]
    exact subset_generatedVonNeumannAlgebra _ ((le_iSup (fun n => (E n).algebra) n) hx)
  have hirrN : ∀ T ∈ N, (∀ r ∈ R, r * T = T * r) →
      ∃ z : ℂ, T = z • (1 : H →L[ℂ] H) := by
    simpa only [← hR] using relative_irreducibility_of_near_increasing_matrices
      M N d E hmono hEM (by simpa only [← hR] using hirr) hgap
  let F := fun n => conjugateMatrixUnits J hJ (E n)
  have hS : conjugateRightAlgebra J hJ R =
      generatedVonNeumannAlgebra (⨆ n, (F n).algebra) := by
    rw [hR]
    exact conjugateRightAlgebra_generated_matrixStages J hJ d E
  have hSM : conjugateRightAlgebra J hJ R ≤ M.commutant := by
    rw [← hJM]
    exact conjugateRightAlgebra_mono J hJ hRM
  have hFM (n : ℕ) : (F n).algebra ≤ M.commutant.toStarSubalgebra := by
    intro x hx
    apply hSM
    rw [hS]
    exact subset_generatedVonNeumannAlgebra _ ((le_iSup (fun n => (F n).algebra) n) hx)
  have hirrS := relative_irreducibility_commutant_of_conjugation J hJ R M hJM hirr
  have hirrN' : ∀ T ∈ N.commutant,
      (∀ r ∈ conjugateRightAlgebra J hJ R, r * T = T * r) →
        ∃ z : ℂ, T = z • (1 : H →L[ℂ] H) := by
    simpa only [← hS] using relative_irreducibility_of_near_increasing_matrices
      M.commutant N.commutant d F (conjugateMatrixUnits_mono J hJ d E hmono)
      hFM (by simpa only [← hS] using hirrS) hgap'
  exact cyclic_separating_of_commonRight_irreducibility J hJ R N hRN hSN Ω hΩ
    hirrN hirrN' hvector

end

end KadisonKastler

end OAI
