import OAI.Analysis.KadisonKastler.Algebra
import OAI.Analysis.KadisonKastler.PublishedPointedOperations
import OAI.Analysis.KadisonKastler.CyclicGramEquivalence
import OAI.Analysis.FactorGeneration.HilbertLimits

namespace OAI

/-! # Dense word-vector spans for cyclic generated algebras

A closed word span is reducing for each generator and hence for the
generated von Neumann algebra. Containing the cyclic vector makes it all
of the represented Hilbert space.
-/

namespace KadisonKastler

noncomputable section

variable {H I J : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

omit [CompleteSpace H] in
/-- Invariance on a spanning family passes to its closed linear span. -/
theorem invariant_closed_linearCombination_range
    (v : I → H) (T : H →L[ℂ] H)
    (h : ∀ i, T (v i) ∈ LinearMap.range (Finsupp.linearCombination ℂ v)) :
    ∀ x ∈ (LinearMap.range (Finsupp.linearCombination ℂ v)).topologicalClosure,
      T x ∈ (LinearMap.range (Finsupp.linearCombination ℂ v)).topologicalClosure := by
  let V := LinearMap.range (Finsupp.linearCombination ℂ v)
  have hV : V ≤ V.topologicalClosure.comap T.toLinearMap := by
    rintro x ⟨c, rfl⟩
    change T (Finsupp.linearCombination ℂ v c) ∈ V.topologicalClosure
    simp only [Finsupp.linearCombination_apply, map_finsuppSum, map_smul]
    apply Submodule.finsuppSum_mem
    intro i hi
    exact V.topologicalClosure.smul_mem (c i) (Submodule.le_topologicalClosure _ (h i))
  exact Submodule.topologicalClosure_minimal _ hV
    ((Submodule.isClosed_topologicalClosure V).preimage T.continuous)

/-- A cyclic representation generated by a star-stable family is already
cyclic on any invariant word span containing its cyclic vector. -/
theorem denseRange_linearCombination_of_cyclic_generators
    (M : VonNeumannAlgebra H) (Ω : H) (g : J → H →L[ℂ] H) (v : I → H)
    (hM : M = generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ (Set.range g)))
    (hcyclic : DenseRange (algebraVectorMap M Ω))
    (hstar : ∀ j, ∃ k, g k = star (g j))
    (hΩ : Ω ∈ LinearMap.range (Finsupp.linearCombination ℂ v))
    (hinv : ∀ j i, g j (v i) ∈ LinearMap.range (Finsupp.linearCombination ℂ v)) :
    DenseRange (Finsupp.linearCombination ℂ v) := by
  let V := (LinearMap.range (Finsupp.linearCombination ℂ v)).topologicalClosure
  have hc (j : J) : V.starProjection * g j = g j * V.starProjection := by
    apply Generator.starProjection_commutes_of_invariant
    · exact invariant_closed_linearCombination_range v (g j) (hinv j)
    · obtain ⟨k, hk⟩ := hstar j
      rw [← hk]
      exact invariant_closed_linearCombination_range v (g k) (hinv k)
  have hS : StarAlgebra.adjoin ℂ (Set.range g) ≤
      StarSubalgebra.centralizer ℂ {V.starProjection} := by
    apply StarAlgebra.adjoin_le
    rintro _ ⟨j, rfl⟩
    change g j ∈ StarSubalgebra.centralizer ℂ {V.starProjection}
    rw [StarSubalgebra.mem_centralizer_iff]
    intro x hx
    rcases Set.mem_singleton_iff.mp hx with rfl
    exact ⟨hc j, by simpa only [(isStarProjection_starProjection (U := V)).isSelfAdjoint.star_eq] using hc j⟩
  have hcomm (a : Algebra M) : V.starProjection * a.val = a.val * V.starProjection := by
    have ha0 : (a : H →L[ℂ] H) ∈ (M : Set (H →L[ℂ] H)) := a.property
    have ha : (a : H →L[ℂ] H) ∈
        (generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ (Set.range g)) :
          Set (H →L[ℂ] H)) :=
      (congrArg (fun Q : VonNeumannAlgebra H =>
        (a : H →L[ℂ] H) ∈ (Q : Set (H →L[ℂ] H))) hM).mp ha0
    rw [generatedVonNeumannAlgebra_coe] at ha
    have hp : V.starProjection ∈ Set.centralizer
        (StarAlgebra.adjoin ℂ (Set.range g) : Set (H →L[ℂ] H)) := by
      intro x hx
      exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp (hS hx) _ (Set.mem_singleton _)).1.symm
    exact ha _ hp
  have hpΩ : V.starProjection Ω = Ω :=
    Submodule.starProjection_eq_self_iff.mpr (Submodule.le_topologicalClosure _ hΩ)
  have hcontains (a : Algebra M) : a.val Ω ∈ V := by
    apply Submodule.starProjection_eq_self_iff.mp
    calc
      V.starProjection (a.val Ω) = a.val (V.starProjection Ω) :=
        congrArg (fun T : H →L[ℂ] H => T Ω) (hcomm a)
      _ = a.val Ω := by rw [hpΩ]
  intro x
  change x ∈ V
  exact hcyclic.induction_on (p := fun y => y ∈ V) x (Submodule.isClosed_topologicalClosure _)
    (fun a => hcontains a)

end

end KadisonKastler

end OAI
