import OAI.Analysis.KadisonKastler.SpatialDerivationClosure
import OAI.Analysis.KadisonKastler.CenterAlgebra
import OAI.Analysis.KadisonKastler.PureExtensionRepresentation
import OAI.Analysis.KadisonKastler.PublishedCentralDecomposition

namespace OAI

/-! # Factoriality in Sakai's one-implementer extension

In an irreducible representation of the algebra generated by the source
and its self-adjoint spatial implementer, every central projection of the
source bicommutant commutes with all generators. It is therefore trivial.
-/

namespace KadisonKastler

noncomputable section

variable {A B H : Type*} [CStarAlgebra A] [CStarAlgebra B]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

local instance derivationExtensionFactorInstance1 : PartialOrder B := CStarAlgebra.spectralOrder B
local instance derivationExtensionFactorInstance2 : StarOrderedRing B := CStarAlgebra.spectralOrderedRing B

/-- The norm-closed unital star algebra generated by the source and one element. -/
def NormGeneratedExtension (φ : A →⋆ₐ[ℂ] B) (d : B) : Prop :=
  ∀ C : StarSubalgebra ℂ B, IsClosed (C : Set B) →
    (∀ a, φ a ∈ C) → d ∈ C → C = ⊤

theorem commutes_of_normGeneratedExtension
    (φ : A →⋆ₐ[ℂ] B) (d : B) (hgen : NormGeneratedExtension φ d)
    (ρ : B →⋆ₐ[ℂ] (H →L[ℂ] H)) (p : H →L[ℂ] H)
    (hp : IsSelfAdjoint p)
    (hA : ∀ a, Commute p (ρ (φ a))) (hd : Commute p (ρ d)) :
    ∀ b, Commute p (ρ b) := by
  let C := (StarSubalgebra.centralizer ℂ ({p} : Set (H →L[ℂ] H))).comap ρ
  have hmem (b : B) : b ∈ C ↔ Commute p (ρ b) := by
    change ρ b ∈ StarSubalgebra.centralizer ℂ ({p} : Set (H →L[ℂ] H)) ↔ _
    simp only [StarSubalgebra.mem_centralizer_iff, Set.mem_singleton_iff,
      forall_eq, hp.star_eq]
    exact ⟨fun h => h.1, fun h => ⟨h, h⟩⟩
  have hclosed : IsClosed (C : Set B) := by
    have he : (C : Set B) = {b | p * ρ b = ρ b * p} := by
      ext b
      exact (hmem b).trans Iff.rfl
    rw [he]
    exact isClosed_eq (continuous_const.mul (show Continuous ρ by fun_prop))
      ((show Continuous ρ by fun_prop).mul continuous_const)
  have htop := hgen C hclosed (fun a => (hmem _).mpr (hA a)) ((hmem _).mpr hd)
  intro b
  apply (hmem b).mp
  rw [htop]
  trivial

theorem factor_of_irreducible_derivation_extension
    (φ : A →⋆ₐ[ℂ] B) (d : B) (hgen : NormGeneratedExtension φ d)
    (D : A →L[ℂ] A) (hd : ∀ a, φ (D a) = d * φ a - φ a * d)
    (ρ : B →⋆ₐ[ℂ] (H →L[ℂ] H))
    (hirr : NaimarkZFC.IsIrreducible ρ.toNonUnitalStarAlgHom) :
    ScalarCenter (generatedVonNeumannAlgebra (ρ.comp φ).range) := by
  let N := generatedVonNeumannAlgebra (ρ.comp φ).range
  have hcomm : ∀ a : (ρ.comp φ).range,
      ρ d * a.val - a.val * ρ d ∈ N := by
    intro a
    obtain ⟨x, hx⟩ := a.property
    change ρ (φ x) = a.val at hx
    rw [← hx, ← map_mul, ← map_mul, ← map_sub, ← hd]
    exact subset_generatedVonNeumannAlgebra (ρ.comp φ).range ⟨D x, rfl⟩
  have hproj : ∀ q : Algebra N, IsStarProjection q →
      (∀ a : Algebra N, a * q = q * a) → q = 0 ∨ q = 1 := by
    intro q hq hqc
    have hp : IsStarProjection q.val := hq.map N.toStarSubalgebra.subtype
    have hqp : ∀ a ∈ N, Commute q.val a := by
      intro a ha
      exact (congrArg Subtype.val (hqc ⟨a, ha⟩)).symm
    have hqd := (spatial_commutator_central_projection
      (ρ.comp φ).range (ρ d) hcomm q.val hp q.property hqp).symm
    have hqA : ∀ a, Commute q.val (ρ (φ a)) := by
      intro a
      exact hqp _ (subset_generatedVonNeumannAlgebra (ρ.comp φ).range ⟨a, rfl⟩)
    obtain ⟨r, hr⟩ := NaimarkZFC.irreducible_commutant_selfAdjoint_scalar
      ρ.toNonUnitalStarAlgHom hirr q.val hp.isSelfAdjoint
      (commutes_of_normGeneratedExtension φ d hgen ρ q.val hp.isSelfAdjoint hqA hqd)
    rcases subsingleton_or_nontrivial H with hH | hH
    · left
      apply Subtype.ext
      exact Subsingleton.elim _ _
    · let : Nontrivial H := hH
      have he : (r * r - r) • (1 : H →L[ℂ] H) = 0 := by
        have hh := hp.isIdempotentElem.eq
        rw [hr, smul_mul_smul_comm, one_mul] at hh
        simpa only [sub_smul] using sub_eq_zero.mpr hh
      have hr0 : r * r - r = 0 := (smul_eq_zero.mp he).resolve_right one_ne_zero
      have hrs : r = 0 ∨ r = 1 := by
        have hf : r * (r - 1) = 0 := by nlinarith
        rcases mul_eq_zero.mp hf with h | h
        · exact Or.inl h
        · exact Or.inr (sub_eq_zero.mp h)
      rcases hrs with h | h
      · left
        apply Subtype.ext
        simpa [h] using hr
      · right
        apply Subtype.ext
        simpa [h] using hr
  intro T hTN hTc
  obtain ⟨z, hz⟩ := scalar_center_of_trivial_central_projections N hproj
    ⟨T, hTN⟩ (fun a => Subtype.ext (hTc a.val a.property))
  exact ⟨z, congrArg Subtype.val hz⟩

end

end KadisonKastler

end OAI
