import OAI.Analysis.KadisonKastler.RowOperatorFactorization

namespace OAI

/-! The reducing subspace generated by the left operator in a factorization.
It retains every coefficient of the factored map and removes undetectable
vectors from the auxiliary representation. -/

namespace KadisonKastler

noncomputable section

open scoped InnerProductSpace

variable {H K : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
  {M : VonNeumannAlgebra H}

def factorizationCyclicSpace (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K))
    (L : H →L[ℂ] K) : Submodule ℂ K :=
  (Submodule.span ℂ (Set.range (fun p : Algebra M × H => π p.1 (L p.2)))).topologicalClosure

theorem mem_factorizationCyclicSpace (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K))
    (L : H →L[ℂ] K) (a : Algebra M) (ξ : H) :
    π a (L ξ) ∈ factorizationCyclicSpace π L :=
  Submodule.le_topologicalClosure _ (Submodule.subset_span ⟨(a, ξ), rfl⟩)

theorem left_mem_factorizationCyclicSpace (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K))
    (L : H →L[ℂ] K) (ξ : H) : L ξ ∈ factorizationCyclicSpace π L := by
  simpa only [map_one, one_apply_eq_self] using mem_factorizationCyclicSpace π L 1 ξ

theorem factorizationCyclicSpace_invariant (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K))
    (L : H →L[ℂ] K) (b : Algebra M) {x : K}
    (hx : x ∈ factorizationCyclicSpace π L) : π b x ∈ factorizationCyclicSpace π L := by
  have h : factorizationCyclicSpace π L ≤
      (factorizationCyclicSpace π L).comap (π b).toLinearMap := by
    apply Submodule.topologicalClosure_minimal
    · apply Submodule.span_le.mpr
      rintro _ ⟨⟨a, ξ⟩, rfl⟩
      change π b (π a (L ξ)) ∈ factorizationCyclicSpace π L
      simpa only [map_mul, mul_apply_eq_comp] using mem_factorizationCyclicSpace π L (b * a) ξ
    · exact (Submodule.isClosed_topologicalClosure _).preimage (π b).continuous
  exact h hx

instance factorizationCyclicSpace_complete (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K))
    (L : H →L[ℂ] K) : CompleteSpace (factorizationCyclicSpace π L) :=
  Submodule.topologicalClosure.completeSpace _

def cyclicFactorRepresentation (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K))
    (L : H →L[ℂ] K) : Algebra M →⋆ₐ[ℂ]
      (factorizationCyclicSpace π L →L[ℂ] factorizationCyclicSpace π L) where
  toFun a := (π a).restrict (fun _ hx => factorizationCyclicSpace_invariant π L a hx)
  map_zero' := by
    ext x
    change π 0 (x : K) = 0
    exact congrArg (fun T : K →L[ℂ] K => T (x : K)) π.toAlgHom.map_zero
  map_one' := by
    ext x
    change π 1 (x : K) = (x : K)
    exact congrArg (fun T : K →L[ℂ] K => T (x : K)) π.toAlgHom.map_one
  map_add' a b := by
    ext x
    change π (a + b) (x : K) = π a (x : K) + π b (x : K)
    exact congrArg (fun T : K →L[ℂ] K => T (x : K)) (π.toAlgHom.map_add a b)
  map_mul' a b := by
    ext x
    change π (a * b) (x : K) = π a (π b (x : K))
    exact congrArg (fun T : K →L[ℂ] K => T (x : K)) (π.toAlgHom.map_mul a b)
  commutes' c := by
    ext x
    change π (algebraMap ℂ (Algebra M) c) (x : K) = c • (x : K)
    exact congrArg (fun T : K →L[ℂ] K => T (x : K)) (π.toAlgHom.commutes c)
  map_star' a := by
    apply ContinuousLinearMap.ext
    intro x
    apply ext_inner_left ℂ
    intro y
    change inner ℂ (y : K) (π (star a) (x : K)) =
      inner ℂ y ((star ((π a).restrict
        (fun _ hx => factorizationCyclicSpace_invariant π L a hx))) x)
    rw [map_star]
    simp only [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.adjoint_inner_right]
    rfl

@[simp] theorem cyclicFactorRepresentation_apply
    (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K)) (L : H →L[ℂ] K)
    (a : Algebra M) (x : factorizationCyclicSpace π L) :
    (cyclicFactorRepresentation π L a x : K) = π a (x : K) := rfl

def cyclicFactorLeft (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K)) (L : H →L[ℂ] K) :
    H →L[ℂ] factorizationCyclicSpace π L :=
  L.codRestrict (factorizationCyclicSpace π L) (left_mem_factorizationCyclicSpace π L)

@[simp] theorem cyclicFactorLeft_apply
    (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K)) (L : H →L[ℂ] K) (ξ : H) :
    (cyclicFactorLeft π L ξ : K) = L ξ := rfl

theorem factorizationCyclicSpace_total
    (π : Algebra M →⋆ₐ[ℂ] (K →L[ℂ] K)) (L : H →L[ℂ] K)
    (z : factorizationCyclicSpace π L)
    (hz : ∀ a ξ, inner ℂ (cyclicFactorRepresentation π L a (cyclicFactorLeft π L ξ)) z = 0) :
    z = 0 := by
  have h : factorizationCyclicSpace π L ≤ (innerSL ℂ (z : K)).ker := by
    apply Submodule.topologicalClosure_minimal
    · apply Submodule.span_le.mpr
      rintro _ ⟨⟨a, ξ⟩, rfl⟩
      change inner ℂ (z : K) (π a (L ξ)) = 0
      exact inner_eq_zero_symm.mp (hz a ξ)
    · exact (innerSL ℂ (z : K)).isClosed_ker
  apply Subtype.ext
  exact inner_self_eq_zero.mp (h z.property)

end

end KadisonKastler

end OAI
