import OAI.Analysis.KadisonKastler.FiniteCornerRefinement
import OAI.Analysis.KadisonKastler.MatrixAveraging
import OAI.Analysis.KadisonKastler.FullMatrixInjectivity

namespace OAI

/-! # Matrix entries generated by the finite corner groups -/

namespace KadisonKastler

open scoped BigOperators

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  {E : Submodule ℂ H} [CompleteSpace E]

namespace FullMatrixCorner

variable (F : FullMatrixCorner E)

theorem scalarBlockHom_single {n : ℕ} (i j : Fin n) (z : ℂ) :
    F.scalarBlockHom n (CStarMatrix.ofMatrix (Matrix.single i j z)) = z • F.entry i j := by
  rw [F.scalarBlockHom_apply]
  simp [CStarMatrix.ofMatrix_apply, Matrix.single_apply, ite_smul, ite_and]

/-- A single sign reflection isolates a diagonal matrix projection. -/
theorem finiteSignedRepresentation_reflection {n : ℕ} (i : Fin n) :
    (F.finiteSignedRepresentation n
      (SemidirectProduct.inl (Function.update (1 : Fin n → ℤˣ) i (-1))) : H →L[ℂ] H) =
      1 - (2 : ℂ) • F.entry i i := by
  have h : (signedPermutationHom
      (SemidirectProduct.inl (Function.update (1 : Fin n → ℤˣ) i (-1))) :
      Matrix (Fin n) (Fin n) ℂ) = 1 - (2 : ℂ) • Matrix.single i i 1 := by
    rw [← signDiagonal_reflection]
    simp [signedPermutationHom, signDiagonalHom, signDiagonalUnitary]
  have hp : (∑ j : Fin n, F.entry j j) = F.partialDiagonal (Finset.range n) :=
    Fin.sum_univ_eq_sum_range (fun j => F.entry j j) n
  have hsingle : (∑ k : Fin n, ∑ l : Fin n,
      Matrix.single i i (1 : ℂ) k l • F.entry k l) = F.entry i i := by
    simpa only [F.scalarBlockHom_apply, CStarMatrix.ofMatrix_apply, one_smul] using
      F.scalarBlockHom_single i i 1
  have hscale : (∑ k : Fin n, ∑ l : Fin n,
      ((2 : ℂ) • Matrix.single i i (1 : ℂ)) k l • F.entry k l) =
        (2 : ℂ) • F.entry i i := by
    change (∑ k : Fin n, ∑ l : Fin n,
      ((2 : ℂ) * Matrix.single i i (1 : ℂ) k l) • F.entry k l) = _
    simp_rw [mul_smul]
    simp only [← Finset.smul_sum, hsingle]
  rw [F.finiteSignedRepresentation_apply, h]
  simp only [Matrix.sub_apply, sub_smul, Finset.sum_sub_distrib, hscale]
  simp only [Matrix.one_apply, ite_smul, one_smul, zero_smul,
    Finset.sum_ite_eq, Finset.mem_univ, ite_true]
  rw [hp]
  abel

theorem entry_scalarBlock_sandwich {n : ℕ} (i j : Fin n)
    (a : CStarMatrix (Fin n) (Fin n) ℂ) :
    F.entry i i * F.scalarBlockHom n a * F.entry j j = a i j • F.entry i j := by
  rw [F.scalarBlockHom_apply]
  simp only [Finset.mul_sum, Finset.sum_mul, mul_smul_comm, smul_mul_assoc, F.mul_entry]
  simp [Fin.val_inj, ite_mul, smul_ite, F.mul_entry]

/-- Sandwiching any finite group element recovers its matrix coefficient. -/
theorem entry_finiteSigned_sandwich {n : ℕ} (i j : Fin n) (g : SignedPermutation (Fin n)) :
    F.entry i i * (F.finiteSignedRepresentation n g : H →L[ℂ] H) * F.entry j j =
      (signedPermutationHom g : Matrix (Fin n) (Fin n) ℂ) i j • F.entry i j := by
  change F.entry i i *
    (F.scalarBlockHom n (CStarMatrix.ofMatrix (signedPermutationHom g :
      Matrix (Fin n) (Fin n) ℂ)) + (1 - F.scalarBlockHom n 1)) * F.entry j j = _
  rw [mul_add, add_mul, F.entry_scalarBlock_sandwich]
  have hz : F.entry i i * (1 - F.scalarBlockHom n 1) * F.entry j j = 0 := by
    rw [mul_sub, mul_one, sub_mul, F.entry_scalarBlock_sandwich, F.mul_entry]
    by_cases hij : i = j
    · subst j
      simp
    · simp [hij, Fin.val_inj]
  rw [hz, add_zero]
  rfl

/-- Containing the finite signed groups forces containment of all countable
matrix entries. -/
theorem entries_mem_of_finiteSigned (Q : VonNeumannAlgebra H)
    (hQ : ∀ n (g : SignedPermutation (Fin n)),
      (F.finiteSignedRepresentation n g : H →L[ℂ] H) ∈ Q) :
    ∀ i j, F.entry i j ∈ Q := by
  have hdiag (n : ℕ) (i : Fin n) : F.entry i i ∈ Q := by
    change F.entry i i ∈ Q.toSubalgebra
    have h := hQ n (SemidirectProduct.inl (Function.update (1 : Fin n → ℤˣ) i (-1)))
    rw [F.finiteSignedRepresentation_reflection] at h
    have hh : (2 : ℂ) • F.entry i i ∈ Q.toSubalgebra := by
      simpa only [sub_sub_cancel] using Q.sub_mem Q.one_mem h
    exact (Q.toStarSubalgebra.toSubalgebra.toSubmodule.smul_mem_iff
      (by norm_num : (2 : ℂ) ≠ 0)).mp hh
  have hentry (n : ℕ) (i j : Fin n) : F.entry i j ∈ Q := by
    change F.entry i j ∈ Q.toSubalgebra
    have h := Q.mul_mem (Q.mul_mem (hdiag n i)
      (hQ n (SemidirectProduct.inr (Equiv.swap i j)))) (hdiag n j)
    rw [F.entry_finiteSigned_sandwich] at h
    have hm : (signedPermutationHom (SemidirectProduct.inr (Equiv.swap i j)) :
        Matrix (Fin n) (Fin n) ℂ) = Matrix.permMatrixHom (R := ℂ) (Equiv.swap i j) := by
      simp [signedPermutationHom, permutationHom, permutationUnitary]
    simpa only [hm, permutationMatrix_apply, Equiv.swap_apply_right, ite_true, one_smul] using h
  intro i j
  exact hentry (max i j + 1) ⟨i, Nat.lt_succ_of_le (Nat.le_max_left i j)⟩
    ⟨j, Nat.lt_succ_of_le (Nat.le_max_right i j)⟩

end FullMatrixCorner

end

end KadisonKastler

end OAI
