import OAI.Analysis.KadisonKastler.FiniteCornerGeneration
import OAI.Analysis.KadisonKastler.LocalizedMatrixChainEmbedding

namespace OAI

/-! # Constructed embeddings of countable scalar matrix algebras -/

namespace KadisonKastler

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  {E : Submodule ℂ H} [CompleteSpace E]

namespace FullMatrixCorner

variable (F : FullMatrixCorner E)

/-- The locally finite group carried by the countable matrix units. -/
def signedGroupUnion : Subgroup (unitary (H →L[ℂ] H)) :=
  increasingSubgroupUnion F.finiteSignedGroup F.finiteSignedGroup_monotone

theorem signedGroupUnion_mem (u : F.signedGroupUnion) :
    (u : H →L[ℂ] H) ∈ F.scalarMatrixAlgebra := by
  obtain ⟨n, hn⟩ := u.property
  exact F.finiteSignedGroup_mem F.scalarMatrixAlgebra F.entry_mem_scalarMatrixAlgebra
    n ⟨u.val, hn⟩

/-- The finite signed groups generate exactly the scalar matrix algebra. -/
theorem signedGroupUnion_generates :
    generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ (Set.range (fun u =>
      (subgroupAlgebraRepresentation F.signedGroupUnion F.scalarMatrixAlgebra
        F.signedGroupUnion_mem u : H →L[ℂ] H)))) = F.scalarMatrixAlgebra := by
  let V := subgroupAlgebraRepresentation F.signedGroupUnion F.scalarMatrixAlgebra
    F.signedGroupUnion_mem
  let Q := generatedVonNeumannAlgebra
    (StarAlgebra.adjoin ℂ (Set.range (fun u => (V u : H →L[ℂ] H))))
  change Q = F.scalarMatrixAlgebra
  apply le_antisymm
  · apply generatedVonNeumannAlgebra_le_of_le
    apply StarAlgebra.adjoin_le
    rintro _ ⟨u, rfl⟩
    exact (V u).val.property
  · apply F.scalarMatrixAlgebra_le
    apply F.entries_mem_of_finiteSigned
    intro n g
    let u : F.signedGroupUnion := ⟨F.finiteSignedRepresentation n g, ⟨n, g, rfl⟩⟩
    exact subset_generatedVonNeumannAlgebra _ (StarAlgebra.subset_adjoin ℂ _ ⟨u, rfl⟩)

/-- A single near-identity unitary embeds all countably many matrix entries.
Its location is retained in the algebra generated by the source and target. -/
theorem exists_localized_embedding (M N : VonNeumannAlgebra H)
    (hF : ∀ i j, F.entry i j ∈ M) {γ : ℝ}
    (hγ : 0 ≤ γ) (hsmall : γ ≤ 1 / 1152) (hnear : NearInclusion M N γ) :
    ∃ w : unitary (H →L[ℂ] H),
      (w : H →L[ℂ] H) ∈ generatedVonNeumannAlgebra (M.toStarSubalgebra ⊔ N.toStarSubalgebra) ∧
      (∀ i j, unitaryConj w (F.entry i j) ∈ N) ∧
      ‖(w : H →L[ℂ] H) - 1‖ ≤ 84 * γ := by
  let K := F.finiteSignedGroup
  let hK := F.finiteSignedGroup_monotone
  let G : Type _ := increasingSubgroupUnion K hK
  let : TopologicalSpace G := ⊥
  let : DiscreteTopology G := ⟨rfl⟩
  let J := generatedVonNeumannAlgebra (M.toStarSubalgebra ⊔ N.toStarSubalgebra)
  have hMJ : M ≤ J := fun _ hx => subset_generatedVonNeumannAlgebra _
    ((show M.toStarSubalgebra ≤ M.toStarSubalgebra ⊔ N.toStarSubalgebra from le_sup_left) hx)
  have hNJ : N ≤ J := fun _ hx => subset_generatedVonNeumannAlgebra _
    ((show N.toStarSubalgebra ≤ M.toStarSubalgebra ⊔ N.toStarSubalgebra from le_sup_right) hx)
  obtain ⟨w, hwJ, hw, hn⟩ := exists_unitary_embedding_of_invariant_group_in_algebra
    (increasingFiniteScalarInvariantMean (increasingUnionStage K hK)
      (increasingUnionStage_monotone K hK) (increasingUnionStage_covers K hK))
    ((F.scalarMatrixAlgebra_le M hF).trans hMJ) hNJ
    (subgroupAlgebraRepresentation F.signedGroupUnion F.scalarMatrixAlgebra
      F.signedGroupUnion_mem) F.signedGroupUnion_generates hγ hsmall
    (nearInclusion_mono_left (F.scalarMatrixAlgebra_le M hF) hnear)
  exact ⟨w, hwJ, fun i j => hw _ (F.entry_mem_scalarMatrixAlgebra i j), hn⟩

end FullMatrixCorner

end

end KadisonKastler

end OAI
