import OAI.Analysis.KadisonKastler.InvariantGroupEmbedding
import OAI.Analysis.KadisonKastler.PublishedKaplansky

namespace OAI

/-! # Embedding a weakly generated locally finite group algebra

The group correction is simultaneous on the entire group. Bicommutant
generation then passes its inclusion into the target to the full algebra.
-/

namespace KadisonKastler

noncomputable section

variable {G H : Type*} [Group G] [TopologicalSpace G] [DiscreteTopology G]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Near inclusion embeds a von Neumann algebra weakly generated by a
unitary representation of a group carrying the supplied invariant mean. -/
theorem exists_unitary_embedding_of_invariant_group
    (m : ScalarInvariantMean G) {M N : VonNeumannAlgebra H}
    (U : G →* unitary (Algebra M))
    (hgen : generatedVonNeumannAlgebra
      (StarAlgebra.adjoin ℂ (Set.range (fun g => (U g : H →L[ℂ] H)))) = M)
    {γ : ℝ} (hγ : 0 ≤ γ) (hsmall : γ ≤ 1 / 1152) (hnear : NearInclusion M N γ) :
    ∃ w : unitary (H →L[ℂ] H), (∀ x ∈ M, unitaryConj w x ∈ N) ∧
      ‖(w : H →L[ℂ] H) - 1‖ ≤ 84 * γ := by
  obtain ⟨w, hw, hn⟩ := exists_unitary_invariantGroup_embedding_of_nearInclusion
    m U hγ hsmall hnear
  let R := unitaryConjugateAlgebra (star w) N
  have hMR : M ≤ R := by
    rw [← hgen]
    apply generatedVonNeumannAlgebra_le_of_le
    apply StarAlgebra.adjoin_le
    rintro _ ⟨g, rfl⟩
    exact ⟨unitaryConj w (U g : H →L[ℂ] H), hw g,
      unitaryConj_star_unitaryConj w _⟩
  refine ⟨w, ?_, hn⟩
  intro x hx
  obtain ⟨y, hy, hxy⟩ := hMR hx
  change unitaryConj (star w) y = x at hxy
  rw [← hxy]
  have he := unitaryConj_star_unitaryConj (star w) y
  simp only [star_star] at he
  rw [he]
  exact hy

/-- The invariant mean is constructed from the increasing finite subgroups;
no amenability hypothesis is retained. -/
theorem exists_unitary_embedding_of_increasing_finite_groups
    (K : ℕ → Subgroup G) [∀ n, Finite (K n)] (hmono : Monotone K)
    (hcover : ∀ g : G, ∃ n, g ∈ K n) {M N : VonNeumannAlgebra H}
    (U : G →* unitary (Algebra M))
    (hgen : generatedVonNeumannAlgebra
      (StarAlgebra.adjoin ℂ (Set.range (fun g => (U g : H →L[ℂ] H)))) = M)
    {γ : ℝ} (hγ : 0 ≤ γ) (hsmall : γ ≤ 1 / 1152) (hnear : NearInclusion M N γ) :
    ∃ w : unitary (H →L[ℂ] H), (∀ x ∈ M, unitaryConj w x ∈ N) ∧
      ‖(w : H →L[ℂ] H) - 1‖ ≤ 84 * γ :=
  exists_unitary_embedding_of_invariant_group
    (increasingFiniteScalarInvariantMean K hmono hcover) U hgen hγ hsmall hnear

end

end KadisonKastler

end OAI
