import OAI.Analysis.KadisonKastler.TraceHilbertActions
import OAI.Analysis.FactorGeneration.MatrixSequence

namespace OAI

/-! # The irreducible matrix-generated subfactor

In a separable tracial representation, the existing matrix refinement
construction supplies the subfactor used in the finite stability argument.
No extra published existence hypothesis is introduced.
-/

namespace KadisonKastler

open Generator Generator.Tracial

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [TopologicalSpace.SeparableSpace H] {M : VonNeumannAlgebra H}

/-- A concrete separable II₁ factor with its faithful vector trace contains
an irreducible II₁ subfactor generated by an increasing sequence of full
matrix algebras. -/
theorem exists_irreducible_matrix_subfactor
    (τ : UltrapowerBridge.TracialRepresentation M)
    (hM : IsII1Factor M.toStarSubalgebra) :
    ∃ (R : VonNeumannAlgebra H) (hRM : R ≤ M),
      IsII1Factor R.toStarSubalgebra ∧
      (∀ b : Algebra M,
        (∀ r : Algebra R, coordinateInclusion hRM r * b = b * coordinateInclusion hRM r) →
        ∃ c : ℂ, b = c • (1 : Algebra M)) ∧
      ∃ A : ℕ → FiniteMatrixStage M,
        R = FiniteMatrixStage.generatedVonNeumann A ∧
        Monotone (fun n => (A n).units.concreteAlgebra) ∧
        (∀ n, FiniteDimensional ℂ (A n).units.concreteAlgebra) := by
  have hsep : TopologicalSpace.IsSeparable (Set.range (baseVector τ)) :=
    TopologicalSpace.IsSeparable.of_separableSpace _
  have hirr : ∀ b : Algebra M,
      (∀ r : Algebra M, coordinateInclusion (le_refl M) r * b =
        b * coordinateInclusion (le_refl M) r) → ∃ c : ℂ, b = c • (1 : Algebra M) := by
    intro b hb
    exact traceHilbert_factor hM b hb
  obtain ⟨A, _, hmono, hfd, hII, _, hscalar⟩ :=
    FiniteMatrixStage.exists_irreducible_matrix_generated_II1 τ (le_refl M)
      (traceHilbert_factor hM) hM.diffuse hirr hsep
  refine ⟨FiniteMatrixStage.generatedVonNeumann A,
    FiniteMatrixStage.generatedVonNeumann_le A, hII, ?_, A, rfl, hmono, hfd⟩
  intro b hb
  refine ⟨τ.trace b, hscalar b ?_⟩
  intro r
  exact congrArg Subtype.val (hb r)

end

end KadisonKastler

end OAI
