import OAI.Analysis.KadisonKastler.MatrixChainEmbedding
import OAI.Analysis.KadisonKastler.LocalizedGroupEmbedding

namespace OAI

/-! # Localized embedding of an increasing matrix closure -/

namespace KadisonKastler

noncomputable section

variable {G H : Type*} [Group G] [TopologicalSpace G] [DiscreteTopology G]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A generating representation gives an embedding of the whole algebra,
with the unitary retained inside any prescribed containing algebra. -/
theorem exists_unitary_embedding_of_invariant_group_in_algebra
    (m : ScalarInvariantMean G) {M N J : VonNeumannAlgebra H}
    (hMJ : M ≤ J) (hNJ : N ≤ J) (U : G →* unitary (Algebra M))
    (hgen : generatedVonNeumannAlgebra
      (StarAlgebra.adjoin ℂ (Set.range (fun g => (U g : H →L[ℂ] H)))) = M)
    {γ : ℝ} (hγ : 0 ≤ γ) (hsmall : γ ≤ 1 / 1152) (hnear : NearInclusion M N γ) :
    ∃ w : unitary (H →L[ℂ] H), (w : H →L[ℂ] H) ∈ J ∧
      (∀ x ∈ M, unitaryConj w x ∈ N) ∧ ‖(w : H →L[ℂ] H) - 1‖ ≤ 84 * γ := by
  obtain ⟨w, hwJ, hw, hn⟩ := exists_unitary_invariantGroup_embedding_in_algebra
    m hMJ hNJ U hγ hsmall hnear
  let R := unitaryConjugateAlgebra (star w) N
  have hMR : M ≤ R := by
    rw [← hgen]
    apply generatedVonNeumannAlgebra_le_of_le
    apply StarAlgebra.adjoin_le
    rintro _ ⟨g, rfl⟩
    exact ⟨unitaryConj w (U g : H →L[ℂ] H), hw g,
      unitaryConj_star_unitaryConj w _⟩
  refine ⟨w, hwJ, ?_, hn⟩
  intro x hx
  obtain ⟨y, hy, hxy⟩ := hMR hx
  change unitaryConj (star w) y = x at hxy
  rw [← hxy]
  have he := unitaryConj_star_unitaryConj (star w) y
  simp only [star_star] at he
  rw [he]
  exact hy

omit [Group G] [TopologicalSpace G] [DiscreteTopology G] in
/-- Localized embedding for the actual increasing full-matrix closure. -/
theorem exists_unitary_matrixChain_embedding_in_algebra [Nontrivial H]
    {A : ℕ → StarSubalgebra ℂ (H →L[ℂ] H)}
    (F : ∀ n, FullMatrixFrame (A n)) (hA : Monotone A)
    {N J : VonNeumannAlgebra H}
    (hRJ : generatedVonNeumannAlgebra (⨆ n, A n) ≤ J) (hNJ : N ≤ J)
    {γ : ℝ} (hγ : 0 ≤ γ) (hsmall : γ ≤ 1 / 1152)
    (hnear : NearInclusion (generatedVonNeumannAlgebra (⨆ n, A n)) N γ) :
    ∃ w : unitary (H →L[ℂ] H), (w : H →L[ℂ] H) ∈ J ∧
      (∀ x ∈ generatedVonNeumannAlgebra (⨆ n, A n), unitaryConj w x ∈ N) ∧
      ‖(w : H →L[ℂ] H) - 1‖ ≤ 84 * γ := by
  let K := fun n => (compatibleMatrixFrames F hA n).group
  let hK := compatibleMatrixFrames_group_monotone F hA
  let D := increasingSubgroupUnion K hK
  let : TopologicalSpace D := ⊥
  let : DiscreteTopology D := ⟨rfl⟩
  exact exists_unitary_embedding_of_invariant_group_in_algebra
    (increasingFiniteScalarInvariantMean (increasingUnionStage K hK)
      (increasingUnionStage_monotone K hK) (increasingUnionStage_covers K hK))
    hRJ hNJ (subgroupAlgebraRepresentation D _ (matrixChainGroup_mem F hA))
    (matrixChainGroup_generates F hA) hγ hsmall hnear

omit [Group G] [TopologicalSpace G] [DiscreteTopology G] in
/-- The conjugating unitary belongs to the algebra generated by the source
matrix closure and its nearby target. -/
theorem exists_localized_unitary_matrixChain_embedding [Nontrivial H]
    {A : ℕ → StarSubalgebra ℂ (H →L[ℂ] H)}
    (F : ∀ n, FullMatrixFrame (A n)) (hA : Monotone A)
    {N : VonNeumannAlgebra H} {γ : ℝ} (hγ : 0 ≤ γ) (hsmall : γ ≤ 1 / 1152)
    (hnear : NearInclusion (generatedVonNeumannAlgebra (⨆ n, A n)) N γ) :
    ∃ w : unitary (H →L[ℂ] H),
      (w : H →L[ℂ] H) ∈ generatedVonNeumannAlgebra
        ((generatedVonNeumannAlgebra (⨆ n, A n)).toStarSubalgebra ⊔ N.toStarSubalgebra) ∧
      (∀ x ∈ generatedVonNeumannAlgebra (⨆ n, A n), unitaryConj w x ∈ N) ∧
      ‖(w : H →L[ℂ] H) - 1‖ ≤ 84 * γ := by
  apply exists_unitary_matrixChain_embedding_in_algebra F hA
    (fun _ hx => subset_generatedVonNeumannAlgebra _ ((show (generatedVonNeumannAlgebra (⨆ n, A n)).toStarSubalgebra ≤
      (generatedVonNeumannAlgebra (⨆ n, A n)).toStarSubalgebra ⊔ N.toStarSubalgebra from le_sup_left) hx))
    (fun _ hx => subset_generatedVonNeumannAlgebra _ ((show N.toStarSubalgebra ≤
      (generatedVonNeumannAlgebra (⨆ n, A n)).toStarSubalgebra ⊔ N.toStarSubalgebra from le_sup_right) hx)) hγ hsmall hnear

end

end KadisonKastler

end OAI
