import OAI.Analysis.KadisonKastler.FiniteBaseExpectation
import OAI.Analysis.KadisonKastler.TraceSeparableAdjoin

namespace OAI

/-! # The second finite-base independence application

The test space is constructed inside the algebra generated by the
constant algebra and the first model unitary. Its separability follows
from the proved trace-separability extension theorem.
-/

namespace KadisonKastler

noncomputable section

variable {B : Type*} [CStarAlgebra B]

def positionAlgebra (A : StarSubalgebra ℂ B) (u : B) : StarSubalgebra ℂ B :=
  StarAlgebra.adjoin ℂ ((A : Set B) ∪ {u})

def positionTestSpace (τ : FaithfulTracialState B) (D : StarSubalgebra ℂ B)
    [FiniteDimensional ℂ D] (A : StarSubalgebra ℂ B) (u : B) : Submodule ℂ B :=
  (positionAlgebra A u).toSubmodule ⊓ LinearMap.ker (finiteBaseExpectation τ D)

theorem mem_positionTestSpace (τ : FaithfulTracialState B) (D : StarSubalgebra ℂ B)
    [FiniteDimensional ℂ D] (A : StarSubalgebra ℂ B) (u x : B) :
    x ∈ positionTestSpace τ D A u ↔
      x ∈ positionAlgebra A u ∧ TraceOrthogonal τ D x := by
  change (x ∈ positionAlgebra A u ∧ finiteBaseExpectation τ D x = 0) ↔ _
  rw [finiteBaseExpectation_zero_iff]

/-- This is exactly the separable test space needed in the second Popa
application; no separability premise remains for the generated algebra. -/
theorem positionTestSpace_traceSeparable (τ : FaithfulTracialState B)
    (D : StarSubalgebra ℂ B) [FiniteDimensional ℂ D]
    (A : StarSubalgebra ℂ B) (hA : TraceSeparable τ (A : Set B)) (u : B) :
    TraceSeparable τ (positionTestSpace τ D A u : Set B) :=
  (hA.adjoin_singleton τ A u).mono (fun _ hx => hx.1)

theorem FiniteBaseIndependence.exists_position {τ : FaithfulTracialState B}
    (h : FiniteBaseIndependence τ) (D : StarSubalgebra ℂ B) [FiniteDimensional ℂ D]
    (A : StarSubalgebra ℂ B) (hA : TraceSeparable τ (A : Set B)) (u : B) :
    ∃ w : unitary B,
      (∀ b ∈ D, Commute (w : B) b) ∧
      (∀ k : ℤ, k ≠ 0 → τ.toLinearMap (haarPower w k) = 0) ∧
      HaarEndpointIndependence τ D (positionTestSpace τ D A u) w := by
  apply h D inferInstance (positionTestSpace τ D A u)
    (positionTestSpace_traceSeparable τ D A hA u)
  intro x hx
  exact (mem_positionTestSpace τ D A u x).mp hx |>.2

end

end KadisonKastler

end OAI
