import OAI.Analysis.KadisonKastler.PreparedPairIrreducibility
import OAI.Analysis.KadisonKastler.AmenableEmbedding
import OAI.Analysis.KadisonKastler.Normalizer

namespace OAI

/-! # Preserving the first inclusion under the commutant correction

The second local embedding in the preparation argument is chosen in the
von Neumann algebra generated by the right algebra and the neighboring
commutant. That entire generated algebra commutes with the common left
algebra. These are algebraic consequences of the location of the chosen
unitary; its existence is not assumed here as a new perturbation theorem.
-/

namespace KadisonKastler

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The right algebra and the neighboring commutant generate an algebra
commuting with the common left algebra. -/
theorem generated_right_correction_le_commutant
    (R S N : VonNeumannAlgebra H) (hRN : R ≤ N) (hSR : S ≤ R.commutant) :
    generatedVonNeumannAlgebra (S.toStarSubalgebra ⊔ N.commutant.toStarSubalgebra) ≤
      R.commutant := by
  apply generatedVonNeumannAlgebra_le_of_le
  apply sup_le hSR
  intro x hx
  apply VonNeumannAlgebra.mem_commutant_iff.mpr
  intro r hr
  exact VonNeumannAlgebra.mem_commutant_iff.mp hx r (hRN hr)

/-- Membership in a conjugated commutant is the same as conjugating
the membership in the original commutant. -/
theorem unitaryConj_mem_conjugated_commutant
    (N : VonNeumannAlgebra H) (w : unitary (H →L[ℂ] H))
    {x : H →L[ℂ] H} (hx : x ∈ N.commutant) :
    unitaryConj w x ∈ (unitaryConjugateAlgebra w N).commutant := by
  apply VonNeumannAlgebra.mem_commutant_iff.mpr
  rintro y ⟨z, hz, rfl⟩
  have he := congrArg (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) w)
    (VonNeumannAlgebra.mem_commutant_iff.mp hx z hz)
  rw [map_mul, map_mul] at he
  exact he

/-- Inverse conjugation of a moved right algebra gives the desired
right inclusion for the corrected neighboring algebra. -/
theorem right_inclusion_of_moved_right_algebra
    (S N : VonNeumannAlgebra H) (w : unitary (H →L[ℂ] H))
    (hmove : ∀ s ∈ S, unitaryConj w s ∈ N.commutant) :
    S ≤ (unitaryConjugateAlgebra (star w) N).commutant := by
  intro s hs
  have hm := unitaryConj_mem_conjugated_commutant N (star w) (hmove s hs)
  simpa only [unitaryConj_star_unitaryConj] using hm

/-- A correction from the indicated generated algebra preserves the
first, literal common inclusion and establishes the second one. -/
theorem preparedPair_second_correction
    (R S N : VonNeumannAlgebra H) (hRN : R ≤ N) (hSR : S ≤ R.commutant)
    (w : unitary (H →L[ℂ] H))
    (hw : (w : H →L[ℂ] H) ∈ generatedVonNeumannAlgebra
      (S.toStarSubalgebra ⊔ N.commutant.toStarSubalgebra))
    (hmove : ∀ s ∈ S, unitaryConj w s ∈ N.commutant) :
    R ≤ unitaryConjugateAlgebra (star w) N ∧
      S ≤ (unitaryConjugateAlgebra (star w) N).commutant := by
  have hwR : (w : H →L[ℂ] H) ∈ R.commutant :=
    generated_right_correction_le_commutant R S N hRN hSR hw
  refine ⟨?_, right_inclusion_of_moved_right_algebra S N w hmove⟩
  apply le_unitaryConjugateAlgebra_star w
  intro r hr
  simpa only [unitaryConj_eq_self_of_mem_commutant hwR hr] using hRN hr

/-- The corrected pair has the same elementary gap loss as any unitary
movement of the neighbor. -/
theorem preparedPair_second_correction_gap
    (M N : VonNeumannAlgebra H) (w : unitary (H →L[ℂ] H)) :
    kkDistance M (unitaryConjugateAlgebra (star w) N) ≤
      kkDistance M N + 2 * ‖(w : H →L[ℂ] H) - 1‖ := by
  have hs : ‖((star w : unitary (H →L[ℂ] H)) : H →L[ℂ] H) - 1‖ =
      ‖(w : H →L[ℂ] H) - 1‖ := by
    simpa only [Unitary.coe_star, star_sub, star_one] using
      norm_star ((w : H →L[ℂ] H) - 1)
  simpa only [hs] using
    (kkDistance_conjugate_le (M := M) (conjugates_unitaryConjugateAlgebra (star w) N))

end

end KadisonKastler

end OAI
