import OAI.Analysis.KadisonKastler.PrescribedWordBounds
import OAI.Analysis.KadisonKastler.FaithfulRepresentation
import Mathlib.Topology.Algebra.StarSubalgebra

namespace OAI

/-!
# The published faithful free-product representation input

The only input here is the standard faithful reduced-free-product
representation of a scalar-free family with a faithful tracial state.
The creation, annihilation and preservation formulas are those of
Ricard–Xu, *Khintchine type inequalities for reduced free products and
applications*, J. reine angew. Math. 599 (2006), §1 and Fact 2.6
(arXiv:math/0505302v2, printed pp. 3 and 7).

We use only finite diagonal algebras with equal trace projections. The
input supplies their representation and structural identities, without
assuming any projection-word norm estimate. The latter has been proved
in `FreeProjectionWords` from those identities.
-/

namespace KadisonKastler

open Finset

noncomputable section

universe u

/-- The state data needed for faithful reduced free products. -/
structure FaithfulTracialState (B : Type u) [CStarAlgebra B] where
  toLinearMap : B →ₗ[ℂ] ℂ
  map_one : toLinearMap 1 = 1
  positive : ∀ x, 0 ≤ (toLinearMap (star x * x)).re
  positive_im : ∀ x, (toLinearMap (star x * x)).im = 0
  faithful : ∀ x, toLinearMap (star x * x) = 0 → x = 0
  tracial : ∀ x y, toLinearMap (x * y) = toLinearMap (y * x)

/-- The norm-closed algebra generated by the diagonal projections. -/
def generatedDiagonal {B : Type u} [CStarAlgebra B] {r d : ℕ}
    (e : Fin r → Fin d → B) : StarSubalgebra ℂ B :=
  (StarAlgebra.adjoin ℂ (Set.range (fun ia : Fin r × Fin d => e ia.1 ia.2))).topologicalClosure

noncomputable instance generatedDiagonalCStarAlgebra {B : Type u} [CStarAlgebra B]
    {r d : ℕ} (e : Fin r → Fin d → B) : CStarAlgebra (generatedDiagonal e) :=
  StarSubalgebra.cstarAlgebra _ (h_closed := StarSubalgebra.isClosed_topologicalClosure _)

theorem mem_generatedDiagonal {B : Type u} [CStarAlgebra B] {r d : ℕ}
    (e : Fin r → Fin d → B) (i : Fin r) (a : Fin d) : e i a ∈ generatedDiagonal e :=
  StarSubalgebra.le_topologicalClosure _
    (StarAlgebra.subset_adjoin ℂ _ ⟨(i, a), rfl⟩)

def generatedDiagonalProjection {B : Type u} [CStarAlgebra B] {r d : ℕ}
    (e : Fin r → Fin d → B) (i : Fin r) (a : Fin d) : generatedDiagonal e :=
  ⟨e i a, mem_generatedDiagonal e i a⟩

/-- Scalar freeness, specialized to the span of each finite diagonal
partition. Adjacent copy indices differ; every letter has zero trace. -/
def ScalarFreeDiagonal {B : Type u} [CStarAlgebra B] {r d : ℕ}
    (τ : FaithfulTracialState B) (e : Fin r → Fin d → B) : Prop :=
  ∀ n : ℕ, 0 < n → ∀ (position : Fin n → Fin r) (c : Fin n → Fin d → ℂ),
    (∀ i j : Fin n, i.val + 1 = j.val → position i ≠ position j) →
    (∀ i, ∑ a, c i a = 0) →
    τ.toLinearMap ((List.ofFn (fun i => ∑ a, c i a • e (position i) a)).prod) = 0

/-- A precise specialization of the faithful reduced-free-product
representation, with no quantitative word bounds in its conclusion. -/
def PublishedDiagonalFockRepresentation : Prop :=
  ∀ (B : Type u) [CStarAlgebra B] (r d : ℕ) [NeZero d]
    (τ : FaithfulTracialState B) (e : Fin r → Fin d → B),
    (∀ i a, IsStarProjection (e i a)) →
    (∀ i a b, a ≠ b → e i a * e i b = 0) →
    (∀ i, ∑ a, e i a = 1) →
    (∀ i a, τ.toLinearMap (e i a) = (d : ℂ)⁻¹) →
    ScalarFreeDiagonal τ e →
    ∃ (K : Type u) (_ : NormedAddCommGroup K) (_ : InnerProductSpace ℂ K)
      (_ : CompleteSpace K) (M : FreeDiagonalModel (Fin r) (Fin d) K)
      (π : generatedDiagonal e →⋆ₐ[ℂ] (K →L[ℂ] K)),
      Function.Injective π ∧ ∀ i a, π (generatedDiagonalProjection e i a) = M.e i a

/-- Faithful representation transfers every finite sum of diagonal
words, including sums with repeated labels, without changing its norm. -/
theorem norm_sum_diagonalWords_eq {B : Type u} [CStarAlgebra B] {r d : ℕ}
    {K : Type*} [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
    [NeZero d] (e : Fin r → Fin d → B) (M : FreeDiagonalModel (Fin r) (Fin d) K)
    (π : generatedDiagonal e →⋆ₐ[ℂ] (K →L[ℂ] K)) (hπ : Function.Injective π)
    (he : ∀ i a, π (generatedDiagonalProjection e i a) = M.e i a)
    {T : Type*} (s : Finset T) (label : T → Fin r → Fin d) :
    ‖∑ t ∈ s, (List.ofFn (fun i => e i (label t i))).prod‖ =
      ‖∑ t ∈ s, M.projectionWord id (label t)‖ := by
  let x : generatedDiagonal e :=
    ∑ t ∈ s, (List.ofFn (fun i => generatedDiagonalProjection e i (label t i))).prod
  have hx : (x : B) = ∑ t ∈ s, (List.ofFn (fun i => e i (label t i))).prod := by
    change (generatedDiagonal e).subtype x = _
    simp only [x, map_sum, map_list_prod, List.map_ofFn, Function.comp_def]
    rfl
  have hmap : π x = ∑ t ∈ s, M.projectionWord id (label t) := by
    simp only [x, map_sum, map_list_prod, List.map_ofFn, Function.comp_def, he,
      FreeDiagonalModel.projectionWord, tupleOperatorProduct, id_eq]
  calc
    _ = ‖x‖ := by rw [← hx]; rfl
    _ = ‖π x‖ := (injective_starAlgHom_norm π hπ x).symm
    _ = _ := by rw [hmap]

/-- The manuscript's projection-word estimate, conditional only on the
standard faithful Fock representation of the scalar-free diagonals. -/
theorem norm_freeProjectionWords_le_of_published
    (hFock : PublishedDiagonalFockRepresentation.{u})
    {B : Type u} [CStarAlgebra B] {r d : ℕ} [NeZero d]
    (τ : FaithfulTracialState B) (e : Fin r → Fin d → B)
    (hprojection : ∀ i a, IsStarProjection (e i a))
    (horthogonal : ∀ i a b, a ≠ b → e i a * e i b = 0)
    (hsum : ∀ i, ∑ a, e i a = 1)
    (htrace : ∀ i a, τ.toLinearMap (e i a) = (d : ℂ)⁻¹)
    (hfree : ScalarFreeDiagonal τ e)
    (hr : 1 ≤ r) (hd : freeWordThreshold r ≤ d) (s : Sym (Fin d) r) :
    ‖∑ t : PrescribedLabelTuple s, (List.ofFn (fun i => e i (t.val i))).prod‖ ≤
      projectionWordWeight (freeWordC r) s := by
  obtain ⟨K, hK, hIP, hComplete, M, π, hπ, he⟩ :=
    hFock B r d τ e hprojection horthogonal hsum htrace hfree
  let := hK
  let := hIP
  let := hComplete
  rw [norm_sum_diagonalWords_eq e M π hπ he univ (fun t : PrescribedLabelTuple s => t.val)]
  exact M.norm_prescribed_projectionWords_le hr (by simpa using hd) s id Function.injective_id

end

end KadisonKastler

end OAI
