import OAI.Analysis.KadisonKastler.DenseUnitBallGap
import OAI.Analysis.FactorGeneration.Bicommutant

namespace OAI

/-! # The published bounded-density input

Irving Kaplansky, *A theorem on rings of operators*, Pacific Journal of
Mathematics 1 (1951), 227--232, Theorem 1, p. 227:
https://msp.org/pjm/1951/1-2/pjm-v1-n2-p06-s.pdf

The paper's terminology "unit sphere" is the closed unit ball, as the
norm bounds in the proof on pp. 228 and 230--231 explicitly show.
The input below is its finite-strong-neighborhood specialization to a
unital star algebra and its bicommutant. The already proved double
commutant theorem supplies the required strong density. No statement
comparing two algebras or their Kadison--Kastler distances is assumed.
-/

namespace KadisonKastler

open Filter
open scoped Topology

noncomputable section

universe u

/-- Kaplansky's published unit-ball density theorem, retaining only finite
vector tests needed in the nonseparable reduction. -/
def PublishedKaplanskyDensity : Prop :=
  ∀ (H : Type u) [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H],
    ∀ (A : StarSubalgebra ℂ (H →L[ℂ] H)) (T : H →L[ℂ] H),
      T ∈ Set.centralizer (Set.centralizer (A : Set (H →L[ℂ] H))) → ‖T‖ ≤ 1 →
      ∀ (V : Finset H) (ε : ℝ), 0 < ε →
        ∃ a : A, ‖a‖ ≤ 1 ∧ ∀ x ∈ V, ‖T x - (a : H →L[ℂ] H) x‖ < ε

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The actual von Neumann algebra generated by a unital star algebra. -/
def generatedVonNeumannAlgebra (A : StarSubalgebra ℂ (H →L[ℂ] H)) :
    VonNeumannAlgebra H where
  toStarSubalgebra := StarSubalgebra.centralizer ℂ
    (StarSubalgebra.centralizer ℂ (A : Set (H →L[ℂ] H)) : Set (H →L[ℂ] H))
  centralizer_centralizer' := by
    let S := (StarSubalgebra.centralizer ℂ (A : Set (H →L[ℂ] H)) :
      Set (H →L[ℂ] H))
    change (S ∪ star S).centralizer.centralizer.centralizer = (S ∪ star S).centralizer
    exact Set.centralizer_centralizer_centralizer _

@[simp] theorem generatedVonNeumannAlgebra_coe
    (A : StarSubalgebra ℂ (H →L[ℂ] H)) :
    (generatedVonNeumannAlgebra A : Set (H →L[ℂ] H)) =
      Set.centralizer (Set.centralizer (A : Set (H →L[ℂ] H))) := by
  change (StarSubalgebra.centralizer ℂ
    (StarSubalgebra.centralizer ℂ (A : Set (H →L[ℂ] H)) : Set (H →L[ℂ] H)) :
      Set (H →L[ℂ] H)) = _
  rw [StarSubalgebra.coe_centralizer_centralizer, StarMemClass.star_coe_eq, Set.union_self]

theorem subset_generatedVonNeumannAlgebra (A : StarSubalgebra ℂ (H →L[ℂ] H)) :
    (A : Set (H →L[ℂ] H)) ⊆ generatedVonNeumannAlgebra A := by
  rw [generatedVonNeumannAlgebra_coe]
  exact Set.subset_centralizer_centralizer

/-- A concrete von Neumann algebra contains the generated algebra of
each of its star subalgebras. -/
theorem generatedVonNeumannAlgebra_le_of_le
    (A : StarSubalgebra ℂ (H →L[ℂ] H)) (B : VonNeumannAlgebra H)
    (hAB : A ≤ B.toStarSubalgebra) : generatedVonNeumannAlgebra A ≤ B := by
  intro x hx
  change x ∈ (generatedVonNeumannAlgebra A : Set (H →L[ℂ] H)) at hx
  rw [generatedVonNeumannAlgebra_coe] at hx
  change x ∈ (B : Set (H →L[ℂ] H))
  rw [← B.centralizer_centralizer]
  exact Set.centralizer_subset (Set.centralizer_subset hAB) hx

/-- Turn the finite-neighborhood published statement into an actual
strongly convergent net of contractions. -/
theorem PublishedKaplanskyDensity.exists_strong_contraction_net
    (hK : PublishedKaplanskyDensity.{u})
    (A : StarSubalgebra ℂ (H →L[ℂ] H)) (T : H →L[ℂ] H)
    (hT : T ∈ Set.centralizer (Set.centralizer (A : Set (H →L[ℂ] H))))
    (hn : ‖T‖ ≤ 1) :
    ∃ a : Finset H × ℕ → A, (∀ d, ‖a d‖ ≤ 1) ∧
      ∀ x : H, Tendsto (fun d => (a d : H →L[ℂ] H) x) atTop (𝓝 (T x)) := by
  classical
  have hex (d : Finset H × ℕ) :=
    hK H A T hT hn d.1 (1 / ((d.2 : ℝ) + 1)) (by positivity)
  choose a hn ha using hex
  refine ⟨a, hn, ?_⟩
  intro x
  apply (tendsto_iff_dist_tendsto_zero).mpr
  have hsnd : Tendsto (fun d : Finset H × ℕ => d.2) atTop atTop := by
    rw [← prod_atTop_atTop_eq]
    exact tendsto_snd
  apply squeeze_zero' (Eventually.of_forall (fun d => dist_nonneg)) ?_
    (tendsto_one_div_add_atTop_nhds_zero_nat.comp hsnd)
  filter_upwards [eventually_ge_atTop (({x} : Finset H), 0)] with d hd
  rw [dist_comm, dist_eq_norm]
  exact (ha d x (hd.1 (Finset.mem_singleton_self x))).le

/-- The same actual net converges on every matrix coefficient. -/
theorem PublishedKaplanskyDensity.exists_weak_contraction_net
    (hK : PublishedKaplanskyDensity.{u})
    (A : StarSubalgebra ℂ (H →L[ℂ] H)) (T : H →L[ℂ] H)
    (hT : T ∈ Set.centralizer (Set.centralizer (A : Set (H →L[ℂ] H))))
    (hn : ‖T‖ ≤ 1) :
    ∃ a : Finset H × ℕ → A, (∀ d, ‖a d‖ ≤ 1) ∧
      ∀ x y : H, Tendsto (fun d => inner ℂ y ((a d : H →L[ℂ] H) x))
        atTop (𝓝 (inner ℂ y (T x))) := by
  obtain ⟨a, ha, hlim⟩ := hK.exists_strong_contraction_net A T hT hn
  exact ⟨a, ha, fun x y =>
    (continuous_const.inner continuous_id).continuousAt.tendsto.comp (hlim x)⟩

/-- The contractive elements of the original algebra give a concrete weakly
dense test family in its generated von Neumann algebra. -/
theorem PublishedKaplanskyDensity.weakUnitBallDense
    (hK : PublishedKaplanskyDensity.{u})
    (A : StarSubalgebra ℂ (H →L[ℂ] H)) :
    WeakUnitBallDense (fun a : {a : A // ‖a‖ ≤ 1} => (a.val : H →L[ℂ] H))
      (generatedVonNeumannAlgebra A) := by
  classical
  constructor
  · intro a
    exact ⟨subset_generatedVonNeumannAlgebra A a.val.property, a.property⟩
  · intro T hT
    have hm : T ∈ Set.centralizer (Set.centralizer (A : Set (H →L[ℂ] H))) := by
      have hm' : T ∈ (generatedVonNeumannAlgebra A : Set (H →L[ℂ] H)) := hT.1
      rwa [generatedVonNeumannAlgebra_coe] at hm'
    obtain ⟨a, ha, hlim⟩ := hK.exists_weak_contraction_net A T hm hT.2
    let b : Finset H × ℕ → {a : A // ‖a‖ ≤ 1} := fun d => ⟨a d, ha d⟩
    have hne : (atTop : Filter (Finset H × ℕ)).NeBot := inferInstance
    refine ⟨Filter.map b (atTop : Filter (Finset H × ℕ)), hne.map b, ?_⟩
    intro x y
    apply Filter.tendsto_map'_iff.mpr
    exact hlim x y

end

end KadisonKastler

end OAI
