import OAI.Analysis.KadisonKastler.FreeJointLaw
import OAI.Analysis.KadisonKastler.RecoveryContraction
import OAI.Analysis.KadisonKastler.HaarPolynomial
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Range

namespace OAI

/-! # Equality of the actual recovery expression for free pairs

Continuous clipping stays in the closed algebra generated by the
projection and the Haar unitary. The finite normal-word trace law therefore
applies to the concrete recovery contraction, without a spectral premise.
-/

namespace KadisonKastler

noncomputable section

universe u v

variable {B : Type u} [CStarAlgebra B]

local instance recoveryJointLawOrder : PartialOrder B := CStarAlgebra.spectralOrder B
local instance recoveryJointLawStarOrder : StarOrderedRing B :=
  CStarAlgebra.spectralOrderedRing B

def projectionHaarClosedAlgebra (p : B) (u : unitary B) : StarSubalgebra ℂ B :=
  (StarAlgebra.adjoin ℂ (insert p (Set.range (haarPower u)))).topologicalClosure

theorem projectionHaarClosedAlgebra_coe (p : B) (hp : IsStarProjection p)
    (u : unitary B) :
    (projectionHaarClosedAlgebra p u : Set B) =
      closure (Algebra.adjoin ℂ (insert p (Set.range (haarPower u))) : Set B) := by
  have hs : star (insert p (Set.range (haarPower u))) ⊆
      insert p (Set.range (haarPower u)) := by
    intro x hx
    change star x ∈ insert p (Set.range (haarPower u)) at hx
    rcases Set.mem_insert_iff.mp hx with hx | ⟨k, hk⟩
    · apply Set.mem_insert_iff.mpr
      left
      simpa only [star_star, hp.isSelfAdjoint.star_eq] using congrArg star hx
    · apply Set.mem_insert_of_mem
      refine ⟨-k, ?_⟩
      rw [haarPower_neg, hk, star_star]
  have heq : (StarAlgebra.adjoin ℂ (insert p (Set.range (haarPower u)))).toSubalgebra =
      Algebra.adjoin ℂ (insert p (Set.range (haarPower u))) := by
    rw [StarAlgebra.adjoin_toSubalgebra, Set.union_eq_self_of_subset_right hs]
  change closure ((StarAlgebra.adjoin ℂ (insert p (Set.range (haarPower u)))).toSubalgebra : Set B) = _
  rw [heq]

theorem projection_mem_projectionHaarClosedAlgebra (p : B) (u : unitary B) :
    p ∈ projectionHaarClosedAlgebra p u :=
  StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin _ _ (Set.mem_insert _ _))

theorem haarPower_mem_projectionHaarClosedAlgebra (p : B) (u : unitary B) (k : ℤ) :
    haarPower u k ∈ projectionHaarClosedAlgebra p u :=
  StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin _ _
    (Set.mem_insert_of_mem _ ⟨k, rfl⟩))

theorem unitaryHaarPolynomial_mem_projectionHaarClosedAlgebra
    (p : B) (u : unitary B) (N : ℕ) :
    unitaryHaarPolynomial N u ∈ projectionHaarClosedAlgebra p u := by
  apply (projectionHaarClosedAlgebra p u).smul_mem
  apply (projectionHaarClosedAlgebra p u).sum_mem
  intro i hi
  change (u : B) ^ (i.val + 1) ∈ projectionHaarClosedAlgebra p u
  simpa only [haarPower_natCast] using
    haarPower_mem_projectionHaarClosedAlgebra p u (i.val + 1 : ℕ)

theorem spectralClip_mem_closedStarSubalgebra (S : StarSubalgebra ℂ B)
    (hS : IsClosed (S : Set B)) (β : ℝ) {x : B} (hx : x ∈ S) :
    spectralClip β x ∈ S := by
  let : IsClosed (S : Set B) := hS
  have hxx : star x * x ∈ S := S.mul_mem (S.star_mem' hx) hx
  have ha : CFC.abs x ∈ S := by
    rw [CFC.abs, CFC.sqrt_eq_real_sqrt _ (star_mul_self_nonneg x), cfcₙ_eq_cfc]
    exact cfc_mem (𝕜' := ℂ) (S := StarSubalgebra ℂ B) (s := S) Real.sqrt hxx
  exact S.mul_mem hx (cfc_mem (𝕜' := ℂ) (S := StarSubalgebra ℂ B) (s := S) (clippingFunction β) ha)

theorem recoveryContraction_mem_closedStarSubalgebra (S : StarSubalgebra ℂ B)
    (hS : IsClosed (S : Set B)) (n : ℕ) {p f : B} (hp : p ∈ S) (hf : f ∈ S) :
    recoveryContraction n p f ∈ S := by
  rw [recoveryContraction, ← Complex.coe_smul]
  apply S.smul_mem
  apply S.star_mem'
  apply spectralClip_mem_closedStarSubalgebra S hS
  exact S.mul_mem (S.mul_mem (S.mul_mem hp hf) hf) hp

theorem recoveryExpression_mem_projectionHaarClosedAlgebra
    (n N : ℕ) (p : B) (u : unitary B) :
    unitaryHaarPolynomial N u *
      recoveryContraction n p (unitaryHaarPolynomial N u) * unitaryHaarPolynomial N u ∈
        projectionHaarClosedAlgebra p u := by
  let S := projectionHaarClosedAlgebra p u
  have hf := unitaryHaarPolynomial_mem_projectionHaarClosedAlgebra p u N
  have hp := projection_mem_projectionHaarClosedAlgebra p u
  have hc := recoveryContraction_mem_closedStarSubalgebra S
    (StarSubalgebra.isClosed_topologicalClosure _) n hp hf
  exact S.mul_mem (S.mul_mem hf hc) hf

variable {C : Type v} [CStarAlgebra C]

local instance recoveryJointLawOrderC : PartialOrder C := CStarAlgebra.spectralOrder C
local instance recoveryJointLawStarOrderC : StarOrderedRing C :=
  CStarAlgebra.spectralOrderedRing C

theorem map_recoveryContraction (π : B →⋆ₐ[ℂ] C) {n : ℕ} (hn : 0 < n) (p f : B) :
    π (recoveryContraction n p f) = recoveryContraction n (π p) (π f) := by
  simp only [recoveryContraction, ← Complex.coe_smul, map_smul, map_star,
    map_spectralClip π (recoveryCutoff_pos hn), recoveryCompression, map_mul]

theorem map_unitaryHaarPolynomial (π : B →⋆ₐ[ℂ] C)
    (N : ℕ) (u : unitary B) (v : unitary C) (huv : π (u : B) = (v : C)) :
    π (unitaryHaarPolynomial N u) = unitaryHaarPolynomial N v := by
  simp only [unitaryHaarPolynomial, unitaryHaarSum, map_smul, map_sum, map_pow, huv]

local instance recoveryJointLawProductCStarAlgebra : CStarAlgebra (B × C) where

/-- Both scalar pairings needed to identify the two affine expectation
coefficients agree on the closed paired algebra. -/
theorem freeHaar_joint_pairings_eq
    (τ : FaithfulTracialState B) (σ : FaithfulTracialState C)
    {A : StarSubalgebra ℂ B} {D : StarSubalgebra ℂ C}
    {u : unitary B} {v : unitary C}
    (hu : FreeHaarMoments τ A u) (hv : FreeHaarMoments σ D v)
    {p : B} {r : C} (hp : IsStarProjection p) (hr : IsStarProjection r)
    (hpA : p ∈ A) (hrD : r ∈ D) {t : ℂ}
    (hpτ : τ.toLinearMap p = t) (hrσ : σ.toLinearMap r = t)
    {x : B × C}
    (hx : x ∈ projectionHaarClosedAlgebra (p, r) (pairedHaarUnitary u v)) :
    τ.toLinearMap x.1 = σ.toLinearMap x.2 ∧
      τ.toLinearMap (p * x.1) = σ.toLinearMap (r * x.2) := by
  have hpr : IsStarProjection (p, r) :=
    ⟨Prod.ext hp.isIdempotentElem.eq hr.isIdempotentElem.eq,
      Prod.ext hp.isSelfAdjoint.star_eq hr.isSelfAdjoint.star_eq⟩
  have hco := projectionHaarClosedAlgebra_coe (p, r) hpr (pairedHaarUnitary u v)
  have htrace : ∀ y ∈ projectionHaarClosedAlgebra (p, r) (pairedHaarUnitary u v),
      τ.toLinearMap y.1 = σ.toLinearMap y.2 := by
    intro y hy
    apply freeHaar_joint_trace_eq_of_mem_closure τ σ hu hv hp hr hpA hrD hpτ hrσ
    rwa [← hco]
  exact ⟨htrace x hx, htrace ((p, r) * x)
    ((projectionHaarClosedAlgebra _ _).mul_mem
      (projection_mem_projectionHaarClosedAlgebra _ _) hx)⟩

/-- The actual clipped recovery expressions have identical traces for
any two free projection--Haar pairs with equal projection traces. -/
theorem freeHaar_recovery_pairings_eq
    (τ : FaithfulTracialState B) (σ : FaithfulTracialState C)
    {A : StarSubalgebra ℂ B} {D : StarSubalgebra ℂ C}
    {u : unitary B} {v : unitary C}
    (hu : FreeHaarMoments τ A u) (hv : FreeHaarMoments σ D v)
    {p : B} {r : C} (hp : IsStarProjection p) (hr : IsStarProjection r)
    (hpA : p ∈ A) (hrD : r ∈ D) {t : ℂ}
    (hpτ : τ.toLinearMap p = t) (hrσ : σ.toLinearMap r = t)
    {n : ℕ} (hn : 0 < n) (N : ℕ) :
    τ.toLinearMap (unitaryHaarPolynomial N u *
      recoveryContraction n p (unitaryHaarPolynomial N u) * unitaryHaarPolynomial N u) =
    σ.toLinearMap (unitaryHaarPolynomial N v *
      recoveryContraction n r (unitaryHaarPolynomial N v) * unitaryHaarPolynomial N v) ∧
    τ.toLinearMap (p * (unitaryHaarPolynomial N u *
      recoveryContraction n p (unitaryHaarPolynomial N u) * unitaryHaarPolynomial N u)) =
    σ.toLinearMap (r * (unitaryHaarPolynomial N v *
      recoveryContraction n r (unitaryHaarPolynomial N v) * unitaryHaarPolynomial N v)) := by
  let uv := pairedHaarUnitary u v
  let f := unitaryHaarPolynomial N uv
  let x := f * recoveryContraction n (p, r) f * f
  have hx : x ∈ projectionHaarClosedAlgebra (p, r) uv := by
    exact recoveryExpression_mem_projectionHaarClosedAlgebra n N (p, r) uv
  have htrace := freeHaar_joint_pairings_eq τ σ hu hv hp hr hpA hrD hpτ hrσ hx
  have hf1 : (StarAlgHom.fst ℂ B C) f = unitaryHaarPolynomial N u :=
    map_unitaryHaarPolynomial _ N uv u rfl
  have hf2 : (StarAlgHom.snd ℂ B C) f = unitaryHaarPolynomial N v :=
    map_unitaryHaarPolynomial _ N uv v rfl
  change τ.toLinearMap ((StarAlgHom.fst ℂ B C) x) =
    σ.toLinearMap ((StarAlgHom.snd ℂ B C) x) ∧
    τ.toLinearMap ((StarAlgHom.fst ℂ B C) ((p, r) * x)) =
    σ.toLinearMap ((StarAlgHom.snd ℂ B C) ((p, r) * x)) at htrace
  simpa only [x, map_mul, map_recoveryContraction _ hn, hf1, hf2,
    StarAlgHom.fst_apply, StarAlgHom.snd_apply] using htrace

theorem freeHaar_recovery_trace_eq
    (τ : FaithfulTracialState B) (σ : FaithfulTracialState C)
    {A : StarSubalgebra ℂ B} {D : StarSubalgebra ℂ C}
    {u : unitary B} {v : unitary C}
    (hu : FreeHaarMoments τ A u) (hv : FreeHaarMoments σ D v)
    {p : B} {r : C} (hp : IsStarProjection p) (hr : IsStarProjection r)
    (hpA : p ∈ A) (hrD : r ∈ D) {t : ℂ}
    (hpτ : τ.toLinearMap p = t) (hrσ : σ.toLinearMap r = t)
    {n : ℕ} (hn : 0 < n) (N : ℕ) :
    τ.toLinearMap (unitaryHaarPolynomial N u *
      recoveryContraction n p (unitaryHaarPolynomial N u) * unitaryHaarPolynomial N u) =
    σ.toLinearMap (unitaryHaarPolynomial N v *
      recoveryContraction n r (unitaryHaarPolynomial N v) * unitaryHaarPolynomial N v) :=
  (freeHaar_recovery_pairings_eq τ σ hu hv hp hr hpA hrD hpτ hrσ hn N).1

end

end KadisonKastler

end OAI
