import OAI.Analysis.KadisonKastler.RegularCoreActions

namespace OAI

/-! # The regular crossed-product commutant and fixed algebra

The sole input is the commutant-generator theorem for a covariant
representation of a von Neumann algebra.  See Takesaki, *Theory of
Operator Algebras II* (2003), Theorem X.1.21, and Van Daele, *Continuous
Crossed Products and Type III von Neumann Algebras* (1978), Part I,
Theorem 3.11.  The exact covariant-implementation formula is also stated
in Takesaki's author notes *Structure of von Neumann Algebras of Type
III*, Lecture 1, Theorem 1.3(ii), pp. 10--11:
https://www.imsc.res.in/~sunder/mtnotes.pdf

Its generators here are constant operators from `P'` and the actual
operators `f(t) ↦ U(s) f(t+s)`.  The fixed-algebra equality is proved
below from this input and double commutants; it is not an input.
-/

namespace KadisonKastler

open MeasureTheory
open scoped Topology

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The concrete generators on the commutant side of the regular
crossed-product commutation theorem. -/
def regularCommutantGenerators
    (U : Multiplicative ℝ →* unitary (H →L[ℂ] H)) (P : VonNeumannAlgebra H) :
    Set (RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) :=
  regularConstantHom (volume : Measure ℝ) '' (P.commutant : Set (H →L[ℂ] H)) ∪
    Set.range (fun s => (regularCoreAction U s :
      RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H))

/-- The actual von Neumann algebra generated by the commutant generators. -/
def regularCommutantAlgebra
    (U : Multiplicative ℝ →* unitary (H →L[ℂ] H)) (P : VonNeumannAlgebra H) :
    VonNeumannAlgebra (RegularCoreHilbert H) :=
  generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ (regularCommutantGenerators U P))

/-- The real-group specialization of the published commutant-generator
theorem. Strong continuity refers to the ordinary topology on `ℝ`.
No fixed-point equality or perturbation assertion is assumed. -/
def PublishedRegularCommutant : Prop :=
  ∀ (H : Type u) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] [TopologicalSpace.SeparableSpace H],
    ∀ (U : Multiplicative ℝ →* unitary (H →L[ℂ] H))
      (hU : ∀ ξ, Continuous (fun t : ℝ => (U (Multiplicative.ofAdd t) : H →L[ℂ] H) ξ))
      (P : VonNeumannAlgebra H),
      (∀ s T, T ∈ P → unitaryConj (U s) T ∈ P) →
      (regularCoreAlgebra U hU P).commutant = regularCommutantAlgebra U P

private theorem generated_le_vonNeumann
    {K : Type*} [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
    (S : Set (K →L[ℂ] K)) (B : VonNeumannAlgebra K)
    (hS : S ⊆ B) :
    generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ S) ≤ B := by
  have hA : (StarAlgebra.adjoin ℂ S : Set (K →L[ℂ] K)) ⊆ B := by
    apply StarAlgebra.adjoin_le
    exact hS
  intro T hT
  have hT' : T ∈ (generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ S) :
      Set (K →L[ℂ] K)) := hT
  rw [generatedVonNeumannAlgebra_coe] at hT'
  have h := Set.centralizer_subset (Set.centralizer_subset hA) hT'
  change T ∈ (B : Set (K →L[ℂ] K))
  simpa only [VonNeumannAlgebra.centralizer_centralizer] using h

/-- Each explicit commutant generator commutes with the fixed algebra;
the same therefore holds for the generated von Neumann algebra. -/
theorem regularCommutantAlgebra_le_fixed_commutant
    (U : Multiplicative ℝ →* unitary (H →L[ℂ] H)) (P : VonNeumannAlgebra H) :
    regularCommutantAlgebra U P ≤
      (fixedPointAlgebra (regularCoreAction U) (regularTensorAlgebra P)).commutant := by
  apply generated_le_vonNeumann
  rintro S (⟨z, hz, rfl⟩ | ⟨s, rfl⟩)
  · apply VonNeumannAlgebra.mem_commutant_iff.mpr
    intro T hT
    have h := ((mem_fixedPointAlgebra_iff _ _ _).mp hT).1
    exact ((mem_regularTensorAlgebra_iff P T).mp h z hz).symm
  · apply VonNeumannAlgebra.mem_commutant_iff.mpr
    intro T hT
    have h := ((mem_fixedPointAlgebra_iff _ _ _).mp hT).2 s
    exact ((commute_unitary_iff_star_right_conjugate
      (regularCoreAction U s).property).mpr h).eq.symm

/-- The reverse core inclusion follows by applying the published
commutant formula and then taking one more commutant. -/
theorem regularCoreAlgebra_eq_fixed_of_published
    [TopologicalSpace.SeparableSpace H]
    (hComm : PublishedRegularCommutant.{u})
    (U : Multiplicative ℝ →* unitary (H →L[ℂ] H))
    (hU : ∀ ξ, Continuous (fun t : ℝ => (U (Multiplicative.ofAdd t) : H →L[ℂ] H) ξ))
    (P : VonNeumannAlgebra H)
    (hP : ∀ s T, T ∈ P → unitaryConj (U s) T ∈ P) :
    regularCoreAlgebra U hU P =
      fixedPointAlgebra (regularCoreAction U) (regularTensorAlgebra P) := by
  apply le_antisymm (regularCoreAlgebra_le_fixed U hU P hP)
  intro T hT
  have he := hComm H U hU P hP
  have hle : (regularCoreAlgebra U hU P).commutant ≤
      (fixedPointAlgebra (regularCoreAction U) (regularTensorAlgebra P)).commutant := by
    rw [he]
    exact regularCommutantAlgebra_le_fixed_commutant U P
  have hm : T ∈ (regularCoreAlgebra U hU P).commutant.commutant := by
    apply VonNeumannAlgebra.mem_commutant_iff.mpr
    intro S hS
    exact (VonNeumannAlgebra.mem_commutant_iff.mp (hle hS) T hT).symm
  simpa only [VonNeumannAlgebra.commutant_commutant] using hm

/-- Character fixed points of the actual generated core recover the
original algebra's regular image. -/
theorem regularCore_characterFixed_coe_of_published
    [TopologicalSpace.SeparableSpace H]
    (hComm : PublishedRegularCommutant.{u})
    (hSpectral : PublishedRealSpectralCommutant.{u})
    (hDiagonal : PublishedRealDiagonalDecomposition.{u})
    (U : Multiplicative ℝ →* unitary (H →L[ℂ] H))
    (hU : ∀ ξ, Continuous (fun t : ℝ => (U (Multiplicative.ofAdd t) : H →L[ℂ] H) ξ))
    (P : VonNeumannAlgebra H)
    (hP : ∀ s T, T ∈ P → unitaryConj (U s) T ∈ P) :
    (fixedPointAlgebra (regularCharacterRepresentation (H := H))
      (regularCoreAlgebra U hU P) :
        Set (RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H)) =
      regularCoreEmbedding U hU '' (P : Set (H →L[ℂ] H)) := by
  rw [regularCoreAlgebra_eq_fixed_of_published hComm U hU P hP]
  exact regular_jointFixed_coe U hU hSpectral hDiagonal P hP

end

end KadisonKastler

end OAI
