import OAI.Analysis.KadisonKastler.RegularCorePeriodic

namespace OAI

/-! # An injective algebra containing the countable matrix units

The factorial periodic stages are actual increasing full matrix algebras.
Their generated von Neumann algebra contains every original matrix unit
by strong approximation.  Only the already stated published implication
from increasing finite-dimensional approximation to injectivity is used.
-/

namespace KadisonKastler

open Generator Generator.Tracial Filter
open scoped BigOperators Topology

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Restriction of a concrete matrix-unit system to a von Neumann algebra
that contains each of its entries. -/
def matrixUnitsInAlgebra {ι : Type*} [Fintype ι] [DecidableEq ι]
    (A : MatrixUnitSystem ι (H →L[ℂ] H)) (M : VonNeumannAlgebra H)
    (hA : ∀ i j, A.entry i j ∈ M) : MatrixUnitSystem ι (Algebra M) where
  entry i j := ⟨A.entry i j, hA i j⟩
  star_entry i j := Subtype.ext (A.star_entry i j)
  mul_entry i j k l := by
    classical
    apply Subtype.ext
    by_cases h : j = k
    · simpa only [ite_eq_left h, MulMemClass.coe_mul] using A.mul_entry i j k l
    · simpa only [ite_eq_right h, MulMemClass.coe_mul, ZeroMemClass.coe_zero]
        using A.mul_entry i j k l
  total := by
    apply Subtype.ext
    change M.toStarSubalgebra.subtype (∑ i, (⟨A.entry i i, hA i i⟩ : Algebra M)) = 1
    rw [map_sum]
    exact A.total

theorem matrixUnitsInAlgebra_concreteHom {ι : Type*} [Fintype ι] [DecidableEq ι]
    (A : MatrixUnitSystem ι (H →L[ℂ] H)) (M : VonNeumannAlgebra H)
    (hA : ∀ i j, A.entry i j ∈ M) (a : Matrix ι ι ℂ) :
    (matrixUnitsInAlgebra A M hA).concreteHom a = A.hom a := by
  change M.toStarSubalgebra.subtype ((matrixUnitsInAlgebra A M hA).hom a) = A.hom a
  simp only [MatrixUnitSystem.hom_apply, map_sum, map_smul]
  rfl

theorem matrixUnitsInAlgebra_concreteAlgebra {ι : Type*} [Fintype ι] [DecidableEq ι]
    (A : MatrixUnitSystem ι (H →L[ℂ] H)) (M : VonNeumannAlgebra H)
    (hA : ∀ i j, A.entry i j ∈ M) :
    (matrixUnitsInAlgebra A M hA).concreteAlgebra = A.algebra := by
  ext T
  change (∃ a, (matrixUnitsInAlgebra A M hA).concreteHom a = T) ↔ ∃ a, A.hom a = T
  simp only [matrixUnitsInAlgebra_concreteHom]

namespace FullMatrixCorner

variable {E : Submodule ℂ H} [CompleteSpace E] (F : FullMatrixCorner E)

local instance periodicStageFactorialNeZero (n : ℕ) : NeZero n.factorial :=
  ⟨Nat.factorial_ne_zero n⟩

/-- The full matrix stage of factorial size inside the containing algebra. -/
def periodicStage (M : VonNeumannAlgebra H) (hM : ∀ i j, F.entry i j ∈ M)
    (n : ℕ) : FiniteMatrixStage M where
  size := (n + 1).factorial
  positive := Nat.factorial_pos _
  units := matrixUnitsInAlgebra (F.periodicMatrixUnits (n + 1).factorial) M
    (F.periodicMatrixUnits_mem _ M hM)

theorem periodicStage_concreteAlgebra (M : VonNeumannAlgebra H)
    (hM : ∀ i j, F.entry i j ∈ M) (n : ℕ) :
    (F.periodicStage M hM n).units.concreteAlgebra =
      (F.periodicMatrixUnits (n + 1).factorial).algebra :=
  matrixUnitsInAlgebra_concreteAlgebra (F.periodicMatrixUnits (n + 1).factorial) M
    (F.periodicMatrixUnits_mem _ M hM)

theorem periodicStage_monotone (M : VonNeumannAlgebra H)
    (hM : ∀ i j, F.entry i j ∈ M) :
    Monotone (fun n => (F.periodicStage M hM n).units.concreteAlgebra) := by
  intro n m hnm
  change (F.periodicStage M hM n).units.concreteAlgebra ≤
    (F.periodicStage M hM m).units.concreteAlgebra
  rw [F.periodicStage_concreteAlgebra, F.periodicStage_concreteAlgebra]
  exact F.periodicMatrixUnits_algebra_le_of_dvd _ _
    (Nat.factorial_dvd_factorial (Nat.add_le_add_right hnm 1))

/-- The actual von Neumann algebra generated by the increasing periodic
matrix stages. -/
def periodicVonNeumann (M : VonNeumannAlgebra H) (hM : ∀ i j, F.entry i j ∈ M) :
    VonNeumannAlgebra H := FiniteMatrixStage.generatedVonNeumann (F.periodicStage M hM)

theorem periodicVonNeumann_le (M : VonNeumannAlgebra H) (hM : ∀ i j, F.entry i j ∈ M) :
    F.periodicVonNeumann M hM ≤ M :=
  FiniteMatrixStage.generatedVonNeumann_le (F.periodicStage M hM)

theorem periodicEntryApprox_mem_periodicVonNeumann (M : VonNeumannAlgebra H)
    (hM : ∀ i j, F.entry i j ∈ M) (i j n : ℕ) :
    F.periodicEntryApprox i j n ∈ F.periodicVonNeumann M hM := by
  unfold periodicEntryApprox
  split_ifs with hij
  · apply FiniteMatrixStage.stage_le_generated (F.periodicStage M hM) n
    rw [F.periodicStage_concreteAlgebra]
    exact (F.periodicMatrixUnits (n + 1).factorial).entry_mem _ _
  · exact (F.periodicVonNeumann M hM).zero_mem

theorem entry_mem_periodicVonNeumann (M : VonNeumannAlgebra H)
    (hM : ∀ i j, F.entry i j ∈ M) (i j : ℕ) :
    F.entry i j ∈ F.periodicVonNeumann M hM := by
  let a (n : ℕ) : Algebra (F.periodicVonNeumann M hM) :=
    ⟨F.periodicEntryApprox i j n, F.periodicEntryApprox_mem_periodicVonNeumann M hM i j n⟩
  apply weak_operator_limit_mem (l := atTop) (F.periodicVonNeumann M hM) a (F.entry i j)
  intro x y
  exact tendsto_const_nhds.inner (𝕜 := ℂ) (F.periodicEntryApprox_strong i j x)

/-- The countable matrix units lie in an injective subalgebra of their
original ambient algebra.  Injectivity uses only the published AFD
implication; the stage construction and inclusion are proved above. -/
theorem exists_injective_matrix_subalgebra [TopologicalSpace.SeparableSpace H]
    (hpub : PublishedIncreasingMatrixInjectivity (H := H))
    (M : VonNeumannAlgebra H) (hM : ∀ i j, F.entry i j ∈ M) :
    ∃ S : VonNeumannAlgebra H, S ≤ M ∧ IsInjective S ∧ ∀ i j, F.entry i j ∈ S := by
  refine ⟨F.periodicVonNeumann M hM, F.periodicVonNeumann_le M hM, ?_,
    F.entry_mem_periodicVonNeumann M hM⟩
  exact hpub M (F.periodicStage M hM) (F.periodicStage_monotone M hM)
    (fun n => inferInstance)

end FullMatrixCorner

end

end KadisonKastler

end OAI
