import OAI.Analysis.KadisonKastler.RegularCoreCharacters
import OAI.Analysis.KadisonKastler.FixedPointGap
import OAI.Analysis.KadisonKastler.PublishedKaplansky

namespace OAI

/-! # The concrete regular core and its first fixed-point inclusion

The tensor algebra is the commutant of the constant copy of `P'` on
`L²(ℝ,H)`. The regular core is the von Neumann algebra generated by the
concrete regular embedding and translations. Its generators lie in the
tensor algebra and are fixed by the common regular action. This proves
the first fixed-point inclusion without a crossed-product assumption.
-/

namespace KadisonKastler

open MeasureTheory Filter
open scoped Topology

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The concrete tensor algebra, specified by its constant commutant. -/
def regularTensorAlgebra (P : VonNeumannAlgebra H) :
    VonNeumannAlgebra (RegularCoreHilbert H) where
  toStarSubalgebra := StarSubalgebra.centralizer ℂ
    (regularConstantHom volume '' (P.commutant : Set (H →L[ℂ] H)))
  centralizer_centralizer' := by
    let S : Set (RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) :=
      regularConstantHom volume '' (P.commutant : Set (H →L[ℂ] H))
    change (S ∪ star S).centralizer.centralizer.centralizer =
      (S ∪ star S).centralizer
    exact Set.centralizer_centralizer_centralizer _

theorem mem_regularTensorAlgebra_iff (P : VonNeumannAlgebra H)
    (T : RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) :
    T ∈ regularTensorAlgebra P ↔ ∀ z ∈ P.commutant,
      regularConstantHom volume z * T = T * regularConstantHom volume z := by
  change T ∈ StarSubalgebra.centralizer ℂ
    (regularConstantHom volume '' (P.commutant : Set (H →L[ℂ] H))) ↔ _
  rw [StarSubalgebra.mem_centralizer_iff]
  constructor
  · intro h z hz
    exact (h _ ⟨z, hz, rfl⟩).1
  · rintro h g ⟨z, hz, hzg⟩
    subst g
    refine ⟨h z hz, ?_⟩
    have hs : regularConstantHom (volume : Measure ℝ) (star z) =
        star (regularConstantHom (volume : Measure ℝ) z) :=
      StarHomClass.map_star (regularConstantHom (H := H) (volume : Measure ℝ)) z
    simpa only [hs] using h (star z) (star_mem hz)

theorem regularConstant_mem_tensorAlgebra (P : VonNeumannAlgebra H)
    {T : H →L[ℂ] H} (hT : T ∈ P) :
    regularConstantHom volume T ∈ regularTensorAlgebra P := by
  apply (mem_regularTensorAlgebra_iff P _).mpr
  intro z hz
  have h : z * T = T * z :=
    (VonNeumannAlgebra.mem_commutant_iff.mp hz T hT).symm
  simpa only [map_mul] using congrArg (regularConstantHom (H := H) volume) h

theorem regularTranslation_mem_tensorAlgebra (P : VonNeumannAlgebra H)
    (s : Multiplicative ℝ) :
    (regularRightTranslation (H := H) s :
      RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) ∈ regularTensorAlgebra P := by
  exact (mem_regularTensorAlgebra_iff P _).mpr
    (fun z _ => (regularConstant_commute_translation z s).eq)

variable (U : Multiplicative ℝ →* unitary (H →L[ℂ] H))
  (hU : ∀ x, Continuous (fun t : ℝ => (U (Multiplicative.ofAdd t) : H →L[ℂ] H) x))

/-- The field formula for the regular embedding preserves the concrete
tensor algebra whenever the original group normalizes `P`. -/
theorem regularCoreEmbedding_mem_tensorAlgebra (P : VonNeumannAlgebra H)
    (hP : ∀ s T, T ∈ P → unitaryConj (U s) T ∈ P)
    {T : H →L[ℂ] H} (hT : T ∈ P) :
    regularCoreEmbedding U hU T ∈ regularTensorAlgebra P := by
  apply (mem_regularTensorAlgebra_iff P _).mpr
  intro z hz
  apply ContinuousLinearMap.ext
  intro f
  apply Lp.ext
  filter_upwards [regularConstantHom_apply_ae volume z (regularCoreEmbedding U hU T f),
    regularCoreEmbedding_apply_ae U hU T f,
    regularCoreEmbedding_apply_ae U hU T (regularConstantHom volume z f),
    regularConstantHom_apply_ae volume z f] with t hleft hπ hright hzv
  change regularConstantHom volume z (regularCoreEmbedding U hU T f) t =
    regularCoreEmbedding U hU T (regularConstantHom volume z f) t
  rw [hleft, hπ, hright, hzv]
  have ht : unitaryConj (star (U (Multiplicative.ofAdd t))) T ∈ P := by
    rw [regularGroup_star_eq U t]
    exact hP _ T hT
  have hc := (VonNeumannAlgebra.mem_commutant_iff.mp hz _ ht).symm
  have he := congrArg (fun A : H →L[ℂ] H => A (f t)) hc
  simpa only [unitaryConj, Unitary.coe_star, star_star,
    mul_apply_eq_comp] using he

/-- Translations are also fixed by the common action: both translation
groups are abelian, and constant operators commute with translations. -/
theorem regularTranslation_fixed (s t : Multiplicative ℝ) :
    unitaryConj (regularCoreAction U s)
      (regularRightTranslation (H := H) t :
        RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) =
      (regularRightTranslation (H := H) t :
        RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) := by
  apply (commute_unitary_iff_star_right_conjugate (regularCoreAction U s).property).mp
  have hρ : Commute
      (regularRightTranslation (H := H) s :
        RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H)
      (regularRightTranslation (H := H) t :
        RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) := by
    change (regularRightTranslation (H := H) s :
        RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) *
        regularRightTranslation (H := H) t = _
    have he : regularRightTranslation (H := H) s * regularRightTranslation (H := H) t =
        regularRightTranslation (H := H) t * regularRightTranslation (H := H) s := by
      rw [← map_mul, ← map_mul, mul_comm]
    exact congrArg Subtype.val he
  exact (regularConstant_commute_translation (U s : H →L[ℂ] H) t).mul_left hρ

/-- The actual generating set of the regular core. -/
def regularCoreGenerators (P : VonNeumannAlgebra H) :
    Set (RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) :=
  regularCoreEmbedding U hU '' (P : Set (H →L[ℂ] H)) ∪
    Set.range (fun s => (regularRightTranslation (H := H) s :
      RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H))

/-- The von Neumann algebra generated by the regular representation. -/
def regularCoreAlgebra (P : VonNeumannAlgebra H) :
    VonNeumannAlgebra (RegularCoreHilbert H) :=
  generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ (regularCoreGenerators U hU P))

private theorem generatedAlgebra_le_of_le
    {K : Type*} [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
    (A : StarSubalgebra ℂ (K →L[ℂ] K)) (B : VonNeumannAlgebra K)
    (h : (A : Set (K →L[ℂ] K)) ⊆ B) : generatedVonNeumannAlgebra A ≤ B := by
  intro T hT
  rw [← SetLike.mem_coe, generatedVonNeumannAlgebra_coe] at hT
  have hc := Set.centralizer_subset (Set.centralizer_subset h)
  have hmem := hc hT
  change T ∈ (B : Set (K →L[ℂ] K))
  simpa only [VonNeumannAlgebra.centralizer_centralizer] using hmem

theorem regularCoreEmbedding_mem_core (P : VonNeumannAlgebra H)
    {T : H →L[ℂ] H} (hT : T ∈ P) :
    regularCoreEmbedding U hU T ∈ regularCoreAlgebra U hU P := by
  exact subset_generatedVonNeumannAlgebra _
    (StarAlgebra.subset_adjoin ℂ _ (Or.inl ⟨T, hT, rfl⟩))

theorem regularTranslation_mem_core (P : VonNeumannAlgebra H)
    (s : Multiplicative ℝ) :
    (regularRightTranslation (H := H) s :
      RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) ∈ regularCoreAlgebra U hU P := by
  exact subset_generatedVonNeumannAlgebra _
    (StarAlgebra.subset_adjoin ℂ _ (Or.inr ⟨s, rfl⟩))

/-- The generator calculation proves the first core fixed-point inclusion. -/
theorem regularCoreAlgebra_le_fixed (P : VonNeumannAlgebra H)
    (hP : ∀ s T, T ∈ P → unitaryConj (U s) T ∈ P) :
    regularCoreAlgebra U hU P ≤
      fixedPointAlgebra (regularCoreAction U) (regularTensorAlgebra P) := by
  apply generatedAlgebra_le_of_le
  apply StarAlgebra.adjoin_le
  rintro T (⟨x, hx, rfl⟩ | ⟨s, rfl⟩)
  · exact (mem_fixedPointAlgebra_iff _ _ _).mpr
      ⟨regularCoreEmbedding_mem_tensorAlgebra U hU P hP hx,
        fun s => regularCoreEmbedding_fixed U hU s x⟩
  · exact (mem_fixedPointAlgebra_iff _ _ _).mpr
      ⟨regularTranslation_mem_tensorAlgebra P s, fun t => regularTranslation_fixed U t s⟩

theorem regularCoreAlgebra_le_tensor (P : VonNeumannAlgebra H)
    (hP : ∀ s T, T ∈ P → unitaryConj (U s) T ∈ P) :
    regularCoreAlgebra U hU P ≤ regularTensorAlgebra P :=
  (regularCoreAlgebra_le_fixed U hU P hP).trans (fixedPointAlgebra_le _ _)

end

end KadisonKastler

end OAI
