import OAI.Analysis.KadisonKastler.RegularCommutantFourier

namespace OAI

/-! # Generation of the bounded diagonal fields

The algebra generated by constant operators from `P` and scalar
characters contains every bounded measurable `P`-valued field. Its
commutant is recovered by the proved diagonal decomposition and
countable commutant tests. This is a concrete generation statement,
without any crossed-product input.
-/

namespace KadisonKastler

open MeasureTheory

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- Constants from `P` together with the complete scalar diagonal. -/
def regularDiagonalAlgebra (P : VonNeumannAlgebra H) :
    VonNeumannAlgebra (RegularCoreHilbert H) :=
  generatedVonNeumannAlgebra (StarAlgebra.adjoin ℂ
    (regularConstantHom (H := H) (volume : Measure ℝ) '' (P : Set (H →L[ℂ] H)) ∪
      Set.range (fun a : ℝ => (regularCharacterUnitary (H := H) a :
        RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H))))

theorem regularConstant_mem_diagonalAlgebra (P : VonNeumannAlgebra H)
    {A : H →L[ℂ] H} (hA : A ∈ P) :
    regularConstantHom volume A ∈ regularDiagonalAlgebra P :=
  subset_generatedVonNeumannAlgebra _
    (StarAlgebra.subset_adjoin ℂ _ (Or.inl ⟨A, hA, rfl⟩))

theorem regularCharacter_mem_constantDiagonalAlgebra (P : VonNeumannAlgebra H) (a : ℝ) :
    (regularCharacterUnitary (H := H) a : RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) ∈
      regularDiagonalAlgebra P :=
  subset_generatedVonNeumannAlgebra _
    (StarAlgebra.subset_adjoin ℂ _ (Or.inr ⟨a, rfl⟩))

/-- Operators commuting with the diagonal algebra have `P'`-valued fields. -/
theorem exists_field_of_mem_regularDiagonal_commutant
    [TopologicalSpace.SeparableSpace H]
    (P : VonNeumannAlgebra H)
    (T : RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H)
    (hT : T ∈ (regularDiagonalAlgebra P).commutant) :
    ∃ F : ℝ → H →L[ℂ] H,
      (∀ ξ, AEStronglyMeasurable (fun t => F t ξ) volume) ∧
      (∀ᵐ t ∂volume, ‖F t‖ ≤ ‖T‖) ∧ (∀ᵐ t ∂volume, F t ∈ P.commutant) ∧
      RepresentsOperatorField volume F T := by
  have hchar (a : ℝ) : Commute T (regularCharacterUnitary (H := H) a :
      RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H) :=
    (VonNeumannAlgebra.mem_commutant_iff.mp hT _
      (regularCharacter_mem_constantDiagonalAlgebra P a)).symm
  obtain ⟨F, hm, hn, hF⟩ := publishedRealDiagonalDecomposition H T
    (publishedRealSpectralCommutant H T hchar)
  refine ⟨F, hm, hn, hF.mem_algebra_ae P.commutant ?_, hF⟩
  apply (mem_regularTensorAlgebra_iff P.commutant T).mpr
  intro A hA
  have hAP : A ∈ P := by simpa only [VonNeumannAlgebra.commutant_commutant] using hA
  exact VonNeumannAlgebra.mem_commutant_iff.mp hT _
    (regularConstant_mem_diagonalAlgebra P hAP)

/-- A represented field with almost-everywhere values in `P` belongs to the
algebra generated by constants from `P` and scalar characters. -/
theorem RepresentsOperatorField.mem_regularDiagonalAlgebra
    [TopologicalSpace.SeparableSpace H]
    {F : ℝ → H →L[ℂ] H}
    {T : RegularCoreHilbert H →L[ℂ] RegularCoreHilbert H}
    (hF : RepresentsOperatorField volume F T) (P : VonNeumannAlgebra H)
    (hmem : ∀ᵐ t ∂volume, F t ∈ P) : T ∈ regularDiagonalAlgebra P := by
  have hd : T ∈ (regularDiagonalAlgebra P).commutant.commutant := by
    apply VonNeumannAlgebra.mem_commutant_iff.mpr
    intro S hS
    obtain ⟨G, _hGm, _hGn, hGmem, hG⟩ :=
      exists_field_of_mem_regularDiagonal_commutant P S hS
    apply ContinuousLinearMap.ext
    intro f
    apply Lp.ext
    filter_upwards [hG (T f), hF f, hF (S f), hG f, hmem, hGmem]
      with t hGT hFf hFS hGf htF htG
    change S (T f) t = T (S f) t
    rw [hGT, hFf, hFS, hGf]
    have hc := VonNeumannAlgebra.mem_commutant_iff.mp htG (F t) htF
    exact congrArg (fun A : H →L[ℂ] H => A (f t)) hc.symm
  simpa only [VonNeumannAlgebra.commutant_commutant] using hd

/-- An essentially bounded measurable field gives a concrete element of the
constant-and-character algebra. -/
theorem regularFieldOperator_mem_diagonalAlgebra
    [TopologicalSpace.SeparableSpace H]
    (P : VonNeumannAlgebra H) (F : ℝ → H →L[ℂ] H)
    (hF : ∀ ξ, AEStronglyMeasurable (fun t => F t ξ) volume)
    (C : ℝ) (hC : ∀ᵐ t ∂volume, ‖F t‖ ≤ C)
    (hmem : ∀ᵐ t ∂volume, F t ∈ P) :
    regularFieldOperator volume F hF C hC ∈ regularDiagonalAlgebra P :=
  (regularFieldOperator_represents volume F hF C hC).mem_regularDiagonalAlgebra P hmem

end

end KadisonKastler

end OAI
