import OAI.Analysis.KadisonKastler.SpatialMatrixImage
import OAI.Analysis.KadisonKastler.SpatialStrong
import OAI.Analysis.KadisonKastler.PreparedPairCorrection

namespace OAI

/-! # Increasing finite spatial matrix images are weakly dense -/

namespace KadisonKastler

open UnitalTomsWinter Generator Filter
open scoped Topology

noncomputable section

universe u

variable {H K : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]

private theorem spatialRight_mem_generated_contraction
    (hK : PublishedKaplanskyDensity.{u})
    (B : StarSubalgebra ℂ (K →L[ℂ] K))
    (A : StarSubalgebra ℂ (SpatialHilbert H K →L[ℂ] SpatialHilbert H K))
    (hBA : ∀ b ∈ B, spatialRight (H := H) b ∈ A)
    (b : K →L[ℂ] K) (hb : b ∈ generatedVonNeumannAlgebra B) (hn : ‖b‖ ≤ 1) :
    spatialRight (H := H) b ∈ generatedVonNeumannAlgebra A := by
  classical
  have hb' : b ∈ Set.centralizer (Set.centralizer (B : Set (K →L[ℂ] K))) := by
    change b ∈ (generatedVonNeumannAlgebra B : Set (K →L[ℂ] K)) at hb
    rwa [generatedVonNeumannAlgebra_coe] at hb
  obtain ⟨a, ha, hlim⟩ := hK.exists_strong_contraction_net B b hb' hn
  let c : Finset K × ℕ → Algebra (generatedVonNeumannAlgebra A) := fun d =>
    ⟨spatialRight (H := H) (a d),
      subset_generatedVonNeumannAlgebra A (hBA _ (a d).property)⟩
  apply Generator.Tracial.weak_operator_limit_mem (l := (atTop : Filter (Finset K × ℕ)))
    (generatedVonNeumannAlgebra A) c
  intro x y
  exact (continuous_const.inner continuous_id).continuousAt.tendsto.comp
    (spatialRight_tendsto_strong (fun d => (a d : K →L[ℂ] K)) b ha hlim x)

/-- The right spatial representation carries the generated von Neumann
algebra into the von Neumann algebra generated by its images. -/
theorem spatialRight_mem_generated
    (hK : PublishedKaplanskyDensity.{u})
    (B : StarSubalgebra ℂ (K →L[ℂ] K))
    (A : StarSubalgebra ℂ (SpatialHilbert H K →L[ℂ] SpatialHilbert H K))
    (hBA : ∀ b ∈ B, spatialRight (H := H) b ∈ A)
    (b : K →L[ℂ] K) (hb : b ∈ generatedVonNeumannAlgebra B) :
    spatialRight (H := H) b ∈ generatedVonNeumannAlgebra A := by
  by_cases hzero : b = 0
  · rw [hzero, map_zero]
    exact (generatedVonNeumannAlgebra A).zero_mem
  have hp : 0 < ‖b‖ := norm_pos_iff.mpr hzero
  have hc : (‖b‖ : ℂ) ≠ 0 := by exact_mod_cast hp.ne'
  have hbn : ‖(‖b‖ : ℂ)⁻¹ • b‖ ≤ 1 := by
    simp only [norm_smul, norm_inv, Complex.norm_real, Real.norm_eq_abs,
      abs_of_pos hp, inv_mul_cancel₀ hp.ne']
    exact le_rfl
  have hs := spatialRight_mem_generated_contraction hK B A hBA
    ((‖b‖ : ℂ)⁻¹ • b) ((generatedVonNeumannAlgebra B).smul_mem hb _) hbn
  have hr := (generatedVonNeumannAlgebra A).smul_mem hs (‖b‖ : ℂ)
  rwa [← map_smul, smul_smul, mul_inv_cancel₀ hc, one_smul] at hr

variable {s : ℕ → ℕ} (M : VonNeumannAlgebra H)
  (E : ∀ n, MatrixUnitSystem (Fin (s n)) (K →L[ℂ] K))

/-- The increasing finite spatial images generate the actual spatial
product with the von Neumann algebra generated by the right stages. -/
theorem generated_spatialMatrixAlgebra_eq_product
    (hK : PublishedKaplanskyDensity.{u})
    (hE : Monotone (fun n => (E n).algebra)) :
    generatedVonNeumannAlgebra (⨆ n, spatialMatrixAlgebra M (E n)) =
      spatialProductAlgebra M (generatedVonNeumannAlgebra (⨆ n, (E n).algebra)) := by
  let A := ⨆ n, spatialMatrixAlgebra M (E n)
  let B := ⨆ n, (E n).algebra
  have hBA : ∀ b ∈ B, spatialRight (H := H) b ∈ A := by
    intro b hb
    change b ∈ (B : Set (K →L[ℂ] K)) at hb
    dsimp only [B] at hb
    rw [StarSubalgebra.coe_iSup_of_directed hE.directed_le] at hb
    obtain ⟨n, hn⟩ := Set.mem_iUnion.mp hb
    exact (le_iSup (fun n => spatialMatrixAlgebra M (E n)) n)
      (spatialRight_mem_matrixAlgebra M (E n) hn)
  apply le_antisymm
  · apply generatedVonNeumannAlgebra_le_of_le
    apply iSup_le
    intro n
    apply spatialMatrixAlgebra_le_product
    intro i j
    exact subset_generatedVonNeumannAlgebra B
      ((le_iSup (fun n => (E n).algebra) n) ((E n).entry_mem i j))
  · apply generatedVonNeumannAlgebra_le_of_le
    apply sup_le
    · rintro _ ⟨a, ha, rfl⟩
      exact subset_generatedVonNeumannAlgebra A
        ((le_iSup (fun n => spatialMatrixAlgebra M (E n)) 0)
          (spatialLeft_mem_matrixAlgebra M (E 0) ha))
    · rintro _ ⟨b, hb, rfl⟩
      exact spatialRight_mem_generated hK B A hBA b hb

/-- Every contraction test in the increasing union has an exact
contractive matrix representative at a finite stage. -/
theorem exists_spatialMatrix_of_stage_union [Nontrivial K]
    (hs : ∀ n, 0 < s n) (hE : Monotone (fun n => (E n).algebra))
    {T : SpatialHilbert H K →L[ℂ] SpatialHilbert H K}
    (hT : T ∈ (⨆ n, spatialMatrixAlgebra M (E n) :
      StarSubalgebra ℂ (SpatialHilbert H K →L[ℂ] SpatialHilbert H K))) (hn : ‖T‖ ≤ 1) :
    ∃ n, ∃ X : CStarMatrix (Fin (s n)) (Fin (s n)) (H →L[ℂ] H),
      (∀ i j, X i j ∈ M) ∧ ‖X‖ ≤ 1 ∧ spatialMatrixHom (E n) X = T := by
  have hm : Monotone (fun n => spatialMatrixAlgebra M (E n)) :=
    fun i j hij => spatialMatrixAlgebra_mono M (E i) (E j) (hE hij)
  have hT' : T ∈ ((⨆ n, spatialMatrixAlgebra M (E n) :
      StarSubalgebra ℂ (SpatialHilbert H K →L[ℂ] SpatialHilbert H K)) :
      Set (SpatialHilbert H K →L[ℂ] SpatialHilbert H K)) := hT
  rw [StarSubalgebra.coe_iSup_of_directed hm.directed_le] at hT'
  obtain ⟨n, hnT⟩ := Set.mem_iUnion.mp hT'
  let : NeZero (s n) := ⟨(hs n).ne'⟩
  obtain ⟨X, hX, hXn, hXT⟩ := exists_matrix_of_mem_spatialMatrixAlgebra M (E n) hnT hn
  exact ⟨n, X, hX, hXn, hXT⟩

/-- These explicit finite-image contraction tests are weakly dense in the
unit ball of the spatial product. -/
theorem spatialMatrix_union_weakUnitBallDense
    (hK : PublishedKaplanskyDensity.{u})
    (hE : Monotone (fun n => (E n).algebra)) :
    WeakUnitBallDense
      (fun a : {a : ↥(⨆ n, spatialMatrixAlgebra M (E n)) // ‖a‖ ≤ 1} =>
        (a.val : SpatialHilbert H K →L[ℂ] SpatialHilbert H K))
      (spatialProductAlgebra M (generatedVonNeumannAlgebra (⨆ n, (E n).algebra))) := by
  rw [← generated_spatialMatrixAlgebra_eq_product M E hK hE]
  exact hK.weakUnitBallDense _

end

end KadisonKastler

end OAI
