import OAI.Analysis.KadisonKastler.SpatialMatrix
import OAI.Analysis.KadisonKastler.MatrixNearInclusion

namespace OAI

/-! # Finite spatial matrix images and their unit balls -/

namespace KadisonKastler

open UnitalTomsWinter Generator
open scoped BigOperators

noncomputable section

variable {H K : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

local instance spatialImageOperatorOrder : PartialOrder (H →L[ℂ] H) :=
  CStarAlgebra.spectralOrder _
local instance spatialImageOperatorStarOrder : StarOrderedRing (H →L[ℂ] H) :=
  CStarAlgebra.spectralOrderedRing _
local instance spatialImageAlgebraOrder (M : VonNeumannAlgebra H) :
    PartialOrder (Algebra M) := CStarAlgebra.spectralOrder _
local instance spatialImageAlgebraStarOrder (M : VonNeumannAlgebra H) :
    StarOrderedRing (Algebra M) := CStarAlgebra.spectralOrderedRing _

/-- Matrix proximity gives an actual finite spatial image approximant. -/
theorem MatrixNearInclusion.spatialMatrix_approx
    {M N : VonNeumannAlgebra H} {γ : ℝ} (h : MatrixNearInclusion M N γ)
    [Nonempty ι] [Nontrivial K] (E : MatrixUnitSystem ι (K →L[ℂ] K))
    (X : CStarMatrix ι ι (H →L[ℂ] H)) (hX : ∀ i j, X i j ∈ M) (hn : ‖X‖ ≤ 1) :
    ∃ Y : CStarMatrix ι ι (H →L[ℂ] H), (∀ i j, Y i j ∈ N) ∧ ‖Y‖ ≤ 1 ∧
      ‖spatialMatrixHom E X - spatialMatrixHom E Y‖ ≤ γ := by
  obtain ⟨Y, hY, hYn, hc⟩ := h.square X hX hn
  refine ⟨Y, hY, hYn, ?_⟩
  rw [← map_sub, norm_spatialMatrixHom]
  exact hc

/-- The finite matrix image with coefficients restricted to `M`. -/
def spatialMatrixAlgebraHom (M : VonNeumannAlgebra H)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) :
    CStarMatrix ι ι (Algebra M) →⋆ₐ[ℂ]
      (SpatialHilbert H K →L[ℂ] SpatialHilbert H K) :=
  (spatialMatrixHom E).comp (coefficientMatrixMap M.toStarSubalgebra.subtype)

def spatialMatrixAlgebra (M : VonNeumannAlgebra H)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) :
    StarSubalgebra ℂ (SpatialHilbert H K →L[ℂ] SpatialHilbert H K) :=
  (spatialMatrixAlgebraHom M E).range

theorem spatialMatrixAlgebraHom_apply (M : VonNeumannAlgebra H)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) (X : CStarMatrix ι ι (Algebra M)) :
    spatialMatrixAlgebraHom M E X =
      ∑ i, ∑ j, spatialTensorOp (X i j).val (E.entry i j) :=
  spatialMatrixHom_apply E (coefficientMatrixMap M.toStarSubalgebra.subtype X)

omit [CompleteSpace H] [CompleteSpace K] [Fintype ι] in
private theorem spatialTensorOp_sum_right (a : H →L[ℂ] H) (s : Finset ι)
    (b : ι → K →L[ℂ] K) :
    spatialTensorOp a (∑ i ∈ s, b i) = ∑ i ∈ s, spatialTensorOp a (b i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih => simp only [Finset.sum_insert hi, spatialTensorOp_add_right, ih]

theorem spatialLeft_mem_matrixAlgebra (M : VonNeumannAlgebra H)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) {a : H →L[ℂ] H} (ha : a ∈ M) :
    spatialLeft (K := K) a ∈ spatialMatrixAlgebra M E := by
  let X : CStarMatrix ι ι (Algebra M) := fun i j => if i = j then ⟨a, ha⟩ else 0
  refine ⟨X, ?_⟩
  change spatialMatrixAlgebraHom M E X = spatialLeft (K := K) a
  rw [spatialMatrixAlgebraHom_apply]
  have hX (i j : ι) : (X i j).val = if i = j then a else 0 := by
    dsimp [X]
    split_ifs <;> rfl
  have hh (i j : ι) : spatialTensorOp (X i j).val (E.entry i j) =
      if i = j then spatialTensorOp a (E.entry i j) else 0 := by
    rw [hX]
    split_ifs <;> simp only [spatialTensorOp_zero_left]
  simp only [hh]
  have hd (i : ι) : (∑ j, if i = j then spatialTensorOp a (E.entry i j) else 0) =
      spatialTensorOp a (E.entry i i) := by
    classical
    rw [Finset.sum_eq_single i]
    · simp only [ite_true]
    · intro j _ hji
      simp only [ite_eq_right (Ne.symm hji)]
    · intro hi
      exact False.elim (hi (Finset.mem_univ i))
  simp only [hd]
  rw [← spatialTensorOp_sum_right, E.total]
  rfl

theorem spatialRight_mem_matrixAlgebra (M : VonNeumannAlgebra H)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) {b : K →L[ℂ] K} (hb : b ∈ E.algebra) :
    spatialRight (H := H) b ∈ spatialMatrixAlgebra M E := by
  obtain ⟨c, rfl⟩ := (E.mem_algebra b).mp hb
  let X : CStarMatrix ι ι (Algebra M) := fun i j => c i j • 1
  refine ⟨X, ?_⟩
  change spatialMatrixAlgebraHom M E X = spatialRight (H := H) _
  rw [spatialMatrixAlgebraHom_apply]
  change (∑ i, ∑ j, spatialTensorOp (c i j • (1 : H →L[ℂ] H)) (E.entry i j)) =
    spatialRight (H := H) (∑ i, ∑ j, c i j • E.entry i j)
  simp only [map_sum, map_smul, spatialTensorOp_smul_left]
  rfl

/-- The finite image is exactly the star algebra generated by the two
commuting coefficient algebras. -/
theorem spatialMatrixAlgebra_eq_sup (M : VonNeumannAlgebra H)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) :
    spatialMatrixAlgebra M E =
      M.toStarSubalgebra.map (spatialLeft (K := K)) ⊔
        E.algebra.map (spatialRight (H := H)) := by
  apply le_antisymm
  · rintro T ⟨X, rfl⟩
    change spatialMatrixAlgebraHom M E X ∈ _
    rw [spatialMatrixAlgebraHom_apply]
    let S : StarSubalgebra ℂ (SpatialHilbert H K →L[ℂ] SpatialHilbert H K) :=
      M.toStarSubalgebra.map (spatialLeft (H := H) (K := K)) ⊔
        E.algebra.map (spatialRight (H := H) (K := K))
    change (∑ i, ∑ j, spatialTensorOp (X i j).val (E.entry i j)) ∈ S
    apply S.sum_mem
    intro i _
    apply S.sum_mem
    intro j _
    have hl : spatialLeft (K := K) (X i j).val ∈
        M.toStarSubalgebra.map (spatialLeft (K := K)) := ⟨(X i j).val, (X i j).property, rfl⟩
    have hr : spatialRight (H := H) (E.entry i j) ∈
        E.algebra.map (spatialRight (H := H)) := ⟨E.entry i j, E.entry_mem i j, rfl⟩
    have hp := S.mul_mem
      ((show M.toStarSubalgebra.map (spatialLeft (K := K)) ≤ S from le_sup_left) hl)
      ((show E.algebra.map (spatialRight (H := H)) ≤ S from le_sup_right) hr)
    change spatialTensorOp (X i j).val 1 * spatialTensorOp 1 (E.entry i j) ∈ _ at hp
    simpa only [← spatialTensorOp_mul, mul_one, one_mul] using hp
  · apply sup_le
    · rintro _ ⟨a, ha, rfl⟩
      exact spatialLeft_mem_matrixAlgebra M E ha
    · rintro _ ⟨b, hb, rfl⟩
      exact spatialRight_mem_matrixAlgebra M E hb

theorem spatialMatrixAlgebra_mono (M : VonNeumannAlgebra H)
    {κ : Type*} [Fintype κ] [DecidableEq κ]
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) (F : MatrixUnitSystem κ (K →L[ℂ] K))
    (hEF : E.algebra ≤ F.algebra) : spatialMatrixAlgebra M E ≤ spatialMatrixAlgebra M F := by
  rw [spatialMatrixAlgebra_eq_sup, spatialMatrixAlgebra_eq_sup]
  exact sup_le_sup le_rfl (StarSubalgebra.map_mono hEF)

theorem spatialMatrixAlgebra_le_product (M : VonNeumannAlgebra H) (D : VonNeumannAlgebra K)
    (E : MatrixUnitSystem ι (K →L[ℂ] K)) (hE : ∀ i j, E.entry i j ∈ D) :
    spatialMatrixAlgebra M E ≤ (spatialProductAlgebra M D).toStarSubalgebra := by
  rintro T ⟨X, rfl⟩
  exact spatialMatrixHom_mem M D E hE
    (coefficientMatrixMap M.toStarSubalgebra.subtype X) (fun i j => (X i j).property)

/-- Every contraction in the finite image has an exact contractive
operator-valued matrix representative. -/
theorem exists_matrix_of_mem_spatialMatrixAlgebra
    [Nonempty ι] [Nontrivial K]
    (M : VonNeumannAlgebra H) (E : MatrixUnitSystem ι (K →L[ℂ] K))
    {T : SpatialHilbert H K →L[ℂ] SpatialHilbert H K}
    (hT : T ∈ spatialMatrixAlgebra M E) (hn : ‖T‖ ≤ 1) :
    ∃ X : CStarMatrix ι ι (H →L[ℂ] H), (∀ i j, X i j ∈ M) ∧ ‖X‖ ≤ 1 ∧
      spatialMatrixHom E X = T := by
  obtain ⟨X, hXT⟩ := hT
  change spatialMatrixAlgebraHom M E X = T at hXT
  refine ⟨coefficientMatrixMap M.toStarSubalgebra.subtype X,
    (fun i j => (X i j).property), ?_, hXT⟩
  rw [← norm_spatialMatrixHom E]
  change ‖spatialMatrixAlgebraHom M E X‖ ≤ 1
  rwa [hXT]

end

end KadisonKastler

end OAI
