import OAI.GroupTheory.PolycyclicRecognition.Algebra.MixedWordIdeal
import OAI.GroupTheory.PolycyclicRecognition.Geometry.WeightSpaceWordSpan
import OAI.GroupTheory.PolycyclicRecognition.Geometry.CartanWordModel

namespace OAI

/-! # The mixed-word ideal contains every outside generalized weight space -/

noncomputable section
namespace PolycyclicRecognition

open Module LieAlgebra LieModule Set

/-- A pure word has weight in any additively closed set containing all of
its letter weights. -/
theorem bracketWordWeight_mem_of_pure
    {I H : Type*} [AddCommGroup H] [Module ℝ H]
    (α : I → H →ₗ[ℝ] ℝ) (C : Set (H →ₗ[ℝ] ℝ))
    (hadd : ∀ x ∈ C, ∀ y ∈ C, x + y ∈ C)
    (w : FreeMagma I) (hw : ¬IsMixedWord (fun i => α i ∉ C) w) :
    bracketWordWeight α w ∈ C := by
  induction w using FreeMagma.rec with
  | of i => exact Classical.not_not.mp hw
  | mul u v hu hv =>
    exact hadd _ (hu (fun h => hw (Or.inl h))) _ (hv (fun h => hw (Or.inr h)))

namespace CartanWordModel

variable {L : Type*} [LieRing L] [LieAlgebra ℝ L] [FiniteDimensional ℝ L]
  {H : LieSubalgebra ℝ L} [H.IsCartanSubalgebra] (M : CartanWordModel H)

/-- The ideal generated by the letters outside the allowed cone of weights. -/
def coneWordIdeal (C : Set (H →ₗ[ℝ] ℝ)) : LieIdeal ℝ (cartanRootIdeal H) :=
  mixedWordIdeal M.letter (fun i => (M.weight i : H →ₗ[ℝ] ℝ) ∉ C) M.generates

/-- Homogeneous word bases show that every generalized weight space outside
an additively closed cone is contained in the mixed-word ideal. -/
theorem outside_genWeightSpace_le_coneWordIdeal
    (C : Set (H →ₗ[ℝ] ℝ)) (hadd : ∀ x ∈ C, ∀ y ∈ C, x + y ∈ C)
    (φ : H →ₗ[ℝ] ℝ) (hφ : φ ∉ C) :
    (genWeightSpace (cartanRootIdeal H) φ).toSubmodule ≤ (M.coneWordIdeal C).toSubmodule := by
  classical
  by_cases hz : genWeightSpace (cartanRootIdeal H) φ = ⊥
  · rw [hz]
    exact bot_le
  let α : Weight ℝ H (cartanRootIdeal H) := ⟨φ, hz⟩
  let β : M.Bases := Classical.choice inferInstance
  let b := WordBasisSelections.basis M.letter M.wordList β
  let χ := fun i => (M.weight i : H →ₗ[ℝ] ℝ)
  have hm (j : Fin (finrank ℝ (cartanRootIdeal H))) :
      b j ∈ genWeightSpace (cartanRootIdeal H) (bracketWordWeight χ (β.val j)) := by
    rw [← WordBasisSelections.eval_words M.letter M.wordList β j]
    exact cartan_word_mem_genWeight H M.letter M.weight M.letter_root (β.val j)
  let ψ : Fin (finrank ℝ (cartanRootIdeal H)) → Weight ℝ H (cartanRootIdeal H) := fun j =>
    { toFun := bracketWordWeight χ (β.val j)
      genWeightSpace_ne_bot' := by
        intro hj
        have h := hm j
        rw [hj] at h
        exact b.ne_zero j h }
  have hψ j : (ψ j : H →ₗ[ℝ] ℝ) = bracketWordWeight χ (β.val j) := by ext h; rfl
  have ha : (α : H →ₗ[ℝ] ℝ) = φ := by ext h; rfl
  have hspan := genWeightSpace_le_span_basis_by_weight b ψ hm
    (fun γ => (γ : H →ₗ[ℝ] ℝ) ∉ C) α (by rwa [ha])
  apply hspan.trans
  apply Submodule.span_le.mpr
  rintro _ ⟨j, hj, rfl⟩
  have hmix : IsMixedWord (fun i => χ i ∉ C) (β.val j) := by
    by_contra hn
    have hc := bracketWordWeight_mem_of_pure χ C hadd (β.val j) hn
    exact hj (by rwa [hψ])
  rw [← WordBasisSelections.eval_words M.letter M.wordList β j]
  exact eval_mixed_mem_span M.letter (fun i => χ i ∉ C) hmix

/-- The mixed ideal is invariant under the full Cartan action, including
its generalized-eigenvector corrections. -/
theorem coneWordIdeal_cartan_invariant
    (C : Set (H →ₗ[ℝ] ℝ)) (hadd : ∀ x ∈ C, ∀ y ∈ C, x + y ∈ C)
    (h : H) (v : cartanRootIdeal H) (hv : v ∈ M.coneWordIdeal C) :
    ⁅h, v⁆ ∈ M.coneWordIdeal C := by
  let D := toEnd ℝ H (cartanRootIdeal H) h
  have hD (x y : cartanRootIdeal H) : D ⁅x, y⁆ = ⁅D x, y⁆ + ⁅x, D y⁆ := by
    apply Subtype.ext
    change ⁅(h : L), ⁅(x : L), (y : L)⁆⁆ =
      ⁅⁅(h : L), (x : L)⁆, (y : L)⁆ + ⁅(x : L), ⁅(h : L), (y : L)⁆⁆
    exact leibniz_lie _ _ _
  apply derivation_preserves_mixedWordIdeal M.letter
    (fun i => (M.weight i : H →ₗ[ℝ] ℝ) ∉ C) M.generates D hD ?_ v hv
  intro i hi
  have hm : M.letter i ∈ genWeightSpace (cartanRootIdeal H) (M.weight i) :=
    cartan_word_mem_genWeight H M.letter M.weight M.letter_root (FreeMagma.of i)
  exact M.outside_genWeightSpace_le_coneWordIdeal C hadd (M.weight i) hi
    ((genWeightSpace (cartanRootIdeal H) (M.weight i)).lie_mem hm)

/-- For a pointed positive cone, the zero generalized weight space is
removed in the quotient. Here the allowed set omits the cone vertex. -/
theorem zero_genWeightSpace_le_coneWordIdeal
    (C : Set (H →ₗ[ℝ] ℝ)) (hadd : ∀ x ∈ C, ∀ y ∈ C, x + y ∈ C)
    (hzero : (0 : H →ₗ[ℝ] ℝ) ∉ C) :
    (genWeightSpace (cartanRootIdeal H) (0 : H → ℝ)).toSubmodule ≤
      (M.coneWordIdeal C).toSubmodule :=
  M.outside_genWeightSpace_le_coneWordIdeal C hadd 0 hzero

/-- In particular the Cartan/root intersection is killed by the cone
quotient, so the later action can descend through the factorization of G. -/
theorem cartan_intersection_mem_coneWordIdeal
    (C : Set (H →ₗ[ℝ] ℝ)) (hadd : ∀ x ∈ C, ∀ y ∈ C, x + y ∈ C)
    (hzero : (0 : H →ₗ[ℝ] ℝ) ∉ C) (v : cartanRootIdeal H) (hv : (v : L) ∈ H) :
    v ∈ M.coneWordIdeal C := by
  let ι : (cartanRootIdeal H) →ₗ⁅ℝ,H⁆ L := ((cartanRootIdeal H).restr H).incl
  have hroot : v ∈ genWeightSpace (cartanRootIdeal H) (0 : H → ℝ) := by
    rw [← comap_genWeightSpace_eq_of_injective (f := ι)
      ((cartanRootIdeal H).restr H).injective_incl]
    exact toLieSubmodule_le_rootSpace_zero ℝ L H hv
  exact M.zero_genWeightSpace_le_coneWordIdeal C hadd hzero hroot

end CartanWordModel
end PolycyclicRecognition

end

end OAI
