import OAI.GroupTheory.PolycyclicRecognition.Geometry.TriangularHeight
import Mathlib.Algebra.Lie.Weights.Cartan
import Mathlib.Algebra.Lie.Solvable

namespace OAI

/-! # The nilpotent ideal in the Cartan model

Nonzero generalized root vectors lie in the derived algebra. Their generated
ideal is nilpotent for an actual triangular adjoint representation, and its
sum with the Cartan subalgebra is the full Lie algebra.
-/

noncomputable section

namespace PolycyclicRecognition

open LieAlgebra LieModule

/-- A generalized eigenvector for a nonzero eigenvalue lies in every
submodule containing the image of the operator. -/
theorem mem_submodule_of_generalized_eigenvector
    {V : Type*} [AddCommGroup V] [Module ℝ V]
    (S : Submodule ℝ V) (f : Module.End ℝ V) (hf : ∀ v, f v ∈ S)
    {a : ℝ} (ha : a ≠ 0) (k : ℕ) (v : V)
    (hv : ((f - a • 1) ^ k) v = 0) : v ∈ S := by
  induction k generalizing v with
  | zero =>
    have hz : v = 0 := by simpa using hv
    rw [hz]
    exact S.zero_mem
  | succ k ih =>
    have hy : (f - a • 1) v ∈ S := by
      apply ih
      simpa only [pow_succ, Module.End.mul_apply] using hv
    have hsmul : a • v ∈ S := by
      convert S.sub_mem (hf v) hy using 1
      simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply]
      abel
    simpa only [smul_smul, inv_mul_cancel₀ ha, one_smul] using S.smul_mem a⁻¹ hsmul

variable {L : Type*} [LieRing L] [LieAlgebra ℝ L]
  (H : LieSubalgebra ℝ L) [H.IsCartanSubalgebra]

/-- Nonzero generalized roots lie in every ideal containing the brackets. -/
theorem nonzero_root_le_ideal (I : LieIdeal ℝ L)
    (hI : ∀ x y : L, ⁅x, y⁆ ∈ I)
    (χ : Weight ℝ H L) (hχ : χ.IsNonZero) : rootSpace H χ ≤ I.restr H := by
  have hex : ∃ h : H, χ h ≠ 0 := by
    by_contra! hz
    apply hχ
    funext h
    exact hz h
  obtain ⟨h, hh⟩ := hex
  intro v hv
  obtain ⟨k, hk⟩ := (mem_genWeightSpace L (χ : H → ℝ) v).mp hv h
  exact mem_submodule_of_generalized_eigenvector I.toSubmodule
    (toEnd ℝ H L h) (fun v => hI h v) hh k v hk

/-- The ideal generated by the nonzero generalized root spaces. -/
def cartanRootIdeal : LieIdeal ℝ L :=
  LieSubmodule.lieSpan ℝ L {v | ∃ χ : Weight ℝ H L, χ.IsNonZero ∧ v ∈ rootSpace H χ}

theorem cartanRootIdeal_le_derived : cartanRootIdeal H ≤ derivedSeries ℝ L 1 := by
  apply LieSubmodule.lieSpan_le.mpr
  rintro v ⟨χ, hχ, hv⟩
  apply nonzero_root_le_ideal H (derivedSeries ℝ L 1) _ χ hχ hv
  intro x y
  change ⁅x, y⁆ ∈ ⁅(⊤ : LieIdeal ℝ L), ⊤⁆
  exact LieSubmodule.lie_mem_lie (LieSubmodule.mem_top _) (LieSubmodule.mem_top _)

/-- The real upper triangular adjoint representation makes the nonzero-root
ideal a subideal of the canonical nilpotent kernel. -/
theorem cartanRootIdeal_le_kernel {n : ℕ} (T : TriangularAdjoint L n) :
    cartanRootIdeal H ≤ T.kernelIdeal := by
  apply LieSubmodule.lieSpan_le.mpr
  rintro v ⟨χ, hχ, hv⟩
  apply nonzero_root_le_ideal H T.kernelIdeal _ χ hχ hv
  intro x y
  exact (T.mem_kernelIdeal _).mpr fun i => T.character_lie i x y

/-- The Cartan-model ideal is genuinely nilpotent, not assumed nilpotent. -/
theorem cartanRootIdeal_nilpotent [FiniteDimensional ℝ L]
    {n : ℕ} (T : TriangularAdjoint L n) : LieRing.IsNilpotent (cartanRootIdeal H) := by
  let := T.kernelIdeal_nilpotent
  exact (LieIdeal.inclusion_injective (cartanRootIdeal_le_kernel H T)).lieAlgebra_isNilpotent

/-- The Cartan subalgebra and the nonzero-root ideal span the full algebra.
Their overlap is retained; no complementary-subalgebra assertion is used. -/
theorem cartanRootIdeal_sup_cartan [FiniteDimensional ℝ L]
    [LieModule.IsTriangularizable ℝ H L] :
    (cartanRootIdeal H).toSubmodule ⊔ H.toSubmodule = ⊤ := by
  have hroot : (⨆ χ : Weight ℝ H L, ⨆ (_ : χ.IsNonZero), rootSpace H χ) ≤
      (cartanRootIdeal H).restr H := by
    apply iSup_le
    intro χ
    apply iSup_le
    intro hχ v hv
    exact LieSubmodule.subset_lieSpan ⟨χ, hχ, hv⟩
  have hh : H.toLieSubmodule ⊔ (cartanRootIdeal H).restr H = ⊤ := by
    apply top_unique
    rw [← cartan_sup_iSup_rootSpace_eq_top (H := H)]
    exact sup_le_sup le_rfl hroot
  have heq := congrArg LieSubmodule.toSubmodule hh
  change H.toSubmodule ⊔ (cartanRootIdeal H).toSubmodule = ⊤ at heq
  simpa only [sup_comm] using heq

end PolycyclicRecognition

end

end OAI
