import OAI.GroupTheory.PolycyclicRecognition.Geometry.AlgebraExponential
import OAI.GroupTheory.PolycyclicRecognition.Geometry.ExponentialProductCoordinates
import OAI.GroupTheory.PolycyclicRecognition.Algebra.AbelianRealSpace

namespace OAI

/-! # The real action generated by an arbitrary linear logarithm

No nilpotence of the logarithm is needed. The operator exponential gives an
actual smooth action on the additive vector model.
-/

noncomputable section
namespace PolycyclicRecognition
variable {n : ℕ}

def additiveOperatorUnitAut (u : (AbelianRealSpace n →L[ℝ] AbelianRealSpace n)ˣ) :
    MulAut (AbelianRealSpace n) where
  toFun := u.val
  invFun := u.inv
  left_inv x := by
    change (u.inv * u.val) x = x
    rw [u.inv_val]
    rfl
  right_inv x := by
    change (u.val * u.inv) x = x
    rw [u.val_inv]
    rfl
  map_mul' x y := by
    change u.val (x + y) = u.val x + u.val y
    exact map_add u.val x y

def additiveOperatorUnitAutHom :
    (AbelianRealSpace n →L[ℝ] AbelianRealSpace n)ˣ →* MulAut (AbelianRealSpace n) where
  toFun := additiveOperatorUnitAut
  map_one' := by apply DFunLike.ext; intro x; rfl
  map_mul' u v := by apply DFunLike.ext; intro x; rfl

def linearExponentialUnits (D : AbelianRealSpace n →L[ℝ] AbelianRealSpace n) :
    Multiplicative ℝ →* (AbelianRealSpace n →L[ℝ] AbelianRealSpace n)ˣ where
  toFun t := algebraExpUnit (t.toAdd • D)
  map_one' := by
    change algebraExpUnit ((0 : ℝ) • D) = 1
    rw [zero_smul, algebraExpUnit_zero]
  map_mul' s t := by
    change algebraExpUnit ((s.toAdd + t.toAdd) • D) = _
    rw [add_smul]
    exact algebraExpUnit_add_of_commute
      (((Commute.refl D).smul_left s.toAdd).smul_right t.toAdd)

def linearExponentialAction (D : AbelianRealSpace n →L[ℝ] AbelianRealSpace n) :
    Multiplicative ℝ →* MulAut (AbelianRealSpace n) :=
  additiveOperatorUnitAutHom.comp (linearExponentialUnits D)

@[simp] theorem linearExponentialAction_apply
    (D : AbelianRealSpace n →L[ℝ] AbelianRealSpace n) (t : ℝ) (x : AbelianRealSpace n) :
    linearExponentialAction D (Multiplicative.ofAdd t) x =
      (NormedSpace.exp (t • D)) x := rfl

theorem linearExponentialAction_smooth
    (D : AbelianRealSpace n →L[ℝ] AbelianRealSpace n) :
    ContDiff ℝ ⊤ (fun p : ℝ × AbelianRealSpace n =>
      linearExponentialAction D (Multiplicative.ofAdd p.1) p.2) := by
  have he : ContDiff ℝ ⊤
      (NormedSpace.exp : (AbelianRealSpace n →L[ℝ] AbelianRealSpace n) →
        (AbelianRealSpace n →L[ℝ] AbelianRealSpace n)) :=
    contDiff_iff_contDiffAt.mpr fun x =>
      (NormedSpace.exp_analytic (𝕂 := ℝ) x).contDiffAt
  have ht : ContDiff ℝ ⊤ (fun p : ℝ × AbelianRealSpace n => p.1 • D) :=
    contDiff_fst.smul_const D
  exact (he.comp ht).clm_apply contDiff_snd

end PolycyclicRecognition

end

end OAI
