import OAI.NumberTheory.Ostmann.Arithmetic.HistoryGiantWeightedPriorReplacementBounds
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryGiantWeightedPriorReplacementGuard
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryGiantWeightedPriorReplacementMixed
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryGiantWeightedPriorReplacementPrime

namespace OAI

open _root_.Erdos970 _root_.OAI.Erdos970

open Erdos970.Erdos970Dependency.SiegelWalfisz



end OAI
