import OAI.NumberTheory.Ostmann.Arithmetic.HistoryBulkFibreIntegralReplacementCorrectedMixed
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryBulkFibreIntegralReplacementCorrectedPrime
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryBulkFibreIntegralReplacementPlainMixed
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryBulkFibreIntegralReplacementPlainPrime

namespace OAI

open _root_.Erdos970 _root_.OAI.Erdos970

open Erdos970.Erdos970Dependency.SiegelWalfisz



end OAI
