import OAI.NumberTheory.Ostmann.Arithmetic.HistoryPairReferenceFlagExpectationCanonicalBudget
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryPairReferenceFlagExpectationSelection
import OAI.NumberTheory.Ostmann.Arithmetic.HistoryPairReferenceFlagExpectationSourceSelection

namespace OAI

open Erdos970



end OAI
