import OAI.NumberTheory.PrimePackets.ErgodicDecomposition
import OAI.NumberTheory.PrimePackets.RootSubgroups

namespace OAI

/-!
# The lattice group action and its ergodic components

Taking inverses writes the right lattice action as a left action.
Measurable ergodic decomposition gives probability components for each
closed matrix subgroup preserving the measure. Adjoining an invariant
subgroup to the diagonal action preserves invariance and ergodicity
of a diagonal-ergodic probability, as required by Margulis--Tomanov.
-/

noncomputable section
open MeasureTheory ProbabilityTheory Set Filter
open scoped Topology Classical

namespace DukePrimeDegree
open PrimeDegreePackets

/-- The left action corresponding to the actual right lattice action. -/
instance latticeSubgroupInverseAction {n : ℕ} (H : Subgroup (G n)) :
    MulAction H (X n) where
  smul h x := rightAction x (h.val)⁻¹
  one_smul x := by
    change rightAction x (1 : G n)⁻¹ = x
    simp
  mul_smul h k x := by
    change rightAction x (h.val * k.val)⁻¹ =
      rightAction (rightAction x k.val⁻¹) h.val⁻¹
    rw [mul_inv_rev, rightAction_mul]

instance latticeSubgroupInverseAction_continuous {n : ℕ} (H : Subgroup (G n)) :
    ContinuousSMul H (X n) where
  continuous_smul := by
    change Continuous (fun p : H × X n => rightAction p.2 (p.1.val)⁻¹)
    exact (continuous_rightAction_uncurry n).comp
      (continuous_snd.prodMk (continuous_subtype_val.comp continuous_fst).inv)

lemma latticeSubgroup_preserving {n : ℕ} (H : Subgroup (G n))
    (μ : Measure (X n)) (hH : H ≤ invariantRightSubgroup μ) (h : H) :
    MeasurePreserving (fun x : X n => h • x) μ μ :=
  ⟨(continuous_rightAction h.val⁻¹).measurable, hH (H.inv_mem h.property)⟩

/-- Measurable ergodic decomposition for the lattice action of a closed
subgroup preserving the probability measure. -/
theorem lattice_subgroup_ergodic_decomposition {n : ℕ}
    (H : Subgroup (G n)) (μ : Measure (X n)) [IsProbabilityMeasure μ]
    (hH : H ≤ invariantRightSubgroup μ) :
    ∃ (m : MeasurableSpace (X n)) (hm : m ≤ xMeasurableSpace n),
      letI : MeasurableSpace (X n) := xMeasurableSpace n
      condExpKernel μ m ∘ₘ μ.trim hm = μ ∧
        ∀ᵐ x ∂μ.trim hm, ErgodicSMul H (X n) (condExpKernel μ m x) := by
  let : SecondCountableTopology H :=
    Topology.IsEmbedding.subtypeVal.secondCountableTopology
  exact continuous_action_ergodic_decomposition μ (latticeSubgroup_preserving H μ hH)

/-- The subgroup generated by A and a prescribed invariant subgroup. -/
def diagonalAdjoinedGroup (d : ℕ) (H : Subgroup (G (d + 1))) : Subgroup (G (d + 1)) :=
  Subgroup.closure ({g | ∃ u : LogCoordinates d, g = diagonalFlow u} ∪ (H : Set _))

lemma diagonal_mem_diagonalAdjoinedGroup (d : ℕ) (H : Subgroup (G (d + 1)))
    (u : LogCoordinates d) : diagonalFlow u ∈ diagonalAdjoinedGroup d H :=
  Subgroup.subset_closure (Or.inl ⟨u, rfl⟩)

lemma subgroup_le_diagonalAdjoinedGroup (d : ℕ) (H : Subgroup (G (d + 1))) :
    H ≤ diagonalAdjoinedGroup d H :=
  fun _ hh => Subgroup.subset_closure (Or.inr hh)

lemma diagonalAdjoinedGroup_preserves (d : ℕ) (H : Subgroup (G (d + 1)))
    (μ : Measure (X (d + 1)))
    (hA : ∀ u : LogCoordinates d, μ.map (fun x => rightAction x (diagonalFlow u)) = μ)
    (hH : H ≤ invariantRightSubgroup μ) :
    diagonalAdjoinedGroup d H ≤ invariantRightSubgroup μ := by
  rw [diagonalAdjoinedGroup, Subgroup.closure_le]
  rintro g (⟨u, rfl⟩ | hg)
  · exact hA u
  · exact hH hg

/-- Diagonal ergodicity implies ergodicity for the group generated by
the diagonal group and an invariant subgroup. -/
theorem diagonalAdjoinedGroup_ergodic (d : ℕ) (H : Subgroup (G (d + 1)))
    (μ : Measure (X (d + 1)))
    [ErgodicSMul (Multiplicative (LogCoordinates d)) (X (d + 1)) μ]
    (hH : H ≤ invariantRightSubgroup μ) :
    ErgodicSMul (diagonalAdjoinedGroup d H) (X (d + 1)) μ := by
  have hA (u : LogCoordinates d) :
      μ.map (fun x => rightAction x (diagonalFlow u)) = μ :=
    (measurePreserving_smul (Multiplicative.ofAdd u) μ).map_eq
  have hpres := latticeSubgroup_preserving (diagonalAdjoinedGroup d H) μ
    (diagonalAdjoinedGroup_preserves d H μ hA hH)
  refine { measure_preimage_smul := ?_, aeconst_of_forall_preimage_smul_ae_eq := ?_ }
  · intro g s hs
    exact (hpres g).measure_preimage hs.nullMeasurableSet
  · intro s hs hfix
    apply ErgodicSMul.aeconst_of_forall_preimage_smul_ae_eq
      (G := Multiplicative (LogCoordinates d)) hs
    intro u
    let a : diagonalAdjoinedGroup d H :=
      ⟨(diagonalFlow u.toAdd)⁻¹,
        (diagonalAdjoinedGroup d H).inv_mem (diagonal_mem_diagonalAdjoinedGroup d H u.toAdd)⟩
    have hh := hfix a
    change (fun x => rightAction x ((diagonalFlow u.toAdd)⁻¹)⁻¹) ⁻¹' s =ᵐ[μ] s at hh
    change (fun x => rightAction x (diagonalFlow u.toAdd)) ⁻¹' s =ᵐ[μ] s
    simpa only [inv_inv] using hh

end DukePrimeDegree

end

end OAI
