import OAI.NumberTheory.DukePrimeDegree.Dynamics.ExtremalRootFlow
import Mathlib.Topology.Algebra.Group.Subgroup

namespace OAI

/-!
# Matrix support of groups generated by positive roots

Transitive positive root sets define matrix patterns preserved by all
products of their root generators. The assertion also holds on the
closure, supplying the concrete support restriction for root induction.
-/

noncomputable section
open Matrix Set
open scoped Topology BigOperators

namespace DukePrimeDegree
open PrimeDegreePackets

/-- Outside the chosen positive roots the matrix equals the identity. -/
def PositiveRootPattern {n : ℕ} (S : Finset (Fin n × Fin n)) (g : G n) : Prop :=
  ∀ r s, (r, s) ∉ S → g.val r s = (1 : Matrix (Fin n) (Fin n) ℝ) r s

lemma positiveRootPattern_one {n : ℕ} (S : Finset (Fin n × Fin n)) :
    PositiveRootPattern S (1 : G n) := by
  intro r s _
  rfl

lemma positiveRootPattern_transvection {n : ℕ} (S : Finset (Fin n × Fin n))
    {i j : Fin n} (hij : i ≠ j) (hijS : (i, j) ∈ S) (t : ℝ) :
    PositiveRootPattern S (Matrix.SpecialLinearGroup.transvection hij t) := by
  intro r s hrs
  have hne : ¬ (r = i ∧ s = j) := by
    rintro ⟨rfl, rfl⟩
    exact hrs hijS
  simp only [Matrix.SpecialLinearGroup.transvection_coe, Matrix.add_apply]
  have hz : Matrix.single i j t r s = 0 := by
    simp only [Matrix.single_apply]
    split_ifs with h
    · exact (hne ⟨h.1.symm, h.2.symm⟩).elim
    · rfl
  rw [hz, add_zero]

lemma positiveRootPattern_mul {n : ℕ} (S : Finset (Fin n × Fin n))
    (htrans : ∀ a b c : Fin n, (a, b) ∈ S → (b, c) ∈ S → (a, c) ∈ S)
    {g h : G n} (hg : PositiveRootPattern S g) (hh : PositiveRootPattern S h) :
    PositiveRootPattern S (g * h) := by
  let M := g.val - 1
  let N := h.val - 1
  have hM (r s : Fin n) (hrs : (r, s) ∉ S) : M r s = 0 := sub_eq_zero.mpr (hg r s hrs)
  have hN (r s : Fin n) (hrs : (r, s) ∉ S) : N r s = 0 := sub_eq_zero.mpr (hh r s hrs)
  have heq : (g * h).val = 1 + M + N + M * N := by
    simp only [Matrix.SpecialLinearGroup.coe_mul, M, N]
    noncomm_ring
  intro r s hrs
  have hMN : (M * N) r s = 0 := by
    change (∑ k, M r k * N k s) = 0
    apply Finset.sum_eq_zero
    intro k _
    by_cases hrk : (r, k) ∈ S
    · have hks : (k, s) ∉ S := fun hks => hrs (htrans r k s hrk hks)
      rw [hN k s hks, mul_zero]
    · rw [hM r k hrk, zero_mul]
  rw [heq]
  change (1 : Matrix (Fin n) (Fin n) ℝ) r s + M r s + N r s + (M * N) r s = _
  rw [hM r s hrs, hN r s hrs, hMN, add_zero, add_zero, add_zero]

/-- The subgroup generated by the root lines in `S`. -/
def positiveRootGeneratedGroup {n : ℕ} (S : Finset (Fin n × Fin n)) : Subgroup (G n) :=
  Subgroup.closure {g | ∃ (i j : Fin n) (hij : i ≠ j) (t : ℝ),
    (i, j) ∈ S ∧ g = Matrix.SpecialLinearGroup.transvection hij t}

lemma positiveRootGeneratedGroup_pattern {n : ℕ} (S : Finset (Fin n × Fin n))
    (htrans : ∀ a b c : Fin n, (a, b) ∈ S → (b, c) ∈ S → (a, c) ∈ S)
    {g : G n} (hg : g ∈ positiveRootGeneratedGroup S) : PositiveRootPattern S g := by
  apply Subgroup.closure_induction'' (p := fun g _ => PositiveRootPattern S g) ?_ ?_ ?_ ?_ hg
  · rintro g ⟨i, j, hij, t, hS, rfl⟩
    exact positiveRootPattern_transvection S hij hS t
  · rintro g ⟨i, j, hij, t, hS, rfl⟩
    rw [Matrix.SpecialLinearGroup.transvection_inv]
    exact positiveRootPattern_transvection S hij hS (-t)
  · exact positiveRootPattern_one S
  · intro g h _ _ hg hh
    exact positiveRootPattern_mul S htrans hg hh

lemma isClosed_positiveRootPattern {n : ℕ} (S : Finset (Fin n × Fin n)) :
    IsClosed {g : G n | PositiveRootPattern S g} := by
  simp only [PositiveRootPattern, Set.ofPred_forall]
  apply isClosed_iInter
  intro r
  apply isClosed_iInter
  intro s
  apply isClosed_iInter
  intro _
  exact isClosed_eq (by fun_prop) continuous_const

/-- The root support restriction survives topological closure. -/
lemma positiveRootClosure_pattern {n : ℕ} (S : Finset (Fin n × Fin n))
    (htrans : ∀ a b c : Fin n, (a, b) ∈ S → (b, c) ∈ S → (a, c) ∈ S)
    {g : G n} (hg : g ∈ (positiveRootGeneratedGroup S).topologicalClosure) :
    PositiveRootPattern S g := by
  exact closure_minimal (fun _ h => positiveRootGeneratedGroup_pattern S htrans h)
    (isClosed_positiveRootPattern S) hg

end DukePrimeDegree

end

end OAI
