import OAI.NumberTheory.DukePrimeDegree.Geometry.PositiveRootHolonomy
import OAI.NumberTheory.DukePrimeDegree.Geometry.RootStableHolonomy

namespace OAI

/-!
# The extremal-root step of the product argument

For a nonempty closed collection of positive roots, one root can be
removed while preserving closure. Its actual intrinsic leaf measure is
constant along the closed group generated by the remaining roots, off
one common null set. This is the holonomy step in Einsiedler--Katok
(2003), Proposition 8.3.
-/

noncomputable section
open Matrix MeasureTheory Set
open scoped Topology

namespace DukePrimeDegree
open PrimeDegreePackets

lemma erase_neutral_root_closed {n : ℕ}
    (S : Finset (Fin n × Fin n))
    (hcomp : ∀ a b c : Fin n, (a, b) ∈ S → (b, c) ∈ S → (a, c) ∈ S)
    (p : Fin n × Fin n) (ell : Fin n → ℝ) (hneut : ell p.1 = ell p.2)
    (hdecay : ∀ q ∈ S, q ≠ p → ell q.1 < ell q.2) :
    ∀ a b c : Fin n, (a, b) ∈ S.erase p → (b, c) ∈ S.erase p →
      (a, c) ∈ S.erase p := by
  intro a b c hab hbc
  obtain ⟨habp, habS⟩ := Finset.mem_erase.mp hab
  obtain ⟨hbcp, hbcS⟩ := Finset.mem_erase.mp hbc
  refine Finset.mem_erase.mpr ⟨?_, hcomp a b c habS hbcS⟩
  intro he
  have ha := hdecay (a, b) habS habp
  have hb := hdecay (b, c) hbcS hbcp
  have hac : ell a = ell c := by simpa only [← he] using hneut
  exact (ne_of_lt (lt_trans ha hb)) hac

lemma positiveRootPattern_mono {n : ℕ} {S T : Finset (Fin n × Fin n)}
    (hST : S ⊆ T) {g : G n} (hg : PositiveRootPattern S g) :
    PositiveRootPattern T g := by
  intro r s h
  exact hg r s (fun hS => h (hST hS))

/-- The remaining closed root group acts trivially on the selected
root's normalized intrinsic leaf data. No product-structure hypothesis
is used here. -/
theorem exists_extremal_root_leaf_constancy
    (d : ℕ) (S : Finset (Fin (d + 1) × Fin (d + 1))) (hS : S.Nonempty)
    (hpos : ∀ p ∈ S, p.1 < p.2)
    (hcomp : ∀ a b c : Fin (d + 1), (a, b) ∈ S → (b, c) ∈ S → (a, c) ∈ S)
    (μ : Measure (X (d + 1))) [IsFiniteMeasure μ]
    (hA : ∀ u : LogCoordinates d, μ.map (fun x => rightAction x (diagonalFlow u)) = μ) :
    ∃ p ∈ S, ∃ hp : p.1 ≠ p.2,
      (∀ a b c : Fin (d + 1), (a, b) ∈ S.erase p → (b, c) ∈ S.erase p →
        (a, c) ∈ S.erase p) ∧
      ∃ N : Set (X (d + 1)), MeasurableSet N ∧ μ N = 0 ∧
        ∀ x ∉ N, ∀ g ∈ (positiveRootGeneratedGroup (S.erase p)).topologicalClosure,
          rightAction x g ∉ N →
          intrinsicRootLeaf hp μ (rightAction x g) = intrinsicRootLeaf hp μ x := by
  obtain ⟨p, hpS, ell, hell, hneut, hdecay⟩ := exists_extremal_root_flow d S hS hpos
  have hp : p.1 ≠ p.2 := ne_of_lt (hpos p hpS)
  have hc := erase_neutral_root_closed S hcomp p ell hneut hdecay
  obtain ⟨N, hN, hN0, hhol⟩ :=
    exists_nullset_positiveRootPattern_holonomy d S hpos hp ell hell hneut hdecay μ hA
  have hfree : ∀ᵐ x ∂μ, ∀ t : ℝ,
      rightAction x (Matrix.SpecialLinearGroup.transvection hp t) = x → t = 0 :=
    (ae_root_stabilizer_trivial d μ hA).mono fun x hx => hx p.1 p.2 hp
  obtain ⟨E, hbad, hE, hE0⟩ := exists_measurable_superset_of_null
    (ae_iff.mp ((ae_intrinsicRootLeaf_spec hp μ hfree).mono fun _ h => h.2))
  refine ⟨p, hpS, hp, hc, N ∪ E, hN.union hE, measure_union_null hN0 hE0, ?_⟩
  intro x hx g hg hy
  have hpattern := positiveRootClosure_pattern (S.erase p) hc hg
  have hzero : g.val p.1 p.2 = 0 := by
    simpa only [Matrix.one_apply, hp, ite_false] using
      hpattern p.1 p.2 (by simp)
  have hunit : intrinsicRootLeaf hp μ x (Metric.ball 0 1) = 1 := by
    by_contra h
    exact hx (Or.inr (hbad h))
  have h := hhol x (fun h => hx (Or.inl h)) (rightAction x g)
    (fun h => hy (Or.inl h)) g
    (positiveRootPattern_mono (Finset.erase_subset p S) hpattern) rfl
  rwa [hzero, basedRealMeasure_zero_of_unit _ hunit] at h

end DukePrimeDegree

end

end OAI
