import Mathlib.Algebra.Order.Star.Basic
import Mathlib.Analysis.CStarAlgebra.Classes

namespace OAI

/-! Positive square-symmetric quasitraces with complex linearity on closed nonunital abelian subalgebras. -/

section

noncomputable section
open scoped ComplexOrder IsMulCommutative

namespace Kaplansky

variable {A : Type*} [CStarAlgebra A]

structure OneQuasitrace (A : Type*) [CStarAlgebra A] where
  toFun : A → ℂ
  square_nonneg : ∀ x, 0 ≤ toFun (star x * x)
  square_swap : ∀ x, toFun (star x * x) = toFun (x * star x)
  real_imag : ∀ h k, IsSelfAdjoint h → IsSelfAdjoint k →
    toFun (h + Complex.I • k) = toFun h + Complex.I * toFun k
  abelian_linear : ∀ S : NonUnitalStarSubalgebra ℂ A,
    IsClosed (S : Set A) → (∀ x y : S, x * y = y * x) →
    ∃ f : S →ₗ[ℂ] ℂ, ∀ x : S, f x = toFun x

instance : CoeFun (OneQuasitrace A) (fun _ => A → ℂ) := ⟨OneQuasitrace.toFun⟩

def OneQuasitrace.Normalized (τ : OneQuasitrace A) : Prop := τ 1 = 1

/-- The closed unital abelian case follows from the actual nonunital axiom. -/
theorem OneQuasitrace.linearOn (τ : OneQuasitrace A)
    (S : StarSubalgebra ℂ A) (hS : IsClosed (S : Set A))
    (hcomm : ∀ x y : S, x * y = y * x) :
    ∃ f : S →ₗ[ℂ] ℂ, ∀ x : S, f x = τ x := by
  exact τ.abelian_linear S.toNonUnitalStarSubalgebra hS hcomm

namespace OneQuasitrace

variable (τ : OneQuasitrace A)

theorem map_add_of_mem (S : StarSubalgebra ℂ A)
    (hS : IsClosed (S : Set A)) (hcomm : ∀ x y : S, x * y = y * x)
    {a b : A} (ha : a ∈ S) (hb : b ∈ S) : τ (a + b) = τ a + τ b := by
  obtain ⟨f, hf⟩ := τ.linearOn S hS hcomm
  exact (hf (⟨a, ha⟩ + ⟨b, hb⟩)).symm.trans
    ((f.map_add ⟨a, ha⟩ ⟨b, hb⟩).trans (congrArg₂ (· + ·) (hf _) (hf _)))

theorem map_sub_of_mem (S : StarSubalgebra ℂ A)
    (hS : IsClosed (S : Set A)) (hcomm : ∀ x y : S, x * y = y * x)
    {a b : A} (ha : a ∈ S) (hb : b ∈ S) : τ (a - b) = τ a - τ b := by
  obtain ⟨f, hf⟩ := τ.linearOn S hS hcomm
  exact (hf (⟨a, ha⟩ - ⟨b, hb⟩)).symm.trans
    ((f.map_sub ⟨a, ha⟩ ⟨b, hb⟩).trans (congrArg₂ (· - ·) (hf _) (hf _)))

theorem map_smul_of_mem (S : StarSubalgebra ℂ A)
    (hS : IsClosed (S : Set A)) (hcomm : ∀ x y : S, x * y = y * x)
    (c : ℂ) {a : A} (ha : a ∈ S) : τ (c • a) = c * τ a := by
  obtain ⟨f, hf⟩ := τ.linearOn S hS hcomm
  exact (hf (c • (⟨a, ha⟩ : S))).symm.trans
    ((f.map_smul c ⟨a, ha⟩).trans (congrArg (c * ·) (hf _)))

@[simp] theorem map_zero : τ 0 = 0 := by
  let S := StarAlgebra.elemental ℂ (0 : A)
  obtain ⟨f, hf⟩ := τ.linearOn S (StarAlgebra.elemental.isClosed ℂ 0)
    (fun x y => mul_comm x y)
  exact (hf 0).symm.trans f.map_zero

theorem map_smul_selfAdjoint (c : ℂ) {a : A} (ha : IsSelfAdjoint a) :
    τ (c • a) = c * τ a := by
  let := ha.isStarNormal
  exact τ.map_smul_of_mem (StarAlgebra.elemental ℂ a)
    (StarAlgebra.elemental.isClosed ℂ a) (fun x y => mul_comm x y) c
    (StarAlgebra.elemental.self_mem ℂ a)

theorem map_scalar_sub (c : ℂ) {a : A} (ha : IsSelfAdjoint a) :
    τ (c • (1 : A) - a) = c * τ 1 - τ a := by
  let := ha.isStarNormal
  rw [τ.map_sub_of_mem (StarAlgebra.elemental ℂ a)
    (StarAlgebra.elemental.isClosed ℂ a) (fun x y => mul_comm x y)
    ((StarAlgebra.elemental ℂ a).smul_mem (one_mem _) c)
    (StarAlgebra.elemental.self_mem ℂ a)]
  rw [τ.map_smul_selfAdjoint c (IsSelfAdjoint.one A)]

/-- Abelian linearity applied to the closed star algebra generated by a
commuting family of self-adjoint elements. -/
theorem linearOn_hull (s : Set A) (hsa : ∀ a ∈ s, IsSelfAdjoint a)
    (hc : ∀ a ∈ s, ∀ b ∈ s, a * b = b * a) :
    ∃ f : (StarAlgebra.adjoin ℂ s).topologicalClosure →ₗ[ℂ] ℂ,
      ∀ x, f x = τ x := by
  have := StarAlgebra.isMulCommutative_adjoin ℂ
    (fun element helement => (hsa element helement).isStarNormal)
    (fun element helement other hother _ => hc element helement other hother)
    (by
      intro element helement other hother _
      rw [(hsa other hother).star_eq]
      exact hc element helement other hother)
  let := StarSubalgebra.isMulCommutative_topologicalClosure (StarAlgebra.adjoin ℂ s)
  exact τ.linearOn _ (StarSubalgebra.isClosed_topologicalClosure _)
    (fun a b => mul_comm a b)

/-- Only commuting self-adjoint pairs are added here. -/
theorem map_add {a b : A} (ha : IsSelfAdjoint a) (hb : IsSelfAdjoint b)
    (hc : Commute a b) : τ (a + b) = τ a + τ b := by
  obtain ⟨f, hf⟩ := τ.linearOn_hull {a,b}
    (by intro x hx; simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl <;> assumption)
    (by intro x hx y hy
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
        rcases hx with rfl | rfl <;> rcases hy with rfl | rfl
        · rfl
        · exact hc.eq
        · exact hc.eq.symm
        · rfl)
  have ha' : a ∈ (StarAlgebra.adjoin ℂ ({a,b} : Set A)).topologicalClosure :=
    StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin ℂ _ (by simp))
  have hb' : b ∈ (StarAlgebra.adjoin ℂ ({a,b} : Set A)).topologicalClosure :=
    StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin ℂ _ (by simp))
  exact (hf (⟨a, ha'⟩ + ⟨b, hb'⟩)).symm.trans
    ((f.map_add ⟨a, ha'⟩ ⟨b, hb'⟩).trans (congrArg₂ (· + ·) (hf _) (hf _)))

theorem map_neg {a : A} (ha : IsSelfAdjoint a) : τ (-a) = -τ a := by
  simpa using τ.map_smul_selfAdjoint (-1) ha

theorem map_sub {a b : A} (ha : IsSelfAdjoint a) (hb : IsSelfAdjoint b)
    (hc : Commute a b) : τ (a - b) = τ a - τ b := by
  simpa [sub_eq_add_neg, τ.map_neg hb] using τ.map_add ha hb.neg hc.neg_right

/-- Finite additivity is derived only for pairwise commuting self-adjoints. -/
theorem map_sum {ι : Type*} (s : Finset ι) (f : ι → A)
    (hsa : ∀ i ∈ s, IsSelfAdjoint (f i))
    (hc : ∀ i ∈ s, ∀ j ∈ s, Commute (f i) (f j)) :
    τ (∑ i ∈ s, f i) = ∑ i ∈ s, τ (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
    have hs : IsSelfAdjoint (∑ i ∈ s, f i) := by
      change star (∑ i ∈ s, f i) = ∑ i ∈ s, f i
      rw [star_sum]
      exact Finset.sum_congr rfl (fun i hi => (hsa i (Finset.mem_insert_of_mem hi)).star_eq)
    rw [Finset.sum_insert ha, Finset.sum_insert ha,
      τ.map_add (hsa a (Finset.mem_insert_self a s)) hs
        (Commute.sum_right s f (f a) (fun i hi =>
          hc a (Finset.mem_insert_self a s) i (Finset.mem_insert_of_mem hi)))]
    rw [ih (fun i hi => hsa i (Finset.mem_insert_of_mem hi))
      (fun i hi j hj => hc i (Finset.mem_insert_of_mem hi) j (Finset.mem_insert_of_mem hj))]

end OneQuasitrace
end Kaplansky

end
end

end OAI
