import OAI.NumberTheory.PrimePackets.ObservationConditionalProbability

namespace OAI

/-! # The sigma algebra and conditional expectations of finite observations -/

noncomputable section
open MeasureTheory Set
open scoped BigOperators

namespace PrimeDegreePackets

variable {Y β : Type*} [mY : MeasurableSpace Y] [Fintype β]

@[instance_reducible] def observationSigma (Q : Y → β) : MeasurableSpace Y :=
  MeasurableSpace.comap Q ⊤

lemma observationSigma_le (Q : Y → β)
    (hQ : ∀ b, MeasurableSet {y | Q y = b}) : observationSigma Q ≤ mY := by
  classical
  rintro s ⟨t,_,rfl⟩
  have heq : Q ⁻¹' t = ⋃ b : t, {y | Q y = b.val} := by
    ext y
    simp only [Set.mem_preimage, Set.mem_iUnion, Set.mem_ofPred_eq]
    exact ⟨fun h => ⟨⟨Q y,h⟩,rfl⟩, fun ⟨b,h⟩ => h ▸ b.property⟩
  rw [heq]
  exact MeasurableSet.iUnion (fun b => hQ b.val)

omit mY in
lemma stronglyMeasurable_observation_values (Q : Y → β) (c : β → ℝ) :
    StronglyMeasurable[observationSigma Q] (fun y => c (Q y)) := by
  let : MeasurableSpace β := ⊤
  exact ((measurable_of_finite c).comp (comap_measurable Q)).stronglyMeasurable

/-- Equality on the finitely many observation atoms determines all set integrals
over the sigma algebra generated by that observation. -/
lemma setIntegral_eq_of_observation_atoms
    (μ : Measure Y) (Q : Y → β) (hQ : ∀ b, MeasurableSet {y | Q y = b})
    {f g : Y → ℝ} (hf : Integrable f μ) (hg : Integrable g μ)
    (hatom : ∀ b, ∫ y in {y | Q y = b}, f y ∂μ = ∫ y in {y | Q y = b}, g y ∂μ)
    {s : Set Y} (hs : MeasurableSet[observationSigma Q] s) :
    ∫ y in s, f y ∂μ = ∫ y in s, g y ∂μ := by
  classical
  obtain ⟨t,_,rfl⟩ := hs
  have heq : Q ⁻¹' t = ⋃ b : t, {y | Q y = b.val} := by
    ext y
    simp only [Set.mem_preimage, Set.mem_iUnion, Set.mem_ofPred_eq]
    exact ⟨fun h => ⟨⟨Q y,h⟩,rfl⟩, fun ⟨b,h⟩ => h ▸ b.property⟩
  have hd : Pairwise (fun b c : t => Disjoint {y | Q y = b.val} {y | Q y = c.val}) := by
    intro b c hbc
    rw [Set.disjoint_left]
    intro y hy hz
    exact hbc (Subtype.ext (hy.symm.trans hz))
  rw [heq, integral_iUnion_fintype (fun b : t => hQ b.val) hd
      (fun _ => hf.integrableOn),
    integral_iUnion_fintype (fun b : t => hQ b.val) hd (fun _ => hg.integrableOn)]
  exact Finset.sum_congr rfl (fun b _ => hatom b.val)

lemma observation_values_ae_eq_condExp
    (μ : Measure Y) [IsFiniteMeasure μ] (Q : Y → β)
    (hQ : ∀ b, MeasurableSet {y | Q y = b}) (f : Y → ℝ) (hf : Integrable f μ)
    (c : β → ℝ)
    (hatom : ∀ b, ∫ y in {y | Q y = b}, c (Q y) ∂μ =
      ∫ y in {y | Q y = b}, f y ∂μ) :
    (fun y => c (Q y)) =ᵐ[μ] μ[f | observationSigma Q] := by
  have hg := integrable_finite_values μ Q hQ c
  apply ae_eq_condExp_of_forall_setIntegral_eq (observationSigma_le Q hQ) hf
  · exact fun _ _ _ => hg.integrableOn
  · intro s hs _
    exact setIntegral_eq_of_observation_atoms μ Q hQ hg hf hatom hs
  · exact (stronglyMeasurable_observation_values Q c).aestronglyMeasurable

end PrimeDegreePackets

end

end OAI
