import Mathlib.Algebra.Colimit.Module
import Mathlib.RingTheory.Localization.BaseChange
import Mathlib.Data.Rat.Encodable

namespace OAI

/-!
# Algebraic persistence in the coarse Novikov construction

The direct-limit and rationalization arguments apply to arbitrary abelian
groups. No compatibility between the tests at different scales is assumed
or needed.
-/

namespace CoarseAssembly

section DirectLimit

variable {G : ℕ → Type*} [∀ r, AddCommGroup (G r)]
variable (f : ∀ r s, r ≤ s → G r →+ G s)
variable [DirectedSystem G (fun r s h => f r s h)]

/-- A class detected with value one at every later scale has no nonzero integer
multiple that vanishes in the actual algebraic direct limit. This is the last
argument of the manuscript's Proposition 4.1, with the geometric tests supplied
as explicit parameters. The tests need not form a compatible family. -/
theorem persistent_multiples_ne_zero (r₀ : ℕ) (a : G r₀)
    (test : ∀ r, r₀ ≤ r → G r →+ ℤ)
    (detects : ∀ r (hr : r₀ ≤ r), test r hr (f r₀ r hr a) = 1)
    (n : ℤ) (hn : n ≠ 0) :
    n • AddCommGroup.DirectLimit.of G f r₀ a ≠ 0 := by
  intro h
  have h' : AddCommGroup.DirectLimit.of G f r₀ (n • a) = 0 := by
    simpa only [map_zsmul] using h
  obtain ⟨r, hr, hz⟩ := AddCommGroup.DirectLimit.of.zero_exact r₀ (n • a) h'
  have ht := congrArg (test r hr) hz
  simp only [map_zsmul, map_zero, detects, zsmul_eq_mul, mul_one] at ht
  exact hn ht

/-- The cyclic subgroup generated by a persistently detected class is an
embedded copy of the integers. -/
theorem persistent_cyclic_injective (r₀ : ℕ) (a : G r₀)
    (test : ∀ r, r₀ ≤ r → G r →+ ℤ)
    (detects : ∀ r (hr : r₀ ≤ r), test r hr (f r₀ r hr a) = 1) :
    Function.Injective (fun n : ℤ => n • AddCommGroup.DirectLimit.of G f r₀ a) := by
  intro n m h
  dsimp only at h
  by_contra hne
  have hz : (n - m) • AddCommGroup.DirectLimit.of G f r₀ a = 0 := by
    rw [sub_smul, h, sub_self]
  exact persistent_multiples_ne_zero f r₀ a test detects (n - m) (sub_ne_zero.mpr hne) hz

end DirectLimit

section Rationalization

variable {A B : Type*} [AddCommGroup A] [AddCommGroup B]

/-- An element with no nonzero integer annihilator remains nonzero after
rationalization. This is the torsion-kernel fact used after Proposition 4.1. -/
theorem rationalization_ne_zero (a : A)
    (ha : ∀ n : ℤ, n ≠ 0 → n • a ≠ 0) :
    (1 : ℚ) ⊗ₜ[ℤ] a ≠ 0 := by
  intro h
  have heq : TensorProduct.mk ℤ ℚ A 1 a = TensorProduct.mk ℤ ℚ A 1 0 := by
    simpa using h
  obtain ⟨s, hs⟩ := IsLocalizedModule.exists_of_eq (S := nonZeroDivisors ℤ)
    (f := TensorProduct.mk ℤ ℚ A 1) heq
  exact ha s (mem_nonZeroDivisors_iff_ne_zero.mp s.property)
    (by simpa only [Submonoid.smul_def, smul_zero] using hs)

/-- A non-torsion kernel element prevents both integral and rational
injectivity. The scalar extension is the actual tensor product of groups. -/
theorem kernel_obstructs_injectivity (μ : A →+ B) (a : A)
    (ha : ∀ n : ℤ, n ≠ 0 → n • a ≠ 0) (hμ : μ a = 0) :
    ¬ Function.Injective μ ∧
      ¬ Function.Injective (μ.toIntLinearMap.lTensor ℚ) := by
  constructor
  · intro hinj
    have hz : a = 0 := hinj (hμ.trans μ.map_zero.symm)
    exact ha 1 one_ne_zero (by simpa using hz)
  · intro hinj
    apply rationalization_ne_zero a ha
    apply hinj
    simp [hμ]

end Rationalization

end CoarseAssembly

end OAI
