import OAI.Topology.CoarseAssembly.Definitions
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
import Mathlib.Analysis.Normed.Operator.Compact.Basic
import Mathlib.Topology.Algebra.NonUnitalStarAlgebra
import OAI.Topology.CoarseAssembly.Conjugation
import OAI.Topology.CoarseAssembly.Sandwich

namespace OAI

/-!
# Discrete reduced Roe algebras

Operators act on the actual Hilbert sum `ℓ²(X; H)`. Matrix entries are
continuous linear maps on the coefficient Hilbert space. The Roe algebra is
the norm-closed star algebra generated by finite-propagation operators whose
entries, and adjoint entries, are compact. On a discrete space with finite
metric balls these are the usual locally compact generators.

The coefficient space is a parameter; the ample module used in the paper
is obtained by taking it to be an infinite-dimensional separable Hilbert
space. No compactness is imposed on the averaging projection itself.
-/

noncomputable section

namespace CoarseAssembly.DiscreteRoe

open scoped Topology

variable {X Y H : Type*}
variable [NormedAddCommGroup H] [InnerProductSpace ℂ H]
variable [DecidableEq X] [DecidableEq Y]

@[simp] theorem insert_apply (x : X) (h : H) : insert x h = lp.single 2 x h := rfl

omit [DecidableEq X] in
@[simp] theorem coordinate_apply (x : X) (v : Module X H) : coordinate x v = v x := rfl

@[simp] theorem entry_apply (T : Operator X H) (x y : X) (h : H) :
    entry T x y h = T (lp.single 2 y h) x := rfl

theorem entry_continuous (x y : X) : Continuous (fun T : Operator X H => entry T x y) := by
  show Continuous (fun T : Operator X H => (coordinate x).comp (T.comp (insert y)))
  exact continuous_const.clm_comp (continuous_id.clm_comp continuous_const)

@[simp] theorem entry_zero (x y : X) : entry (0 : Operator X H) x y = 0 := by
  ext h
  simp

@[simp] theorem entry_add (T S : Operator X H) (x y : X) :
    entry (T + S) x y = entry T x y + entry S x y := by
  ext h
  simp [entry, ContinuousLinearMap.comp_add, ContinuousLinearMap.add_comp]

@[simp] theorem entry_smul (c : ℂ) (T : Operator X H) (x y : X) :
    entry (c • T) x y = c • entry T x y := by
  ext h
  simp [entry]

variable [CompleteSpace H] [PseudoMetricSpace X]

attribute [local instance] OAI.CoarseAssembly.DiscreteRoe.operatorScalarTower

attribute [local instance] OAI.CoarseAssembly.DiscreteRoe.operatorScalarComm

theorem algebra_isClosed : IsClosed (algebra (X := X) (H := H) : Set (Operator X H)) :=
  NonUnitalStarSubalgebra.isClosed_topologicalClosure _

theorem generator_mem {T : Operator X H} (hT : Generator T) :
    T ∈ algebra (X := X) (H := H) :=
  (NonUnitalStarSubalgebra.le_topologicalClosure _)
    (NonUnitalStarAlgebra.subset_adjoin ℂ _ hT)

instance : CompleteSpace (algebra (X := X) (H := H)) :=
  algebra_isClosed.completeSpace_coe

variable [PseudoMetricSpace Y]

/-- A continuous spatial homomorphism maps the whole Roe algebra once its
range has been proved on the locally compact finite-propagation generators.
The range proof remains an obligation, rather than part of the definition. -/
theorem map_mem (φ : Operator X H →⋆ₙₐ[ℂ] Operator Y H) (hφ : Continuous φ)
    (hgen : ∀ T, Generator T → φ T ∈ algebra (X := Y) (H := H))
    {T : Operator X H} (hT : T ∈ algebra (X := X) (H := H)) : φ T ∈ algebra (X := Y) (H := H) := by
  let S := (algebra (X := Y) (H := H)).comap φ
  have hS : IsClosed (S : Set (Operator X H)) := algebra_isClosed.preimage hφ
  have hle : NonUnitalStarAlgebra.adjoin ℂ {T : Operator X H | Generator T} ≤ S :=
    NonUnitalStarAlgebra.adjoin_le hgen
  exact (NonUnitalStarSubalgebra.topologicalClosure_minimal _ hle hS) hT

/-- The final norm-closure step in the finite-fiber transfer argument. -/
theorem sandwich_mem {P A : Operator X H} {Pn : ℕ → Operator X H}
    (hlim : Filter.Tendsto Pn Filter.atTop (nhds P))
    (hgen : ∀ n, Generator (Pn n * A * Pn n)) : P * A * P ∈ algebra (X := X) (H := H) :=
  sandwich_mem_of_tendsto _ algebra_isClosed P Pn hlim A
    (fun n => generator_mem (hgen n))

end CoarseAssembly.DiscreteRoe

end

end OAI
