import OAI.GroupTheory.PolycyclicRecognition.Algebra.BooleanStepAction
import OAI.GroupTheory.PolycyclicRecognition.Algebra.SubgroupInductionCoordinates
import Mathlib.GroupTheory.Finiteness

namespace OAI

/-! # A small ring of bounded functions with finite-subgroup projectivity

For each finite subgroup choose its right-coset transversal. Take the Boolean
algebra generated by every left translate of these transversals and of
subgroup coset partitions inside finitely generated subgroups. When the group
is countable, this uses countably many coordinates. Its step-function ring is
projective over the integers and has a trace-one element for every finite
subgroup.
-/
noncomputable section
namespace PolycyclicRecognition
open CategoryTheory
attribute [local instance] Classical.propDecidable
variable (G : Type) [Group G]

abbrev finiteSubgroupIndex := {H : Subgroup G // Finite H}

def finiteSubgroupElements (H : finiteSubgroupIndex G) : Finset G := by
  let := H.property
  exact (Set.toFinite (H.val : Set G)).toFinset

@[simp]
theorem finiteSubgroupElements_coe (H : finiteSubgroupIndex G) :
    (finiteSubgroupElements G H : Set G) = H.val := by
  simp [finiteSubgroupElements]

instance finiteSubgroupIndex_countable [Countable G] : Countable (finiteSubgroupIndex G) := by
  apply Function.Injective.countable (f := finiteSubgroupElements G)
  intro H K h
  apply Subtype.ext
  apply SetLike.coe_injective
  simpa only [finiteSubgroupElements_coe] using congrArg (fun s : Finset G => (s : Set G)) h

instance finiteSubgroupIndex_nonempty : Nonempty (finiteSubgroupIndex G) :=
  ⟨⟨⊥, inferInstance⟩⟩

abbrev finitelyGeneratedSubgroupIndex := {H : Subgroup G // H.FG}

def finitelyGeneratedSubgroupGenerators (H : finitelyGeneratedSubgroupIndex G) : Finset G :=
  Classical.choose H.property

instance finitelyGeneratedSubgroupIndex_countable [Countable G] :
    Countable (finitelyGeneratedSubgroupIndex G) := by
  apply Function.Injective.countable (f := finitelyGeneratedSubgroupGenerators G)
  intro H K h
  apply Subtype.ext
  have hH := Classical.choose_spec H.property
  have hK := Classical.choose_spec K.property
  change Subgroup.closure (finitelyGeneratedSubgroupGenerators G H : Set G) = H.val at hH
  change Subgroup.closure (finitelyGeneratedSubgroupGenerators G K : Set G) = K.val at hK
  rw [← hH, ← hK, h]

abbrev smallCoefficientBase := finiteSubgroupIndex G ⊕
  (Σ J : finitelyGeneratedSubgroupIndex G, finitelyGeneratedSubgroupIndex J.val)

abbrev smallCoefficientIndex := smallCoefficientBase G × G

def smallCoefficientFeature (i : smallCoefficientIndex G) (x : G) : Bool := by
  classical
  exact match i.1 with
    | .inl H => decide (subgroupRightPart H.val (i.2⁻¹ * x) = 1)
    | .inr JN => decide (subgroupRightPart JN.1.val (i.2⁻¹ * x) ∈ JN.2.val)

def smallCoefficientTranslate (g : G) (i : smallCoefficientIndex G) : smallCoefficientIndex G :=
  (i.1, g * i.2)

theorem smallCoefficientFeature_translate (g : G) (i : smallCoefficientIndex G) (x : G) :
    smallCoefficientFeature G i (g⁻¹ * x) =
      smallCoefficientFeature G (smallCoefficientTranslate G g i) x := by
  dsimp only [smallCoefficientFeature, smallCoefficientTranslate]
  simp only [mul_inv_rev, mul_assoc]

abbrev SmallCoefficientRing := booleanStepRing (smallCoefficientFeature G)

instance smallCoefficientRing_mulSemiringAction : MulSemiringAction G (SmallCoefficientRing G) :=
  booleanStepMulSemiringAction (smallCoefficientFeature G) (smallCoefficientTranslate G)
    (smallCoefficientFeature_translate G)

@[simp]
theorem smallCoefficientRing_smul_apply (g x : G) (f : SmallCoefficientRing G) :
    (g • f).val x = f.val (g⁻¹ * x) := rfl

instance smallCoefficientRing_integer_projective [Countable G] :
    Module.Projective ℤ (SmallCoefficientRing G) :=
  booleanStepRing_integer_projective (smallCoefficientFeature G)

/-- The indicator of the chosen transversal of a finite subgroup. -/
def smallCoefficientTransversal (H : Subgroup G) [Finite H] : SmallCoefficientRing G :=
  ⟨fun x => if smallCoefficientFeature G (Sum.inl ⟨H, inferInstance⟩, 1) x then 1 else 0,
    booleanStepRing_coordinate _ _⟩

@[simp]
theorem smallCoefficientTransversal_apply (H : Subgroup G) [Finite H] (x : G) :
    (smallCoefficientTransversal G H).val x =
      if subgroupRightPart H x = 1 then 1 else 0 := by
  classical
  simp [smallCoefficientTransversal, smallCoefficientFeature]

theorem smallCoefficientTransversal_trace_one (H : Subgroup G) [Fintype H] :
    (∑ h : H, (h : G) • smallCoefficientTransversal G H) = 1 := by
  classical
  apply Subtype.ext
  funext x
  change ((SmallCoefficientRing G).subtype
    (∑ h : H, (h : G) • smallCoefficientTransversal G H)) x = 1
  rw [map_sum, Finset.sum_apply]
  change (∑ h : H, ((h : G) • smallCoefficientTransversal G H).val x) = 1
  simp only [smallCoefficientRing_smul_apply, smallCoefficientTransversal_apply]
  have hpart (h : H) : subgroupRightPart H ((h : G)⁻¹ * x) = h⁻¹ * subgroupRightPart H x :=
    subgroupRightPart_mul H h⁻¹ x
  simp only [hpart, inv_mul_eq_one]
  simp

/-- The coefficient ring with its actual translation representation. -/
abbrev smallCoefficientRepresentation : Rep ℤ G :=
  ringActionRepresentation (H := G) (R := SmallCoefficientRing G)

theorem smallCoefficient_finite_subgroup_projective [Countable G]
    (H : Subgroup G) [Finite H] :
    Projective (Rep.res H.subtype (smallCoefficientRepresentation G)) := by
  let := Fintype.ofFinite H
  let := MulSemiringAction.compHom (SmallCoefficientRing G) H.subtype
  change Projective (ringActionRepresentation (H := H) (R := SmallCoefficientRing G))
  apply ringAction_projective_of_trace_one (smallCoefficientTransversal G H)
  exact smallCoefficientTransversal_trace_one G H

end PolycyclicRecognition

end

end OAI
