import OAI.Analysis.KadisonSimilarity.FreeProduct.GeneratedCompression
import OAI.Analysis.KadisonSimilarity.Tracial.TracialCornerHilbert
import OAI.Analysis.KadisonSimilarity.FreeProduct.SpectralArc

namespace OAI

/-! The narrow spectral arc has the required small norm in the original
algebra. Its creation model is applied on the closed algebra generated by
the two corner factors, with the normalized restricted trace. -/

noncomputable section
namespace KadisonSimilarity

variable {P H : Type*} [CStarAlgebra P]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

namespace CStarCorner

instance isClosed_subalgebra (p : P) (hp : IsStarProjection p)
    (A : StarSubalgebra ℂ P) (hpA : p ∈ A) [IsClosed (A : Set P)] :
    IsClosed (subalgebra p hp A hpA : Set (CStarCorner p hp)) :=
  (show IsClosed (A : Set P) from inferInstance).preimage continuous_subtype_val

end CStarCorner

namespace TracialCornerGeometry

variable (G : TracialCornerGeometry P H) (C D : StarSubalgebra ℂ P)
  [IsClosed (C : Set P)] [IsClosed (D : Set P)]
  (w d : Pˣ) (hp : IsStarProjection (dihedralHalfProjection d))
  (hpC : dihedralHalfProjection d ∈ C) (hpD : dihedralHalfProjection d ∈ D)
  (htp : G.trace (dihedralHalfProjection d) = (1 / 2 : ℂ))

/-- This is the ordinary normalized corner geometry before restriction to
the algebra generated by its two free factors. -/
def halfCornerGeometry :
    TracialCornerGeometry (CStarCorner (dihedralHalfProjection d) hp)
      (G.corner (dihedralHalfProjection d) (dihedralHalfProjection d)) :=
  G.normalizedCornerGeometry (dihedralHalfProjection d) hp (by norm_num : 0 < (1 / 2 : ℝ))
    (by simpa using htp)

variable
  (S : StarSubalgebra ℂ (CStarCorner (dihedralHalfProjection d) hp))
  [IsClosed (S : Set (CStarCorner (dihedralHalfProjection d) hp))]

/-- The published elementary creation model yields the actual `3u` norm
bound for the spectral test, with `u = 2t`. -/
theorem norm_spectral_arc_compression
    (hS : (factorAlgebra (CStarCorner.subalgebra (dihedralHalfProjection d) hp D hpD)
      (CStarCorner.subalgebra (dihedralHalfProjection d) hp C hpC)).topologicalClosure = S)
    (published : RicardXuCompressionInput
      ((G.halfCornerGeometry d hp htp).baseGeometry S)
      ((CStarCorner.subalgebra (dihedralHalfProjection d) hp D hpD).comap S.subtype)
      ((CStarCorner.subalgebra (dihedralHalfProjection d) hp C hpC).comap S.subtype))
    (hfaithful : Function.Injective G.vector)
    (hfree : ScalarFree (CStarCorner.normalizedTrace (dihedralHalfProjection d) hp G.trace)
      (CStarCorner.subalgebra (dihedralHalfProjection d) hp D hpD)
      (CStarCorner.subalgebra (dihedralHalfProjection d) hp C hpC))
    (hdC : (d : P) ∈ C)
    {θ : ℝ} (F : DihedralSpectralArc G.trace C w d θ)
    (hθ : 0 ≤ θ) (hπ : θ ≤ Real.pi)
    (e : CStarCorner (dihedralHalfProjection d) hp) (he : IsStarProjection e)
    (heD : (e : P) ∈ D) {t : ℝ} (ht : 0 ≤ t) (hte : G.trace (e : P) = (t : ℂ))
    (hwidth : 4 * θ ≤ 2 * t) :
    ‖(e : P) * (F.element * dihedralHalfProjection d) * (e : P)‖ ≤ 3 * (2 * t) := by
  let DA := CStarCorner.subalgebra (dihedralHalfProjection d) hp D hpD
  let CA := CStarCorner.subalgebra (dihedralHalfProjection d) hp C hpC
  have hDA : DA ≤ S := by
    rw [← hS]
    exact fun x hx => (StarSubalgebra.le_topologicalClosure _)
      (StarAlgebra.subset_adjoin ℂ _ (Or.inl hx))
  have hCA : CA ≤ S := by
    rw [← hS]
    exact fun x hx => (StarSubalgebra.le_topologicalClosure _)
      (StarAlgebra.subset_adjoin ℂ _ (Or.inr hx))
  let ee : DA := ⟨e, heD⟩
  let bb : CA := ⟨F.corner hp, F.corner_mem hp hdC⟩
  have hbself : star bb = bb := Subtype.ext (F.corner_selfAdjoint hp)
  have hb0 : (G.halfCornerGeometry d hp htp).trace (bb : CStarCorner _ hp) = 0 := by
    change (G.trace (dihedralHalfProjection d))⁻¹ * G.trace (F.corner hp : P) = 0
    rw [F.corner_trace_zero hp hθ hπ, mul_zero]
  have hetrace : (G.halfCornerGeometry d hp htp).trace (ee : CStarCorner _ hp) =
      ((2 * t : ℝ) : ℂ) := by
    change (G.trace (dihedralHalfProjection d))⁻¹ * G.trace (e : P) = _
    rw [htp, hte]
    push_cast
    ring
  have hb₂ : ((G.halfCornerGeometry d hp htp).trace
      (star (bb : CStarCorner _ hp) * (bb : CStarCorner _ hp))).re ≤ 2 * t :=
    (F.corner_second_moment_le hp htp hθ hπ).trans hwidth
  exact (G.halfCornerGeometry d hp htp).norm_narrow_compression_on_generated_algebra
    DA CA S hDA hCA hS published
    (G.normalizedCornerGeometry_trace_one _ hp (by norm_num : 0 < (1 / 2 : ℝ))
      (by simpa using htp))
    (G.normalizedCornerGeometry_vector_injective _ hp (by norm_num : 0 < (1 / 2 : ℝ))
      (by simpa using htp) hfaithful) hfree.symm ee he bb hbself hb0
    (mul_nonneg (by norm_num) ht) hetrace hb₂
    (F.corner_norm_le hp)

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
