import Mathlib.Tactic.DeriveFintype
import OAI.Computability.UniqueGames.Machines.MachineCopy
import OAI.Computability.UniqueGames.Machines.MachineSubroutineLemmas

namespace OAI


namespace PerfectCompleteness.SourceOccurrenceIndexMachine


open Turing
open UniqueGamesTheorem.Foundations.Complexity
open MachineComposition
open UniqueGamesTheorem.Reduction.MachineTransfer

variable {K Λ A : Type} [DecidableEq K]

abbrev Alphabet (_ : K) := Bool
abbrev State (A : Type) := A × Option Bool

def clean (ambient : A) : State A := (ambient, none)

inductive Label
  | copyOut
  | copyBack
  | delimiter
  deriving DecidableEq

/-- A list enumerating every element of the type, which are all zero-argument constructors. (Generated by the `Fintype` deriving handler.)-/
protected abbrev Label.enumList : List Label := [.copyOut, .copyBack, .delimiter]

protected theorem Label.enumList_getElem?_ctorIdx_eq (x : Label) :
    Label.enumList[x.ctorIdx]? = some x := by
  cases x <;> rfl

protected theorem Label.enumList_nodup : Label.enumList.Nodup := by decide

instance : Fintype Label where
  elems := ⟨Label.enumList, Label.enumList_nodup⟩
  complete x := by cases x <;> decide

def main : Label := .copyOut

def instruction (tape : Fin 3 → K) (labels : Label → Λ) (exit : Option Λ) :
    Label → TM2.Stmt (Alphabet (K := K)) Λ (State A)
  | .copyOut => loopAt (tape 0) (tape 1) id false
      (labels .copyOut) (some (labels .copyBack))
  | .copyBack => MachineCopy.forkLoop (tape 1) (tape 0) (tape 2) false
      (labels .copyBack) (some (labels .delimiter))
  | .delimiter => .push (tape 2) (fun _ => false) (exitAt (tape 2) exit)

def steps (index : Nat) : Nat := 2 * (index + 1) + 1

private theorem joinTrace {X : Type*} {f : X → X} {a b c : X} {n m : Nat}
    (first : f^[n] a = b) (second : f^[m] b = c) : f^[n + m] a = c := by
  rw [Nat.add_comm, Function.iterate_add_apply, first, second]

theorem indexTrace (tape : Fin 3 → K) (distinct : Function.Injective tape)
    (labels : Label → Λ) (exit : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabels : ∀ l, program (labels l) = instruction tape labels exit l)
    (base : K → List Bool) (ambient : A) (index : Nat)
    (counterWord : base (tape 0) = List.replicate index true)
    (scratchEmpty : base (tape 1) = []) :
    (advance (TM2.step program))^[steps index]
      (some ⟨some (labels main), clean ambient, base⟩) =
      some ⟨exit, clean ambient, Function.update base (tape 2)
        ((encodeWord index).reverse ++ base (tape 2))⟩ := by
  have hd (i j : Fin 3) (hne : i ≠ j) : tape i ≠ tape j := fun h => hne (distinct h)
  have copied := MachineCopy.copyTrace (tape 0) (tape 2) (tape 1)
    (hd 0 2 (by decide)) (hd 0 1 (by decide)) (hd 2 1 (by decide)) false
    (labels .copyOut) (labels .copyBack) (some (labels .delimiter)) program
    (atLabels .copyOut) (atLabels .copyBack) base scratchEmpty ambient none
  rw [counterWord, List.length_replicate] at copied
  have emitted : (advance (TM2.step program))^[1]
      (some ⟨some (labels .delimiter), clean ambient,
        Function.update base (tape 2) (List.replicate index true ++ base (tape 2))⟩) =
      some ⟨exit, clean ambient, Function.update base (tape 2)
        ((encodeWord index).reverse ++ base (tape 2))⟩ := by
    change some (TM2.stepAux (program (labels .delimiter)) _ _) = _
    rw [atLabels .delimiter]
    cases exit <;>
      simp [instruction, TM2.stepAux, exitAt, encodeWord, List.reverse_append,
        List.reverse_replicate]
  exact joinTrace copied emitted

def indexInTime (tape : Fin 3 → K) (distinct : Function.Injective tape)
    (labels : Label → Λ) (exit : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabels : ∀ l, program (labels l) = instruction tape labels exit l)
    (base : K → List Bool) (ambient : A) (index : Nat)
    (counterWord : base (tape 0) = List.replicate index true)
    (scratchEmpty : base (tape 1) = []) :
    StateTransition.EvalsToInTime (TM2.step program)
      ⟨some (labels main), clean ambient, base⟩
      (some ⟨exit, clean ambient, Function.update base (tape 2)
        ((encodeWord index).reverse ++ base (tape 2))⟩)
      (2 * (index + 1) + 1) where
  steps := steps index
  evals_in_steps := indexTrace tape distinct labels exit program atLabels base ambient index
    counterWord scratchEmpty
  steps_le_m := Nat.le_refl _

theorem label_finite : Finite Label := inferInstance

theorem state_finite [Finite A] : Finite (State A) := inferInstance

end PerfectCompleteness.SourceOccurrenceIndexMachine

end OAI
