import OAI.Computability.UniqueGames.Machines.MachineCopy
import OAI.Computability.UniqueGames.Machines.MachineSubroutineLemmas
import OAI.Computability.UniqueGames.Reduction.MachineSubstitution

namespace OAI


namespace PerfectCompleteness.TargetHeaderMachine


open Turing
open UniqueGamesTheorem.Foundations.Complexity
open MachineComposition
open UniqueGamesTheorem.Reduction.MachineTransfer (loopAt exitAt)
open UniqueGamesTheorem.Reduction.MachineSubstitution

abbrev Alphabet {K : Type} (_ : K) := Bool
abbrev State (A : Type) := A × Option Bool

inductive Label
  | copyLast | restoreLast | pushAlphabet
  | copyRight | restoreRight | copyLeft | restoreLeft
  deriving DecidableEq

/-- A list enumerating every element of the type, which are all zero-argument constructors. (Generated by the `Fintype` deriving handler.)-/
protected abbrev Label.enumList : List Label := [.copyLast, .restoreLast, .pushAlphabet,
  .copyRight, .restoreRight, .copyLeft, .restoreLeft]

protected theorem Label.enumList_getElem?_ctorIdx_eq (x : Label) :
    Label.enumList[x.ctorIdx]? = some x := by
  cases x <;> rfl

protected theorem Label.enumList_nodup : Label.enumList.Nodup := by decide

instance : Fintype Label where
  elems := ⟨Label.enumList, Label.enumList_nodup⟩
  complete x := by cases x <;> decide

def main : Label := .copyLast

variable {K Λ A : Type} [DecidableEq K]

def instruction (q : Nat) (tape : Fin 3 → K) (labels : Label → Λ)
    (done : Option Λ) : Label → TM2.Stmt (Alphabet (K := K)) Λ (State A)
  | .copyLast => loopAt (tape 0) (tape 1) id false (labels .copyLast)
      (some (labels .restoreLast))
  | .restoreLast => MachineCopy.forkLoop (tape 1) (tape 0) (tape 2) false
      (labels .restoreLast) (some (labels .pushAlphabet))
  | .pushAlphabet => pushWord (tape 2) (encodeWord q).reverse
      (.goto fun _ => labels .copyRight)
  | .copyRight => loopAt (tape 0) (tape 1) id false (labels .copyRight)
      (some (labels .restoreRight))
  | .restoreRight => MachineCopy.forkLoop (tape 1) (tape 0) (tape 2) false
      (labels .restoreRight) (some (labels .copyLeft))
  | .copyLeft => loopAt (tape 0) (tape 1) id false (labels .copyLeft)
      (some (labels .restoreLeft))
  | .restoreLeft => MachineCopy.forkLoop (tape 1) (tape 0) (tape 2) false
      (labels .restoreLeft) done

omit [DecidableEq K] in
theorem instruction_pushBound (q : Nat) (tape : Fin 3 → K) (labels : Label → Λ)
    (done : Option Λ) (label : Label) :
    Runtime.statementPushBound (instruction (A := A) q tape labels done label) ≤ q + 2 := by
  cases label <;> cases done <;>
    simp [instruction, loopAt, MachineCopy.forkLoop, exitAt,
      statementPushBound_pushWord, Runtime.statementPushBound]

theorem pushAlphabetStep (q : Nat) (tape : Fin 3 → K) (labels : Label → Λ)
    (done : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabel : program (labels .pushAlphabet) = instruction q tape labels done .pushAlphabet)
    (base : K → List Bool) (ambient : A) (register : Option Bool) :
    TM2.step program ⟨some (labels .pushAlphabet), (ambient, register), base⟩ =
      some ⟨some (labels .copyRight), (ambient, register),
        Function.update base (tape 2) (encodeWord q ++ base (tape 2))⟩ := by
  change some (TM2.stepAux (program (labels .pushAlphabet)) (ambient, register) base) = _
  rw [atLabel]
  simp only [instruction, stepAux_pushWord, List.reverse_reverse, TM2.stepAux]

private theorem joinTrace {X : Type*} {f : X → X} {a b c : X} {n m : Nat}
    (first : f^[n] a = b) (second : f^[m] b = c) : f^[n + m] a = c := by
  rw [Nat.add_comm, Function.iterate_add_apply, first, second]

theorem headerTrace (q : Nat) (tape : Fin 3 → K) (distinct : Function.Injective tape)
    (labels : Label → Λ) (done : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabels : ∀ label, program (labels label) = instruction q tape labels done label)
    (base : K → List Bool) (N : Nat) (sourceWord : base (tape 0) = encodeWord N)
    (scratchEmpty : base (tape 1) = []) (ambient : A) (register : Option Bool) :
    (advance (TM2.step program))^[6 * (N + 2) + 1]
      (some ⟨some (labels main), (ambient, register), base⟩) =
      some ⟨done, (ambient, none),
        Function.update base (tape 2) (encodeWords [N, N, q, N] ++ base (tape 2))⟩ := by
  have h02 : tape 0 ≠ tape 2 := fun h => (by decide : (0 : Fin 3) ≠ 2) (distinct h)
  have h01 : tape 0 ≠ tape 1 := fun h => (by decide : (0 : Fin 3) ≠ 1) (distinct h)
  have h21 : tape 2 ≠ tape 1 := fun h => (by decide : (2 : Fin 3) ≠ 1) (distinct h)
  let firstTapes := Function.update base (tape 2) (encodeWord N ++ base (tape 2))
  let literalTapes := Function.update firstTapes (tape 2)
    (encodeWord q ++ firstTapes (tape 2))
  let secondTapes := Function.update literalTapes (tape 2)
    (encodeWord N ++ literalTapes (tape 2))
  have first := MachineCopy.copyTrace (tape 0) (tape 2) (tape 1) h02 h01 h21 false
    (labels .copyLast) (labels .restoreLast) (some (labels .pushAlphabet)) program
    (atLabels .copyLast) (atLabels .restoreLast) base scratchEmpty ambient register
  rw [sourceWord, encodeWord_length] at first
  have literal : (advance (TM2.step program))^[1]
      (some ⟨some (labels .pushAlphabet), (ambient, none), firstTapes⟩) =
      some ⟨some (labels .copyRight), (ambient, none), literalTapes⟩ := by
    exact pushAlphabetStep q tape labels done program (atLabels .pushAlphabet)
      firstTapes ambient none
  have literalSource : literalTapes (tape 0) = encodeWord N := by
    simp [literalTapes, firstTapes, h02, sourceWord]
  have literalScratch : literalTapes (tape 1) = [] := by
    simp [literalTapes, firstTapes, Ne.symm h21, scratchEmpty]
  have second := MachineCopy.copyTrace (tape 0) (tape 2) (tape 1) h02 h01 h21 false
    (labels .copyRight) (labels .restoreRight) (some (labels .copyLeft)) program
    (atLabels .copyRight) (atLabels .restoreRight) literalTapes literalScratch ambient none
  rw [literalSource, encodeWord_length] at second
  have secondSource : secondTapes (tape 0) = encodeWord N := by
    simp [secondTapes, h02, literalSource]
  have secondScratch : secondTapes (tape 1) = [] := by
    simp [secondTapes, Ne.symm h21, literalScratch]
  have third := MachineCopy.copyTrace (tape 0) (tape 2) (tape 1) h02 h01 h21 false
    (labels .copyLeft) (labels .restoreLeft) done program
    (atLabels .copyLeft) (atLabels .restoreLeft) secondTapes secondScratch ambient none
  rw [secondSource, encodeWord_length] at third
  have all := joinTrace (joinTrace (joinTrace first literal) second) third
  have count : ((2 * (N + 1 + 1) + 1) + 2 * (N + 1 + 1)) +
      2 * (N + 1 + 1) = 6 * (N + 2) + 1 := by omega
  rw [count] at all
  simpa only [main, secondTapes, literalTapes, firstTapes,
    Function.update_self, Function.update_idem, encodeWords, List.append_nil,
    List.append_assoc] using all

def headerInTime (q : Nat) (tape : Fin 3 → K) (distinct : Function.Injective tape)
    (labels : Label → Λ) (done : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabels : ∀ label, program (labels label) = instruction q tape labels done label)
    (base : K → List Bool) (N : Nat) (sourceWord : base (tape 0) = encodeWord N)
    (scratchEmpty : base (tape 1) = []) (ambient : A) (register : Option Bool) :
    StateTransition.EvalsToInTime (TM2.step program)
      ⟨some (labels main), (ambient, register), base⟩
      (some ⟨done, (ambient, none),
        Function.update base (tape 2) (encodeWords [N, N, q, N] ++ base (tape 2))⟩)
      (6 * (N + 2) + 1) where
  steps := 6 * (N + 2) + 1
  evals_in_steps := headerTrace q tape distinct labels done program atLabels base N
    sourceWord scratchEmpty ambient register
  steps_le_m := Nat.le_refl _

def increment (count : K) (done : Option Λ) : TM2.Stmt (Alphabet (K := K)) Λ (State A) :=
  .push count (fun _ => true) (exitAt count done)

@[simp] theorem encodeWord_zero : encodeWord 0 = [false] := rfl

theorem incrementStep (count : K) (label : Λ) (done : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabel : program label = increment count done) (base : K → List Bool)
    (N : Nat) (sourceWord : base count = encodeWord N) (state : State A) :
    TM2.step program ⟨some label, state, base⟩ =
      some ⟨done, state, Function.update base count (encodeWord (N + 1))⟩ := by
  change some (TM2.stepAux (program label) state base) = _
  rw [atLabel]
  cases done <;>
    simp [increment, exitAt, TM2.stepAux, sourceWord, encodeWord,
      List.replicate_succ]

def incrementInTime (count : K) (label : Λ) (done : Option Λ)
    (program : Λ → TM2.Stmt (Alphabet (K := K)) Λ (State A))
    (atLabel : program label = increment count done) (base : K → List Bool)
    (N : Nat) (sourceWord : base count = encodeWord N) (state : State A) :
    StateTransition.EvalsToInTime (TM2.step program) ⟨some label, state, base⟩
      (some ⟨done, state, Function.update base count (encodeWord (N + 1))⟩) 1 where
  steps := 1
  evals_in_steps := incrementStep count label done program atLabel base N sourceWord state
  steps_le_m := Nat.le_refl _

theorem finiteState [Finite A] : Finite (State A) := inferInstance

omit [DecidableEq K] in
theorem finiteAlphabet (key : K) : Finite (Alphabet key) := by
  change Finite Bool
  infer_instance

end PerfectCompleteness.TargetHeaderMachine

end OAI
