import OAI.Analysis.KadisonSimilarity.FreeProduct.TracialHaarPerturbation

namespace OAI

/-! The constant-two matrix estimate for an algebra generated by a compact
unitary group. Haar averaging supplies an element of the commutant within
the scalar commutator bound. This is the finite type-I case of the manuscript. -/

noncomputable section
namespace KadisonSimilarity

open MeasureTheory

variable {H Γ : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [Group Γ] [MeasurableSpace Γ] [MeasurableMul Γ]

theorem commutator_matrix_bound_of_close_commutant
    (P : VonNeumannAlgebra H) (Y Z : H →L[ℂ] H) {δ : ℝ}
    (hclose : ‖Y - Z‖ ≤ δ)
    (hZ : ∀ a : H →L[ℂ] H, a ∈ P → commutator Z a = 0)
    (n : ℕ) (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H))
    (hX : ∀ i j, X i j ∈ P) :
    ‖commutator (amplify Y n) (matrixOperator X)‖ ≤ 2 * δ * ‖matrixOperator X‖ := by
  have hzero : commutator (amplify Z n) (matrixOperator X) = 0 := by
    rw [commutator_amplify_matrixOperator]
    have he : (fun i j => commutator Z (X i j)) =
        (0 : Matrix (Fin n) (Fin n) (H →L[ℂ] H)) := by
      funext i j
      exact hZ _ (hX i j)
    rw [he]
    ext ξ i
    simp [matrixOperator]
  have hdiff : amplify Y n - amplify Z n = amplify (Y - Z) n := by
    ext ξ i
    simp only [sub_apply, PiLp.sub_apply, amplify_apply]
  have hbound : ‖amplify Y n - amplify Z n‖ ≤ δ := by
    rw [hdiff]
    exact (norm_amplify_le (Y - Z) n).trans hclose
  have hb := norm_commutator_sub_le (amplify Y n) (amplify Z n) (matrixOperator X)
  rw [hzero, sub_zero] at hb
  exact hb.trans (mul_le_mul_of_nonneg_right
    (mul_le_mul_of_nonneg_left hbound (by norm_num)) (norm_nonneg (matrixOperator X)))

/-- The Haar integral gives the required approximation uniformly in matrix
size, as soon as commutation with the group implies commutation with P. -/
theorem compact_group_commutator_estimate
    (P : VonNeumannAlgebra H) (ν : Measure Γ)
    [IsProbabilityMeasure ν] [ν.IsMulLeftInvariant]
    (U : Γ →* (H →L[ℂ] H)) (hU : ∀ g, ‖U g‖ ≤ 1)
    (hmem : ∀ g, U g ∈ P)
    (hgenerate : ∀ Z : H →L[ℂ] H,
      (∀ g, commutator Z (U g) = 0) →
      ∀ a : H →L[ℂ] H, a ∈ P → commutator Z a = 0)
    (hintegrable : ∀ Y : H →L[ℂ] H,
      WeaklyIntegrable ν (unitaryConjugate U Y)) :
    CommutatorEstimate P 2 := by
  intro Y n X hX
  let Z := haarTwirl ν U hU Y (hintegrable Y)
  have hclose : ‖Y - Z‖ ≤ scalarCommutatorNorm P Y := by
    rw [norm_sub_rev]
    apply norm_haarTwirl_sub_le ν U hU Y (hintegrable Y)
      (scalarCommutatorNorm_nonneg P Y)
    intro g
    exact (norm_commutator_le_scalarCommutatorNorm P Y (U g) (hmem g)).trans
      (mul_le_of_le_one_right (scalarCommutatorNorm_nonneg P Y) (hU g))
  have hZ : ∀ a : H →L[ℂ] H, a ∈ P → commutator Z a = 0 := by
    apply hgenerate Z
    exact fun g => haarTwirl_commute ν U hU Y (hintegrable Y) g
  exact commutator_matrix_bound_of_close_commutant P Y Z hclose hZ n X hX

/-- Double-commutant generation supplies the generation condition used by
Haar averaging, without a separate operator-invariance hypothesis. -/
theorem compact_generated_algebra_estimate
    (P : VonNeumannAlgebra H) (ν : Measure Γ)
    [IsProbabilityMeasure ν] [ν.IsMulLeftInvariant]
    (U : Γ →* (H →L[ℂ] H)) (hU : ∀ g, ‖U g‖ ≤ 1)
    (hmem : ∀ g, U g ∈ P)
    (hgenerate : (P : Set (H →L[ℂ] H)) =
      Set.centralizer (Set.centralizer (Set.range U)))
    (hintegrable : ∀ Y : H →L[ℂ] H,
      WeaklyIntegrable ν (unitaryConjugate U Y)) :
    CommutatorEstimate P 2 := by
  apply compact_group_commutator_estimate P ν U hU hmem ?_ hintegrable
  intro Z hZ a ha
  have hZcentral : Z ∈ Set.centralizer (Set.range U) := by
    rintro x ⟨g, rfl⟩
    exact (sub_eq_zero.mp (hZ g)).symm
  change a ∈ (P : Set (H →L[ℂ] H)) at ha
  rw [hgenerate] at ha
  exact sub_eq_zero.mpr (ha Z hZcentral)

end KadisonSimilarity

end

end OAI
