import OAI.Analysis.KadisonSimilarity.Representation.SeparableRepresentationTests
import Mathlib.Algebra.Group.Submonoid.Membership
import Mathlib.Topology.Algebra.Module.Basic

namespace OAI

/-! # A separable C-star algebra generating a separably represented algebra

The complex linear span of the words in a countable family and its adjoints
is separable. Its norm closure is therefore a separable C-star algebra.
Applying this to the countable weakly dense contraction tests gives an
actual norm-separable C-star subalgebra whose bicommutant is the original
von Neumann algebra.
-/

noncomputable section
namespace KadisonSimilarity

open ContinuousLinearMapWOT
open scoped Topology Pointwise

variable {A : Type*} [CStarAlgebra A]

/-- Words in a countable generating set and its adjoints span a separable
complex star algebra. -/
theorem isSeparable_starAlgebra_adjoin {s : Set A} (hs : s.Countable) :
    TopologicalSpace.IsSeparable (StarAlgebra.adjoin ℂ s : Set A) := by
  have hstar : (star s).Countable := by
    rw [← Set.image_star]
    exact hs.image star
  have hunion := hs.union hstar
  let : Countable {x : A // x ∈ s ∪ star s} := hunion.to_subtype
  have hwords : (Submonoid.closure (s ∪ star s) : Set A).Countable := by
    rw [Submonoid.closure_eq_mrange, MonoidHom.coe_mrange]
    exact Set.countable_range _
  change TopologicalSpace.IsSeparable
    ((StarAlgebra.adjoin ℂ s).toSubalgebra.toSubmodule : Set A)
  rw [StarAlgebra.adjoin_eq_span]
  exact hwords.isSeparable.span

/-- The concrete norm-closed C-star algebra generated by a sequence. -/
abbrev sequenceGeneratedCStarAlgebra (g : ℕ → A) : StarSubalgebra ℂ A :=
  (StarAlgebra.adjoin ℂ (Set.range g)).topologicalClosure

instance sequenceGeneratedCStarAlgebra_isClosed (g : ℕ → A) :
    IsClosed (sequenceGeneratedCStarAlgebra g : Set A) :=
  StarSubalgebra.isClosed_topologicalClosure _

instance sequenceGeneratedCStarAlgebra_separable (g : ℕ → A) :
    TopologicalSpace.SeparableSpace (sequenceGeneratedCStarAlgebra g) := by
  apply TopologicalSpace.IsSeparable.separableSpace
  exact (isSeparable_starAlgebra_adjoin (Set.countable_range g)).closure

theorem mem_sequenceGeneratedCStarAlgebra (g : ℕ → A) (n : ℕ) :
    g n ∈ sequenceGeneratedCStarAlgebra g :=
  (StarSubalgebra.le_topologicalClosure _)
    (StarAlgebra.subset_adjoin ℂ (Set.range g) (Set.mem_range_self n))

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A concrete von Neumann algebra contains the weak closure of any of its
subsets, proved directly from commutation with its commutant. -/
theorem mem_vonNeumannAlgebra_of_mem_weakClosure
    (P : VonNeumannAlgebra H) (S : Set (H →L[ℂ] H)) (hS : S ⊆ P)
    (T : H →L[ℂ] H) (hT : ofCLM T ∈ closure (ofCLM '' S)) : T ∈ P := by
  rw [← P.commutant_commutant]
  apply VonNeumannAlgebra.mem_commutant_iff.mpr
  intro R hR
  have hc : IsClosed {X : H →WOT[ℂ] H | ofCLM R * X = X * ofCLM R} :=
    isClosed_eq (continuous_const_mul _) (continuous_mul_const _)
  have hs : ofCLM '' S ⊆ {X : H →WOT[ℂ] H | ofCLM R * X = X * ofCLM R} := by
    rintro _ ⟨X, hX, rfl⟩
    exact congrArg ofCLM ((VonNeumannAlgebra.mem_commutant_iff.mp hR) X (hS hX)).symm
  exact congrArg toCLM (closure_minimal hs hc hT)

/-- A norm-closed star subalgebra contained in `P`, containing a weakly dense
family of contractions, has bicommutant exactly `P`. -/
theorem representationVonNeumannAlgebra_subtype_eq_of_dense_tests
    (P : VonNeumannAlgebra H) (B : StarSubalgebra ℂ (H →L[ℂ] H))
    [IsClosed (B : Set (H →L[ℂ] H))]
    (hB : B ≤ P.toStarSubalgebra) (g : ℕ → H →L[ℂ] H) (hg : ∀ n, g n ∈ B)
    (hdense : ∀ T : H →L[ℂ] H, T ∈ P → ‖T‖ ≤ 1 →
      ofCLM T ∈ closure (Set.range fun n => ofCLM (g n))) :
    representationVonNeumannAlgebra B.subtype = P := by
  let Q := representationVonNeumannAlgebra B.subtype
  apply VonNeumannAlgebra.ext
  intro T
  constructor
  · intro hT
    rw [← P.commutant_commutant]
    apply VonNeumannAlgebra.mem_commutant_iff.mpr
    intro R hR
    have hT' : T ∈ Set.centralizer (Set.centralizer
        (B.subtype.range : Set (H →L[ℂ] H))) := by
      simpa only [← SetLike.mem_coe, coe_representationVonNeumannAlgebra] using hT
    apply hT' R
    rintro _ ⟨b, rfl⟩
    exact (VonNeumannAlgebra.mem_commutant_iff.mp hR) b (hB b.property)
  · intro hT
    by_cases hz : T = 0
    · rw [hz, ← SetLike.mem_coe, coe_representationVonNeumannAlgebra]
      intro R _
      simp
    let c : ℂ := (‖T‖ : ℂ)⁻¹
    have hnorm : ‖c • T‖ ≤ 1 := by
      simp only [c, norm_smul, norm_inv, Complex.norm_real, Real.norm_eq_abs,
        abs_of_nonneg (norm_nonneg T), inv_mul_cancel₀ (norm_ne_zero_iff.mpr hz), le_refl]
    have hC : c • T ∈ Q := by
      apply mem_vonNeumannAlgebra_of_mem_weakClosure Q (Set.range g)
      · rintro _ ⟨n, rfl⟩
        exact mem_representationVonNeumannAlgebra B.subtype ⟨g n, hg n⟩
      · simpa only [Set.range_comp'] using
          hdense (c • T) (P.toStarSubalgebra.smul_mem hT c) hnorm
    have hback : (‖T‖ : ℂ) • (c • T) = T := by
      rw [smul_smul]
      simp only [c, mul_inv_cancel₀ (Complex.ofReal_ne_zero.mpr (norm_ne_zero_iff.mpr hz)),
        one_smul]
    rw [← hback]
    exact Q.toStarSubalgebra.smul_mem hC _

/-- Every concretely separably represented von Neumann algebra is the
bicommutant of an actual norm-separable unital C-star subalgebra. -/
theorem exists_separable_generating_cstar_subalgebra
    [TopologicalSpace.SeparableSpace H] (P : VonNeumannAlgebra H) :
    ∃ B : StarSubalgebra ℂ (H →L[ℂ] H),
      IsClosed (B : Set (H →L[ℂ] H)) ∧ TopologicalSpace.SeparableSpace B ∧
      B ≤ P.toStarSubalgebra ∧ (starSubalgebraCommutant B).commutant = P := by
  obtain ⟨test, _, hdense⟩ := exists_separable_contraction_tests P
  let g : ℕ → H →L[ℂ] H := fun n => test n
  let B := sequenceGeneratedCStarAlgebra g
  have hPclosed : IsClosed (P.toStarSubalgebra : Set (H →L[ℂ] H)) := by
    change IsClosed (P : Set (H →L[ℂ] H))
    rw [← P.centralizer_centralizer]
    exact Set.isClosed_centralizer _
  have hB : B ≤ P.toStarSubalgebra := by
    apply StarSubalgebra.topologicalClosure_minimal _ hPclosed
    apply StarAlgebra.adjoin_le
    rintro _ ⟨n, rfl⟩
    exact (test n).property
  refine ⟨B, inferInstance, inferInstance, hB, ?_⟩
  have hmain := representationVonNeumannAlgebra_subtype_eq_of_dense_tests P B hB g
    (mem_sequenceGeneratedCStarAlgebra g) hdense
  have hrange : B.subtype.range = B := by
    ext x
    constructor
    · rintro ⟨b, rfl⟩
      exact b.property
    · intro hx
      exact ⟨⟨x, hx⟩, rfl⟩
  simpa only [representationVonNeumannAlgebra, hrange] using hmain

end KadisonSimilarity

end

end OAI
