import OAI.Analysis.KadisonSimilarity.Representation.DiagonalFieldAlgebra
import OAI.Analysis.KadisonSimilarity.Tracial.MatrixVonNeumannRange

namespace OAI

/-! # Commutants of genuine fiber representations

A global commutation relation passes to the operator fields by their action
on all L² vectors. Norm separability then gives one conull set on which the
field commutes with the entire represented algebra, and hence its bicommutant.
-/

noncomputable section
namespace KadisonSimilarity

open MeasureTheory Filter
open scoped CStarAlgebra

variable {Ω H : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsFiniteMeasure μ]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [TopologicalSpace.SeparableSpace H]

omit [CompleteSpace H] in
/-- Commuting L² operators have commuting fields almost everywhere. -/
theorem pointwise_field_commute
    (T S : Lp H 2 μ →L[ℂ] Lp H 2 μ) (R Q : Ω → H →L[ℂ] H)
    (hR : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ, T f a = R a (f a))
    (hQ : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ, S f a = Q a (f a))
    (hcomm : T * S = S * T) :
    ∀ᵐ a ∂μ, R a * Q a = Q a * R a := by
  have hrev : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ,
      (T * S) f a = (Q a * R a) (f a) := by
    intro f
    rw [hcomm]
    filter_upwards [hQ (T f), hR f] with a hq hr
    simp only [mul_apply_eq_comp, hq, hr]
  filter_upwards [pointwise_field_mul μ T S R Q (fun a => Q a * R a)
    hR hQ hrev] with a ha
  exact ha.symm

variable {A : Type*} [CStarAlgebra A] [TopologicalSpace.SeparableSpace A]

/-- A countable dense family of algebra elements makes the exceptional set
independent of the element of the algebra. -/
theorem ae_commutes_fiber_representation
    (σ : A →⋆ₐ[ℂ] (Lp H 2 μ →L[ℂ] Lp H 2 μ))
    (ρ : ∀ _a : Ω, A →⋆ₐ[ℂ] (H →L[ℂ] H))
    (T : Lp H 2 μ →L[ℂ] Lp H 2 μ) (R : Ω → H →L[ℂ] H)
    (hσ : ∀ b : A, ∀ f : Lp H 2 μ,
      ∀ᵐ a ∂μ, σ b f a = ρ a b (f a))
    (hR : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ, T f a = R a (f a))
    (hcomm : ∀ b : A, T * σ b = σ b * T) :
    ∀ᵐ a ∂μ, ∀ b : A, R a * ρ a b = ρ a b * R a := by
  have hdense : ∀ᵐ a ∂μ, ∀ n : ℕ,
      R a * ρ a (TopologicalSpace.denseSeq A n) =
        ρ a (TopologicalSpace.denseSeq A n) * R a :=
    eventually_countable_forall.mpr fun n =>
      pointwise_field_commute μ T (σ (TopologicalSpace.denseSeq A n)) R
        (fun a => ρ a (TopologicalSpace.denseSeq A n)) hR
        (hσ (TopologicalSpace.denseSeq A n)) (hcomm _)
  filter_upwards [hdense] with a ha
  have heq : (fun b : A => R a * ρ a b) = (fun b : A => ρ a b * R a) :=
    (TopologicalSpace.denseRange_denseSeq A).equalizer
      (by fun_prop) (by fun_prop) (funext ha)
  exact fun b => congrFun heq b

/-- The same field belongs almost everywhere to the commutant of the
von Neumann algebra generated by the genuine fiber representation. -/
theorem ae_mem_fiber_representation_commutant
    (σ : A →⋆ₐ[ℂ] (Lp H 2 μ →L[ℂ] Lp H 2 μ))
    (ρ : ∀ _a : Ω, A →⋆ₐ[ℂ] (H →L[ℂ] H))
    (T : Lp H 2 μ →L[ℂ] Lp H 2 μ) (R : Ω → H →L[ℂ] H)
    (hσ : ∀ b : A, ∀ f : Lp H 2 μ,
      ∀ᵐ a ∂μ, σ b f a = ρ a b (f a))
    (hR : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ, T f a = R a (f a))
    (hcomm : ∀ b : A, T * σ b = σ b * T) :
    ∀ᵐ a ∂μ, R a ∈ (representationVonNeumannAlgebra (ρ a)).commutant := by
  filter_upwards [ae_commutes_fiber_representation μ σ ρ T R hσ hR hcomm] with a ha
  apply (mem_representation_commutant_iff (ρ a) (R a)).mpr
  rintro _ ⟨b, rfl⟩
  exact (ha b).symm

omit [CompleteSpace H] in
/-- The field commutation argument also works on a measurable restricted
base, while the original operators still act on L² of the full base. -/
theorem pointwise_field_commute_on
    (s : Set Ω) (hs : MeasurableSet s)
    (T S : Lp H 2 μ →L[ℂ] Lp H 2 μ) (R Q : s → H →L[ℂ] H)
    (hR : ∀ f : Lp H 2 μ,
      ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, T f a = R a (f a))
    (hQ : ∀ f : Lp H 2 μ,
      ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, S f a = Q a (f a))
    (hcomm : T * S = S * T) :
    ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, R a * Q a = Q a * R a := by
  apply ae_operator_eq_of_forall_vectors
  intro x
  let f : Lp H 2 μ := Lp.const 2 μ x
  have hf : ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, f a = x :=
    (ae_restrict_iff_subtype hs).mp (ae_restrict_of_ae (Lp.coeFn_const 2 μ x))
  filter_upwards [hR (S f), hQ (T f), hR f, hQ f, hf] with a hrs hqt hr hq hx
  have h := congrArg (fun U : Lp H 2 μ →L[ℂ] Lp H 2 μ => U f a) hcomm
  simpa only [mul_apply_eq_comp, hrs, hqt, hr, hq, hx] using h

/-- Genuine fiber representations need only exist on their measurable
conull base. No representation on the exceptional complement is used.
The conclusion remains valid for any measurable restricted base. -/
theorem ae_commutes_restricted_fiber_representation
    (s : Set Ω) (hs : MeasurableSet s)
    (σ : A →⋆ₐ[ℂ] (Lp H 2 μ →L[ℂ] Lp H 2 μ))
    (ρ : ∀ _a : s, A →⋆ₐ[ℂ] (H →L[ℂ] H))
    (T : Lp H 2 μ →L[ℂ] Lp H 2 μ) (R : Ω → H →L[ℂ] H)
    (hσ : ∀ b : A, ∀ f : Lp H 2 μ,
      ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, σ b f a = ρ a b (f a))
    (hR : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ, T f a = R a (f a))
    (hcomm : ∀ b : A, T * σ b = σ b * T) :
    ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ,
      ∀ b : A, R a * ρ a b = ρ a b * R a := by
  have hRon : ∀ f : Lp H 2 μ,
      ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, T f a = R a (f a) :=
    fun f => (ae_restrict_iff_subtype hs).mp (ae_restrict_of_ae (hR f))
  have hdense : ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, ∀ n : ℕ,
      R a * ρ a (TopologicalSpace.denseSeq A n) =
        ρ a (TopologicalSpace.denseSeq A n) * R a :=
    eventually_countable_forall.mpr fun n =>
      pointwise_field_commute_on μ s hs T (σ (TopologicalSpace.denseSeq A n))
        (fun a => R a) (fun a => ρ a (TopologicalSpace.denseSeq A n)) hRon
        (hσ (TopologicalSpace.denseSeq A n)) (hcomm _)
  filter_upwards [hdense] with a ha
  have heq : (fun b : A => R a * ρ a b) = (fun b : A => ρ a b * R a) :=
    (TopologicalSpace.denseRange_denseSeq A).equalizer
      (by fun_prop) (by fun_prop) (funext ha)
  exact fun b => congrFun heq b

/-- Restricted-base form of the fiber bicommutant-commutant conclusion. -/
theorem ae_mem_restricted_fiber_representation_commutant
    (s : Set Ω) (hs : MeasurableSet s)
    (σ : A →⋆ₐ[ℂ] (Lp H 2 μ →L[ℂ] Lp H 2 μ))
    (ρ : ∀ _a : s, A →⋆ₐ[ℂ] (H →L[ℂ] H))
    (T : Lp H 2 μ →L[ℂ] Lp H 2 μ) (R : Ω → H →L[ℂ] H)
    (hσ : ∀ b : A, ∀ f : Lp H 2 μ,
      ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ, σ b f a = ρ a b (f a))
    (hR : ∀ f : Lp H 2 μ, ∀ᵐ a ∂μ, T f a = R a (f a))
    (hcomm : ∀ b : A, T * σ b = σ b * T) :
    ∀ᵐ a : s ∂Measure.comap ((↑) : s → Ω) μ,
      R a ∈ (representationVonNeumannAlgebra (ρ a)).commutant := by
  filter_upwards [ae_commutes_restricted_fiber_representation μ s hs σ ρ T R
    hσ hR hcomm] with a ha
  apply (mem_representation_commutant_iff (ρ a) (R a)).mpr
  rintro _ ⟨b, rfl⟩
  exact (ha b).symm

end KadisonSimilarity

end

end OAI
