import OAI.Analysis.KadisonSimilarity.Similarity.FiniteCyclicSimilarity
import OAI.Analysis.KadisonSimilarity.Derivation.BoundedHomRestriction

namespace OAI

/-! The closed invariant subspace generated by finitely many vectors is
finitely cyclic, and therefore its restricted representation is similar. -/

noncomputable section
namespace KadisonSimilarity

variable {A H : Type*} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

def finiteOrbitSubspace (π : BoundedUnitalHom A H) {n : ℕ} (ξ : Fin n → H) :
    ClosedSubmodule ℂ H := (LinearMap.range (finiteOrbitMap π ξ)).closure

omit [PartialOrder A] [StarOrderedRing A] [CompleteSpace H] in
theorem finiteOrbitSubspace_invariant (π : BoundedUnitalHom A H)
    {n : ℕ} (ξ : Fin n → H) (a : A) (x : H) (hx : x ∈ finiteOrbitSubspace π ξ) :
    π.1 a x ∈ finiteOrbitSubspace π ξ := by
  have hm : Set.MapsTo (π.1 a) (Set.range (finiteOrbitMap π ξ))
      (Set.range (finiteOrbitMap π ξ)) := by
    rintro y ⟨b, rfl⟩
    refine ⟨fun i => a * b i, ?_⟩
    simp only [finiteOrbitMap, LinearMap.coe_mk, AddHom.coe_mk, map_mul,
      mul_apply_eq_comp, map_sum]
  exact hm.closure (π.1 a).continuous hx

omit [PartialOrder A] [StarOrderedRing A] [CompleteSpace H] in
theorem mem_finiteOrbitSubspace (π : BoundedUnitalHom A H)
    {n : ℕ} (ξ : Fin n → H) (i : Fin n) : ξ i ∈ finiteOrbitSubspace π ξ := by
  apply (LinearMap.range (finiteOrbitMap π ξ)).le_topologicalClosure
  refine ⟨Pi.single i 1, ?_⟩
  simp [finiteOrbitMap, Pi.single_apply, apply_ite, ite_apply]

def finiteOrbitGenerators (π : BoundedUnitalHom A H) {n : ℕ} (ξ : Fin n → H) :
    Fin n → finiteOrbitSubspace π ξ := fun i => ⟨ξ i, mem_finiteOrbitSubspace π ξ i⟩

omit [PartialOrder A] [StarOrderedRing A] in
theorem finiteOrbitSubspace_cyclic (π : BoundedUnitalHom A H) {n : ℕ} (ξ : Fin n → H) :
    DenseRange (finiteOrbitMap
      (restrictBoundedHom π (finiteOrbitSubspace π ξ) (finiteOrbitSubspace_invariant π ξ))
      (finiteOrbitGenerators π ξ)) := by
  let M := finiteOrbitSubspace π ξ
  let F := finiteOrbitMap π ξ
  let e : (Fin n → A) →ₗ[ℂ] M := F.codRestrict M.toSubmodule
    (fun a => (LinearMap.range F).le_topologicalClosure ⟨a, rfl⟩)
  have he : DenseRange e := by
    change Dense (Set.range e)
    rw [Subtype.dense_iff, ← Set.range_comp]
    change closure (Set.range F) ⊆ closure (Set.range F)
    exact Set.Subset.rfl
  have heq : finiteOrbitMap
      (restrictBoundedHom π (finiteOrbitSubspace π ξ) (finiteOrbitSubspace_invariant π ξ))
      (finiteOrbitGenerators π ξ) = e := by
    apply LinearMap.ext
    intro a
    apply Subtype.ext
    simp [finiteOrbitMap, e, F, finiteOrbitGenerators, restrictBoundedHom_apply]
    rfl
  rw [heq]
  exact he

theorem finiteOrbitSubspace_similar (π : BoundedUnitalHom A H) {n : ℕ} (hn : 0 < n)
    (ξ : Fin n → H) :
    SimilarToStar A (finiteOrbitSubspace π ξ)
      (restrictBoundedHom π (finiteOrbitSubspace π ξ) (finiteOrbitSubspace_invariant π ξ)) :=
  finitely_cyclic_similarity _ hn (finiteOrbitGenerators π ξ) (finiteOrbitSubspace_cyclic π ξ)

end KadisonSimilarity

end

end OAI
