import OAI.Analysis.KadisonSimilarity.Representation.SeparableReducingTest
import OAI.Analysis.KadisonSimilarity.Representation.ScalarKaplansky
import OAI.Analysis.KadisonSimilarity.Representation.ReducingRepresentationTransfer
import Mathlib.Topology.Algebra.StarSubalgebra

namespace OAI

/-! # Removing separability from the uniform commutator estimate

Each operator-norm test involves finitely many matrix entries and finitely
many vectors. Their common reducing subspace is separable. We restrict the
actual C-star algebra generated by those entries, use the two-vector
Kaplansky specialization to reach its bicommutant, and recover the original
vector test by the isometric inclusion.
-/

noncomputable section
universe u
namespace KadisonSimilarity
open scoped ComplexOrder

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The norm-closed C-star algebra generated by the entries of one test. -/
def finiteMatrixTestAlgebra {n : ℕ} (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H)) :
    StarSubalgebra ℂ (H →L[ℂ] H) :=
  (StarAlgebra.adjoin ℂ (Set.range (fun ij : Fin n × Fin n => X ij.1 ij.2))).topologicalClosure

instance finiteMatrixTestAlgebra_closed {n : ℕ}
    (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H)) :
    IsClosed (finiteMatrixTestAlgebra X : Set (H →L[ℂ] H)) :=
  StarSubalgebra.isClosed_topologicalClosure _

theorem matrix_entry_mem_test_algebra {n : ℕ}
    (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H)) (i j : Fin n) :
    X i j ∈ finiteMatrixTestAlgebra X :=
  StarSubalgebra.le_topologicalClosure _
    (StarAlgebra.subset_adjoin ℂ _ ⟨(i, j), rfl⟩)

theorem finiteMatrixTestAlgebra_le {n : ℕ}
    (P : VonNeumannAlgebra H) (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H))
    (hX : ∀ i j, X i j ∈ P) : finiteMatrixTestAlgebra X ≤ P.toStarSubalgebra := by
  apply StarSubalgebra.topologicalClosure_minimal
  · apply StarAlgebra.adjoin_le
    rintro _ ⟨⟨i, j⟩, rfl⟩
    exact hX i j
  · change IsClosed P.carrier
    rw [← P.centralizer_centralizer']
    exact Set.isClosed_centralizer _

/-- A common reducing space for the entries reduces their generated algebra. -/
theorem finiteMatrixTestAlgebra_invariant {n : ℕ}
    (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H)) (M : ClosedSubmodule ℂ H)
    (hX : ∀ i j, Commute M.toSubmodule.starProjection (X i j)) :
    ∀ a : finiteMatrixTestAlgebra X, ∀ x : H, x ∈ M → (a : H →L[ℂ] H) x ∈ M := by
  let q := M.toSubmodule.starProjection
  have hqstar : star q = q := isSelfAdjoint_starProjection M.toSubmodule
  have hle : finiteMatrixTestAlgebra X ≤ StarSubalgebra.centralizer ℂ {q} := by
    apply StarSubalgebra.topologicalClosure_minimal
    · apply StarAlgebra.adjoin_le
      rintro _ ⟨⟨i, j⟩, rfl⟩
      apply (StarSubalgebra.mem_centralizer_iff ℂ).mpr
      intro g hg
      obtain rfl := Set.mem_singleton_iff.mp hg
      exact ⟨(hX i j).eq, by simpa only [hqstar] using (hX i j).eq⟩
    · exact Set.isClosed_centralizer _
  intro a x hx
  have hcomm : q * (a : H →L[ℂ] H) = (a : H →L[ℂ] H) * q :=
    ((StarSubalgebra.mem_centralizer_iff ℂ).mp (hle a.property) q (Set.mem_singleton q)).1
  apply Submodule.starProjection_eq_self_iff.mp
  have h := congrArg (fun T : H →L[ℂ] H => T x) hcomm
  change q ((a : H →L[ℂ] H) x) = _
  have hfix : q x = x := Submodule.starProjection_eq_self_iff.mpr hx
  simpa only [mul_apply_eq_comp, hfix] using h

/-- Restriction of an invariant star subalgebra to the closed subspace. -/
def invariantStarRepresentation (B : StarSubalgebra ℂ (H →L[ℂ] H))
    (M : ClosedSubmodule ℂ H)
    (hM : ∀ a : B, ∀ x : H, x ∈ M → (a : H →L[ℂ] H) x ∈ M) :
    B →⋆ₐ[ℂ] (M →L[ℂ] M) where
  toFun a := (a : H →L[ℂ] H).restrict (hM a)
  map_zero' := by ext x; simp
  map_one' := by ext x; simp
  map_add' a b := by ext x; simp
  map_mul' a b := by ext x; simp [mul_apply_eq_comp]
  commutes' c := by ext x; simp [Algebra.algebraMap_eq_smul_one]
  map_star' a := by
    let : CompleteSpace M.toSubmodule := M.isClosed.completeSpace_coe
    apply ContinuousLinearMap.ext
    intro x
    apply ext_inner_left ℂ
    intro y
    change inner ℂ (y : H) ((star a : H →L[ℂ] H) (x : H)) =
      inner ℂ y (((a : H →L[ℂ] H).restrict (hM a)).adjoint x)
    rw [ContinuousLinearMap.adjoint_inner_right]
    exact ContinuousLinearMap.adjoint_inner_right _ _ _

@[simp] theorem invariantStarRepresentation_apply
    (B : StarSubalgebra ℂ (H →L[ℂ] H)) (M : ClosedSubmodule ℂ H)
    (hM : ∀ a : B, ∀ x : H, x ∈ M → (a : H →L[ℂ] H) x ∈ M)
    (a : B) (x : M) : (invariantStarRepresentation B M hM a x : H) = a.val x := rfl

/-- A fixed finite test fits in a separable reducing subspace. -/
theorem exists_matrix_test_reducing_space {n : ℕ}
    (Y : H →L[ℂ] H) (X : Matrix (Fin n) (Fin n) (H →L[ℂ] H))
    (ξ : HilbertCopies H n) :
    ∃ M : ClosedSubmodule ℂ H, TopologicalSpace.SeparableSpace M ∧
      (∀ i, ξ i ∈ M) ∧ (∀ x, x ∈ M → Y x ∈ M) ∧
      (∀ i j, Commute M.toSubmodule.starProjection (X i j)) := by
  let e := Fintype.equivFin (Option (Fin n × Fin n))
  let T : Fin (Fintype.card (Option (Fin n × Fin n))) → H →L[ℂ] H := fun k =>
    match e.symm k with
    | none => Y
    | some ij => X ij.1 ij.2
  obtain ⟨M, hsep, hξ, hinv, _, hcomm⟩ := exists_separable_reducing_test_space T (fun i => ξ i)
  refine ⟨M, hsep, hξ, ?_, ?_⟩
  · intro x hx
    simpa only [T, Equiv.symm_apply_apply] using hinv (e none) x hx
  · intro i j
    simpa only [T, Equiv.symm_apply_apply] using hcomm (e (some (i, j)))

/-- The separable version of the actual universal von Neumann estimate. -/
def SeparableUniformCommutatorEstimate (C : ℝ) : Prop :=
  ∀ (K : Type u) [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
    [TopologicalSpace.SeparableSpace K] (P : VonNeumannAlgebra K), CommutatorEstimate P C

/-- Blackadar I.9.1.3 and C-star quotient norm lifting, only on two test
vectors in a separable represented Hilbert space. This is the exact
published closure input used in the reduction below. -/
def SeparableTwoVectorKaplanskyInput : Prop :=
  ∀ (K : Type u) [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]
    [TopologicalSpace.SeparableSpace K] (A : Type u) [CStarAlgebra A]
    [PartialOrder A] [StarOrderedRing A] (σ : A →⋆ₐ[ℂ] (K →L[ℂ] K)),
      TwoVectorKaplanskyInput σ (representationVonNeumannAlgebra σ)

omit [CompleteSpace H] in
private theorem norm_mapCopies_subtype (M : ClosedSubmodule ℂ H) (n : ℕ)
    (ξ : HilbertCopies M n) :
    ‖mapCopies M.toSubmodule.subtypeL n ξ‖ = ‖ξ‖ := by
  apply (sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)).mp
  rw [PiLp.norm_sq_eq_of_L2, PiLp.norm_sq_eq_of_L2]
  rfl

omit [CompleteSpace H] in
private theorem intertwines_commutator {K : Type*}
    [NormedAddCommGroup K] [NormedSpace ℂ K]
    (I : K →L[ℂ] H) (Y₀ X₀ : K →L[ℂ] K) (Y X : H →L[ℂ] H)
    (hY : I.comp Y₀ = Y.comp I) (hX : I.comp X₀ = X.comp I) :
    I.comp (commutator Y₀ X₀) = (commutator Y X).comp I := by
  have hy z : I (Y₀ z) = Y (I z) := congrArg (fun T : K →L[ℂ] H => T z) hY
  have hx z : I (X₀ z) = X (I z) := congrArg (fun T : K →L[ℂ] H => T z) hX
  ext z
  change I (Y₀ (X₀ z) - X₀ (Y₀ z)) = Y (X (I z)) - X (Y (I z))
  rw [map_sub, hy, hx, hx, hy]

/-- The uniform estimate on separable Hilbert spaces implies the same
estimate, with the identical constant, on arbitrary Hilbert spaces. -/
theorem uniformCommutatorEstimate_of_separable {C : ℝ} (hC : 0 ≤ C)
    (estimate : SeparableUniformCommutatorEstimate.{u} C)
    (kaplansky : SeparableTwoVectorKaplanskyInput.{u}) : UniformCommutatorEstimate.{u} C := by
  intro H _ _ _ P Y n X hX
  let δ := scalarCommutatorNorm P Y
  have hδ : 0 ≤ δ := scalarCommutatorNorm_nonneg P Y
  apply ContinuousLinearMap.opNorm_le_bound _ (by positivity)
  intro ξ
  obtain ⟨M, hsep, hξ, hY, hXM⟩ := exists_matrix_test_reducing_space Y X ξ
  let : TopologicalSpace.SeparableSpace M := hsep
  let B := finiteMatrixTestAlgebra X
  have hB := finiteMatrixTestAlgebra_le P X hX
  have hM := finiteMatrixTestAlgebra_invariant X M hXM
  let σ := invariantStarRepresentation B M hM
  let Z : M →L[ℂ] M := Y.restrict hY
  let a : Fin n → Fin n → B := fun i j => ⟨X i j, matrix_entry_mem_test_algebra X i j⟩
  let X₀ : Matrix (Fin n) (Fin n) (M →L[ℂ] M) := fun i j => σ (a i j)
  have hZ (b : B) : ‖commutator Z (σ b)‖ ≤ δ * ‖b‖ := by
    apply ContinuousLinearMap.opNorm_le_bound _ (mul_nonneg hδ (norm_nonneg b))
    intro x
    change ‖(commutator Y (b : H →L[ℂ] H)) (x : H)‖ ≤ _
    calc
      _ ≤ ‖commutator Y (b : H →L[ℂ] H)‖ * ‖x‖ :=
        (commutator Y (b : H →L[ℂ] H)).le_opNorm x
      _ ≤ (δ * ‖b‖) * ‖x‖ :=
        mul_le_mul_of_nonneg_right
          (norm_commutator_le_scalarCommutatorNorm P Y b (hB b.property)) (norm_nonneg x)
  have hscalar : scalarCommutatorNorm (representationVonNeumannAlgebra σ) Z ≤ δ :=
    scalarKaplanskyClosure_of_twoVector σ (representationVonNeumannAlgebra σ)
      (kaplansky M B σ) Z δ hδ hZ
  have hsmall := estimate M (representationVonNeumannAlgebra σ) Z n X₀
    (fun i j => mem_representationVonNeumannAlgebra σ (a i j))
  have hmatrix : ‖matrixOperator X₀‖ ≤ ‖matrixOperator X‖ := by
    let A₀ : CStarMatrix (Fin n) (Fin n) B := CStarMatrix.ofMatrix a
    calc
      ‖matrixOperator X₀‖ = ‖representedMatrix σ A₀‖ := rfl
      _ ≤ ‖A₀‖ := NonUnitalStarAlgHom.norm_apply_le (representedMatrixHom σ n) A₀
      _ = ‖matrixOperator X‖ :=
        (norm_representedMatrix_of_injective B.subtype Subtype.val_injective n A₀).symm
  have hbound : ‖commutator (amplify Z n) (matrixOperator X₀)‖ ≤
      C * δ * ‖matrixOperator X‖ :=
    hsmall.trans (mul_le_mul (mul_le_mul_of_nonneg_left hscalar hC) hmatrix
      (norm_nonneg (matrixOperator X₀)) (mul_nonneg hC hδ))
  let I := mapCopies M.toSubmodule.subtypeL n
  let ξ₀ : HilbertCopies M n := WithLp.toLp 2 (fun i => ⟨ξ i, hξ i⟩)
  have hIξ : I ξ₀ = ξ := by ext i; rfl
  have hIY : I.comp (amplify Z n) = (amplify Y n).comp I := by ext x i; rfl
  have hIX : I.comp (matrixOperator X₀) = (matrixOperator X).comp I :=
    mapCopies_intertwines_matrix M.toSubmodule.subtypeL X₀ X (fun _ _ => rfl)
  have hIcomm := intertwines_commutator I (amplify Z n) (matrixOperator X₀)
    (amplify Y n) (matrixOperator X) hIY hIX
  have he : I (commutator (amplify Z n) (matrixOperator X₀) ξ₀) =
      commutator (amplify Y n) (matrixOperator X) ξ := by
    simpa only [ContinuousLinearMap.comp_apply, hIξ] using
      congrArg (fun T : HilbertCopies M n →L[ℂ] HilbertCopies H n => T ξ₀) hIcomm
  calc
    ‖commutator (amplify Y n) (matrixOperator X) ξ‖ =
        ‖commutator (amplify Z n) (matrixOperator X₀) ξ₀‖ := by
      rw [← he]
      exact norm_mapCopies_subtype M n _
    _ ≤ ‖commutator (amplify Z n) (matrixOperator X₀)‖ * ‖ξ₀‖ :=
      (commutator (amplify Z n) (matrixOperator X₀)).le_opNorm ξ₀
    _ ≤ (C * δ * ‖matrixOperator X‖) * ‖ξ‖ := by
      have hnorm : ‖ξ₀‖ = ‖ξ‖ := by
        rw [← norm_mapCopies_subtype M n ξ₀]
        exact congrArg norm hIξ
      rw [hnorm]
      exact mul_le_mul_of_nonneg_right hbound (norm_nonneg ξ)

end KadisonSimilarity

end

end OAI
