import OAI.Analysis.Nonexpansive.CompactMapSemigroup
import OAI.Analysis.Nonexpansive.TailMaps

namespace OAI

/-!
# The compact semigroup supplied by the actual resolvent tails

The ambient convex hull of each resolvent tail consists of genuine generated
selfmaps.  Changing their values to the weak carrier therefore gives a convex,
composition-closed family of nonexpansive selfmaps.  The decreasing sequence
of their pointwise weak closures has an actual idempotent.
-/

noncomputable section

open Set
open scoped Topology

namespace ReflexiveFixedPoints

universe u

variable {X : Type u} [NormedAddCommGroup X] [NormedSpace ℝ X]
variable [CompleteSpace X] {K : Set X}
variable (hKclosed : IsClosed K) (hKconvex : Convex ℝ K)
variable (T : K → K) (hT : LipschitzWith 1 T)

/-- Actual selfmaps whose ambient representatives belong to the algebraic
convex hull of the resolvent tail.  The ambient function space is used for
convexity, and the weak selfmap space is used for topology. -/
def weakTailConvexFamily (m : ℕ) : Set (WeakSelfMap K) :=
  {f | ambientMap (WeakSelfMap.toNorm f) ∈
    ambientTailConvexHull hKclosed hKconvex T hT m}

/-- Every point of the ambient convex hull has an actual selfmap
representative, so passing to weak values loses no elements. -/
theorem weakAmbient_image_weakTailConvexFamily (m : ℕ) :
    WeakSelfMap.weakAmbient '' weakTailConvexFamily hKclosed hKconvex T hT m =
      WeakSelfMap.weakify '' ambientTailConvexHull hKclosed hKconvex T hT m := by
  ext y
  constructor
  · rintro ⟨f, hf, rfl⟩
    refine ⟨ambientMap (WeakSelfMap.toNorm f), hf, ?_⟩
    exact (congrArg WeakSelfMap.weakify
      (funext (ambientMap_apply (WeakSelfMap.toNorm f)))).trans
      ((WeakSelfMap.weakAmbient_ofNorm (WeakSelfMap.toNorm f)).symm.trans
        (congrArg WeakSelfMap.weakAmbient (WeakSelfMap.ofNorm_toNorm f)))
  · rintro ⟨f, hf, rfl⟩
    obtain ⟨g, _, hgf⟩ :=
      ambientTailConvexHull_representative hKclosed hKconvex T hT hf
    refine ⟨WeakSelfMap.ofNorm g, ?_, ?_⟩
    · change ambientMap (WeakSelfMap.toNorm (WeakSelfMap.ofNorm g)) ∈
        ambientTailConvexHull hKclosed hKconvex T hT m
      rw [WeakSelfMap.toNorm_ofNorm, hgf]
      exact hf
    · rw [WeakSelfMap.weakAmbient_ofNorm]
      exact congrArg WeakSelfMap.weakify hgf

theorem weakTailConvexFamily_nonempty (m : ℕ) (hm : 1 ≤ m) :
    (weakTailConvexFamily hKclosed hKconvex T hT m).Nonempty := by
  obtain ⟨f, hf⟩ := ambientTailConvexHull_nonempty hKclosed hKconvex T hT m hm
  obtain ⟨g, _, hgf⟩ :=
    ambientTailConvexHull_representative hKclosed hKconvex T hT hf
  refine ⟨WeakSelfMap.ofNorm g, ?_⟩
  change ambientMap (WeakSelfMap.toNorm (WeakSelfMap.ofNorm g)) ∈
    ambientTailConvexHull hKclosed hKconvex T hT m
  rw [WeakSelfMap.toNorm_ofNorm, hgf]
  exact hf

theorem weakTailConvexFamily_antitone :
    Antitone (weakTailConvexFamily hKclosed hKconvex T hT) := by
  intro m n hmn f hf
  exact ambientTailConvexHull_antitone hKclosed hKconvex T hT hmn hf

theorem convex_weakTailConvexFamily (m : ℕ) :
    WeakSelfMap.ConvexFamily (weakTailConvexFamily hKclosed hKconvex T hT m) := by
  change Convex ℝ
    (WeakSelfMap.weakAmbient '' weakTailConvexFamily hKclosed hKconvex T hT m)
  rw [weakAmbient_image_weakTailConvexFamily]
  exact (convex_ambientTailConvexHull hKclosed hKconvex T hT m).linear_image
    WeakSelfMap.weakify.toLinearMap

/-- A member is generated by the actual identity, resolvents, composition,
and finite convex operations. -/
theorem weakTailConvexFamily_generated {m : ℕ} {f : WeakSelfMap K}
    (hf : f ∈ weakTailConvexFamily hKclosed hKconvex T hT m) :
    Generated hKclosed hKconvex T hT (WeakSelfMap.toNorm f) :=
  generated_of_ambient_mem
    (ambientTailConvexHull_subset_generated hKclosed hKconvex T hT m hf)

theorem weakTailConvexFamily_nonexpansive {m : ℕ} {f : WeakSelfMap K}
    (hf : f ∈ weakTailConvexFamily hKclosed hKconvex T hT m) :
    LipschitzWith 1 (WeakSelfMap.toNorm f) :=
  generated_nonexpansive (weakTailConvexFamily_generated hKclosed hKconvex T hT hf)

/-- Composition closure is inherited from actual tail maps.  No nonlinear
map is distributed over a convex combination in its input. -/
theorem weakTailConvexFamily_comp {m : ℕ} {f g : WeakSelfMap K}
    (hf : f ∈ weakTailConvexFamily hKclosed hKconvex T hT m)
    (hg : g ∈ weakTailConvexFamily hKclosed hKconvex T hT m) :
    WeakSelfMap.comp f g ∈ weakTailConvexFamily hKclosed hKconvex T hT m := by
  change ambientMap (WeakSelfMap.toNorm (WeakSelfMap.comp f g)) ∈
    ambientTailConvexHull hKclosed hKconvex T hT m
  rw [WeakSelfMap.toNorm_comp]
  exact ambientTailConvexHull_comp hKclosed hKconvex T hT hf hg

/-- An idempotent in every positive tail closure.  Compactness and
Hausdorffness are properties of the actual weak carrier supplied by the
weak-compactness foundations. -/
theorem exists_idempotent_in_tail_closures
    [CompactSpace (WeakCarrier K)] [T2Space (WeakCarrier K)] :
    ∃ P ∈ ⋂ n, closure (weakTailConvexFamily hKclosed hKconvex T hT (n + 1)),
      WeakSelfMap.comp P P = P ∧ LipschitzWith 1 (WeakSelfMap.toNorm P) := by
  refine WeakSelfMap.exists_idempotent_in_iInter_closure
    (fun n => weakTailConvexFamily hKclosed hKconvex T hT (n + 1)) ?_ ?_ ?_ ?_ ?_
  · intro n
    exact weakTailConvexFamily_nonempty hKclosed hKconvex T hT (n + 1)
      (Nat.succ_le_succ (Nat.zero_le n))
  · intro m n hmn
    exact weakTailConvexFamily_antitone hKclosed hKconvex T hT
      (Nat.add_le_add_right hmn 1)
  · intro n
    exact convex_weakTailConvexFamily hKclosed hKconvex T hT (n + 1)
  · intro n f hf
    exact weakTailConvexFamily_nonexpansive hKclosed hKconvex T hT hf
  · intro n f hf g hg
    exact weakTailConvexFamily_comp hKclosed hKconvex T hT hf hg

end ReflexiveFixedPoints

end

end OAI
