import OAI.NumberTheory.EgyptianFractions.ThreePrimeFourierReduction
import OAI.NumberTheory.EgyptianFractions.ThreePrimeContinuousMinorArc
import OAI.NumberTheory.EgyptianFractions.ThreePrimeIntegralCount
import OAI.NumberTheory.EgyptianFractions.ThreePrimeMangoldtIntegral