import Mathlib

namespace OAI

noncomputable section

universe u

namespace Problem335

/-- Every countable characteristic-zero field admits an embedding into the complex numbers.
This applies to the subfield generated by the finitely many coefficients of a circuit. -/
theorem countable_field_embeds_complex (K : Type u) [Field K] [CharZero K] [Countable K] :
    Nonempty (K →+* ℂ) := by
  classical
  obtain ⟨s, hs⟩ := exists_isTranscendenceBasis ℚ K
  obtain ⟨t, ht⟩ := exists_isTranscendenceBasis ℚ ℂ
  have htcard : Cardinal.mk ℂ = Cardinal.mk t :=
    IsAlgClosed.cardinal_eq_cardinal_transcendence_basis_of_aleph0_lt'
      (fun x : t => (x : ℂ)) ht Cardinal.mk_le_aleph0
      (by simpa using Cardinal.aleph0_lt_continuum)
  have : Infinite t := Cardinal.infinite_iff.mpr (by
    rw [← htcard]
    simpa using Cardinal.aleph0_lt_continuum.le)
  let e : s ↪ t := (Classical.choice (nonempty_embedding_nat s)).trans
    (Infinite.natEmbedding t)
  let v : s → ℂ := fun x => (e x : ℂ)
  have hv : AlgebraicIndependent ℚ v := ht.1.comp e e.injective
  let A := Algebra.adjoin ℚ (Set.range (fun x : s => (x : K)))
  let f : A →+* ℂ := (MvPolynomial.aeval v).toRingHom.comp hs.1.aevalEquiv.symm.toRingHom
  have hf : Function.Injective f :=
    (algebraicIndependent_iff_injective_aeval.mp hv).comp hs.1.aevalEquiv.symm.injective
  let : Algebra A ℂ := f.toAlgebra
  have : Module.IsTorsionFree A ℂ :=
    (Module.isTorsionFree_iff_algebraMap_injective).mpr hf
  have : Algebra.IsAlgebraic A K := hs.isAlgebraic
  exact ⟨(IsAlgClosed.lift (R := A) (S := K) (M := ℂ)).toRingHom⟩

end Problem335

end

end OAI
