import OAI.RingTheory.DirectFiniteness.PrescribedData

namespace OAI

universe u_1 u_2 u_3

noncomputable section
open scoped Classical
open Monoid Function
namespace KaplanskyCounterexample.MultipleHNN

universe u v
variable {H : Type u} [Group H] {I : Type v}
variable (A B : I → Subgroup H) (φ : ∀ i, A i ≃* B i)

def con : Con (Monoid.Coprod H (FreeGroup I)) := conGen fun x y =>
  ∃ (i : I) (a : A i), x = Coprod.inr (FreeGroup.of i) * Coprod.inl (a : H) ∧
    y = Coprod.inl (φ i a : H) * Coprod.inr (FreeGroup.of i)

abbrev Extension := (con A B φ).Quotient

instance : Group (Extension A B φ) := by delta Extension; infer_instance

def of : H →* Extension A B φ := (con A B φ).mk'.comp Coprod.inl

def letter (i : I) : Extension A B φ := (con A B φ).mk' (Coprod.inr (FreeGroup.of i))

lemma letter_mul_of (i : I) (a : A i) :
    letter A B φ i * of A B φ a = of A B φ (φ i a) * letter A B φ i :=
  (Con.eq _).mpr <| ConGen.Rel.of _ _ ⟨i, a, rfl, rfl⟩

def lift {G : Type u_1} [Group G] (f : H →* G) (t : I → G)
    (ht : ∀ i (a : A i), t i * f a = f (φ i a) * t i) : Extension A B φ →* G :=
  Con.lift _ (Coprod.lift f (FreeGroup.lift t)) (Con.conGen_le.mpr (by
    rintro _ _ ⟨i, a, rfl, rfl⟩
    simp [ht]))

@[simp] lemma lift_of {G : Type u_2} [Group G] (f : H →* G) (t : I → G)
    (ht : ∀ i (a : A i), t i * f a = f (φ i a) * t i) (h : H) :
    lift A B φ f t ht (of A B φ h) = f h := by
  change Coprod.lift f (FreeGroup.lift t) (Coprod.inl h) = f h
  simp

@[simp] lemma lift_letter {G : Type u_3} [Group G] (f : H →* G) (t : I → G)
    (ht : ∀ i (a : A i), t i * f a = f (φ i a) * t i) (i : I) :
    lift A B φ f t ht (letter A B φ i) = t i := by
  change Coprod.lift f (FreeGroup.lift t) (Coprod.inr (FreeGroup.of i)) = t i
  simp

/-- Extend any finite sublist of the required conjugacies one at a time.
Mathlib's complete Britton-lemma proof supplies the embedding at each step. -/
theorem finite_partial_realization (S : Finset I) :
    ∃ (G : Type (max u v)) (_ : Group G) (f : H →* G),
      Function.Injective f ∧ ∃ t : I → G,
        ∀ i ∈ S, ∀ a : A i, t i * f a = f (φ i a) * t i := by
  induction S using Finset.induction_on with
  | empty =>
    refine ⟨ULift.{v} H, inferInstance, (MulEquiv.ulift : ULift.{v} H ≃* H).symm.toMonoidHom,
      (MulEquiv.ulift : ULift.{v} H ≃* H).symm.injective, fun _ => 1, ?_⟩
    simp
  | @insert i S hi ih =>
    obtain ⟨G, hG, f, hf, t, ht⟩ := ih
    let fA := (A i).equivMapOfInjective f hf
    let fB := (B i).equivMapOfInjective f hf
    let ψ : (A i).map f ≃* (B i).map f := fA.symm.trans ((φ i).trans fB)
    let E := HNNExtension G ((A i).map f) ((B i).map f) ψ
    let emb : G →* E := HNNExtension.of
    let t' : I → E := fun j => if j = i then HNNExtension.t else emb (t j)
    refine ⟨E, inferInstance, emb.comp f,
      (HNNExtension.of_injective ψ).comp hf, t', ?_⟩
    intro j hj a
    rcases Finset.mem_insert.mp hj with rfl | hj
    · have h := HNNExtension.t_mul_of (φ := ψ) (fA a)
      simpa [t', fA, fB, ψ, emb] using h
    · by_cases hji : j = i
      · subst j
        have h := HNNExtension.t_mul_of (φ := ψ) (fA a)
        simpa [t', fA, fB, ψ, emb] using h
      · simpa [t', hji, ← map_mul] using congrArg emb (ht j hj a)

theorem of_injective [Fintype I] : Function.Injective (of A B φ) := by
  obtain ⟨G, hG, f, hf, t, ht⟩ := finite_partial_realization A B φ Finset.univ
  intro x y h
  apply hf
  have h' := congrArg (lift A B φ f t (fun i a => ht i (Finset.mem_univ i) a)) h
  simpa using h'

/-- The presentation is generated by the base group and the stable letters. -/
@[elab_as_elim]
theorem induction_on {P : Extension A B φ → Prop} (x : Extension A B φ)
    (hof : ∀ h, P (of A B φ h)) (ht : ∀ i, P (letter A B φ i))
    (hmul : ∀ x y, P x → P y → P (x * y)) (hinv : ∀ x, P x → P x⁻¹) : P x := by
  obtain ⟨w, rfl⟩ := (Con.mk'_surjective (c := con A B φ)) x
  induction w using Coprod.induction_on with
  | inl h => exact hof h
  | inr w =>
    induction w using FreeGroup.induction_on with
    | one => simpa only [map_one] using hof 1
    | of i => exact ht i
    | inv_of i ih => simpa only [map_inv] using hinv _ ih
    | mul a b ha hb => simpa only [map_mul] using hmul _ _ ha hb
  | mul a b ha hb => simpa only [map_mul] using hmul _ _ ha hb

/-- A central base element fixed in every associated subgroup stays central. -/
theorem of_central (z : H) (hz : ∀ h : H, Commute h z)
    (ha : ∀ i, z ∈ A i) (hφ : ∀ i, (φ i ⟨z, ha i⟩ : H) = z) :
    ∀ x : Extension A B φ, Commute x (of A B φ z) := by
  intro x
  induction x using induction_on A B φ with
  | hof h => exact (hz h).map (of A B φ)
  | ht i =>
    have h := letter_mul_of A B φ i ⟨z, ha i⟩
    rw [hφ i] at h
    exact h
  | hmul x y hx hy => exact hx.mul_left hy
  | hinv x hx => exact hx.inv_left

/-- Finite generation of the exact multiple-HNN presentation. -/
instance [Finite I] [Group.FG H] : Group.FG (Extension A B φ) := by
  obtain ⟨S, hS, hfin⟩ := Group.fg_iff.mp (inferInstance : Group.FG H)
  let T : Set (Extension A B φ) := of A B φ '' S ∪ Set.range (letter A B φ)
  apply Group.fg_iff.mpr
  refine ⟨T, ?_, (hfin.image _).union (Set.finite_range _)⟩
  apply top_unique
  intro x hxTop
  clear hxTop
  induction x using induction_on A B φ with
  | hof h =>
    have hh : h ∈ Subgroup.closure S := hS ▸ Subgroup.mem_top h
    induction hh using Subgroup.closure_induction with
    | mem h hh => exact Subgroup.subset_closure (Or.inl ⟨h, hh, rfl⟩)
    | one => simp
    | mul h k _ _ hh hk => simpa using (Subgroup.closure T).mul_mem hh hk
    | inv h _ hh => simpa using (Subgroup.closure T).inv_mem hh
  | ht i => exact Subgroup.subset_closure (Or.inr ⟨i, rfl⟩)
  | hmul x y hx hy => exact (Subgroup.closure T).mul_mem hx hy
  | hinv x hx => exact (Subgroup.closure T).inv_mem hx

end KaplanskyCounterexample.MultipleHNN
end

end OAI
