import Mathlib
import OAI.Analysis.LaughlinFock.RowTraces

namespace OAI

/-! Entry Enumeration. -/
noncomputable section
namespace LaughlinFock
open scoped BigOperators Matrix ComplexOrder
def rowEntryList_0 : List (RowEntry 0) := [⟨(⟨0, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩]

def rowEntryData_0 : Finset (RowEntry 0) := ⟨rowEntryList_0, by decide⟩

theorem rowEntryChecked_0 : (Finset.univ : Finset (RowEntry 0)) = rowEntryData_0 := by
  decide +kernel

def rowEntryList_1 : List (RowEntry 1) := [⟨(⟨0, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩]

def rowEntryData_1 : Finset (RowEntry 1) := ⟨rowEntryList_1, by decide⟩

theorem rowEntryChecked_1 : (Finset.univ : Finset (RowEntry 1)) = rowEntryData_1 := by
  decide +kernel

def rowEntryList_2 : List (RowEntry 2) := [⟨(⟨0, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨3, by decide⟩), by decide⟩]

def rowEntryData_2 : Finset (RowEntry 2) := ⟨rowEntryList_2, by decide⟩

theorem rowEntryChecked_2 : (Finset.univ : Finset (RowEntry 2)) = rowEntryData_2 := by
  decide +kernel

def rowEntryList_3 : List (RowEntry 3) := [⟨(⟨0, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨4, by decide⟩), by decide⟩]

def rowEntryData_3 : Finset (RowEntry 3) := ⟨rowEntryList_3, by decide⟩

theorem rowEntryChecked_3 : (Finset.univ : Finset (RowEntry 3)) = rowEntryData_3 := by
  decide +kernel

def rowEntryList_4 : List (RowEntry 4) := [⟨(⟨0, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨5, by decide⟩), by decide⟩]

def rowEntryData_4 : Finset (RowEntry 4) := ⟨rowEntryList_4, by decide⟩

theorem rowEntryChecked_4 : (Finset.univ : Finset (RowEntry 4)) = rowEntryData_4 := by
  decide +kernel

def rowEntryList_5 : List (RowEntry 5) := [⟨(⟨0, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨6, by decide⟩), by decide⟩]

def rowEntryData_5 : Finset (RowEntry 5) := ⟨rowEntryList_5, by decide⟩

theorem rowEntryChecked_5 : (Finset.univ : Finset (RowEntry 5)) = rowEntryData_5 := by
  decide +kernel

def rowEntryList_6 : List (RowEntry 6) := [⟨(⟨0, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨7, by decide⟩), by decide⟩]

def rowEntryData_6 : Finset (RowEntry 6) := ⟨rowEntryList_6, by decide⟩

theorem rowEntryChecked_6 : (Finset.univ : Finset (RowEntry 6)) = rowEntryData_6 := by
  decide +kernel

def rowEntryList_7 : List (RowEntry 7) := [⟨(⟨0, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨0, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨1, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨2, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨3, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨4, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨5, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨6, by decide⟩, ⟨8, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨0, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨1, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨2, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨3, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨4, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨5, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨6, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨7, by decide⟩), by decide⟩, ⟨(⟨7, by decide⟩, ⟨8, by decide⟩), by decide⟩]

def rowEntryData_7 : Finset (RowEntry 7) := ⟨rowEntryList_7, by decide⟩

theorem rowEntryChecked_7 : (Finset.univ : Finset (RowEntry 7)) = rowEntryData_7 := by
  decide +kernel

end LaughlinFock
end

end OAI
