import OAI.Analysis.FactorGeneration.Main
import OAI.Analysis.RelativeGeneration.InclusionTransport
import OAI.Analysis.RelativeGeneration.OriginalUnitary
import OAI.Analysis.RelativeGeneration.RepresentedLocus

namespace OAI

noncomputable section

/- The full relative-generating locus of the original inclusion,
   together with the single-generation corollary. -/
namespace Generator
open Tracial UltrapowerBridge
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Relative generation for the original concrete
factors and the arbitrary given irreducible inclusion. No ambient separability,
cyclicity, or perturbation hypothesis appears. The entire generating locus is
Gδ and dense, for the metric identified with normalized trace-2 in
`FactorTraceUnitary.dist_eq_trace`. -/
theorem relative_generation_of_II1_separable_predual
    (P S : StarSubalgebra ℂ (H →L[ℂ] H)) (hP : IsII1Factor P) (hS : IsII1Factor S)
    (hPS : P ≤ S)
    (hirr : ∀ c : S,
      (∀ a : P,StarSubalgebra.inclusion hPS a*c=c*StarSubalgebra.inclusion hPS a) →
      ∃ z : ℂ,c=algebraMap ℂ S z)
    (hsep : HasSeparablePredual S) :
    IsGδ {u : FactorTraceUnitary S hS |
      wstar ((P : Set (H →L[ℂ] H)) ∪ {(u.algebra S hS).val})=S} ∧
    Dense {u : FactorTraceUnitary S hS |
      wstar ((P : Set (H →L[ℂ] H)) ∪ {(u.algebra S hS).val})=S} := by
  let hf := hS.factor_smul
  let hu := hS.one_ne_zero
  let K := TraceFreeHilbert hf hS.diffuse hS.finite hu
  let R := traceFreeHilbertClosure hf hS.diffuse hS.finite hu
  let σ := traceFreeHilbertClosureTrace hf hS.diffuse hS.finite hu
  let N := traceFreeRelativeImage hf hS.diffuse hS.finite hu P hP.weaklyClosed
  have hNR : N ≤ R := traceFreeRelativeImage_le hf hS.diffuse hS.finite hu P hP.weaklyClosed
  have hN : IsII1Factor N.toStarSubalgebra :=
    traceFreeRelativeImage_isII1Factor hf hS.diffuse hS.finite hu P hP.weaklyClosed hPS hP
  have hfN : ∀ c : N.toStarSubalgebra,
      (∀ a : N.toStarSubalgebra,a*c=c*a) → ∃ z : ℂ,c=z • (1 : N.toStarSubalgebra) := by
    intro c hc
    obtain ⟨z,hz⟩ := hN.factor c hc
    exact ⟨z,hz.trans (Algebra.algebraMap_eq_smul_one z)⟩
  have hirr' : ∀ c : S,
      (∀ a : P,StarSubalgebra.inclusion hPS a*c=c*StarSubalgebra.inclusion hPS a) →
      ∃ z : ℂ,c=z • (1 : S) := by
    intro c hc
    obtain ⟨z,hz⟩ := hirr c hc
    exact ⟨z,hz.trans (Algebra.algebraMap_eq_smul_one z)⟩
  have hi := traceFreeRelativeImage_irreducible hf hS.diffuse hS.finite hu
    P hP.weaklyClosed hPS hirr'
  have hs := traceOrbit_isSeparable_of_separablePredual σ
    (traceFreeHilbertClosure_hasSeparablePredual hf hS.diffuse hS.finite hu hsep)
  obtain ⟨hg,hd⟩ := represented_full_relative_generation σ hNR hfN hN.diffuse hi hs
  let f := FactorTraceUnitary.representedHomeomorph S hS
  have he : {u : FactorTraceUnitary S hS |
      wstar ((P : Set (H →L[ℂ] H)) ∪ {(u.algebra S hS).val})=S} =
      f ⁻¹' {v : TraceUnitary σ |
        wstar ((N : Set (K →L[ℂ] K)) ∪ {(v.algebra σ).val})=R.toStarSubalgebra} := by
    ext u
    exact traceFreeRelativeGeneration_iff hf hS.diffuse hS.finite hu P hP.weaklyClosed hPS
      (u.algebra S hS)
  rw [he]
  exact ⟨IsGδ.preimage f.continuous hg, f.isOpenQuotientMap.dense_preimage_iff.mpr hd⟩

/-- A factor with separable predual is singly generated, equivalently
   generated by two self-adjoint elements. -/
theorem source_main_reused (S : StarSubalgebra ℂ (H →L[ℂ] H))
    (hS : IsII1Factor S) (hsep : HasSeparablePredual S) :
    SinglyGenerated S ∧ ∃ a ∈ S, ∃ b ∈ S,
      IsSelfAdjoint a ∧ IsSelfAdjoint b ∧ wstar {a,b}=S := by
  have h := single_generation_of_II1_separable_predual S hS hsep
  exact ⟨h,(singlyGenerated_iff_two_selfAdjoint S).mp h⟩

end Generator

namespace RelativeGeneration

universe level

/-- The concrete finite diffuse factor hypotheses are the ones used in the trace construction. -/
theorem IsII1Factor.toGenerator {Hilbert : Type level} [NormedAddCommGroup Hilbert]
    [InnerProductSpace ℂ Hilbert] [CompleteSpace Hilbert]
    {algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)} (factor : IsII1Factor algebra) :
    Generator.IsII1Factor algebra :=
  ⟨factor.nonzero, factor.weaklyClosed, factor.factor, factor.finite, factor.diffuse⟩

/-- The entire relative-generator locus of an irreducible inclusion is dense Gδ in the
normalized trace two-topology on the original, genuine unitaries. -/
theorem main_theorem : MainTarget.{level} := by
  intro Hilbert _ _ _ small large smallFactor largeFactor inclusion irreducible separablePredual
  let smallFactor' := smallFactor.toGenerator
  let largeFactor' := largeFactor.toGenerator
  obtain ⟨gdelta, dense⟩ := Generator.relative_generation_of_II1_separable_predual
    small large smallFactor' largeFactor' inclusion irreducible separablePredual
  refine ⟨Generator.normalizedFactorTrace large largeFactor',
    Generator.normalizedFactorTrace_isNormalizedTrace large largeFactor', ?_⟩
  let : TopologicalSpace (unitary large) :=
    traceTopology large (Generator.normalizedFactorTrace large largeFactor')
  let unitaryHomeomorph := Generator.FactorTraceUnitary.traceHomeomorph large largeFactor'
  have locus_eq : relativeGeneratorLocus small large = unitaryHomeomorph.symm ⁻¹'
      {element : Generator.FactorTraceUnitary large largeFactor' |
        Generator.wstar ((small : Set (Hilbert →L[ℂ] Hilbert)) ∪
          {(element.algebra large largeFactor').val}) = large} := by
    ext element
    rfl
  rw [locus_eq]
  exact ⟨IsGδ.preimage unitaryHomeomorph.symm.continuous gdelta,
    unitaryHomeomorph.symm.isOpenQuotientMap.dense_preimage_iff.mpr dense⟩

end RelativeGeneration

end

end OAI
