import Mathlib

namespace OAI

noncomputable section

universe level

namespace RelativeGeneration

variable {Hilbert : Type level} [NormedAddCommGroup Hilbert]
  [InnerProductSpace ℂ Hilbert] [CompleteSpace Hilbert]

/-- Weak operator closedness of a concrete unital star subalgebra. -/
def WOTClosed (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)) : Prop :=
  IsClosed {operator : Hilbert →WOT[ℂ] Hilbert | operator.toCLM ∈ algebra}

/-- The weakly closed unital star algebra generated by a set of operators. -/
def wstar (operators : Set (Hilbert →L[ℂ] Hilbert)) :
    StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert) :=
  sInf {algebra | WOTClosed algebra ∧ operators ⊆ algebra}

/-- A nonzero, weakly closed, finite diffuse algebra with scalar center. -/
structure IsII1Factor (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)) : Prop where
  nonzero : (0 : Hilbert →L[ℂ] Hilbert) ≠ 1
  weaklyClosed : WOTClosed algebra
  factor : ∀ element : algebra, (∀ other : algebra, other * element = element * other) →
    ∃ scalar : ℂ, element = algebraMap ℂ algebra scalar
  finite : ∀ isometry : algebra, star isometry * isometry = 1 → isometry * star isometry = 1
  diffuse : ∀ projection : algebra, IsStarProjection projection → projection ≠ 0 →
    ∃ subprojection : algebra, IsStarProjection subprojection ∧ subprojection ≠ 0 ∧
      subprojection ≠ projection ∧ projection * subprojection = subprojection ∧
      subprojection * projection = subprojection

/-- A same-universe separable Banach predual, with the conjugate-linear dual convention.
This imposes no separability on the Hilbert representation or the operator norm topology. -/
def HasSeparablePredual (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)) : Prop :=
  ∃ (Banach : Type level) (_ : NormedAddCommGroup Banach) (_ : NormedSpace ℂ Banach)
    (_ : CompleteSpace Banach) (_ : TopologicalSpace.SeparableSpace Banach),
    Nonempty (StrongDual ℂ Banach ≃ₗᵢ⋆[ℂ] algebra)

/-- The ultraweak topology is generated by absolutely summable vector functionals. -/
abbrev ultraweakTopology (Hilbert : Type level) [NormedAddCommGroup Hilbert]
    [InnerProductSpace ℂ Hilbert] [CompleteSpace Hilbert] :
    TopologicalSpace (Hilbert →L[ℂ] Hilbert) :=
  ⨅ (left : ℕ → Hilbert) (right : ℕ → Hilbert)
    (_ : Summable (fun index => ‖left index‖ * ‖right index‖)),
    TopologicalSpace.induced
      (fun operator : Hilbert →L[ℂ] Hilbert =>
        ∑' index, inner ℂ (left index) (operator (right index))) inferInstance

/-- The concrete algebra carries the induced ultraweak topology. -/
abbrev algebraUltraweakTopology (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)) :
    TopologicalSpace algebra :=
  TopologicalSpace.induced (fun operator : algebra => (operator : Hilbert →L[ℂ] Hilbert))
    (ultraweakTopology Hilbert)

/-- A faithful normal normalized trace, not an additional hypothesis on the inclusion. -/
structure IsNormalizedTrace (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert))
    (trace : algebra →L[ℂ] ℂ) : Prop where
  normalized : trace 1 = 1
  positive : ∀ element : algebra, 0 ≤ (trace (star element * element)).re
  star_preserving : ∀ element : algebra, trace (star element) = star (trace element)
  tracial : ∀ left right : algebra, trace (left * right) = trace (right * left)
  faithful : ∀ element : algebra, trace (star element * element) = 0 → element = 0
  normal : @Continuous algebra ℂ (algebraUltraweakTopology algebra) inferInstance trace

/-- The normalized trace two-distance between genuine unitaries of the original algebra. -/
def traceDistance (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert))
    (trace : algebra →L[ℂ] ℂ) (left right : unitary algebra) : ℝ :=
  Real.sqrt (trace (star ((left : algebra) - (right : algebra)) *
    ((left : algebra) - (right : algebra)))).re

/-- The topology generated by trace two-distance balls, not the inherited operator norm topology. -/
abbrev traceTopology (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert))
    (trace : algebra →L[ℂ] ℂ) : TopologicalSpace (unitary algebra) :=
  TopologicalSpace.generateFrom {ball | ∃ center : unitary algebra, ∃ radius : ℝ,
    0 < radius ∧ ball = {point | traceDistance algebra trace center point < radius}}

/-- A metric presentation with the trace two-distance gives precisely the trace-ball topology
on all genuine unitaries. -/
def traceUnitaryHomeomorph (algebra : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert))
    (trace : algebra →L[ℂ] ℂ) {UnitarySpace : Type*} [MetricSpace UnitarySpace]
    (unitaryEquiv : UnitarySpace ≃ unitary algebra)
    (distance_eq : ∀ first second, dist first second =
      traceDistance algebra trace (unitaryEquiv first) (unitaryEquiv second)) :
    @Homeomorph UnitarySpace (unitary algebra) inferInstance (traceTopology algebra trace) := by
  letI : TopologicalSpace (unitary algebra) := traceTopology algebra trace
  refine { unitaryEquiv with continuous_toFun := ?_, continuous_invFun := ?_ }
  · apply continuous_generateFrom_iff.mpr
    rintro ball ⟨center, radius, _, rfl⟩
    have preimage_ball : unitaryEquiv ⁻¹'
        {point | traceDistance algebra trace center point < radius} =
        Metric.ball (unitaryEquiv.symm center) radius := by
      ext point
      change traceDistance algebra trace center (unitaryEquiv point) < radius ↔
        dist point (unitaryEquiv.symm center) < radius
      rw [dist_comm, distance_eq, unitaryEquiv.apply_symm_apply]
    change IsOpen (unitaryEquiv ⁻¹' {point | traceDistance algebra trace center point < radius})
    rw [preimage_ball]
    exact Metric.isOpen_ball
  · apply continuous_def.mpr
    intro openSet isOpenSet
    refine isOpen_iff_forall_mem_open.mpr ?_
    intro point point_mem
    obtain ⟨radius, radius_pos, ball_subset⟩ :=
      Metric.isOpen_iff.mp isOpenSet (unitaryEquiv.symm point) point_mem
    refine ⟨{candidate | traceDistance algebra trace point candidate < radius}, ?_,
      TopologicalSpace.isOpen_generateFrom_of_mem ⟨point, radius, radius_pos, rfl⟩, ?_⟩
    · intro candidate candidate_mem
      apply ball_subset
      change dist (unitaryEquiv.symm candidate) (unitaryEquiv.symm point) < radius
      rw [dist_comm, distance_eq, unitaryEquiv.apply_symm_apply, unitaryEquiv.apply_symm_apply]
      exact candidate_mem
    · change traceDistance algebra trace point point < radius
      calc
        traceDistance algebra trace point point =
            dist (unitaryEquiv.symm point) (unitaryEquiv.symm point) := by
          simpa only [unitaryEquiv.apply_symm_apply] using
            (distance_eq (unitaryEquiv.symm point) (unitaryEquiv.symm point)).symm
        _ = 0 := dist_self _
        _ < radius := radius_pos

/-- The entire relative-generator locus in the original unitary group. -/
def relativeGeneratorLocus (small large : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)) :
    Set (unitary large) :=
  {element | wstar ((small : Set (Hilbert →L[ℂ] Hilbert)) ∪
    {((element : large) : Hilbert →L[ℂ] Hilbert)}) = large}

/-- Every irreducible inclusion of concrete type II₁ factors with separable predual
of the larger factor has a dense Gδ full relative-generator locus in the normalized
trace two-topology. The normalized faithful normal trace is asserted to exist;
no representation, transport, cyclicity, or perturbation premise is imposed. -/
def MainTarget : Prop :=
  ∀ (Hilbert : Type level) [NormedAddCommGroup Hilbert] [InnerProductSpace ℂ Hilbert]
    [CompleteSpace Hilbert] (small large : StarSubalgebra ℂ (Hilbert →L[ℂ] Hilbert)),
    IsII1Factor small → IsII1Factor large → ∀ inclusion : small ≤ large,
      (∀ element : large,
        (∀ member : small, StarSubalgebra.inclusion inclusion member * element =
          element * StarSubalgebra.inclusion inclusion member) →
        ∃ scalar : ℂ, element = algebraMap ℂ large scalar) →
      HasSeparablePredual large →
      ∃ trace : large →L[ℂ] ℂ, IsNormalizedTrace large trace ∧
        @IsGδ (unitary large) (traceTopology large trace) (relativeGeneratorLocus small large) ∧
        @Dense (unitary large) (traceTopology large trace) (relativeGeneratorLocus small large)

end RelativeGeneration

end

end OAI
