import OAI.Algebra.Finitistic.Localization.FiniteProjectiveHomotopy
import OAI.Algebra.Finitistic.Localization.AmbientQuotientEvaluation
import OAI.Algebra.Finitistic.Selected.SelectedFiniteTensorEvaluation
import Mathlib.Algebra.Homology.HomotopyCategory.Triangulated

namespace OAI
noncomputable section
open CategoryTheory CategoryTheory.Limits
namespace LittleFinitistic
open BalancedTensor ThickEvaluation FiniteProjectiveHomotopy IdempotentTensor
universe u v

namespace FiniteProjectiveHomotopy
variable {R : Type u} [Ring R]

lemma single_property (M : ModuleCat.{v} R) [Module.Finite R M] [Projective M] (n : ℤ) :
    ComplexProperty R ((HomologicalComplex.single _ (.up ℤ) n).obj M) := by
  constructor
  · exact ⟨n,n,fun i hi => HomologicalComplex.isZero_single_obj_X (.up ℤ) n M i (by omega)⟩
  · intro i
    by_cases h : i=n
    · subst i
      let e := HomologicalComplex.singleObjXSelf (.up ℤ) n M
      exact ⟨finite_of_iso R e.symm,Projective.of_iso e.symm inferInstance⟩
    · exact finite_projective_of_isZero R _
        (HomologicalComplex.isZero_single_obj_X (.up ℤ) n M i h)
end FiniteProjectiveHomotopy

namespace QuadraticEncoding
variable {k : Type u} [Field k] {d t : ℕ} (P : Relations k d t)

instance vertexModuleFinite (i : Fin 3) : Module.Finite (B P)ᵐᵒᵖ (vertexModule P i) := by
  let e := Representation.vertexId (P := P) i
  have he : e*e=e := (ThreeVertexAlgebra.directedSystem (composition P)).idem i
  apply Module.Finite.of_surjective (splitProjection he)
  intro m
  exact ⟨MulOpposite.op m.val,Subtype.ext m.property⟩

instance vertexModuleProjective (i : Fin 3) : Projective (vertexModule P i) := by
  have : Module.Projective (B P)ᵐᵒᵖ (vertexModule P i) :=
    rightIdeal_projective ((ThreeVertexAlgebra.directedSystem (composition P)).idem i)
  exact ModuleCat.projective_of_categoryTheory_projective (vertexModule P i)

/-- The exact bounded-projective source category used in Section 3. -/
abbrev BoundedK := K.{u,u} (B P)ᵐᵒᵖ

def boundedConeS : BoundedK P := ⟨coneS P,
  mappingCone_property _ _ (single_property (vertexModule P 0) 0) (single_property (vertexModule P 1) 0)⟩
def boundedConeS' : BoundedK P := ⟨coneS' P,
  mappingCone_property _ _ (single_property (vertexModule P 1) 0) (single_property (vertexModule P 2) 0)⟩

def boundedConeGenerators : ObjectProperty (BoundedK P) :=
  fun T => T = boundedConeS P ∨ T = boundedConeS' P

abbrev boundedDenominators : MorphismProperty (BoundedK P) :=
  ObjectProperty.trW (Thick (boundedConeGenerators P))

/-- The actual localization of K^b(proj-B) by the thick subcategory generated by the two cones. -/
abbrev BoundedQ := (boundedDenominators P).Localization

variable {P} {Y : Type v} [AddCommGroup Y] [Module k Y] (X : Representation P Y)

def boundedEvaluation : BoundedK P ⥤ HomotopyCategory (ModuleCat.{max u v} k) (.up ℤ) :=
  inclusion (B P)ᵐᵒᵖ ⋙ homotopyEvaluation k (B P) X.Evaluation

instance boundedEvaluationAdditive : (boundedEvaluation X).Additive :=
  inferInstanceAs (inclusion (B P)ᵐᵒᵖ ⋙ homotopyEvaluation k (B P) X.Evaluation).Additive
instance boundedEvaluationShift : (boundedEvaluation X).CommShift ℤ :=
  inferInstanceAs ((inclusion (B P)ᵐᵒᵖ ⋙ homotopyEvaluation k (B P) X.Evaluation).CommShift ℤ)
instance boundedEvaluationTriangulated : (boundedEvaluation X).IsTriangulated :=
  inferInstanceAs (inclusion (B P)ᵐᵒᵖ ⋙ homotopyEvaluation k (B P) X.Evaluation).IsTriangulated

lemma boundedEvaluation_kills_generators : ∀ T, boundedConeGenerators P T →
    IsZero ((boundedEvaluation X).obj T) := by
  rintro T (rfl | rfl)
  · exact evaluation_coneS_zero X
  · exact evaluation_coneS'_zero X

/-- Tensor evaluation on the manuscript's fixed quotient; no generator-vanishing assumption remains. -/
def boundedQuotientEvaluation : BoundedQ P ⥤ HomotopyCategory (ModuleCat.{max u v} k) (.up ℤ) :=
  quotientEvaluation (boundedConeGenerators P) (boundedEvaluation X)
    (boundedEvaluation_kills_generators X)

def boundedQuotientEvaluationFactors :
    (boundedDenominators P).Q ⋙ boundedQuotientEvaluation X ≅ boundedEvaluation X :=
  quotientEvaluationFactors (boundedConeGenerators P) (boundedEvaluation X)
    (boundedEvaluation_kills_generators X)

/-- Evaluation of every bounded-projective representative has bounded finite-dimensional terms. -/
theorem boundedEvaluation_finite [FiniteDimensional k Y] (T : BoundedK P) :
    (∃ a b : ℤ, ∀ i, i < a ∨ b < i → IsZero (((boundedEvaluation X).obj T).as.X i)) ∧
    ∀ i, FiniteDimensional k (((boundedEvaluation X).obj T).as.X i) := by
  obtain ⟨⟨a,b,hb⟩,hp⟩ := T.property
  constructor
  · exact ⟨a,b,bounded_support X.Evaluation T.obj.as a b hb⟩
  · intro i
    have := (hp i).1
    have : FiniteDimensional k (B P) := finiteDimensional P
    exact tensorFunctor_finite X.Evaluation (T.obj.as.X i)
end QuadraticEncoding
end LittleFinitistic

end

end OAI
