import Mathlib.CategoryTheory.Triangulated.Subcategory

namespace OAI
noncomputable section
open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open ZeroObject
namespace LittleFinitistic.ThickEvaluation
universe u v u' v'
variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C]
  [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]

/-- The actual thick closure: zero, isomorphisms, shifts, extensions, and retracts. -/
inductive Thick (S : ObjectProperty C) : C → Prop
  | generator {X : C} : S X → Thick S X
  | zero : Thick S 0
  | iso {X Y : C} : (X ≅ Y) → Thick S X → Thick S Y
  | shift {X : C} (n : ℤ) : Thick S X → Thick S (X⟦n⟧)
  | extension (T : Triangle C) : T ∈ distTriang C → Thick S T.obj₁ → Thick S T.obj₃ → Thick S T.obj₂
  | retract {X Y : C} : Retract X Y → Thick S Y → Thick S X

variable (S : ObjectProperty C)

instance thickRetracts : ObjectProperty.IsStableUnderRetracts (Thick S) where
  of_retract r h := Thick.retract r h

instance thickZero : ObjectProperty.ContainsZero (Thick S) where
  exists_zero := ⟨0,isZero_zero C,Thick.zero⟩

instance thickShift : ObjectProperty.IsStableUnderShift (Thick S) ℤ where
  isStableUnderShiftBy n := ⟨fun _ h => Thick.shift n h⟩

instance thickTriangulated : ObjectProperty.IsTriangulated (Thick S) where
  toIsTriangulatedClosed₂ := .mk' (fun T hT h₁ h₃ => Thick.extension T hT h₁ h₃)

/-- Minimality proves that this is the thick subcategory generated by S. -/
theorem thick_minimal (P : ObjectProperty C) [P.IsTriangulated] [P.IsStableUnderRetracts]
    (h : S ≤ P) : Thick S ≤ P := by
  intro X hX
  induction hX with
  | generator hX => exact h _ hX
  | zero => exact P.prop_zero
  | iso e _ ih => exact P.prop_of_iso e ih
  | shift n _ ih => exact P.le_shift n _ ih
  | extension T hT _ _ ih₁ ih₃ => exact P.ext_of_isTriangulatedClosed₂ T hT ih₁ ih₃
  | retract r _ ih => exact P.prop_of_retract r ih

variable {D : Type u'} [Category.{v'} D] [Preadditive D] [HasZeroObject D]
  [HasShift D ℤ] [∀ n : ℤ, (shiftFunctor D n).Additive] [Pretriangulated D]
variable (F : C ⥤ D) [F.Additive] [F.CommShift ℤ] [F.IsTriangulated]

omit [F.Additive] in
/-- Exact evaluation kills the whole thick closure once it kills the generators. -/
theorem kills_thick (hS : ∀ X, S X → IsZero (F.obj X)) :
    ∀ X, Thick S X → IsZero (F.obj X) := by
  intro X hX
  induction hX with
  | generator hX => exact hS _ hX
  | zero => exact F.map_isZero (isZero_zero C)
  | iso e _ ih => exact ih.of_iso (F.mapIso e).symm
  | shift n _ ih =>
    exact ((shiftFunctor D n).map_isZero ih).of_iso ((F.commShiftIso n).app _)
  | extension T hT _ _ ih₁ ih₃ =>
    exact Triangle.isZero₂_of_isZero₁₃ _ (F.map_distinguished T hT) ih₁ ih₃
  | retract r _ ih =>
    apply (IsZero.iff_id_eq_zero _).2
    rw [← (r.map F).retract]
    change F.map r.i ≫ F.map r.r = 0
    rw [ih.eq_of_src (F.map r.r) 0, comp_zero]

omit [F.Additive] in
/-- Every morphism whose cone lies in the generated thick subcategory evaluates to an isomorphism. -/
theorem inverts_thick (hS : ∀ X, S X → IsZero (F.obj X)) :
    (ObjectProperty.trW (Thick S)).IsInvertedBy F := by
  rintro X Y f ⟨Z,g,h,hT,hZ⟩
  exact (Triangle.isZero₃_iff_isIso₁ _ (F.map_distinguished _ hT)).mp
    (kills_thick S F hS Z hZ)

/-- Evaluation on the actual localization at cones in the thick closure. -/
def quotientEvaluation (hS : ∀ X, S X → IsZero (F.obj X)) :
    (ObjectProperty.trW (Thick S)).Localization ⥤ D :=
  Localization.lift F (inverts_thick S F hS) (ObjectProperty.trW (Thick S)).Q

def quotientEvaluationFactors (hS : ∀ X, S X → IsZero (F.obj X)) :
    (ObjectProperty.trW (Thick S)).Q ⋙ quotientEvaluation S F hS ≅ F :=
  Localization.fac F (inverts_thick S F hS) (ObjectProperty.trW (Thick S)).Q
end LittleFinitistic.ThickEvaluation

end

end OAI
