import Mathlib

namespace OAI

/-!
Coxeter presentation and universal lifts of finite symmetric groups.
-/

/- A normal-form argument for the adjacent transpositions. This is used for
symmetric coherence in the positive-object category of the endpoint quotient. -/
namespace FiniteAlgebraicEnvelopes.Adjacent

section
universe u
variable {H : Type u} [Group H]

/-- The Coxeter relations on the first `n` adjacent generators. -/
structure Relations (r : ℕ → H) (n : ℕ) : Prop where
  square : ∀ i, i < n → r i * r i = 1
  braid : ∀ i, i + 1 < n → r (i+1) * r i * r (i+1) = r i * r (i+1) * r i
  distant : ∀ i j, i + 1 < j → j < n → Commute (r i) (r j)

lemma Relations.mono {r : ℕ → H} {m n : ℕ} (h : Relations r n) (hmn : m ≤ n) :
    Relations r m :=
  ⟨fun i hi => h.square i (hi.trans_le hmn),
   fun i hi => h.braid i (hi.trans_le hmn),
   fun i j hij hj => h.distant i j hij (hj.trans_le hmn)⟩

/-- `r (n-1) ... r i`, with the empty product when `n ≤ i`. -/
def descending (r : ℕ → H) (i : ℕ) : ℕ → H
  | 0 => 1
  | n+1 => if i ≤ n then r n * descending r i n else 1

@[simp] lemma descending_zero (r : ℕ → H) (i : ℕ) : descending r i 0 = 1 := rfl
lemma descending_step (r : ℕ → H) {i n : ℕ} (hi : i ≤ n) :
    descending r i (n+1) = r n * descending r i n := ite_eq_left hi

lemma descending_empty (r : ℕ → H) {i n : ℕ} (hi : n ≤ i) : descending r i n = 1 := by
  cases n with
  | zero => rfl
  | succ n => simp only [descending, ite_eq_right (show ¬ i ≤ n by omega)]

lemma descending_commute {r : ℕ → H} {n : ℕ} (h : Relations r n)
    {j : ℕ} (hj : j < n) (i m : ℕ) (hm : m < j) :
    Commute (descending r i m) (r j) := by
  induction m with
  | zero => exact Commute.one_left _
  | succ m ih =>
    by_cases hi : i ≤ m
    · rw [descending_step r hi]
      exact (h.distant m j (by omega) hj).mul_left (ih (by omega))
    · rw [descending, ite_eq_right hi]
      exact Commute.one_left _

lemma descending_extend (r : ℕ → H) {i n : ℕ} (hi : i < n) :
    descending r (i+1) n * r i = descending r i n := by
  induction n with
  | zero => omega
  | succ n ih =>
    by_cases he : i = n
    · subst i
      rw [descending_empty r (Nat.le_refl _), descending_step r (Nat.le_refl _),
        descending_empty r (Nat.le_refl _), one_mul, mul_one]
    · rw [descending_step r (by omega), descending_step r (by omega), mul_assoc,
        ih (by omega)]

lemma descending_cancel {r : ℕ → H} {n i : ℕ} (h : Relations r n) (hi : i < n) :
    descending r i n * r i = descending r (i+1) n := by
  rw [← descending_extend r hi, mul_assoc, h.square i hi, mul_one]

lemma descending_last {r : ℕ → H} {n i : ℕ} (h : Relations r (n+1)) (hi : i < n) :
    descending r i (n+1) * r n = r (n-1) * descending r i (n+1) := by
  cases n with
  | zero => omega
  | succ n =>
    rw [descending_step r (by omega), descending_step r (by omega)]
    have hc := descending_commute h (show n+1 < n+1+1 by omega) i n (by omega)
    have hb := h.braid n (by omega)
    simp only [Nat.add_sub_cancel]
    calc
      _ = (r (n+1) * r n * r (n+1)) * descending r i n := by
        rw [mul_assoc, mul_assoc, hc.eq]
        group
      _ = _ := by rw [hb]; group

/-- The elementary normal-form multiplication rules. -/
lemma descending_mul {r : ℕ → H} {n : ℕ} (h : Relations r n)
    (i : ℕ) (hi : i ≤ n) (j : ℕ) (hj : j < n) :
    descending r i n * r j =
      if j+1 < i then r j * descending r i n else
      if j+1 = i then descending r j n else
      if j = i then descending r (i+1) n else
        r (j-1) * descending r i n := by
  induction n with
  | zero => omega
  | succ n ih =>
    by_cases hie : i = n+1
    · subst i
      rw [descending_empty r (Nat.le_refl _), one_mul]
      by_cases hje : j = n
      · subst j
        simp only [Nat.lt_irrefl, ↓reduceIte, descending_step r (Nat.le_refl _),
          descending_empty r (Nat.le_refl _), mul_one]
      · simp only [show j+1 < n+1 by omega, ↓reduceIte, mul_one]
    · have hin : i ≤ n := by omega
      by_cases hje : j = n
      · subst j
        by_cases hie : i = n
        · subst i
          simp only [show ¬ n+1 < n by omega, show ¬ n+1 = n by omega,
            ↓reduceIte]
          exact descending_cancel h (by omega)
        · simp only [show ¬ n+1 < i by omega, show ¬ n+1 = i by omega,
            show ¬ n = i by omega, ↓reduceIte]
          exact descending_last h (by omega)
      · have hjn : j < n := by omega
        rw [descending_step r hin, mul_assoc, ih (h.mono (by omega)) hin hjn]
        split_ifs with h₁ h₂ h₃
        · rw [← mul_assoc, (h.distant j n (by omega) (by omega)).eq.symm, mul_assoc]
        · rw [descending_step r (by omega)]
        · rw [descending_step r (by omega)]
        · rw [← mul_assoc, (h.distant (j-1) n (by omega) (by omega)).eq.symm, mul_assoc]

def first (r : ℕ → H) (n : ℕ) : Set H := {g | ∃ i, i < n ∧ r i = g}

/-- Every element generated by `n+1` adjacent generators is in one of `n+2`
right cosets of the subgroup generated by the first `n`. -/
lemma normal_form {r : ℕ → H} {n : ℕ} (h : Relations r (n+1)) {g : H}
    (hg : g ∈ Subgroup.closure (first r (n+1))) :
    ∃ (i : ℕ), i ≤ n+1 ∧ ∃ k ∈ Subgroup.closure (first r n),
      g = k * descending r i (n+1) := by
  have step (g : H) (j : ℕ) (hj : j < n+1)
      (hg : ∃ i, i ≤ n+1 ∧ ∃ k ∈ Subgroup.closure (first r n),
        g = k * descending r i (n+1)) :
      ∃ i, i ≤ n+1 ∧ ∃ k ∈ Subgroup.closure (first r n),
        g * r j = k * descending r i (n+1) := by
    obtain ⟨i,hi,k,hk,rfl⟩ := hg
    rw [mul_assoc,descending_mul h i hi j hj]
    split_ifs with h₁ h₂ h₃
    · refine ⟨i,hi,k*r j,Subgroup.mul_mem _ hk ?_,(mul_assoc _ _ _).symm⟩
      exact Subgroup.subset_closure ⟨j,by omega,rfl⟩
    · exact ⟨j,by omega,k,hk,rfl⟩
    · exact ⟨i+1,by omega,k,hk,rfl⟩
    · refine ⟨i,hi,k*r (j-1),Subgroup.mul_mem _ hk ?_,(mul_assoc _ _ _).symm⟩
      exact Subgroup.subset_closure ⟨j-1,by omega,rfl⟩
  induction hg using Subgroup.closure_induction_right with
  | one =>
    exact ⟨n+1,le_rfl,1,Subgroup.one_mem _,by rw [descending_empty r le_rfl,mul_one]⟩
  | mul_right g hg a ha ih =>
    obtain ⟨i,hi,rfl⟩ := ha
    exact step g i hi ih
  | mul_inv_cancel g hg a ha ih =>
    obtain ⟨i,hi,rfl⟩ := ha
    rw [inv_eq_of_mul_eq_one_right (h.square i hi)]
    exact step g i hi ih

end

section
universe u

/-- The usual finite type-A Coxeter presentation. -/
def relators (n : ℕ) : Set (FreeGroup (Fin n)) := {w |
  (∃ i, w = FreeGroup.of i * FreeGroup.of i) ∨
  (∃ i j : Fin n, (j : ℕ) = (i : ℕ)+1 ∧ w =
    (FreeGroup.of j * FreeGroup.of i * FreeGroup.of j) *
      (FreeGroup.of i * FreeGroup.of j * FreeGroup.of i)⁻¹) ∨
  (∃ i j : Fin n, (i : ℕ)+1 < (j : ℕ) ∧ w =
    (FreeGroup.of i * FreeGroup.of j) * (FreeGroup.of j * FreeGroup.of i)⁻¹)}

abbrev Presentation (n : ℕ) := PresentedGroup (relators n)

noncomputable def generator (n i : ℕ) : Presentation n :=
  if hi : i < n then PresentedGroup.of ⟨i,hi⟩ else 1

@[simp] lemma generator_lt {n i : ℕ} (hi : i < n) :
    generator n i = PresentedGroup.of ⟨i,hi⟩ := dite_eq_left hi
@[simp] lemma generator_ge {n i : ℕ} (hi : n ≤ i) : generator n i = 1 :=
  dite_eq_right (by omega)

lemma generator_relations (n : ℕ) : Relations (generator n) n := by
  constructor
  · intro i hi
    simpa only [generator_lt hi, map_mul, PresentedGroup.of] using
      (PresentedGroup.one_of_mem (rels:=relators n)
        (show FreeGroup.of ⟨i,hi⟩ * FreeGroup.of ⟨i,hi⟩ ∈ relators n from
          Or.inl ⟨⟨i,hi⟩,rfl⟩))
  · intro i hi
    have h := PresentedGroup.one_of_mem (rels:=relators n)
      (show (FreeGroup.of ⟨i+1,hi⟩ * FreeGroup.of ⟨i,by omega⟩ * FreeGroup.of ⟨i+1,hi⟩) *
          (FreeGroup.of ⟨i,by omega⟩ * FreeGroup.of ⟨i+1,hi⟩ * FreeGroup.of ⟨i,by omega⟩)⁻¹ ∈ relators n from
        Or.inr (Or.inl ⟨⟨i,by omega⟩,⟨i+1,hi⟩,rfl,rfl⟩))
    simpa only [map_mul,map_inv,PresentedGroup.of,mul_inv_eq_one,generator_lt hi,
      generator_lt (show i<n by omega)] using h
  · intro i j hij hj
    have h := PresentedGroup.one_of_mem (rels:=relators n)
      (show (FreeGroup.of ⟨i,by omega⟩ * FreeGroup.of ⟨j,hj⟩) *
          (FreeGroup.of ⟨j,hj⟩ * FreeGroup.of ⟨i,by omega⟩)⁻¹ ∈ relators n from
        Or.inr (Or.inr ⟨⟨i,by omega⟩,⟨j,hj⟩,hij,rfl⟩))
    simpa only [map_mul,map_inv,PresentedGroup.of,mul_inv_eq_one,generator_lt hj,
      generator_lt (show i<n by omega),Commute,SemiconjBy] using h

variable {H : Type u} [Group H]
lemma relators_valid {r : ℕ → H} {n : ℕ} (h : Relations r n) :
    ∀ w ∈ relators n, FreeGroup.lift (fun i : Fin n => r i) w = 1 := by
  rintro w (⟨i,rfl⟩ | ⟨i,j,hij,rfl⟩ | ⟨i,j,hij,rfl⟩)
  · simpa only [map_mul,FreeGroup.lift_apply_of] using h.square i i.isLt
  · simp only [map_mul,map_inv,FreeGroup.lift_apply_of,mul_inv_eq_one]
    simpa only [hij] using h.braid i (by omega)
  · simp only [map_mul,map_inv,FreeGroup.lift_apply_of,mul_inv_eq_one]
    exact (h.distant i j hij j.isLt).eq

noncomputable def lift {r : ℕ → H} {n : ℕ} (h : Relations r n) : Presentation n →* H :=
  PresentedGroup.toGroup (relators_valid h)

@[simp] lemma lift_of {r : ℕ → H} {n : ℕ} (h : Relations r n) (i : Fin n) :
    lift h (PresentedGroup.of i) = r i := PresentedGroup.toGroup.of _
@[simp] lemma lift_generator {r : ℕ → H} {n i : ℕ} (h : Relations r n) (hi : i < n) :
    lift h (generator n i) = r i := by rw [generator_lt hi,lift_of]

lemma closure_first (n : ℕ) : Subgroup.closure (first (generator n) n) = ⊤ := by
  rw [show first (generator n) n = Set.range (PresentedGroup.of (rels:=relators n)) by
    ext g
    constructor
    · rintro ⟨i,hi,rfl⟩; exact ⟨⟨i,hi⟩,(generator_lt hi).symm⟩
    · rintro ⟨i,rfl⟩; exact ⟨i,i.isLt,generator_lt i.isLt⟩]
  exact PresentedGroup.closure_range_of _

noncomputable def inclusion (n : ℕ) : Presentation n →* Presentation (n+1) :=
  lift ((generator_relations (n+1)).mono (Nat.le_succ n))

@[simp] lemma inclusion_of (n : ℕ) (i : Fin n) :
    inclusion n (PresentedGroup.of i) = generator (n+1) i := lift_of _ i

lemma presentation_normal (n : ℕ) (g : Presentation (n+1)) :
    ∃ i, i ≤ n+1 ∧ ∃ k : Presentation n,
      g = inclusion n k * descending (generator (n+1)) i (n+1) := by
  have hg : g ∈ Subgroup.closure (first (generator (n+1)) (n+1)) := by
    rw [closure_first]; trivial
  obtain ⟨i,hi,k,hk,hg⟩ := normal_form (generator_relations (n+1)) hg
  have hm : Subgroup.closure (first (generator (n+1)) n) ≤ (inclusion n).range := by
    rw [Subgroup.closure_le]
    rintro z ⟨j,hj,rfl⟩
    exact ⟨PresentedGroup.of ⟨j,hj⟩,inclusion_of n ⟨j,hj⟩⟩
  obtain ⟨k,rfl⟩ := hm hk
  exact ⟨i,hi,k,hg⟩

end

universe u

lemma map_descending {H K : Type*} [Group H] [Group K] (f : H →* K)
    (r : ℕ → H) (i n : ℕ) : f (descending r i n) = descending (fun j => f (r j)) i n := by
  induction n with
  | zero => exact map_one f
  | succ n ih => simp only [descending]; split_ifs <;> simp [ih]

def natSwap (i : ℕ) : Equiv.Perm ℕ := Equiv.swap i (i+1)

lemma natSwap_relations (n : ℕ) : Relations natSwap n := by
  constructor
  · intro i _; exact Equiv.swap_mul_self _ _
  · intro i _
    ext a
    simp only [natSwap,Equiv.Perm.mul_apply,Equiv.swap_apply_def]
    split_ifs <;> omega
  · intro i j hij _
    apply Equiv.Perm.Disjoint.commute
    apply Equiv.Perm.disjoint_swap_swap
    simp only [List.nodup_cons,List.mem_cons,List.not_mem_nil,
      not_false_eq_true,List.nodup_nil,and_true,not_or]
    omega

noncomputable def natEvaluation (n : ℕ) : Presentation n →* Equiv.Perm ℕ :=
  lift (natSwap_relations n)

@[simp] lemma natEvaluation_of (n : ℕ) (i : Fin n) :
    natEvaluation n (PresentedGroup.of i) = natSwap i := lift_of _ _
@[simp] lemma natEvaluation_generator {n i : ℕ} (hi : i < n) :
    natEvaluation n (generator n i) = natSwap i := lift_generator _ hi

lemma natEvaluation_inclusion (n : ℕ) :
    (natEvaluation (n+1)).comp (inclusion n) = natEvaluation n := by
  apply PresentedGroup.ext
  intro i
  simp [show (i:ℕ)<n+1 by omega]

lemma natEvaluation_fixes {n : ℕ} (g : Presentation n) {k : ℕ} (hk : n < k) :
    natEvaluation n g k = k := by
  have hg : g ∈ Subgroup.closure (first (generator n) n) := by rw [closure_first]; trivial
  induction hg using Subgroup.closure_induction_right with
  | one => simp
  | mul_right g hg a ha ih =>
    obtain ⟨i,hi,rfl⟩ := ha
    rw [map_mul,Equiv.Perm.mul_apply,natEvaluation_generator hi]
    simpa [natSwap,Equiv.swap_apply_def,show k≠i by omega,show k≠i+1 by omega] using ih
  | mul_inv_cancel g hg a ha ih =>
    obtain ⟨i,hi,rfl⟩ := ha
    rw [inv_eq_of_mul_eq_one_right ((generator_relations n).square i hi)]
    rw [map_mul,Equiv.Perm.mul_apply,natEvaluation_generator hi]
    simpa [natSwap,Equiv.swap_apply_def,show k≠i by omega,show k≠i+1 by omega] using ih

lemma descending_nat_apply {i n : ℕ} (hi : i ≤ n) : descending natSwap i n i = n := by
  induction n with
  | zero =>
    have : i=0 := by omega
    subst i
    rfl
  | succ n ih =>
    by_cases hin : i ≤ n
    · rw [descending_step natSwap hin,Equiv.Perm.mul_apply,ih hin]
      exact Equiv.swap_apply_left _ _
    · have : i=n+1 := by omega
      subst i
      rw [descending_empty natSwap le_rfl]; rfl

lemma natEvaluation_descending {n i : ℕ} (hi : i ≤ n) :
    natEvaluation n (descending (generator n) i n) i = n := by
  have hmap (m : ℕ) (hm : m ≤ n) :
      natEvaluation n (descending (generator n) i m) = descending natSwap i m := by
    induction m with
    | zero => simp
    | succ m ih =>
      simp only [descending]
      split_ifs <;> simp [show m<n by omega,ih (by omega)]
  rw [hmap n le_rfl]
  exact descending_nat_apply hi

lemma natEvaluation_injective (n : ℕ) : Function.Injective (natEvaluation n) := by
  apply (MonoidHom.ker_eq_bot_iff _).mp
  apply le_antisymm _ bot_le
  intro g hg
  change natEvaluation n g = 1 at hg
  change g = 1
  induction n with
  | zero =>
    have hc := closure_first 0
    have he : first (generator 0) 0 = ∅ := by ext g; simp [first]
    rw [he,Subgroup.closure_empty] at hc
    have : g ∈ (⊥ : Subgroup (Presentation 0)) := by rw [hc]; trivial
    exact this
  | succ n ih =>
    obtain ⟨i,hi,k,rfl⟩ := presentation_normal n g
    have he : natEvaluation (n+1) (inclusion n k) = natEvaluation n k :=
      DFunLike.congr_fun (natEvaluation_inclusion n) k
    have ha := congrArg (fun f : Equiv.Perm ℕ => f i) hg
    rw [map_mul,Equiv.Perm.mul_apply,he,natEvaluation_descending hi,
      natEvaluation_fixes k (Nat.lt_succ_self n)] at ha
    change n+1=i at ha
    subst i
    rw [descending_empty _ le_rfl,mul_one] at hg ⊢
    rw [he] at hg
    rw [ih hg,map_one]

noncomputable def natExtend (n : ℕ) : Equiv.Perm (Fin n) →* Equiv.Perm ℕ :=
  Equiv.Perm.ofSubtype.comp (Equiv.permCongrHom Fin.equivSubtype).toMonoidHom

lemma natExtend_injective (n : ℕ) : Function.Injective (natExtend n) :=
  Equiv.Perm.ofSubtype_injective.comp (Equiv.permCongrHom Fin.equivSubtype).injective

@[simp] lemma natExtend_swap (n : ℕ) (i j : Fin n) :
    natExtend n (Equiv.swap i j) = Equiv.swap (i:ℕ) (j:ℕ) := by
  have hc : (Equiv.permCongrHom Fin.equivSubtype) (Equiv.swap i j) =
      Equiv.swap (Fin.equivSubtype i) (Fin.equivSubtype j) :=
    Equiv.symm_trans_swap_trans i j Fin.equivSubtype
  rw [natExtend,MonoidHom.comp_apply,MulEquiv.coe_toMonoidHom,hc,Equiv.Perm.ofSubtype_swap_eq]
  rfl

noncomputable def finSwap (n i : ℕ) : Equiv.Perm (Fin (n+1)) :=
  if hi : i < n then Equiv.swap ⟨i,by omega⟩ ⟨i+1,by omega⟩ else 1

lemma finSwap_lt {n i : ℕ} (hi : i < n) :
    finSwap n i = Equiv.swap ⟨i,by omega⟩ ⟨i+1,by omega⟩ := dite_eq_left hi

lemma natExtend_finSwap {n i : ℕ} (hi : i < n) :
    natExtend (n+1) (finSwap n i) = natSwap i := by
  rw [finSwap_lt hi,natExtend_swap]; rfl

lemma finSwap_relations (n : ℕ) : Relations (finSwap n) n := by
  constructor
  · intro i hi
    apply natExtend_injective (n+1)
    simpa only [map_mul,natExtend_finSwap hi,map_one] using (natSwap_relations n).square i hi
  · intro i hi
    apply natExtend_injective (n+1)
    simpa only [map_mul,natExtend_finSwap hi,natExtend_finSwap (show i<n by omega)] using
      (natSwap_relations n).braid i hi
  · intro i j hij hj
    apply (natExtend_injective (n+1))
    simpa only [map_mul,natExtend_finSwap hj,natExtend_finSwap (show i<n by omega)] using
      ((natSwap_relations n).distant i j hij hj).eq

noncomputable def finEvaluation (n : ℕ) : Presentation n →* Equiv.Perm (Fin (n+1)) :=
  lift (finSwap_relations n)

@[simp] lemma finEvaluation_of (n : ℕ) (i : Fin n) :
    finEvaluation n (PresentedGroup.of i) = Equiv.swap i.castSucc i.succ := by
  rw [finEvaluation,lift_of,finSwap_lt i.isLt]; rfl

lemma natExtend_finEvaluation (n : ℕ) :
    (natExtend (n+1)).comp (finEvaluation n) = natEvaluation n := by
  apply PresentedGroup.ext
  intro i
  simp only [MonoidHom.comp_apply,finEvaluation_of,natExtend_swap,natEvaluation_of]
  rfl

lemma finEvaluation_bijective (n : ℕ) : Function.Bijective (finEvaluation n) := by
  constructor
  · exact Function.Injective.of_comp (f:=natExtend (n+1))
      (show Function.Injective ((natExtend (n+1)) ∘ finEvaluation n) from
        by
          change Function.Injective (((natExtend (n+1)).comp (finEvaluation n)) : _ → _)
          rw [natExtend_finEvaluation]
          exact natEvaluation_injective n)
  · have hc : Submonoid.closure (Set.range fun i : Fin n => Equiv.swap i.castSucc i.succ) ≤
        (finEvaluation n).range.toSubmonoid := by
      rw [Submonoid.closure_le]
      rintro s ⟨i,rfl⟩
      exact ⟨PresentedGroup.of i,finEvaluation_of n i⟩
    intro p
    have hp : p ∈ (finEvaluation n).range := hc (by
      rw [Equiv.Perm.mclosure_swap_castSucc_succ]; trivial)
    exact hp

noncomputable def permutationEquiv (n : ℕ) : Presentation n ≃* Equiv.Perm (Fin (n+1)) :=
  MulEquiv.ofBijective (finEvaluation n) (finEvaluation_bijective n)

/-- Coxeter's relations are sufficient, not just necessary: any adjacent family
satisfying the three local laws gives a canonical finite permutation action. -/
noncomputable def permutationLift {H : Type u} [Group H] {n : ℕ} {r : ℕ → H}
    (h : Relations r n) : Equiv.Perm (Fin (n+1)) →* H :=
  (lift h).comp (permutationEquiv n).symm.toMonoidHom

@[simp] lemma permutationLift_swap {H : Type u} [Group H] {n : ℕ} {r : ℕ → H}
    (h : Relations r n) (i : Fin n) :
    permutationLift h (Equiv.swap i.castSucc i.succ) = r i := by
  change lift h ((permutationEquiv n).symm _) = r i
  rw [show Equiv.swap i.castSucc i.succ = permutationEquiv n (PresentedGroup.of i) from
    (finEvaluation_of n i).symm,MulEquiv.symm_apply_apply,lift_of]

end FiniteAlgebraicEnvelopes.Adjacent

end OAI
