import Mathlib

namespace OAI

noncomputable section

/-!
Cantor prefixes, bricks, charts, finite-table group, localization, and displacement.
-/

namespace FiniteAlgebraicEnvelopes.TwistedBrinThompson

section
universe u v
attribute [local instance] Classical.propDecidable

/-- The Cantor cube used by the twisted Brin--Thompson construction. -/
abbrev Cube (X : Type u) := X → Stream' Bool

/-- A dyadic brick has only finitely many nonempty coordinate prefixes. -/
structure Prefix (X : Type u) where
  word : X → List Bool
  finite_support : {x | word x ≠ []}.Finite

namespace Prefix
variable {X : Type u}

def empty : Prefix X := ⟨fun _ => [], by simp⟩

def attach (p : Prefix X) (z : Cube X) : Cube X :=
  fun x => Stream'.appendStream' (p.word x) (z x)

@[simp] theorem empty_attach (z : Cube X) : empty.attach z = z := by
  funext x
  exact Stream'.nil_append_stream _

theorem attach_injective (p : Prefix X) : Function.Injective p.attach := by
  intro z w he
  funext x
  exact Stream'.append_right_injective (p.word x) (z x) (w x) (congrFun he x)

def oneBit (x : X) (b : Bool) : Prefix X := by
  classical
  exact ⟨fun y => if y=x then [b] else [],
    (Set.finite_singleton x).subset (by
      intro y hy
      by_contra hn
      exact hy (ite_eq_right hn))⟩

@[simp] theorem oneBit_word (x y : X) (b : Bool) :
    (oneBit x b).word y = if y=x then [b] else [] := by classical exact rfl

lemma mem_oneBit (x : X) (b : Bool) (z : Cube X) :
    (∃ w, (oneBit x b).attach w=z) ↔ z x 0=b := by
  classical
  constructor
  · rintro ⟨w,rfl⟩
    simp [attach,Stream'.cons]
  · intro hz
    refine ⟨fun y => if y=x then Stream'.tail (z y) else z y,?_⟩
    funext y n
    by_cases hy : y=x
    · subst y
      cases n with
      | zero => simpa [attach,Stream'.appendStream',Stream'.cons] using hz.symm
      | succ n => simp [attach,Stream'.cons,Stream'.tail,Stream'.get]
    · simp [attach,hy]

end Prefix

variable {Γ : Type u} {X : Type v} [Group Γ] [MulAction Γ X]

/-- Coordinate permutation by the input group; precomposition is contravariant. -/
def twist (g : Γ) : Equiv.Perm (Cube X) where
  toFun z x := z (g⁻¹ • x)
  invFun z x := z (g • x)
  left_inv z := by funext x; simp
  right_inv z := by funext x; simp

@[simp] lemma twist_apply (g : Γ) (z : Cube X) (x : X) :
    twist g z x = z (g⁻¹ • x) := rfl

@[simp] lemma twist_one : twist (1 : Γ) = (1 : Equiv.Perm (Cube X)) := by
  ext z x n
  simp

lemma twist_mul (g h : Γ) : twist (g*h) = twist (X:=X) g * twist h := by
  ext z x n
  simp [mul_smul]

def twistHom : Γ →* Equiv.Perm (Cube X) where
  toFun := twist
  map_one' := twist_one
  map_mul' := twist_mul

theorem twist_injective [FaithfulSMul Γ X] : Function.Injective (twistHom (Γ:=Γ) (X:=X)) := by
  classical
  intro g h he
  have hcoord (x : X) : g⁻¹ • x = h⁻¹ • x := by
    by_contra hn
    let z : Cube X := fun y _ => if y=g⁻¹ • x then true else false
    have he' := congrFun (congrFun (Equiv.congr_fun he z) x) 0
    change (if g⁻¹ • x=g⁻¹ • x then true else false) =
      (if h⁻¹ • x=g⁻¹ • x then true else false) at he'
    simp [Ne.symm hn] at he'
  exact inv_injective (eq_of_smul_eq_smul hcoord)

/-- A finite prefix-replacement table, with one input-group twist on each brick.
The uniqueness clauses say that the source and target bricks are partitions. -/
structure Table (f : Equiv.Perm (Cube X)) where
  index : Type
  finite : Fintype index
  source : index → Prefix X
  target : index → Prefix X
  label : index → Γ
  source_cover : ∀ z : Cube X, ∃! i, ∃ w, (source i).attach w=z
  target_cover : ∀ z : Cube X, ∃! i, ∃ w, (target i).attach w=z
  chart : ∀ i z, f ((source i).attach z) = (target i).attach (twist (label i) z)

/-- Concrete permutation model generated by finite twisted dyadic tables. -/
def group : Subgroup (Equiv.Perm (Cube X)) :=
  Subgroup.closure {f | Nonempty (Table (Γ:=Γ) f)}

lemma twist_table (g : Γ) : Nonempty (Table (Γ:=Γ) (twist (X:=X) g)) := by
  refine ⟨⟨PUnit,inferInstance,fun _ => Prefix.empty,fun _ => Prefix.empty,
    fun _ => g,?_,?_,?_⟩⟩
  · intro z
    exact ⟨PUnit.unit,⟨z,Prefix.empty_attach z⟩,fun i _ => Subsingleton.elim _ _⟩
  · intro z
    exact ⟨PUnit.unit,⟨z,Prefix.empty_attach z⟩,fun i _ => Subsingleton.elim _ _⟩
  · intro i z
    simp

def embedding : Γ →* group (Γ:=Γ) (X:=X) :=
  (twistHom (Γ:=Γ) (X:=X)).codRestrict _
    (fun g => Subgroup.subset_closure (twist_table g))

theorem embedding_injective [FaithfulSMul Γ X] :
    Function.Injective (embedding (Γ:=Γ) (X:=X)) := by
  intro g h he
  exact twist_injective (congrArg Subtype.val he)

/-- The elementary swap in a single cube coordinate. -/
def bitFlip (x : X) : Equiv.Perm (Cube X) := by
  classical
  exact {
    toFun := fun z y n => if y=x ∧ n=0 then !(z y n) else z y n
    invFun := fun z y n => if y=x ∧ n=0 then !(z y n) else z y n
    left_inv := by intro z; funext y n; by_cases h : y=x ∧ n=0 <;> simp [h]
    right_inv := by intro z; funext y n; by_cases h : y=x ∧ n=0 <;> simp [h] }

@[simp] lemma bitFlip_apply (x : X) (z : Cube X) (y : X) (n : ℕ) :
    bitFlip x z y n = if y=x ∧ n=0 then !(z y n) else z y n := rfl

lemma bitFlip_table (x : X) : Nonempty (Table (Γ:=Γ) (bitFlip x)) := by
  classical
  refine ⟨⟨Bool,inferInstance,Prefix.oneBit x,fun b => Prefix.oneBit x (!b),
    fun _ => 1,?_,?_,?_⟩⟩
  · intro z
    refine ⟨z x 0,(Prefix.mem_oneBit x _ z).mpr rfl,?_⟩
    intro b hb
    exact ((Prefix.mem_oneBit x b z).mp hb).symm
  · intro z
    refine ⟨!(z x 0),(Prefix.mem_oneBit x _ z).mpr (by simp),?_⟩
    intro b hb
    have he := (Prefix.mem_oneBit x (!b) z).mp hb
    simpa using congrArg Bool.not he.symm
  · intro b z
    funext y n
    by_cases hy : y=x
    · subst y
      cases n <;> simp [Prefix.attach,Stream'.cons]
    · simp [Prefix.attach,hy]

lemma bitFlip_ne_one (x : X) : bitFlip x ≠ 1 := by
  classical
  intro he
  have h := congrFun (congrFun (Equiv.congr_fun he (fun _ _ => false)) x) 0
  change (if x=x ∧ (0 : ℕ)=0 then !false else false)=false at h
  simp at h

instance group_nontrivial [Nonempty X] : Nontrivial (group (Γ:=Γ) (X:=X)) := by
  obtain ⟨x⟩ := ‹Nonempty X›
  let f : group (Γ:=Γ) (X:=X) := ⟨bitFlip x,Subgroup.subset_closure (bitFlip_table x)⟩
  refine ⟨⟨f,1,?_⟩⟩
  intro he
  exact bitFlip_ne_one x (congrArg Subtype.val he)

end

section
universe u v
attribute [local instance] Classical.propDecidable
namespace Prefix
variable {X : Type u}

@[ext] lemma ext {p q : Prefix X} (h : ∀ x, p.word x=q.word x) : p=q := by
  cases p with | mk p hp => cases q with | mk q hq =>
    have he : p=q := funext h
    cases he
    rfl

lemma mem_range_iff (p : Prefix X) (z : Cube X) :
    (∃ w, p.attach w=z) ↔ ∀ x, (z x).take (p.word x).length = p.word x := by
  constructor
  · rintro ⟨w,rfl⟩ x
    exact (Stream'.take_append_of_le_length _ _ _ le_rfl).trans List.take_length
  · intro h
    refine ⟨fun x => (z x).drop (p.word x).length,?_⟩
    funext x
    change Stream'.appendStream' (p.word x) ((z x).drop (p.word x).length)=z x
    rw [← h x]
    simp

def comp (p q : Prefix X) : Prefix X :=
  ⟨fun x => p.word x ++ q.word x,(p.finite_support.union q.finite_support).subset
    (by
      intro x hx
      by_cases hp : p.word x=[]
      · exact Or.inr (by intro hq; exact hx (by simp [hp,hq]))
      · exact Or.inl hp)⟩

@[simp] lemma comp_word (p q : Prefix X) (x : X) :
    (p.comp q).word x = p.word x ++ q.word x := rfl

@[simp] lemma comp_attach (p q : Prefix X) (z : Cube X) :
    (p.comp q).attach z = p.attach (q.attach z) := by
  funext x
  exact Stream'.append_append_stream _ _ _

def Extends (p q : Prefix X) : Prop := ∀ x, p.word x <+: q.word x

lemma extends_refl (p : Prefix X) : p.Extends p := fun _ => ⟨[],by simp⟩

def remainder (p q : Prefix X) : Prefix X :=
  ⟨fun x => (q.word x).drop (p.word x).length,q.finite_support.subset
    (by intro x hx hq; exact hx (by simp [hq]))⟩

@[simp] lemma remainder_word (p q : Prefix X) (x : X) :
    (p.remainder q).word x = (q.word x).drop (p.word x).length := rfl

lemma comp_remainder {p q : Prefix X} (h : p.Extends q) : p.comp (p.remainder q)=q := by
  apply Prefix.ext
  intro x
  change p.word x ++ (q.word x).drop (p.word x).length=q.word x
  obtain ⟨r,hr⟩ := h x
  rw [← hr]
  simp

lemma extends_of_ranges {p q : Prefix X}
    (h : ∀ z, (∃ w, q.attach w=z) → ∃ w, p.attach w=z) : p.Extends q := by
  intro x
  by_cases hl : (p.word x).length ≤ (q.word x).length
  · let z : Cube X := q.attach (fun _ _ => false)
    have hp := (mem_range_iff p z).mp (h z ⟨fun _ _ => false,rfl⟩) x
    have htake : (z x).take (p.word x).length = (q.word x).take (p.word x).length :=
      Stream'.take_append_of_le_length _ _ _ hl
    rw [htake] at hp
    rw [← hp]
    exact List.take_prefix _ _
  · have hlt : (q.word x).length < (p.word x).length := by omega
    let a₀ : Stream' Bool := fun _ => false
    let a₁ : Stream' Bool := fun _ => true
    let z₀ : Cube X := q.attach (fun _ => a₀)
    let z₁ : Cube X := q.attach (fun _ => a₁)
    have hp₀ := (mem_range_iff p z₀).mp (h z₀ ⟨fun _ => a₀,rfl⟩) x
    have hp₁ := (mem_range_iff p z₁).mp (h z₁ ⟨fun _ => a₁,rfl⟩) x
    have he := congrArg (fun (l : List Bool) => l[(q.word x).length]?) (hp₀.trans hp₁.symm)
    rw [Stream'.getElem?_take hlt,Stream'.getElem?_take hlt] at he
    simp only [z₀,z₁,attach] at he
    rw [Stream'.get_append_length,Stream'.get_append_length] at he
    simp [a₀,a₁,Stream'.get] at he

/-- Nonempty intersection of the two dyadic bricks. -/
def Compatible (p q : Prefix X) : Prop := ∃ z, (∃ w,p.attach w=z) ∧ ∃ w,q.attach w=z

def commonPoint {p q : Prefix X} (h : p.Compatible q) : Cube X := h.choose

lemma commonPoint_mem_left {p q : Prefix X} (h : p.Compatible q) :
    ∃ w, p.attach w=commonPoint h := h.choose_spec.1

lemma commonPoint_mem_right {p q : Prefix X} (h : p.Compatible q) :
    ∃ w, q.attach w=commonPoint h := h.choose_spec.2

/-- Intersection is again one brick: take the longer prefix at each coordinate. -/
def meet {p q : Prefix X} (h : p.Compatible q) : Prefix X :=
  ⟨fun x => ((commonPoint h) x).take (max (p.word x).length (q.word x).length),
    (p.finite_support.union q.finite_support).subset (by
      intro x hx
      by_contra hn
      have hp : p.word x=[] := by simpa using (not_or.mp hn).1
      have hq : q.word x=[] := by simpa using (not_or.mp hn).2
      exact hx (by simp [hp,hq]))⟩

lemma meet_extends_left {p q : Prefix X} (h : p.Compatible q) : p.Extends (meet h) := by
  intro x
  have hp := (mem_range_iff p _).mp (commonPoint_mem_left h) x
  rw [← hp]
  exact Stream'.take_prefix_take_left _ _ _ (le_max_left _ _)

lemma meet_extends_right {p q : Prefix X} (h : p.Compatible q) : q.Extends (meet h) := by
  intro x
  have hq := (mem_range_iff q _).mp (commonPoint_mem_right h) x
  rw [← hq]
  exact Stream'.take_prefix_take_left _ _ _ (le_max_right _ _)

lemma mem_range_of_extends {p q : Prefix X} (h : p.Extends q) {z : Cube X}
    (hz : ∃ w,q.attach w=z) : ∃ w,p.attach w=z := by
  obtain ⟨w,rfl⟩ := hz
  rw [← comp_remainder h,comp_attach]
  exact ⟨_,rfl⟩

lemma mem_meet_iff {p q : Prefix X} (h : p.Compatible q) (z : Cube X) :
    (∃ w,(meet h).attach w=z) ↔ (∃ w,p.attach w=z) ∧ ∃ w,q.attach w=z := by
  constructor
  · intro hz
    exact ⟨mem_range_of_extends (meet_extends_left h) hz,
      mem_range_of_extends (meet_extends_right h) hz⟩
  · rintro ⟨hp,hq⟩
    apply (mem_range_iff _ _).mpr
    intro x
    change (z x).take (((commonPoint h) x).take _).length =
      ((commonPoint h) x).take (max (p.word x).length (q.word x).length)
    rw [Stream'.length_take]
    have hp' := (mem_range_iff p _).mp hp x
    have hq' := (mem_range_iff q _).mp hq x
    have hc₁ := (mem_range_iff p _).mp (commonPoint_mem_left h) x
    have hc₂ := (mem_range_iff q _).mp (commonPoint_mem_right h) x
    rcases le_total (p.word x).length (q.word x).length with hl|hl
    · rw [max_eq_right hl,hq',hc₂]
    · rw [max_eq_left hl,hp',hc₁]

end Prefix

variable {Γ : Type u} {X : Type v} [Group Γ] [MulAction Γ X]

/-- The induced coordinate permutation on finite prefixes. -/
def twistPrefix (g : Γ) (p : Prefix X) : Prefix X :=
  ⟨fun x => p.word (g⁻¹ • x),p.finite_support.preimage
    (MulAction.injective (g⁻¹ : Γ)).injOn⟩

@[simp] lemma twistPrefix_word (g : Γ) (p : Prefix X) (x : X) :
    (twistPrefix g p).word x=p.word (g⁻¹ • x) := rfl

@[simp] lemma twist_attach (g : Γ) (p : Prefix X) (z : Cube X) :
    twist g (p.attach z) = (twistPrefix g p).attach (twist g z) := rfl

lemma untwist_attach (g : Γ) (p : Prefix X) (z : Cube X) :
    twist g ((twistPrefix g⁻¹ p).attach z) = p.attach (twist g z) := by
  ext x n
  simp [Prefix.attach]

end

section
universe u
attribute [local instance] Classical.propDecidable

/-- A finite dyadic partition of the entire cube. -/
structure Partition (X : Type u) where
  index : Type
  finite : Fintype index
  brick : index → Prefix X
  cover : ∀ z : Cube X, ∃! i, ∃ w,(brick i).attach w=z

namespace Partition
variable {X : Type u}

def trivial : Partition X where
  index := PUnit
  finite := inferInstance
  brick _ := Prefix.empty
  cover z := ⟨PUnit.unit,⟨z,Prefix.empty_attach z⟩,fun _ _=>Subsingleton.elim _ _⟩

abbrev bit (x : X) : Partition X where
  index := Bool
  finite := inferInstance
  brick := Prefix.oneBit x
  cover z := ⟨z x 0,(Prefix.mem_oneBit x _ z).mpr rfl,
    fun b hb => ((Prefix.mem_oneBit x b z).mp hb).symm⟩

def RefineIndex (P Q : Partition X) (i : P.index) := {j : P.index // j≠i} ⊕ Q.index

instance refineIndex_finite (P Q : Partition X) (i : P.index) : Fintype (RefineIndex P Q i) := by
  letI := P.finite
  letI := Q.finite
  exact inferInstanceAs (Fintype ({j : P.index // j≠i} ⊕ Q.index))

def refineBrick (P Q : Partition X) (i : P.index) : RefineIndex P Q i → Prefix X
  | Sum.inl j => P.brick j.val
  | Sum.inr j => (P.brick i).comp (Q.brick j)

lemma refine_cover (P Q : Partition X) (i : P.index) :
    ∀ z : Cube X, ∃! j : RefineIndex P Q i, ∃ w,(refineBrick P Q i j).attach w=z := by
  intro z
  obtain ⟨k,⟨v,hv⟩,hk⟩ := P.cover z
  by_cases hki : k=i
  · subst k
    obtain ⟨j,⟨w,hw⟩,hj⟩ := Q.cover v
    refine ⟨Sum.inr j,⟨w,?_⟩,?_⟩
    · change ((P.brick i).comp (Q.brick j)).attach w=z
      rw [Prefix.comp_attach,hw,hv]
    · intro b hb
      cases b with
      | inl b =>
          have hb' : b.val=i := hk _ hb
          exact (b.property hb').elim
      | inr b =>
          obtain ⟨a,ha⟩ := hb
          have hab : (Q.brick b).attach a=v :=
            (P.brick i).attach_injective ((Prefix.comp_attach _ _ _).symm.trans (ha.trans hv.symm))
          exact congrArg Sum.inr (hj b ⟨a,hab⟩)
  · refine ⟨Sum.inl ⟨k,hki⟩,⟨v,hv⟩,?_⟩
    intro b hb
    cases b with
    | inl b =>
        exact congrArg Sum.inl (Subtype.ext (hk _ hb))
    | inr b =>
        obtain ⟨w,hw⟩ := hb
        have hik : i=k := hk i ⟨(Q.brick b).attach w,
          (Prefix.comp_attach _ _ _).symm.trans hw⟩
        exact (hki hik.symm).elim

def refinement (P Q : Partition X) (i : P.index) : Partition X where
  index := RefineIndex P Q i
  finite := refineIndex_finite P Q i
  brick := refineBrick P Q i
  cover := refine_cover P Q i

end Partition

namespace Prefix
variable {X : Type u}

/-- The brick occurs as one member of an actual finite partition. -/
def HasPartition (p : Prefix X) : Prop := ∃ P : Partition X, ∃ i, P.brick i=p

lemma empty_hasPartition : (empty : Prefix X).HasPartition :=
  ⟨Partition.trivial,PUnit.unit,rfl⟩

lemma oneBit_hasPartition (x : X) (b : Bool) : (oneBit x b).HasPartition :=
  ⟨Partition.bit x,b,rfl⟩

lemma comp_hasPartition {p q : Prefix X} (hp : p.HasPartition) (hq : q.HasPartition) :
    (p.comp q).HasPartition := by
  obtain ⟨P,i,hi⟩ := hp
  obtain ⟨Q,j,hj⟩ := hq
  refine ⟨P.refinement Q i,Sum.inr j,?_⟩
  change (P.brick i).comp (Q.brick j)=p.comp q
  rw [hi,hj]

def atWord (x : X) (w : List Bool) : Prefix X :=
  ⟨fun y => if y=x then w else [],(Set.finite_singleton x).subset (by
    intro y hy
    by_contra hn
    exact hy (ite_eq_right hn))⟩

@[simp] lemma atWord_word (x y : X) (w : List Bool) :
    (atWord x w).word y=if y=x then w else [] := rfl

lemma atWord_nil (x : X) : atWord x []=empty := by
  apply Prefix.ext
  intro y
  simp [empty]

lemma atWord_cons (x : X) (b : Bool) (w : List Bool) :
    atWord x (b::w)=(oneBit x b).comp (atWord x w) := by
  apply Prefix.ext
  intro y
  by_cases hy : y=x <;> simp [hy]

lemma atWord_hasPartition (x : X) (w : List Bool) : (atWord x w).HasPartition := by
  induction w with
  | nil => rw [atWord_nil]; exact empty_hasPartition
  | cons b w ih =>
      rw [atWord_cons]
      exact comp_hasPartition (oneBit_hasPartition x b) ih

def erase (p : Prefix X) (x : X) : Prefix X :=
  ⟨fun y => if y=x then [] else p.word y,p.finite_support.subset (by
    intro y hy he
    exact hy (by simp [he]))⟩

@[simp] lemma erase_word (p : Prefix X) (x y : X) :
    (p.erase x).word y=if y=x then [] else p.word y := rfl

lemma atWord_comp_erase (p : Prefix X) (x : X) :
    (atWord x (p.word x)).comp (p.erase x)=p := by
  apply Prefix.ext
  intro y
  by_cases hy : y=x
  · subst y; simp
  · simp [hy]

/-- Every finite dyadic brick has a finite dyadic complement partition. -/
theorem hasPartition (p : Prefix X) : p.HasPartition := by
  suffices ∀ (s : Finset X) (q : Prefix X),
      (∀ x,q.word x≠[] → x∈s) → q.HasPartition by
    exact this p.finite_support.toFinset p (by intro x hx; simpa using hx)
  intro s
  induction s using Finset.induction_on with
  | empty =>
      intro q hq
      have he : q=empty := by
        apply Prefix.ext
        intro x
        have hx : q.word x=[] := by
          by_contra hn
          exact Finset.notMem_empty x (hq x hn)
        exact hx
      rw [he]
      exact empty_hasPartition
  | @insert x s hx ih =>
      intro q hq
      have he : (q.erase x).HasPartition := ih _ (by
        intro y hy
        have hne : y≠x := by intro hyx; subst y; simp at hy
        have hn : q.word y≠[] := by simpa [hne] using hy
        exact (Finset.mem_insert.mp (hq y hn)).resolve_left hne)
      have hh := comp_hasPartition (atWord_hasPartition x (q.word x)) he
      rwa [atWord_comp_erase] at hh

end Prefix

end

section
universe u v
attribute [local instance] Classical.propDecidable
variable {Γ : Type u} {X : Type v} [Group Γ] [MulAction Γ X]

@[simp] lemma twist_inv_twist (g : Γ) (z : Cube X) : twist g⁻¹ (twist g z)=z := by
  ext x n
  simp

@[simp] lemma twist_twist_inv (g : Γ) (z : Cube X) : twist g (twist g⁻¹ z)=z := by
  ext x n
  simp

lemma twist_twist (g h : Γ) (z : Cube X) : twist g (twist h z)=twist (g*h) z := by
  ext x n
  simp [mul_smul]

namespace Table

/-- Target partition follows from the source partition and the bijective charts. -/
lemma transport_partition {I : Type} (f : Equiv.Perm (Cube X))
    (p q : I → Prefix X) (a : I → Γ)
    (hp : ∀ z : Cube X, ∃! i, ∃ w, (p i).attach w=z)
    (hchart : ∀ i z, f ((p i).attach z) = (q i).attach (twist (a i) z)) :
    ∀ z : Cube X, ∃! i, ∃ w, (q i).attach w=z := by
  intro z
  obtain ⟨i,⟨w,hw⟩,hi⟩ := hp (f.symm z)
  refine ⟨i,⟨twist (a i) w,?_⟩,?_⟩
  · rw [← hchart,hw,Equiv.apply_symm_apply]
  · intro j hj
    apply hi j
    obtain ⟨v,hv⟩ := hj
    refine ⟨twist (a j)⁻¹ v,?_⟩
    apply f.injective
    rw [hchart,twist_twist_inv,hv,Equiv.apply_symm_apply]

def inverse {f : Equiv.Perm (Cube X)} (A : Table (Γ:=Γ) f) : Table (Γ:=Γ) f⁻¹ where
  index := A.index
  finite := A.finite
  source := A.target
  target := A.source
  label i := (A.label i)⁻¹
  source_cover := A.target_cover
  target_cover := A.source_cover
  chart i z := by
    apply f.injective
    change f (f.symm ((A.target i).attach z)) = _
    rw [Equiv.apply_symm_apply,A.chart,twist_twist_inv]

variable {f g : Equiv.Perm (Cube X)}

/-- The nonempty intersections of the intermediate partitions. -/
def Overlap (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) :=
  {ij : A.index × B.index // (A.target ij.1).Compatible (B.source ij.2)}

instance overlap_fintype (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) : Fintype (Overlap A B) := by
  letI := A.finite
  letI := B.finite
  exact inferInstanceAs (Fintype {ij : A.index × B.index //
    (A.target ij.1).Compatible (B.source ij.2)})

def middle (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) : Prefix X :=
  Prefix.meet ij.property

def leftRemainder (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) : Prefix X :=
  (A.target ij.val.1).remainder (middle A B ij)

def rightRemainder (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) : Prefix X :=
  (B.source ij.val.2).remainder (middle A B ij)

def domain (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) : Prefix X :=
  (A.source ij.val.1).comp (twistPrefix (A.label ij.val.1)⁻¹ (leftRemainder A B ij))

def codomain (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) : Prefix X :=
  (B.target ij.val.2).comp (twistPrefix (B.label ij.val.2) (rightRemainder A B ij))

lemma leftFactor (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) :
    (A.target ij.val.1).comp (leftRemainder A B ij)=middle A B ij :=
  Prefix.comp_remainder (Prefix.meet_extends_left ij.property)

lemma rightFactor (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B) :
    (B.source ij.val.2).comp (rightRemainder A B ij)=middle A B ij :=
  Prefix.comp_remainder (Prefix.meet_extends_right ij.property)

lemma domain_chart (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B)
    (z : Cube X) :
    f ((domain A B ij).attach z) = (middle A B ij).attach (twist (A.label ij.val.1) z) := by
  rw [domain,Prefix.comp_attach,A.chart,untwist_attach,← Prefix.comp_attach,leftFactor]

lemma compose_chart (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B)
    (z : Cube X) :
    (g*f) ((domain A B ij).attach z) =
      (codomain A B ij).attach (twist (B.label ij.val.2 * A.label ij.val.1) z) := by
  change g (f ((domain A B ij).attach z)) = _
  rw [domain_chart,← rightFactor A B ij,Prefix.comp_attach,B.chart,twist_attach,
    twist_twist,codomain,Prefix.comp_attach]

lemma mem_domain_iff (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) (ij : Overlap A B)
    (z : Cube X) :
    (∃ w,(domain A B ij).attach w=z) ↔
      (∃ w,(A.source ij.val.1).attach w=z) ∧
      ∃ w,(B.source ij.val.2).attach w=f z := by
  constructor
  · rintro ⟨w,rfl⟩
    refine ⟨⟨(twistPrefix (A.label ij.val.1)⁻¹ (leftRemainder A B ij)).attach w,
      (Prefix.comp_attach _ _ _).symm⟩,?_⟩
    rw [domain_chart]
    exact Prefix.mem_range_of_extends (Prefix.meet_extends_right ij.property) ⟨_,rfl⟩
  · rintro ⟨⟨v,hv⟩,hb⟩
    have ha : ∃ w,(A.target ij.val.1).attach w=f z :=
      ⟨twist (A.label ij.val.1) v,by rw [← A.chart,hv]⟩
    obtain ⟨w,hw⟩ := (Prefix.mem_meet_iff ij.property (f z)).mpr ⟨ha,hb⟩
    refine ⟨twist (A.label ij.val.1)⁻¹ w,?_⟩
    apply f.injective
    rw [domain_chart,twist_twist_inv]
    exact hw

lemma domain_partition (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) :
    ∀ z : Cube X, ∃! ij : Overlap A B, ∃ w,(domain A B ij).attach w=z := by
  intro z
  obtain ⟨i,hi,huniq⟩ := A.source_cover z
  obtain ⟨j,hj,huniq'⟩ := B.source_cover (f z)
  have hcompat : (A.target i).Compatible (B.source j) := by
    refine ⟨f z,?_,hj⟩
    obtain ⟨w,hw⟩ := hi
    exact ⟨twist (A.label i) w,by rw [← A.chart,hw]⟩
  let ij : Overlap A B := ⟨(i,j),hcompat⟩
  refine ⟨ij,(mem_domain_iff A B ij z).mpr ⟨hi,hj⟩,?_⟩
  intro kl hkl
  obtain ⟨hk,hl⟩ := (mem_domain_iff A B kl z).mp hkl
  apply Subtype.ext
  exact Prod.ext (huniq _ hk) (huniq' _ hl)

/-- Composition is obtained by the literal common refinement of the middle bricks. -/
def compose (A : Table (Γ:=Γ) f) (B : Table (Γ:=Γ) g) : Table (Γ:=Γ) (g*f) where
  index := Overlap A B
  finite := overlap_fintype A B
  source := domain A B
  target := codomain A B
  label ij := B.label ij.val.2 * A.label ij.val.1
  source_cover := domain_partition A B
  target_cover := transport_partition _ _ _ _ (domain_partition A B) (compose_chart A B)
  chart := compose_chart A B

end Table

def tableSubgroup : Subgroup (Equiv.Perm (Cube X)) where
  carrier := {f | Nonempty (Table (Γ:=Γ) f)}
  one_mem' := by rw [← twist_one (Γ:=Γ) (X:=X)]; exact twist_table 1
  inv_mem' := by rintro f ⟨A⟩; exact ⟨A.inverse⟩
  mul_mem' := by rintro f g ⟨A⟩ ⟨B⟩; exact ⟨B.compose A⟩

lemma mem_group_iff_table (f : Equiv.Perm (Cube X)) :
    f ∈ group (Γ:=Γ) (X:=X) ↔ Nonempty (Table (Γ:=Γ) f) := by
  constructor
  · intro hf
    change f ∈ Subgroup.closure {f | Nonempty (Table (Γ:=Γ) f)} at hf
    induction hf using Subgroup.closure_induction with
    | mem x hx => exact hx
    | one => rw [← twist_one (Γ:=Γ) (X:=X)]; exact twist_table 1
    | mul x y hx hy ihx ihy =>
      obtain ⟨A⟩ := ihx
      obtain ⟨B⟩ := ihy
      exact ⟨B.compose A⟩
    | inv x hx ih =>
      obtain ⟨A⟩ := ih
      exact ⟨A.inverse⟩
  · intro hf
    exact Subgroup.subset_closure hf

end

universe u v
attribute [local instance] Classical.propDecidable
namespace Prefix
variable {X : Type u}

/-- A finite rectangular neighbourhood of a cube point. -/
def box (z : Cube X) (s : Finset X) (n : ℕ) : Prefix X :=
  ⟨fun x => if x∈s then (z x).take n else [],s.finite_toSet.subset (by
    intro x hx
    by_contra hn
    exact hx (ite_eq_right hn))⟩

@[simp] lemma box_word (z : Cube X) (s : Finset X) (n : ℕ) (x : X) :
    (box z s n).word x = if x∈s then (z x).take n else [] := rfl

lemma box_mem (z : Cube X) (s : Finset X) (n : ℕ) : ∃ w,(box z s n).attach w=z := by
  apply (mem_range_iff _ _).mpr
  intro x
  by_cases hx : x∈s <;> simp [hx]

lemma agree_before {p : Prefix X} {z w : Cube X}
    (hz : ∃ a,p.attach a=z) (hw : ∃ a,p.attach a=w)
    (x : X) (n : ℕ) (hn : n<(p.word x).length) : z x n=w x n := by
  have he := ((mem_range_iff p z).mp hz x).trans ((mem_range_iff p w).mp hw x).symm
  have he' := congrArg (fun (l : List Bool) => l[n]?) he
  rw [Stream'.getElem?_take hn,Stream'.getElem?_take hn] at he'
  exact Option.some.inj he'

end Prefix

variable {Γ : Type u} {X : Type v} [Group Γ] [MulAction Γ X]

namespace Table
variable {f : Equiv.Perm (Cube X)}

lemma refined_chart (A : Table (Γ:=Γ) f) (i : A.index) (r : Prefix X) (z : Cube X) :
    f (((A.source i).comp r).attach z) =
      ((A.target i).comp (twistPrefix (A.label i) r)).attach (twist (A.label i) z) := by
  rw [Prefix.comp_attach,A.chart,twist_attach,Prefix.comp_attach]

lemma image_refinement (A : Table (Γ:=Γ) f) (i : A.index) (r : Prefix X) :
    f '' Set.range ((A.source i).comp r).attach =
      Set.range ((A.target i).comp (twistPrefix (A.label i) r)).attach := by
  ext z
  constructor
  · rintro ⟨w,⟨v,rfl⟩,rfl⟩
    exact ⟨twist (A.label i) v,(A.refined_chart i r v).symm⟩
  · rintro ⟨w,rfl⟩
    refine ⟨((A.source i).comp r).attach (twist (A.label i)⁻¹ w),⟨_,rfl⟩,?_⟩
    rw [A.refined_chart,twist_twist_inv]

/-- Every nonidentity table displaces a nonempty dyadic brick. -/
theorem exists_displaced_brick (A : Table (Γ:=Γ) f) (hf : f≠1) :
    ∃ p : Prefix X, Disjoint (Set.range p.attach) (f '' Set.range p.attach) := by
  have hpoint : ∃ z : Cube X, f z≠z := by
    by_contra hn
    apply hf
    apply Equiv.ext
    intro z
    exact not_not.mp (fun hz => hn ⟨z,hz⟩)
  obtain ⟨z,hz⟩ := hpoint
  have hcoord : ∃ x n, f z x n≠z x n := by
    by_contra hn
    apply hz
    funext x n
    exact not_not.mp (fun he => hn ⟨x,n,he⟩)
  obtain ⟨x,n,hneq⟩ := hcoord
  obtain ⟨i,⟨v,hv⟩,_⟩ := A.source_cover z
  let r := Prefix.box v {x,(A.label i)⁻¹ • x} (n+1)
  let p := (A.source i).comp r
  let q := (A.target i).comp (twistPrefix (A.label i) r)
  have hzmem : ∃ w,p.attach w=z := by
    obtain ⟨w,hw⟩ := Prefix.box_mem v {x,(A.label i)⁻¹ • x} (n+1)
    exact ⟨w,by dsimp only [p]; rw [Prefix.comp_attach,hw,hv]⟩
  have hfzmem : ∃ w,q.attach w=f z := by
    obtain ⟨w,hw⟩ := hzmem
    exact ⟨twist (A.label i) w,by rw [← A.refined_chart i r w,hw]⟩
  have hpLength : n<(p.word x).length := by
    simp only [p,Prefix.comp_word,List.length_append,r,Prefix.box_word,
      Finset.mem_insert_self,ite_true,Stream'.length_take]
    omega
  have hqLength : n<(q.word x).length := by
    simp only [q,Prefix.comp_word,List.length_append,twistPrefix_word,r,Prefix.box_word,
      Finset.mem_insert,Finset.mem_singleton,or_true,ite_true,Stream'.length_take]
    omega
  refine ⟨p,Set.disjoint_left.mpr ?_⟩
  intro w hw hw'
  have hqr : w∈Set.range q.attach := by
    rw [← A.image_refinement i r]
    exact hw'
  exact hneq ((Prefix.agree_before hfzmem hqr x n hqLength).trans
    (Prefix.agree_before hzmem hw x n hpLength).symm)

end Table

theorem exists_displaced_brick {f : group (Γ:=Γ) (X:=X)} (hf : f≠1) :
    ∃ p : Prefix X, Disjoint (Set.range p.attach) (f.val '' Set.range p.attach) := by
  obtain ⟨A⟩ := (mem_group_iff_table f.val).mp f.property
  exact A.exists_displaced_brick (fun h => hf (Subtype.ext h))

end FiniteAlgebraicEnvelopes.TwistedBrinThompson

namespace FiniteAlgebraicEnvelopes.DisplacementCommutator
universe u v
variable {G : Type u} [Group G] {Y : Type v}

/-- A permutation is supported in a set when it fixes its complement pointwise. -/
def Supported (ρ : G →* Equiv.Perm Y) (s : Set Y) (g : G) : Prop :=
  ∀ x, x∉s → ρ g x=x

variable (ρ : G →* Equiv.Perm Y)

lemma supported_inv {s : Set Y} {g : G} (hg : Supported ρ s g) : Supported ρ s g⁻¹ := by
  intro x hx
  rw [map_inv]
  exact (ρ g).injective (by simpa using (hg x hx).symm)

lemma supported_conjugate {s : Set Y} {g : G} (hg : Supported ρ s g) (n : G) :
    Supported ρ (ρ n '' s) (n*g*n⁻¹) := by
  intro x hx
  have hn : (ρ n).symm x∉s := by
    intro hs
    exact hx ⟨(ρ n).symm x,hs,(ρ n).apply_symm_apply x⟩
  simp only [map_mul,map_inv,Equiv.Perm.mul_apply]
  change ρ n (ρ g ((ρ n).symm x))=x
  rw [hg _ hn,Equiv.apply_symm_apply]

lemma commute_of_disjoint_support (hρ : Function.Injective ρ)
    {s t : Set Y} {a b : G} (ha : Supported ρ s a) (hb : Supported ρ t b)
    (hst : Disjoint s t) : Commute a b := by
  apply hρ
  simp only [map_mul]
  apply Equiv.Perm.Disjoint.commute
  intro x
  by_cases hx : x∈s
  · exact Or.inr (hb x (fun ht => Set.disjoint_left.mp hst hx ht))
  · exact Or.inl (ha x hx)

lemma commutator_factor {a b c : G} (hc : Commute c b) :
    (a*c)*b*(a*c)⁻¹*b⁻¹ = a*b*a⁻¹*b⁻¹ := by
  calc
    (a*c)*b*(a*c)⁻¹*b⁻¹ = a*(c*b*c⁻¹)*a⁻¹*b⁻¹ := by group
    _ = a*b*a⁻¹*b⁻¹ := by rw [hc.eq]; simp

/-- Double-commutator localization. All commutators supported in a displaced
set lie in the normal subgroup containing the displacing element. -/
theorem local_commutator_mem (hρ : Function.Injective ρ)
    (N : Subgroup G) [N.Normal] {n a b : G} (hn : n∈N) {s : Set Y}
    (hdis : Disjoint s (ρ n '' s)) (ha : Supported ρ s a) (hb : Supported ρ s b) :
    a*b*a⁻¹*b⁻¹∈N := by
  let c := n*a⁻¹*n⁻¹
  have hc : Commute c b := commute_of_disjoint_support ρ hρ
    (supported_conjugate ρ (supported_inv ρ ha) n) hb hdis.symm
  let d := a*n*a⁻¹*n⁻¹
  have hd : d∈N := N.mul_mem ((inferInstance : N.Normal).conj_mem n hn a) (N.inv_mem hn)
  have he : d*b*d⁻¹*b⁻¹∈N := by
    have hm := N.mul_mem hd
      ((inferInstance : N.Normal).conj_mem d⁻¹ (N.inv_mem hd) b)
    simpa only [mul_assoc] using hm
  have hd' : d=a*c := by dsimp [d,c]; group
  rw [hd',commutator_factor hc] at he
  exact he

end FiniteAlgebraicEnvelopes.DisplacementCommutator

namespace FiniteAlgebraicEnvelopes.TwistedBrinThompson
universe u v
attribute [local instance] Classical.propDecidable
variable {Γ : Type u} {X : Type v} [Group Γ] [MulAction Γ X]

/-- Conjugate a cube permutation into a brick, extending by identity. -/
def localizePerm (p : Prefix X) : Equiv.Perm (Cube X) →* Equiv.Perm (Cube X) :=
  Equiv.Perm.ofSubtype.comp
    (Equiv.ofInjective p.attach p.attach_injective).permCongrHom.toMonoidHom

lemma localizePerm_attach (p : Prefix X) (f : Equiv.Perm (Cube X)) (z : Cube X) :
    localizePerm p f (p.attach z)=p.attach (f z) := by
  change Equiv.Perm.ofSubtype
    ((Equiv.ofInjective p.attach p.attach_injective).permCongr f) (p.attach z)=_
  rw [Equiv.Perm.ofSubtype_apply_of_mem _ (show p.attach z∈Set.range p.attach from ⟨z,rfl⟩)]
  simp [Equiv.permCongr,Equiv.equivCongr]

lemma localizePerm_outside (p : Prefix X) (f : Equiv.Perm (Cube X))
    {z : Cube X} (hz : z∉Set.range p.attach) : localizePerm p f z=z :=
  Equiv.Perm.ofSubtype_apply_of_not_mem _ hz

lemma localizePerm_injective (p : Prefix X) : Function.Injective (localizePerm p) := by
  intro f g he
  apply Equiv.ext
  intro z
  apply p.attach_injective
  simpa only [localizePerm_attach] using Equiv.congr_fun he (p.attach z)

namespace Table
variable {f : Equiv.Perm (Cube X)}

abbrev sourcePartition (A : Table (Γ:=Γ) f) : Partition X :=
  ⟨A.index,A.finite,A.source,A.source_cover⟩

abbrev targetPartition (A : Table (Γ:=Γ) f) : Partition X :=
  ⟨A.index,A.finite,A.target,A.target_cover⟩

/-- Insert a whole finite table into one member of a finite partition. -/
def localize (A : Table (Γ:=Γ) f) (P : Partition X) (i : P.index) :
    Table (Γ:=Γ) (localizePerm (P.brick i) f) where
  index := {j : P.index // j≠i} ⊕ A.index
  finite := P.refineIndex_finite A.sourcePartition i
  source := P.refineBrick A.sourcePartition i
  target := P.refineBrick A.targetPartition i
  label := fun j => match j with | Sum.inl _ => 1 | Sum.inr k => A.label k
  source_cover := P.refine_cover A.sourcePartition i
  target_cover := P.refine_cover A.targetPartition i
  chart := by
    intro j z
    cases j with
    | inl k =>
        change localizePerm (P.brick i) f ((P.brick k.val).attach z)=
          (P.brick k.val).attach (twist 1 z)
        have hz : (P.brick k.val).attach z∉Set.range (P.brick i).attach := by
          intro hi
          obtain ⟨l,hl,huniq⟩ := P.cover ((P.brick k.val).attach z)
          exact k.property ((huniq k.val ⟨z,rfl⟩).trans (huniq i hi).symm)
        rw [localizePerm_outside _ _ hz,twist_one]
        rfl
    | inr k =>
        change localizePerm (P.brick i) f (((P.brick i).comp (A.source k)).attach z)=
          ((P.brick i).comp (A.target k)).attach (twist (A.label k) z)
        rw [Prefix.comp_attach,Prefix.comp_attach,localizePerm_attach,A.chart]

end Table

lemma localizePerm_table (p : Prefix X) {f : Equiv.Perm (Cube X)}
    (hf : Nonempty (Table (Γ:=Γ) f)) : Nonempty (Table (Γ:=Γ) (localizePerm p f)) := by
  obtain ⟨A⟩ := hf
  obtain ⟨P,i,hi⟩ := p.hasPartition
  rw [← hi]
  exact ⟨A.localize P i⟩

/-- Every brick contains a canonical isomorphic copy of the entire twisted group. -/
def localize (p : Prefix X) : group (Γ:=Γ) (X:=X) →* group (Γ:=Γ) (X:=X) :=
  ((localizePerm p).comp (group (Γ:=Γ) (X:=X)).subtype).codRestrict _ (by
    intro f
    exact (mem_group_iff_table _).mpr (localizePerm_table p ((mem_group_iff_table _).mp f.property)))

@[simp] lemma localize_val (p : Prefix X) (f : group (Γ:=Γ) (X:=X)) :
    (localize p f).val=localizePerm p f.val := rfl

lemma localize_injective (p : Prefix X) : Function.Injective (localize (Γ:=Γ) p) := by
  intro f g he
  exact Subtype.ext (localizePerm_injective p (congrArg Subtype.val he))

lemma localize_supported (p : Prefix X) (f : group (Γ:=Γ) (X:=X)) :
    DisplacementCommutator.Supported (group (Γ:=Γ) (X:=X)).subtype
      (Set.range p.attach) (localize p f) := by
  intro z hz
  exact localizePerm_outside p f.val hz

/-- A nontrivial normal subgroup contains all commutators of a whole localized
copy of the group. No simplicity assumption is used. -/
theorem normal_contains_local_commutators (N : Subgroup (group (Γ:=Γ) (X:=X))) [N.Normal]
    (hN : N≠⊥) : ∃ p : Prefix X, ∀ a b : group (Γ:=Γ) (X:=X),
      localize p (a*b*a⁻¹*b⁻¹)∈N := by
  have hx : ∃ n∈N,n≠1 := by
    by_contra hh
    apply hN
    apply le_antisymm _ bot_le
    intro n hn
    rw [Subgroup.mem_bot]
    by_contra hne
    exact hh ⟨n,hn,hne⟩
  obtain ⟨n,hn,hne⟩ := hx
  obtain ⟨p,hp⟩ := exists_displaced_brick hne
  refine ⟨p,fun a b => ?_⟩
  simp only [map_mul,map_inv]
  exact DisplacementCommutator.local_commutator_mem _ Subtype.val_injective N hn hp
    (localize_supported p a) (localize_supported p b)

end FiniteAlgebraicEnvelopes.TwistedBrinThompson

end

end OAI
