import OAI.NumberTheory.DukePrimeDegree.Geometry.StationaryRestrictions
import OAI.NumberTheory.DukePrimeDegree.Entropy.BilateralConditionalSupport
import OAI.NumberTheory.DukePrimeDegree.Entropy.ConditionalMapEntropy

namespace OAI

/-! # Conditional distributions from a stationary fiber kernel

A stationary kernel which is constant almost everywhere on each of its
own probability fibers is the conditional distribution for the sigma
algebra generated by that kernel. This is the precise extra condition
needed beyond stationarity in the whole-future application.
-/

noncomputable section
open MeasureTheory ProbabilityTheory Set
open scoped ENNReal

namespace DukePrimeDegree
open PrimeDegreePackets

variable {Y : Type*} [mY : MeasurableSpace Y]

theorem setIntegral_selfConstant_kernel
    (μ : Measure Y) [IsFiniteMeasure μ]
    (κ : Kernel Y Y) [IsMarkovKernel κ]
    (hstat : μ.bind κ = μ)
    (hself : ∀ᵐ x ∂μ, ∀ᵐ y ∂κ x, κ y = κ x)
    {S : Set Y} (hS : MeasurableSet[MeasurableSpace.comap κ inferInstance] S)
    {A : Set Y} (hA : MeasurableSet A) :
    (∫ x in S, (κ x).real A ∂μ) = μ.real (A ∩ S) := by
  have hSm : MeasurableSet S := κ.measurable.comap_le S hS
  obtain ⟨B,hB,rfl⟩ := hS
  have he : ∀ᵐ x ∂μ,
      (κ x).real (A ∩ (κ ⁻¹' B)) =
        (κ ⁻¹' B).indicator (fun x => (κ x).real A) x := by
    filter_upwards [hself] with x hx
    by_cases hb : κ x ∈ B
    · rw [Set.indicator_of_mem (show x ∈ κ ⁻¹' B from hb)]
      apply congrArg ENNReal.toReal
      apply measure_congr
      filter_upwards [hx] with y hy
      simp only [mem_inter_iff,mem_preimage,hy,hb,and_true]
    · rw [Set.indicator_of_notMem (show x ∉ κ ⁻¹' B from hb)]
      have hz : (κ x) (A ∩ (κ ⁻¹' B)) = 0 := by
        rw [←measure_empty (μ := κ x)]
        apply measure_congr
        filter_upwards [hx] with y hy
        simp only [mem_inter_iff,mem_preimage,hy,hb,and_false,mem_empty_iff_false]
      rw [Measure.real,hz,ENNReal.toReal_zero]
  calc
    _ = ∫ x, (κ ⁻¹' B).indicator (fun x => (κ x).real A) x ∂μ :=
      (integral_indicator hSm).symm
    _ = ∫ x, (κ x).real (A ∩ (κ ⁻¹' B)) ∂μ := by
      apply integral_congr_ae
      filter_upwards [he] with x hx
      exact hx.symm
    _ = (μ.bind κ).real (A ∩ (κ ⁻¹' B)) :=
      (bind_kernel_real κ μ _ (hA.inter hSm)).symm
    _ = _ := by rw [hstat]

/-- The kernel evaluations are actual conditional probabilities. -/
theorem selfConstant_kernel_ae_eq_condExp
    (μ : Measure Y) [IsFiniteMeasure μ]
    (κ : Kernel Y Y) [IsMarkovKernel κ]
    (hstat : μ.bind κ = μ)
    (hself : ∀ᵐ x ∂μ, ∀ᵐ y ∂κ x, κ y = κ x)
    {A : Set Y} (hA : MeasurableSet A) :
    (fun x => (κ x).real A) =ᵐ[μ]
      μ[A.indicator (fun _ => (1 : ℝ)) | MeasurableSpace.comap κ inferInstance] := by
  have hm : MeasurableSpace.comap (fun x => κ x)
      (inferInstance : MeasurableSpace (Measure Y)) ≤ mY := κ.measurable.comap_le
  apply ae_eq_condExp_of_forall_setIntegral_eq (μ := μ) hm
    ((integrable_const (μ := μ) (1 : ℝ)).indicator hA)
  · exact fun _ _ _ => (integrable_kernel_real μ κ hA).integrableOn
  · intro S hS _
    rw [setIntegral_selfConstant_kernel μ κ hstat hself hS hA,
      integral_indicator_const (1 : ℝ) hA]
    simp only [smul_eq_mul,mul_one,Measure.real,Measure.restrict_apply hA]
  · have h : @Measurable Y ℝ (MeasurableSpace.comap κ inferInstance)
        inferInstance (fun x => (κ x).real A) :=
      (Measure.measurable_coe hA).ennreal_toReal.comp (comap_measurable κ)
    exact h.stronglyMeasurable.aestronglyMeasurable

theorem selfConstant_kernel_conditionalEntropy {α : Type*} [Fintype α]
    (μ : Measure Y) [IsFiniteMeasure μ]
    (κ : Kernel Y Y) [IsMarkovKernel κ]
    (hstat : μ.bind κ = μ)
    (hself : ∀ᵐ x ∂μ, ∀ᵐ y ∂κ x, κ y = κ x)
    (P : Y → α) (hP : ∀ a, MeasurableSet {y | P y=a}) :
    conditionalSigmaEntropy μ P (MeasurableSpace.comap κ inferInstance) =
      ∫ x, observationEntropy (κ x) P ∂μ := by
  unfold conditionalSigmaEntropy observationEntropy
  apply integral_congr_ae
  filter_upwards [ae_all_iff.mpr (fun a =>
    selfConstant_kernel_ae_eq_condExp μ κ hstat hself (hP a))] with x hx
  congr 1
  exact funext fun a => (hx a).symm

/-- An actual regular conditional distribution has the required constancy
on its fibers. This supplies the local case in quotient charts. -/
theorem condDistrib_self_constant {S : Type*} [MeasurableSpace S] [MeasurableEq S]
    [StandardBorelSpace Y] [Nonempty Y]
    (μ : Measure Y) [IsProbabilityMeasure μ]
    (F : Y → S) (hF : Measurable F) :
    ∀ᵐ x ∂μ, ∀ᵐ y ∂condDistrib id F μ (F x),
      condDistrib id F μ (F y) = condDistrib id F μ (F x) := by
  have h := ae_condDistrib_self_fiber μ F hF
  have h' := ae_of_ae_map hF.aemeasurable h
  filter_upwards [h'] with x hx
  filter_upwards [hx] with y hy
  rw [hy]

/-- Self-consistency passes through a genuine measurable coordinate chart
when the ambient kernel is its pushforward. -/
theorem selfConstant_kernel_pushforward
    {Z : Type*} [MeasurableSpace Z]
    (ρ : Measure Z) (η : Kernel Z Z) [IsMarkovKernel η]
    (hstat : ρ.bind η=ρ)
    (hself : ∀ᵐ z ∂ρ, ∀ᵐ w ∂η z, η w=η z)
    (F : Z → Y) (hF : MeasurableEmbedding F)
    (κ : Kernel Y Y) [IsMarkovKernel κ]
    (hversion : ∀ᵐ z ∂ρ, κ (F z)=(η z).map F) :
    ∀ᵐ x ∂ρ.map F, ∀ᵐ y ∂κ x, κ y=κ x := by
  have hv : ∀ᵐ z ∂ρ, ∀ᵐ w ∂η z, κ (F w)=(η w).map F := by
    apply Measure.ae_ae_of_ae_bind η.measurable.aemeasurable
    rwa [hstat]
  apply hF.ae_map_iff.mpr
  filter_upwards [hversion,hself,hv] with z hz hs hvz
  rw [hz]
  apply hF.ae_map_iff.mpr
  filter_upwards [hs,hvz] with w hw hvw
  rw [hvw,hw]

end DukePrimeDegree

end

end OAI
