import OAI.Combinatorics.EuclideanRamsey.CircleExtension
import OAI.Combinatorics.EuclideanRamsey.CircleSpan
import Mathlib.RingTheory.AlgebraicIndependent.Basic

namespace OAI

/-! Rational parametrization of the unit circle and its coordinate field. -/

noncomputable section
namespace EuclideanRamsey.NineGeometry

def circlePoint (x : ℝ) : Space 2 :=
  CircleConsequence.stereographic (0 : Space 2) 1 x

def circleConfig (t : Fin 9 → ℝ) (i : Fin 9) : Space 2 := circlePoint (t i)

@[simp] theorem circlePoint_zero (x : ℝ) :
    circlePoint x 0 = (1 - x^2) / (1 + x^2) := by
  simp [circlePoint, CircleConsequence.stereographic]

@[simp] theorem circlePoint_one (x : ℝ) :
    circlePoint x 1 = (2*x) / (1 + x^2) := by
  simp [circlePoint, CircleConsequence.stereographic]

theorem circlePoint_recover (x : ℝ) :
    circlePoint x 1 / (1 + circlePoint x 0) = x := by
  simpa only [circlePoint_zero, circlePoint_one] using
    CircleConsequence.stereographic_recover x

theorem circlePoint_on_circle (x : ℝ) : dist (circlePoint x) 0 = 1 :=
  CircleConsequence.stereographic_on_circle 0 1 x (by norm_num)

theorem circlePoint_injective : Function.Injective circlePoint := by
  intro x y h
  have hr := congrArg (fun p : Space 2 => p 1 / (1 + p 0)) h
  simpa only [circlePoint_recover] using hr

theorem circleConfig_on_circle (t : Fin 9 → ℝ) (i : Fin 9) :
    dist (circleConfig t i) 0 = 1 := circlePoint_on_circle (t i)

theorem circleConfig_injective (t : Fin 9 → ℝ)
    (ht : AlgebraicIndependent ℚ t) : Function.Injective (circleConfig t) :=
  circlePoint_injective.comp ht.injective

/-- Restriction to the first five points. -/
def firstFive (i : Fin 5) : Fin 9 := ⟨i.val, by omega⟩

theorem firstFive_injective : Function.Injective firstFive := by
  intro i j h
  apply Fin.ext
  simpa only [firstFive] using congrArg (fun k : Fin 9 => k.val) h

theorem circleConfig_affineSpan (t : Fin 9 → ℝ)
    (ht : AlgebraicIndependent ℚ t) :
    affineSpan ℝ (Set.range (circleConfig t)) = ⊤ := by
  have hfive : affineSpan ℝ (Set.range (circleConfig t ∘ firstFive)) = ⊤ :=
    CircleConsequence.circle_five_affineSpan (circleConfig t ∘ firstFive)
      ((circleConfig_injective t ht).comp firstFive_injective) 0 1
      (fun i => circleConfig_on_circle t (firstFive i))
  apply top_unique
  rw [← hfive]
  apply affineSpan_mono
  rintro p ⟨i, rfl⟩
  exact Set.mem_range_self (firstFive i)

/-- The coordinate field is generated by the circle parameters. -/
theorem circleConfig_coordinateField (t : Fin 9 → ℝ) :
    coordinateField (circleConfig t) = IntermediateField.adjoin ℚ (Set.range t) := by
  let F : IntermediateField ℚ ℝ := IntermediateField.adjoin ℚ (Set.range t)
  apply le_antisymm
  · change IntermediateField.adjoin ℚ
      (Set.range (fun ij : Fin 9 × Fin 2 => circleConfig t ij.1 ij.2)) ≤ F
    apply IntermediateField.adjoin_le_iff.mpr
    rintro x ⟨⟨i, j⟩, rfl⟩
    have ht : t i ∈ F := IntermediateField.subset_adjoin ℚ _ (Set.mem_range_self i)
    have ht2 : (t i)^2 ∈ F := F.pow_mem ht 2
    have hden : 1 + (t i)^2 ∈ F := F.add_mem F.one_mem ht2
    fin_cases j
    · change circlePoint (t i) 0 ∈ F
      rw [circlePoint_zero]
      exact F.div_mem (F.sub_mem F.one_mem ht2) hden
    · change circlePoint (t i) 1 ∈ F
      rw [circlePoint_one]
      exact F.div_mem (F.mul_mem (F.natCast_mem 2) ht) hden
  · apply IntermediateField.adjoin_le_iff.mpr
    rintro x ⟨i, rfl⟩
    let K : IntermediateField ℚ ℝ := coordinateField (circleConfig t)
    have hcoord (j : Fin 2) : circleConfig t i j ∈ K :=
      IntermediateField.subset_adjoin ℚ _ (Set.mem_range_self (i, j))
    have hrecovered : circleConfig t i 1 / (1 + circleConfig t i 0) ∈ K :=
      K.div_mem (hcoord 1) (K.add_mem K.one_mem (hcoord 0))
    change t i ∈ K
    simpa only [circleConfig, circlePoint_recover] using hrecovered

end EuclideanRamsey.NineGeometry

end

end OAI
