import OAI.NumberTheory.DukePrimeDegree.Geometry.CanonicalRootCoefficients

namespace OAI

/-!
# The invariant root blocks

The canonical root entropy identity makes the invariant-root relation
an equivalence relation. The associated subgroup is defined by its root
generators and fixes the measure.
-/

noncomputable section
open MeasureTheory Filter Set
open scoped Topology

namespace DukePrimeDegree
open PrimeDegreePackets

variable (d : ℕ) (μ : Measure (X (d + 1))) [IsProbabilityMeasure μ]
  [ErgodicSMul (Multiplicative (LogCoordinates d)) (X (d + 1)) μ]
  (hd : 2 < d + 1) (hformula : CanonicalRootEntropyFormula d μ)

omit [IsProbabilityMeasure μ] in
private lemma diagonal_preserves (u : LogCoordinates d) :
    μ.map (fun x => rightAction x (diagonalFlow u)) = μ :=
  (measurePreserving_smul (Multiplicative.ofAdd u) μ).map_eq

include hd hformula

lemma rootInvarianceRelation_iff_coefficient (i j : Fin (d + 1)) :
    rootInvarianceRelation μ i j ↔ i = j ∨ 0 < canonicalRootCoefficient d μ i j := by
  constructor
  · rintro (h | ⟨hij, h⟩)
    · exact Or.inl h
    · right
      have he := canonicalRootCoefficient_one_of_invariant d μ
        (diagonal_preserves d μ) i j hij h
      rw [he]
      exact zero_lt_one
  · rintro (h | h)
    · exact Or.inl h
    · have hij : i ≠ j := by
        intro he
        subst j
        rw [canonicalRootCoefficient_diagonal] at h
        exact (lt_irrefl 0 h)
      exact Or.inr ⟨hij, (canonicalRootEntropyCoefficients d μ
        (diagonal_preserves d μ) hformula).invariant_of_pos hd hij h⟩

lemma rootInvarianceRelation_symm {i j : Fin (d + 1)}
    (h : rootInvarianceRelation μ i j) : rootInvarianceRelation μ j i := by
  rw [rootInvarianceRelation_iff_coefficient d μ hd hformula] at h ⊢
  rcases h with h | h
  · exact Or.inl h.symm
  · right
    have hs := (canonicalRootEntropyCoefficients d μ
      (diagonal_preserves d μ) hformula).symmetric j i
    change canonicalRootCoefficient d μ j i = canonicalRootCoefficient d μ i j at hs
    rwa [hs]

/-- The blocks are equivalence classes of actual root invariance. -/
def invariantRootSetoid : Setoid (Fin (d + 1)) where
  r := rootInvarianceRelation μ
  iseqv := ⟨fun _ => Or.inl rfl,
    fun h => rootInvarianceRelation_symm d μ hd hformula h,
    fun h₁ h₂ => rootInvarianceRelation_trans μ h₁ h₂⟩

end DukePrimeDegree

namespace PrimeDegreePackets

/-- The group generated by all root groups preserving the actual measure. -/
def invariantRootGeneratedGroup {n : ℕ} (μ : Measure (X n)) : Subgroup (G n) :=
  Subgroup.closure {g | ∃ (i j : Fin n) (hij : i ≠ j) (t : ℝ),
    rootInvarianceRelation μ i j ∧ g = Matrix.SpecialLinearGroup.transvection hij t}

lemma invariantRootGeneratedGroup_le {n : ℕ} (μ : Measure (X n)) :
    invariantRootGeneratedGroup μ ≤ invariantRightSubgroup μ := by
  rw [invariantRootGeneratedGroup, Subgroup.closure_le]
  rintro g ⟨i, j, hij, t, h, rfl⟩
  rcases h with h | ⟨_, hi⟩
  · exact (hij h).elim
  · exact hi t

lemma root_mem_invariantRootGeneratedGroup {n : ℕ} (μ : Measure (X n))
    {i j : Fin n} (hij : i ≠ j) (h : rootInvarianceRelation μ i j) (t : ℝ) :
    Matrix.SpecialLinearGroup.transvection hij t ∈ invariantRootGeneratedGroup μ :=
  Subgroup.subset_closure ⟨i, j, hij, t, h, rfl⟩

lemma measure_map_rootGeneratedGroup {n : ℕ} (μ : Measure (X n))
    (g : invariantRootGeneratedGroup μ) : μ.map (fun x => rightAction x g.val) = μ :=
  invariantRootGeneratedGroup_le μ g.prop

/-- Every real diagonal flow normalizes the group generated by invariant
root groups, since it only rescales each root parameter. -/
theorem diagonal_normalizes_rootGeneratedGroup {n : ℕ} (μ : Measure (X n))
    (ell : Fin n → ℝ) (hell : ∑ i, ell i = 0) (t : ℝ) :
    diagonalOneParameter ell hell t ∈
      Subgroup.normalizer (invariantRootGeneratedGroup μ : Set (G n)) := by
  let S : Set (G n) := {g | ∃ (i j : Fin n) (hij : i ≠ j) (a : ℝ),
    rootInvarianceRelation μ i j ∧ g = Matrix.SpecialLinearGroup.transvection hij a}
  have hconj (s : ℝ) {g : G n} (hg : g ∈ S) :
      diagonalOneParameter ell hell s * g * diagonalOneParameter ell hell (-s) ∈ S := by
    obtain ⟨i, j, hij, a, hr, rfl⟩ := hg
    exact ⟨i, j, hij, Real.exp ((ell i - ell j) * s) * a, hr,
      diagonal_conjugation_transvection ell hell hij a s⟩
  apply Subgroup.normalizer_le_normalizer_closure S
  rw [Subgroup.mem_normalizer_iff_conj_image_eq]
  apply subset_antisymm
  · rintro _ ⟨g, hg, rfl⟩
    simpa only [MulAut.conj_apply, ← diagonalOneParameter_neg] using hconj t hg
  · intro g hg
    refine ⟨(MulAut.conj (diagonalOneParameter ell hell t)).symm g, ?_,
      (MulAut.conj (diagonalOneParameter ell hell t)).apply_symm_apply g⟩
    simpa only [MulAut.conj_symm_apply, ← diagonalOneParameter_neg, neg_neg] using hconj (-t) hg

end PrimeDegreePackets

end

end OAI
