import Mathlib.Algebra.FreeAlgebra
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import OAI.Topology.ArtinGroups.Quivers.ReversibleQuiver

namespace OAI

/-!
# The published finite-Dynkin path input

`MeshNilpotent` is the positive-degree nilpotence assertion for the
preprojective (mesh) algebra of an induced finite Dynkin graph. Its
relations are displayed explicitly, rather than asserted for a complex.
The standard finite-dimensionality input is Amiot, *On the structure of
triangulated categories with finitely many indecomposables*, Bull. Soc.
Math. France 135 (2007), Proposition 9.1; the essential-path formulation
is Coquereaux (2002), §§3.1–3.2, and Cooper (2007), Theorem 5.4.3 and
Proposition 5.6.10. On a bipartite Dynkin graph the usual signed mesh
relations have the same zero sets as the displayed all-plus relations.

This module proves evaluation of the abstract relations. It does not
assume their vanishing for coefficient maps of the target paper's
complexes, nor assume any stabilizer or bounded-height conclusion.
-/
namespace HarmonicArtin.ParabolicIntersections
attribute [local instance] Classical.decEq Classical.propDecidable
variable {V A : Type} (Q : ReversibleQuiver V A) [Fintype A]

noncomputable def meshRelation (v : V) : FreeAlgebra ℂ A :=
  ∑ a, if Q.source a = v then FreeAlgebra.ι ℂ a * FreeAlgebra.ι ℂ (Q.reverse a) else 0

def meshRelations (U : Set V) : Set (FreeAlgebra ℂ A) :=
  {z | ∃ a, (Q.source a ∉ U ∨ Q.target a ∉ U) ∧ z = FreeAlgebra.ι ℂ a} ∪
  {z | ∃ a b, Q.target a ≠ Q.source b ∧ z = FreeAlgebra.ι ℂ a * FreeAlgebra.ι ℂ b} ∪
  {z | ∃ v ∈ U, z = meshRelation Q v}

/-- Exact abstract algebra input: sufficiently long positive words lie
in the two-sided ideal generated by the mesh relations. -/
def MeshNilpotent (U : Set V) : Prop :=
  ∃ N : ℕ, 0 < N ∧ ∀ w : List A, w.length = N →
    (w.map (FreeAlgebra.ι ℂ)).prod ∈ TwoSidedIdeal.span (meshRelations Q U)

/-- Evaluation of one abstract path identity into an arbitrary complex algebra. -/
theorem mesh_word_evaluate {U : Set V}
    {R : Type*} [Ring R] [Algebra ℂ R] (B : A → R)
    (houtside : ∀ a, Q.source a ∉ U ∨ Q.target a ∉ U → B a = 0)
    (hpath : ∀ a b, Q.target a ≠ Q.source b → B a * B b = 0)
    (hmesh : ∀ v ∈ U, (∑ a, if Q.source a = v then B a * B (Q.reverse a) else 0) = 0)
    (w : List A) (hw : (w.map (FreeAlgebra.ι ℂ)).prod ∈
      TwoSidedIdeal.span (meshRelations Q U)) : (w.map B).prod = 0 := by
  let φ : FreeAlgebra ℂ A →ₐ[ℂ] R := FreeAlgebra.lift ℂ B
  have hk : TwoSidedIdeal.span (meshRelations Q U) ≤ TwoSidedIdeal.ker φ.toRingHom := by
    apply TwoSidedIdeal.span_le.mpr
    intro z hz
    change φ z = φ 0
    rw [map_zero]
    rcases hz with (⟨a, ha, rfl⟩ | ⟨a, b, hab, rfl⟩) | ⟨v, hv, rfl⟩
    · simpa only [φ, FreeAlgebra.lift_ι_apply] using houtside a ha
    · simpa only [map_mul, φ, FreeAlgebra.lift_ι_apply] using hpath a b hab
    · simp only [meshRelation, map_sum]
      convert hmesh v hv using 1
      apply Finset.sum_congr rfl
      intro a _
      split_ifs
      · simp only [map_mul, φ, FreeAlgebra.lift_ι_apply]
      · exact map_zero φ
  have he : φ (w.map (FreeAlgebra.ι ℂ)).prod = φ 0 := hk hw
  rw [map_zero] at he
  simpa only [map_list_prod, List.map_map, Function.comp_def, φ, FreeAlgebra.lift_ι_apply] using he

/-- The nilpotence exponent depends only on the graph, not on the algebra
in which the paths are evaluated. -/
theorem meshNilpotent_evaluate {U : Set V} (h : MeshNilpotent Q U)
    {R : Type*} [Ring R] [Algebra ℂ R] (B : A → R)
    (houtside : ∀ a, Q.source a ∉ U ∨ Q.target a ∉ U → B a = 0)
    (hpath : ∀ a b, Q.target a ≠ Q.source b → B a * B b = 0)
    (hmesh : ∀ v ∈ U, (∑ a, if Q.source a = v then B a * B (Q.reverse a) else 0) = 0) :
    ∃ N : ℕ, 0 < N ∧ ∀ w : List A, w.length = N → (w.map B).prod = 0 := by
  obtain ⟨N, hN, hwords⟩ := h
  exact ⟨N, hN, fun w hw => mesh_word_evaluate Q B houtside hpath hmesh w (hwords w hw)⟩

end HarmonicArtin.ParabolicIntersections

end OAI
