import OAI.Analysis.KadisonSimilarity.FreeProduct.DihedralPositiveDensity

namespace OAI

/-! The ordinary dihedral word span is a unital star subalgebra. This
reduces its L²-density to density of the algebra generated by the two
symmetries, without assuming a normal-form density statement. -/

noncomputable section
namespace KadisonSimilarity
namespace DihedralWordAlgebra

section Group
variable {G : Type*} [Group G]

/-- Moving a reflection through any integer rotation power. -/
theorem reflection_zpow (d w : G) (hc : d * w = w⁻¹ * d) (l : ℤ) :
    d * w ^ l = w ^ (-l) * d := by
  have h := (show SemiconjBy d w w⁻¹ from hc).zpow_right l
  simpa only [inv_zpow, zpow_neg] using h.eq

/-- The rotation exponent changes sign when its left factor is a reflection. -/
theorem reflection_rotation (d w : G) (hc : d * w = w⁻¹ * d) (l m : ℤ) :
    (w ^ l * d) * w ^ m = w ^ (l - m) * d := by
  rw [mul_assoc, reflection_zpow d w hc, ← mul_assoc, ← zpow_add]
  simp only [sub_eq_add_neg]

/-- The product of two reflection-coset words is a rotation. -/
theorem reflection_reflection (d w : G) (hd : d * d = 1)
    (hc : d * w = w⁻¹ * d) (l m : ℤ) :
    (w ^ l * d) * (w ^ m * d) = w ^ (l - m) := by
  rw [← mul_assoc, reflection_rotation d w hc, mul_assoc, hd, mul_one]

end Group

variable {P : Type*} [CStarAlgebra P]

/-- Rotation words and reflection-coset words, as elements of the algebra. -/
def wordSet (d w : Pˣ) : Set P :=
  Set.range (fun l : ℤ => (↑(w ^ l) : P)) ∪
    Set.range (fun l : ℤ => (↑(w ^ l) : P) * (d : P))

/-- Normal forms are closed under multiplication. -/
theorem wordSet_mul (d w : Pˣ) (hd : d * d = 1) (hc : d * w = w⁻¹ * d)
    {a b : P} (ha : a ∈ wordSet d w) (hb : b ∈ wordSet d w) : a * b ∈ wordSet d w := by
  rcases ha with ⟨l, rfl⟩ | ⟨l, rfl⟩ <;> rcases hb with ⟨m, rfl⟩ | ⟨m, rfl⟩
  · left
    refine ⟨l + m, ?_⟩
    dsimp only
    rw [zpow_add, Units.val_mul]
  · right
    refine ⟨l + m, ?_⟩
    dsimp only
    rw [zpow_add, Units.val_mul, mul_assoc]
  · right
    refine ⟨l - m, ?_⟩
    have h := congrArg (fun g : Pˣ => (g : P)) (reflection_rotation d w hc l m)
    simpa only [Units.val_mul] using h.symm
  · left
    refine ⟨l - m, ?_⟩
    have h := congrArg (fun g : Pˣ => (g : P)) (reflection_reflection d w hd hc l m)
    simpa only [Units.val_mul] using h.symm

/-- Taking adjoints preserves the two normal forms. -/
theorem wordSet_star (d w : Pˣ) (hc : d * w = w⁻¹ * d)
    (hdstar : star d = d) (hwstar : star w = w⁻¹)
    {a : P} (ha : a ∈ wordSet d w) : star a ∈ wordSet d w := by
  rcases ha with ⟨l, rfl⟩ | ⟨l, rfl⟩
  · left
    exact ⟨-l, (star_unitary_zpow w hwstar l).symm⟩
  · right
    refine ⟨l, ?_⟩
    have hdval : star (d : P) = (d : P) := congrArg (fun g : Pˣ => (g : P)) hdstar
    rw [star_mul, hdval, star_unitary_zpow w hwstar]
    have h := congrArg (fun g : Pˣ => (g : P)) (reflection_zpow d w hc (-l))
    simpa only [Units.val_mul, neg_neg] using h.symm

/-- Bilinearity extends multiplication closure to the full linear span. -/
theorem span_mul (d w : Pˣ) (hd : d * d = 1) (hc : d * w = w⁻¹ * d)
    {a b : P} (ha : a ∈ Submodule.span ℂ (wordSet d w))
    (hb : b ∈ Submodule.span ℂ (wordSet d w)) :
    a * b ∈ Submodule.span ℂ (wordSet d w) := by
  let M := Submodule.span ℂ (wordSet d w)
  refine Submodule.span_induction₂ (p := fun a b _ _ => a * b ∈ M) ?_ ?_ ?_ ?_ ?_ ?_ ?_ ha hb
  · intro a b ha hb
    exact Submodule.subset_span (wordSet_mul d w hd hc ha hb)
  · intro b _
    rw [zero_mul]
    exact M.zero_mem
  · intro a _
    rw [mul_zero]
    exact M.zero_mem
  · intro a b c _ _ _ ha hb
    rw [add_mul]
    exact M.add_mem ha hb
  · intro a b c _ _ _ hb hc
    rw [mul_add]
    exact M.add_mem hb hc
  · intro r a b _ _ h
    rw [smul_mul_assoc]
    exact M.smul_mem r h
  · intro r a b _ _ h
    rw [mul_smul_comm]
    exact M.smul_mem r h

/-- Conjugate linearity extends adjoint closure to the word span. -/
theorem span_star (d w : Pˣ) (hc : d * w = w⁻¹ * d)
    (hdstar : star d = d) (hwstar : star w = w⁻¹)
    {a : P} (ha : a ∈ Submodule.span ℂ (wordSet d w)) :
    star a ∈ Submodule.span ℂ (wordSet d w) := by
  let M := Submodule.span ℂ (wordSet d w)
  induction ha using Submodule.span_induction with
  | mem a ha => exact Submodule.subset_span (wordSet_star d w hc hdstar hwstar ha)
  | zero => simpa only [star_zero] using M.zero_mem
  | add a b _ _ ha hb => simpa only [star_add] using M.add_mem ha hb
  | smul r a _ ha => simpa only [star_smul] using M.smul_mem (star r) ha

/-- The span itself is the required unital star subalgebra. -/
def spanStarAlgebra (d w : Pˣ) (hd : d * d = 1) (hc : d * w = w⁻¹ * d)
    (hdstar : star d = d) (hwstar : star w = w⁻¹) : StarSubalgebra ℂ P where
  carrier := Submodule.span ℂ (wordSet d w)
  zero_mem' := Submodule.zero_mem _
  add_mem' := fun ha hb => Submodule.add_mem _ ha hb
  one_mem' := Submodule.subset_span (Or.inl ⟨0, by simp⟩)
  mul_mem' := span_mul d w hd hc
  algebraMap_mem' c := by
    rw [Algebra.algebraMap_eq_smul_one]
    exact Submodule.smul_mem _ c (Submodule.subset_span (Or.inl ⟨0, by simp⟩))
  star_mem' := span_star d w hc hdstar hwstar

@[simp] theorem spanStarAlgebra_toSubmodule (d w : Pˣ) (hd : d * d = 1)
    (hc : d * w = w⁻¹ * d) (hdstar : star d = d) (hwstar : star w = w⁻¹) :
    (spanStarAlgebra d w hd hc hdstar hwstar).toSubalgebra.toSubmodule =
      Submodule.span ℂ (wordSet d w) := rfl

/-- The normal-form span contains the reflection. -/
theorem reflection_mem (d w : Pˣ) (hd : d * d = 1) (hc : d * w = w⁻¹ * d)
    (hdstar : star d = d) (hwstar : star w = w⁻¹) :
    (d : P) ∈ spanStarAlgebra d w hd hc hdstar hwstar :=
  Submodule.subset_span (Or.inr ⟨0, by simp⟩)

/-- The normal-form span contains the rotation. -/
theorem rotation_mem (d w : Pˣ) (hd : d * d = 1) (hc : d * w = w⁻¹ * d)
    (hdstar : star d = d) (hwstar : star w = w⁻¹) :
    (w : P) ∈ spanStarAlgebra d w hd hc hdstar hwstar :=
  Submodule.subset_span (Or.inl ⟨1, by simp⟩)

/-- The other symmetry is the reflection times the rotation. -/
theorem second_symmetry_mem (d s : Pˣ) (hd : d * d = 1)
    (hc : d * (d * s) = (d * s)⁻¹ * d)
    (hdstar : star d = d) (hwstar : star (d * s) = (d * s)⁻¹) :
    (s : P) ∈ spanStarAlgebra d (d * s) hd hc hdstar hwstar := by
  have h := (spanStarAlgebra d (d * s) hd hc hdstar hwstar).mul_mem
    (reflection_mem d (d * s) hd hc hdstar hwstar)
    (rotation_mem d (d * s) hd hc hdstar hwstar)
  have heq : d * (d * s) = s := by rw [← mul_assoc, hd, one_mul]
  have hval := congrArg (fun u : Pˣ => (u : P)) heq
  simp only [Units.val_mul] at hval
  change (s : P) ∈ (spanStarAlgebra d (d * s) hd hc hdstar hwstar).toSubalgebra
  simpa only [Units.val_mul, hval] using h

/-- Thus every finite algebraic star word in the two symmetries belongs to
the linear span of dihedral normal forms. -/
theorem generated_le_span (d s : Pˣ) (hd : d * d = 1)
    (hc : d * (d * s) = (d * s)⁻¹ * d)
    (hdstar : star d = d) (hwstar : star (d * s) = (d * s)⁻¹) :
    StarAlgebra.adjoin ℂ ({(d : P), (s : P)} : Set P) ≤
      spanStarAlgebra d (d * s) hd hc hdstar hwstar := by
  apply StarAlgebra.adjoin_le
  intro a ha
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
  rcases ha with rfl | rfl
  · exact reflection_mem d (d * s) hd hc hdstar hwstar
  · exact second_symmetry_mem d s hd hc hdstar hwstar

/-- A linear map takes the ordinary word span into the span of its word vectors. -/
theorem map_mem_word_span {H : Type*} [AddCommGroup H] [Module ℂ H]
    (V : P →ₗ[ℂ] H) (d w : Pˣ) {a : P}
    (ha : a ∈ Submodule.span ℂ (wordSet d w)) :
    V a ∈ Submodule.span ℂ (V '' wordSet d w) := by
  let M := Submodule.span ℂ (V '' wordSet d w)
  induction ha using Submodule.span_induction with
  | mem a ha => exact Submodule.subset_span ⟨a, ha, rfl⟩
  | zero => simpa only [map_zero] using M.zero_mem
  | add a b _ _ ha hb => simpa only [map_add] using M.add_mem ha hb
  | smul c a _ ha => simpa only [map_smul] using M.smul_mem c ha

end DihedralWordAlgebra
namespace TracialCornerGeometry

variable {P H : Type*} [CStarAlgebra P] [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (G : TracialCornerGeometry P H)

/-- The algebraic and Hilbert-space versions of the normal-form set agree. -/
theorem image_dihedralWordSet (d w : Pˣ) :
    G.vector '' DihedralWordAlgebra.wordSet d w = G.dihedralGroupWordVectors d w := by
  ext z
  constructor
  · rintro ⟨a, ha, rfl⟩
    rcases ha with ⟨l, rfl⟩ | ⟨l, rfl⟩
    · exact Or.inl ⟨l, rfl⟩
    · exact Or.inr ⟨l, rfl⟩
  · rintro (⟨l, rfl⟩ | ⟨l, rfl⟩)
    · exact ⟨_, Or.inl ⟨l, rfl⟩, rfl⟩
    · exact ⟨_, Or.inr ⟨l, rfl⟩, rfl⟩

/-- Density of the ordinary generated star algebra supplies exactly the
dihedral group-word span used by the centered corner argument. -/
theorem group_word_density_of_generated_density
    (d s : Pˣ) (hdi : d⁻¹ = d) (hsi : s⁻¹ = s)
    (hdstar : star d = d) (hsstar : star s = s) (x : P)
    (hspan : G.vector x ∈ (Submodule.span ℂ
      (G.vector '' (StarAlgebra.adjoin ℂ ({(d : P), (s : P)} : Set P) : Set P))).topologicalClosure) :
    G.vector x ∈ (Submodule.span ℂ (G.dihedralGroupWordVectors d (d * s))).topologicalClosure := by
  have hdd : d * d = 1 := by simpa only [hdi] using inv_mul_cancel d
  have hinc : Submodule.span ℂ
      (G.vector '' (StarAlgebra.adjoin ℂ ({(d : P), (s : P)} : Set P) : Set P)) ≤
        Submodule.span ℂ (G.dihedralGroupWordVectors d (d * s)) := by
    apply Submodule.span_le.mpr
    rintro z ⟨a, ha, rfl⟩
    rw [← G.image_dihedralWordSet]
    exact DihedralWordAlgebra.map_mem_word_span G.vector d (d * s)
      (DihedralWordAlgebra.generated_le_span d s hdd
        (free_symmetry_rotation_conjugation d s hdi hsi) hdstar
        (free_symmetry_product_star d s hdstar hsstar hdi hsi) ha)
  exact Submodule.topologicalClosure_mono hinc hspan

/-- Corner freeness reduces to ordinary L²-density of the algebra
generated by the two centered symmetries. -/
theorem scalarFree_corner_of_generated_word_density
    (D A C : StarSubalgebra ℂ P) (hf : ScalarFree G.trace D A) (hτ : G.trace 1 = 1)
    (d s : Pˣ) (hd : (d : P) ∈ D) (hs : (s : P) ∈ A)
    (hd0 : G.trace (d : P) = 0) (hs0 : G.trace (s : P) = 0)
    (hdi : d⁻¹ = d) (hsi : s⁻¹ = s) (hdstar : star d = d) (hsstar : star s = s)
    (hp : IsStarProjection (dihedralHalfProjection d))
    (hpC : dihedralHalfProjection d ∈ C)
    (hspan : ∀ x : CStarCorner (dihedralHalfProjection d) hp, (x : P) ∈ C →
      G.vector (x : P) ∈ (Submodule.span ℂ
        (G.vector '' (StarAlgebra.adjoin ℂ ({(d : P), (s : P)} : Set P) : Set P))).topologicalClosure) :
    ScalarFree (CStarCorner.normalizedTrace (dihedralHalfProjection d) hp G.trace)
      (CStarCorner.subalgebra (dihedralHalfProjection d) hp D
        (D.smul_mem (D.add_mem D.one_mem hd) (1 / 2 : ℂ)))
      (CStarCorner.subalgebra (dihedralHalfProjection d) hp C hpC) := by
  apply G.scalarFree_corner_of_dihedral_word_density D A C hf hτ d s hd hs hd0 hs0 hdi hsi hp hpC
  intro x hx
  exact G.group_word_density_of_generated_density d s hdi hsi hdstar hsstar (x : P) (hspan x hx)

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
