import OAI.Analysis.KadisonSimilarity.FreeProduct.FreeProductAutomorphisms
import Mathlib.Topology.UniformSpace.UniformApproximation
import Mathlib.Topology.Algebra.Module.FiniteDimension
import Mathlib.Topology.Sequences

namespace OAI

/-! Strong continuity of the constructed finite matrix action follows from
ordinary factor-algebra density and the isometry bound; it is not an extra
free-product or Haar-averaging hypothesis. -/

noncomputable section
namespace KadisonSimilarity

open Filter
open scoped Topology CStarAlgebra

section ContinuousOrbits
variable {Γ H : Type*} [TopologicalSpace Γ]
  [NormedAddCommGroup H] [NormedSpace ℂ H]
  (U : Γ → H →L[ℂ] H)

/-- Vectors with continuous orbit form a linear subspace. -/
def continuousOrbitSubmodule : Submodule ℂ H where
  carrier := {x | Continuous (fun g => U g x)}
  zero_mem' := by simpa only [Set.mem_ofPred_eq, map_zero] using (continuous_const : Continuous (fun _ : Γ => (0 : H)))
  add_mem' hx hy := by simpa only [Set.mem_ofPred_eq, map_add] using hx.fun_add hy
  smul_mem' c _ hx := by simpa only [Set.mem_ofPred_eq, map_smul] using
    (continuous_const : Continuous (fun _ : Γ => c)).fun_smul hx

/-- A common contraction bound makes the continuous-orbit subspace closed. -/
theorem continuousOrbitSubmodule_isClosed (hU : ∀ g, ‖U g‖ ≤ 1) :
    IsClosed (continuousOrbitSubmodule U : Set H) := by
  apply isSeqClosed_iff_isClosed.mp
  intro x y hx hy
  have hu : TendstoUniformly (fun n g => U g (x n)) (fun g => U g y) atTop := by
    rw [Metric.tendstoUniformly_iff]
    intro ε hε
    filter_upwards [Metric.tendsto_nhds.mp hy ε hε] with n hn
    intro g
    have hbound : dist (U g y) (U g (x n)) ≤ dist (x n) y := by
      rw [dist_eq_norm, ← map_sub, dist_eq_norm, norm_sub_rev]
      calc
        ‖U g (y - x n)‖ ≤ ‖U g‖ * ‖y - x n‖ := (U g).le_opNorm _
        _ ≤ 1 * ‖y - x n‖ := mul_le_mul_of_nonneg_right (hU g) (norm_nonneg _)
        _ = ‖y - x n‖ := one_mul _
    exact hbound.trans_lt hn
  exact hu.continuous (Filter.Eventually.of_forall hx).frequently

end ContinuousOrbits

namespace TracialCornerGeometry
variable {P H : Type*} [CStarAlgebra P]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (G : TracialCornerGeometry P H)

/-- The tracial vector map is continuous because it is left multiplication
on its fixed vacuum vector. -/
theorem continuous_vector : Continuous G.vector := by
  have he : (G.vector : P → H) = fun a => G.left a (G.vector 1) := by
    funext a
    simpa only [mul_one] using (G.left_vector a 1).symm
  rw [he]
  exact (map_continuous G.left).clm_apply continuous_const

variable (A D : StarSubalgebra ℂ P)
  {α : Type*} [Fintype α] [DecidableEq α]
  (ι : Matrix α α ℂ →⋆ₐ[ℂ] D)
  (hgen : G.FactorsTraciallyGenerate A D) (hfaithful : Function.Injective G.vector)
  (hext : G.MatrixConjugationExtensionInput D ι A)

/-- Conjugation of a fixed factor element depends continuously on the matrix
unitary, directly from finite-dimensional continuity and multiplication. -/
theorem continuous_matrixConjugateLetter (d : D) :
    Continuous (fun u : Matrix.unitaryGroup α ℂ => (matrixConjugateLetter D ι u d : P)) := by
  have hι : Continuous (D.subtype.comp ι : Matrix α α ℂ →⋆ₐ[ℂ] P) :=
    (D.subtype.comp ι).toAlgHom.toLinearMap.continuous_of_finiteDimensional
  have hc : Continuous (fun u : Matrix.unitaryGroup α ℂ => (ι (u : Matrix α α ℂ) : P)) :=
    hι.comp continuous_subtype_val
  simpa only [matrixConjugateLetter, MulMemClass.coe_mul, StarMemClass.coe_star] using
    (hc.fun_mul continuous_const).fun_mul hc.star

/-- Every element of the algebra generated by the two factors has a
continuous orbit in the original operator norm. -/
theorem continuous_chosenMatrixExtension (a : factorAlgebra A D) :
    Continuous (fun u : Matrix.unitaryGroup α ℂ => G.chosenMatrixExtension A D ι hext u (a : P)) := by
  let S : StarSubalgebra ℂ P :=
    { carrier := {a | Continuous (fun u : Matrix.unitaryGroup α ℂ =>
        G.chosenMatrixExtension A D ι hext u a)}
      zero_mem' := by simpa only [Set.mem_ofPred_eq, map_zero] using
        (continuous_const : Continuous (fun _ : Matrix.unitaryGroup α ℂ => (0 : P)))
      one_mem' := by simpa only [Set.mem_ofPred_eq, map_one] using
        (continuous_const : Continuous (fun _ : Matrix.unitaryGroup α ℂ => (1 : P)))
      add_mem' := by intro a b ha hb; simpa only [Set.mem_ofPred_eq, map_add] using ha.fun_add hb
      mul_mem' := by intro a b ha hb; simpa only [Set.mem_ofPred_eq, map_mul] using ha.fun_mul hb
      algebraMap_mem' := by
        intro c
        have he : (fun u : Matrix.unitaryGroup α ℂ =>
            G.chosenMatrixExtension A D ι hext u (algebraMap ℂ P c)) =
            fun _ => algebraMap ℂ P c :=
          funext (fun u => (G.chosenMatrixExtension A D ι hext u).commutes c)
        change Continuous (fun u : Matrix.unitaryGroup α ℂ =>
          G.chosenMatrixExtension A D ι hext u (algebraMap ℂ P c))
        rw [he]
        exact continuous_const
      star_mem' := by intro a ha; simpa only [Set.mem_ofPred_eq, map_star] using ha.star }
  have hs : factorAlgebra A D ≤ S := by
    apply StarAlgebra.adjoin_le
    intro x hx
    rcases hx with hx | hx
    · change Continuous (fun u : Matrix.unitaryGroup α ℂ =>
        G.chosenMatrixExtension A D ι hext u x)
      simpa only [G.chosenMatrixExtension_base A D ι hext _ (⟨x, hx⟩ : A)] using
        (continuous_const : Continuous (fun _ : Matrix.unitaryGroup α ℂ => x))
    · change Continuous (fun u : Matrix.unitaryGroup α ℂ =>
        G.chosenMatrixExtension A D ι hext u x)
      simpa only [G.chosenMatrixExtension_other A D ι hext _ (⟨x, hx⟩ : D)] using
        continuous_matrixConjugateLetter D ι (⟨x, hx⟩ : D)
  exact hs a.property

/-- The actual free-product matrix representation is strongly continuous;
only the ordinary tracial generation and published factor extension are used. -/
theorem matrixExtensionUnitaryRepresentation_stronglyContinuous (x : H) :
    Continuous (fun u : Matrix.unitaryGroup α ℂ =>
      (G.matrixExtensionUnitaryRepresentation A D ι hgen hfaithful hext u : H →L[ℂ] H) x) := by
  let U : Matrix.unitaryGroup α ℂ → H →L[ℂ] H := fun u =>
    (G.matrixExtensionUnitaryRepresentation A D ι hgen hfaithful hext u : H →L[ℂ] H)
  have hclosed : IsClosed (continuousOrbitSubmodule U : Set H) :=
    continuousOrbitSubmodule_isClosed U (fun u =>
      (Unitary.linearIsometryEquiv
        (G.matrixExtensionUnitaryRepresentation A D ι hgen hfaithful hext u)).toLinearIsometry.norm_toContinuousLinearMap_le)
  refine hgen.induction_on x hclosed ?_
  intro a
  change Continuous (fun u : Matrix.unitaryGroup α ℂ =>
    (G.matrixExtensionUnitaryRepresentation A D ι hgen hfaithful hext u : H →L[ℂ] H)
      (G.vector (a : P)))
  simpa only [G.matrixExtensionUnitaryRepresentation_vector, Function.comp_def] using
    G.continuous_vector.comp (G.continuous_chosenMatrixExtension A D ι hext a)

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
