import OAI.Analysis.KadisonSimilarity.Tracial.TracialL2Closure
import OAI.Analysis.KadisonSimilarity.FreeProduct.TracialFreeCornerModel

namespace OAI

/-! The two auxiliary algebras in the spectral test are the actual bounded
L² closures of their algebraic generators. Their inclusions and the density
premises in the free-corner theorem follow from this construction. -/

noncomputable section
namespace KadisonSimilarity
namespace TracialCornerGeometry

variable {P H : Type*} [CStarAlgebra P]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (G : TracialCornerGeometry P H)

/-- Bounded L² generation is monotone in its algebraic generators. -/
theorem l2GeneratedAlgebra_mono {S T : StarSubalgebra ℂ P} (hST : S ≤ T) :
    G.l2GeneratedAlgebra S ≤ G.l2GeneratedAlgebra T := by
  intro x hx
  have hx' : G.vector x ∈ G.baseSpace S := by
    have : G.vector x ∈ G.baseSpace S.topologicalClosure := hx
    simpa only [G.baseSpace_topologicalClosure S] using this
  have hxT := G.baseSpace_mono hST hx'
  change G.vector x ∈ G.baseSpace T.topologicalClosure
  simpa only [G.baseSpace_topologicalClosure T] using hxT

/-- The constructed algebra has precisely the algebra-vector density used
in the Fourier test, in the linear-span formulation of that theorem. -/
theorem l2GeneratedAlgebra_vector_mem_span (S : StarSubalgebra ℂ P)
    (x : G.l2GeneratedAlgebra S) :
    G.vector (x : P) ∈ (Submodule.span ℂ
      (G.vector '' (S : Set P))).topologicalClosure := by
  have hx := G.l2GeneratedAlgebra_vector_mem S x
  apply closure_mono (s := Set.range (G.baseAlgebraVectors S)) ?_ hx
  rintro _ ⟨a, rfl⟩
  exact Submodule.subset_span ⟨a, a.property, rfl⟩

/-- The finite dihedral von Neumann algebra, expressed through its bounded
L² closure; no normal-form density is imposed as an extra premise. -/
def generatedDihedralAlgebra (d s : P) : StarSubalgebra ℂ P :=
  G.l2GeneratedAlgebra (StarAlgebra.adjoin ℂ ({d, s} : Set P))

/-- The auxiliary algebra generated by the second factor and the test
symmetry. -/
def generatedTestAlgebra (D : StarSubalgebra ℂ P) (s : P) : StarSubalgebra ℂ P :=
  G.l2GeneratedAlgebra (StarAlgebra.adjoin ℂ ((D : Set P) ∪ {s}))

instance generatedDihedralAlgebra_isClosed (d s : P) :
    IsClosed (G.generatedDihedralAlgebra d s : Set P) :=
  G.l2GeneratedAlgebra_isClosed _

instance generatedTestAlgebra_isClosed (D : StarSubalgebra ℂ P) (s : P) :
    IsClosed (G.generatedTestAlgebra D s : Set P) :=
  G.l2GeneratedAlgebra_isClosed _

theorem first_mem_generatedDihedralAlgebra (d s : P) :
    d ∈ G.generatedDihedralAlgebra d s :=
  G.le_l2GeneratedAlgebra _ (StarAlgebra.subset_adjoin ℂ _ (Set.mem_insert d _))

theorem second_mem_generatedDihedralAlgebra (d s : P) :
    s ∈ G.generatedDihedralAlgebra d s :=
  G.le_l2GeneratedAlgebra _ (StarAlgebra.subset_adjoin ℂ _ (by simp))

theorem le_generatedTestAlgebra (D : StarSubalgebra ℂ P) (s : P) :
    D ≤ G.generatedTestAlgebra D s := by
  intro x hx
  exact G.le_l2GeneratedAlgebra _ (StarAlgebra.subset_adjoin ℂ _ (Or.inl hx))

theorem generatedDihedralAlgebra_le_test (D : StarSubalgebra ℂ P)
    (d : D) (s : P) :
    G.generatedDihedralAlgebra (d : P) s ≤ G.generatedTestAlgebra D s := by
  apply G.l2GeneratedAlgebra_mono
  apply StarAlgebra.adjoin_mono
  intro x hx
  rcases Set.mem_insert_iff.mp hx with rfl | hx
  · exact Or.inl d.property
  · exact Or.inr hx

theorem generatedDihedralAlgebra_density (d s : P)
    (x : G.generatedDihedralAlgebra d s) :
    G.vector (x : P) ∈ (Submodule.span ℂ (G.vector ''
      (StarAlgebra.adjoin ℂ ({d, s} : Set P) : Set P))).topologicalClosure :=
  G.l2GeneratedAlgebra_vector_mem_span _ x

theorem generatedTestAlgebra_density (D : StarSubalgebra ℂ P) (s : P)
    (x : G.generatedTestAlgebra D s) :
    G.vector (x : P) ∈ (Submodule.span ℂ (G.vector ''
      (StarAlgebra.adjoin ℂ ((D : Set P) ∪ {s}) : Set P))).topologicalClosure :=
  G.l2GeneratedAlgebra_vector_mem_span _ x

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
