import OAI.Analysis.KadisonSimilarity.FreeProduct.GeneratedWordDensity
import OAI.Analysis.KadisonSimilarity.FreeProduct.FreeProductMatrixContinuity
import OAI.Analysis.KadisonSimilarity.FreeProduct.PublishedWordCreation

namespace OAI

/-! Restriction to the C-star algebra generated by the two free factors.
The compression model is used on this cyclic generated representation,
and faithfulness transfers its norm estimate to the ambient algebra. -/

noncomputable section
namespace KadisonSimilarity

open scoped Topology
open TracialCornerGeometry

variable {P H : Type*} [CStarAlgebra P]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

namespace TracialCornerGeometry

variable (G : TracialCornerGeometry P H) (A D : StarSubalgebra ℂ P)

/-- Norm generation implies generation of the actual tracial Hilbert space. -/
theorem factorsTraciallyGenerate_of_norm_generation
    (hgen : (factorAlgebra A D).topologicalClosure = ⊤) :
    G.FactorsTraciallyGenerate A D := by
  let M := (G.vector.comp (factorAlgebra A D).subtype.toLinearMap).range.topologicalClosure
  have ha (a : P) : G.vector a ∈ M := by
    have hc : IsClosed (G.vector ⁻¹' (M : Set H)) :=
      (Submodule.isClosed_topologicalClosure _).preimage G.continuous_vector
    have hs : (factorAlgebra A D : Set P) ⊆ G.vector ⁻¹' (M : Set H) := by
      intro x hx
      exact Submodule.le_topologicalClosure _ ⟨⟨x, hx⟩, rfl⟩
    have ha : a ∈ closure (factorAlgebra A D : Set P) := by
      change a ∈ (factorAlgebra A D).topologicalClosure
      rw [hgen]
      trivial
    exact hc.closure_subset_iff.mpr hs ha
  have hM : M = ⊤ := by
    apply top_unique
    intro x _
    exact G.dense_vector.induction_on x (Submodule.isClosed_topologicalClosure _) ha
  apply dense_iff_closure_eq.mpr
  change (M : Set H) = Set.univ
  rw [hM]
  rfl

end TracialCornerGeometry

/-- Pulling the two factors into their closed generated algebra preserves
their ordinary norm-generation property. -/
theorem factorAlgebra_comap_generates (A D S : StarSubalgebra ℂ P)
    (hA : A ≤ S) (hD : D ≤ S) (hS : (factorAlgebra A D).topologicalClosure = S)
    [IsClosed (S : Set P)] :
    (factorAlgebra (A.comap S.subtype) (D.comap S.subtype)).topologicalClosure = ⊤ := by
  have himage (B : StarSubalgebra ℂ P) (hB : B ≤ S) :
      S.subtype '' (B.comap S.subtype : Set S) = (B : Set P) := by
    ext x
    constructor
    · rintro ⟨y, hy, rfl⟩; exact hy
    · intro hx; exact ⟨⟨x, hB hx⟩, hx, rfl⟩
  have hm : (factorAlgebra (A.comap S.subtype) (D.comap S.subtype)).map S.subtype =
      factorAlgebra A D := by
    simp only [factorAlgebra, StarAlgHom.map_adjoin, Set.image_union, himage A hA, himage D hD]
  have hclosed : IsClosedMap S.subtype :=
    (show IsClosed (S : Set P) from inferInstance).isClosedMap_subtype_val
  have hmap := StarSubalgebra.topologicalClosure_map
    (factorAlgebra (A.comap S.subtype) (D.comap S.subtype)) S.subtype hclosed
      continuous_subtype_val
  rw [hm, hS] at hmap
  apply top_unique
  intro x _
  have hx : (x : P) ∈ ((factorAlgebra (A.comap S.subtype)
      (D.comap S.subtype)).topologicalClosure).map S.subtype := by
    rw [← hmap]
    exact x.property
  obtain ⟨y, hy, heq⟩ := hx
  exact (Subtype.ext heq : y = x) ▸ hy

instance isClosed_comap_subtype (A S : StarSubalgebra ℂ P) [IsClosed (A : Set P)] :
    IsClosed (A.comap S.subtype : Set S) :=
  (show IsClosed (A : Set P) from inferInstance).preimage continuous_subtype_val

theorem alternatingCenteredWord_subtype (τ : P →ₗ[ℂ] ℂ)
    (A D S : StarSubalgebra ℂ P) {side : Bool} {xs : List S}
    (h : AlternatingCenteredWord (τ.comp S.subtype.toLinearMap)
      (A.comap S.subtype) (D.comap S.subtype) side xs) :
    AlternatingCenteredWord τ A D side (xs.map (fun x : S => (x : P))) := by
  induction h with
  | nil side => exact .nil side
  | @cons side x xs hm hz _ ih =>
    change AlternatingCenteredWord τ A D side ((x : P) :: xs.map (fun x : S => (x : P)))
    apply AlternatingCenteredWord.cons ?_ (show τ (x : P) = 0 from hz) ih
    cases side <;> exact hm

theorem scalarFree_subtype (τ : P →ₗ[ℂ] ℂ) (A D S : StarSubalgebra ℂ P)
    (hf : ScalarFree τ A D) :
    ScalarFree (τ.comp S.subtype.toLinearMap) (A.comap S.subtype) (D.comap S.subtype) := by
  intro side x xs h
  have ht := hf side (x : P) (xs.map (fun y : S => (y : P)))
    (alternatingCenteredWord_subtype τ A D S h)
  exact (congrArg τ (map_list_prod S.subtype (x :: xs))).trans ht

namespace TracialCornerGeometry

variable (G : TracialCornerGeometry P H) (A D S : StarSubalgebra ℂ P)
  [IsClosed (A : Set P)] [IsClosed (D : Set P)] [IsClosed (S : Set P)]

/-- The narrow compression bound is proved in the cyclic Hilbert space of
the generated algebra, then read in the ambient C-star norm. -/
theorem norm_narrow_compression_on_generated_algebra
    (hA : A ≤ S) (hD : D ≤ S) (hS : (factorAlgebra A D).topologicalClosure = S)
    (published : RicardXuCompressionInput (G.baseGeometry S)
      (A.comap S.subtype) (D.comap S.subtype))
    (hτ : G.trace 1 = 1) (hfaithful : Function.Injective G.vector)
    (hfree : ScalarFree G.trace D A)
    (e : A) (he : IsStarProjection (e : P))
    (b : D) (hbself : star b = b) (hb0 : G.trace (b : P) = 0)
    {u : ℝ} (hu : 0 ≤ u) (hetrace : G.trace (e : P) = (u : ℂ))
    (hb₂ : (G.trace (star (b : P) * (b : P))).re ≤ u) (hbnorm : ‖(b : P)‖ ≤ 1) :
    ‖(e : P) * (b : P) * (e : P)‖ ≤ 3 * u := by
  let eS : A.comap S.subtype := ⟨⟨e, hA e.property⟩, e.property⟩
  let bS : D.comap S.subtype := ⟨⟨b, hD b.property⟩, b.property⟩
  have heS : IsStarProjection (eS : S) := by
    constructor
    · exact Subtype.ext he.isIdempotentElem.eq
    · exact Subtype.ext he.isSelfAdjoint.star_eq
  have hbS : star bS = bS := by
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun x : D => (x : P)) hbself
  have hτS := G.baseGeometry_trace_one S hτ
  have hgen := factorAlgebra_comap_generates A D S hA hD hS
  have hdense := (G.baseGeometry S).reducedWordGenerated_of_factorsTraciallyGenerate
    (A.comap S.subtype) (D.comap S.subtype) hτS
    ((G.baseGeometry S).factorsTraciallyGenerate_of_norm_generation
      (A.comap S.subtype) (D.comap S.subtype) hgen)
  exact norm_narrow_compression_of_published_words (G.baseGeometry S)
    (A.comap S.subtype) (D.comap S.subtype) published hτS
    (G.baseGeometry_vector_injective S hfaithful) (scalarFree_subtype G.trace D A S hfree)
    hdense eS heS bS hbS hb0 hu hetrace hb₂ hbnorm

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
