import OAI.Analysis.KadisonSimilarity.FreeProduct.FreeProductAutomorphisms
import OAI.Analysis.KadisonSimilarity.FreeProduct.ReducedWordModel

namespace OAI

/-! Dense reduced words provide the tracial generation needed to turn
published factor embeddings into actual free-product automorphisms. -/

noncomputable section
namespace KadisonSimilarity
namespace TracialCornerGeometry

variable {P H : Type*} [CStarAlgebra P]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (G : TracialCornerGeometry P H) (A D : StarSubalgebra ℂ P)

/-- Every bounded reduced word belongs to the algebra generated by the factors. -/
theorem reducedWord_mem_factorAlgebra (n : ℕ) (d : D) (b : A)
    (a : Fin n → A) (c : Fin n → D) :
    (d : P) * alternatingProduct (fun i => (a i : P)) (fun i => (c i : P)) * (b : P) ∈
      factorAlgebra A D := by
  have hA (x : A) : (x : P) ∈ factorAlgebra A D :=
    StarAlgebra.subset_adjoin ℂ _ (Or.inl x.property)
  have hD (x : D) : (x : P) ∈ factorAlgebra A D :=
    StarAlgebra.subset_adjoin ℂ _ (Or.inr x.property)
  apply (factorAlgebra A D).mul_mem
  · apply (factorAlgebra A D).mul_mem (hD d)
    unfold alternatingProduct
    have hprod (l : List P) :
        (∀ x ∈ l, x ∈ factorAlgebra A D) → l.prod ∈ factorAlgebra A D := by
      induction l with
      | nil => intro _; exact (factorAlgebra A D).one_mem
      | cons x l ih =>
        intro hl
        exact (factorAlgebra A D).mul_mem (hl x (List.mem_cons_self))
          (ih (fun y hy => hl y (List.mem_cons_of_mem _ hy)))
    apply hprod
    intro x hx
    obtain ⟨i, rfl⟩ := List.mem_ofFn.mp hx
    exact (factorAlgebra A D).mul_mem (hA (a i)) (hD (c i))
  · exact hA b

/-- The ordinary reduced-word density supplies the tracial algebraic generation;
no separate factor-generation hypothesis is required for automorphism extension. -/
theorem factorsTraciallyGenerate_of_reducedWordGenerated
    (hgen : ReducedWordGenerated G A D) : G.FactorsTraciallyGenerate A D := by
  let V : factorAlgebra A D →ₗ[ℂ] H :=
    G.vector.comp (factorAlgebra A D).subtype.toLinearMap
  have hspan : Submodule.span ℂ (reducedWordVectors G A D) ≤ V.range := by
    apply Submodule.span_le.mpr
    intro x hx
    obtain ⟨n, d, b, a, c, _ha, _hc, rfl⟩ := hx
    refine ⟨⟨_, reducedWord_mem_factorAlgebra A D n d b a c⟩, rfl⟩
  have htop : V.range.topologicalClosure = ⊤ := by
    apply top_unique
    have h := Submodule.topologicalClosure_mono hspan
    rw [hgen] at h
    exact h
  change DenseRange V
  apply dense_iff_closure_eq.mpr
  change (V.range.topologicalClosure : Set H) = Set.univ
  rw [htop]
  rfl

/-- Existence of the ambient matrix-conjugation automorphism follows from the
published two-factor extension and the actual reduced-word density. -/
def matrixAutomorphismOfReducedWords
    (hgen : ReducedWordGenerated G A D) (hfaithful : Function.Injective G.vector)
    {α : Type*} [Fintype α] [DecidableEq α]
    (ι : Matrix α α ℂ →⋆ₐ[ℂ] D) (hext : G.MatrixConjugationExtensionInput D ι A)
    (u : Matrix.unitaryGroup α ℂ) : P ≃⋆ₐ[ℂ] P :=
  G.matrixExtensionAutomorphism A D ι
    (G.factorsTraciallyGenerate_of_reducedWordGenerated A D hgen) hfaithful hext u

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
