import OAI.Analysis.KadisonSimilarity.FreeProduct.FreeWordExpectation
import OAI.Analysis.KadisonSimilarity.FreeProduct.ExpectationWordClosure
import OAI.Analysis.KadisonSimilarity.FreeProduct.SymmetryExpectation

namespace OAI

/-! The base expectation on the algebra generated by the other free factor
and one centered symmetry. The only density datum is the ordinary reduced
word span; the two-dimensional expectation range is proved. -/

noncomputable section
namespace KadisonSimilarity

variable {P : Type*} [CStarAlgebra P]

/-- Alternating words in centered other-factor letters and one fixed symmetry.
`true` means that the next letter comes from the other factor. -/
inductive CenteredSymmetryWord (τ : P →ₗ[ℂ] ℂ) (D : StarSubalgebra ℂ P) (s : P) :
    Bool → List P → Prop
  | nil (side : Bool) : CenteredSymmetryWord τ D s side []
  | other {d : P} {xs : List P} (hd : d ∈ D) (hzero : τ d = 0)
      (tail : CenteredSymmetryWord τ D s false xs) :
      CenteredSymmetryWord τ D s true (d :: xs)
  | symmetry {xs : List P} (tail : CenteredSymmetryWord τ D s true xs) :
      CenteredSymmetryWord τ D s false (s :: xs)

namespace CenteredSymmetryWord

variable {τ : P →ₗ[ℂ] ℂ} {D A : StarSubalgebra ℂ P} {s : P}

theorem alternating (hs : s ∈ A) (hs0 : τ s = 0)
    {side : Bool} {xs : List P} (h : CenteredSymmetryWord τ D s side xs) :
    AlternatingCenteredWord τ D A side xs := by
  induction h with
  | nil side => exact .nil side
  | other hd hz _ ih => exact .cons (by simpa using hd) hz ih
  | symmetry _ ih => exact .cons (by simpa using hs) hs0 ih

/-- The expectation of a reduced word is either zero, the unit, or the
specified symmetry. This follows from freeness and bimodularity. -/
theorem expectation_span
    (E : TracialExpectation τ A)
    (hfaithful : ∀ x, τ (star x * x) = 0 → x = 0)
    (hτ : τ 1 = 1) (hfree : ScalarFree τ D A)
    (hs : s ∈ A) (hs0 : τ s = 0)
    {side : Bool} {xs : List P} (h : CenteredSymmetryWord τ D s side xs) :
    ∃ α β : ℂ, E.map xs.prod = α • (1 : P) + β • s := by
  cases h with
  | nil side =>
    refine ⟨1, 0, ?_⟩
    simp only [List.prod_nil, E.map_one hfaithful, one_smul, zero_smul, add_zero]
  | @other d xs hd hz tail =>
    refine ⟨0, 0, ?_⟩
    have hw : AlternatingCenteredWord τ D A true (d :: xs) :=
      .cons (by simpa using hd) hz (tail.alternating hs hs0)
    rw [E.map_reduced_word hfaithful hτ hfree d xs hw]
    simp
  | @symmetry xs tail =>
    cases tail with
    | nil =>
      refine ⟨0, 1, ?_⟩
      simp only [List.prod_cons, List.prod_nil, mul_one,
        E.map_of_mem hfaithful hs, zero_smul, one_smul, zero_add]
    | @other d ys hd hz tail =>
      refine ⟨0, 0, ?_⟩
      have hw : AlternatingCenteredWord τ D A true (d :: ys) :=
        .cons (by simpa using hd) hz (tail.alternating hs hs0)
      change E.map (s * (d :: ys).prod) = _
      rw [E.map_base_mul_reduced_word hfaithful hτ hfree s hs d ys hw]
      simp

end CenteredSymmetryWord

/-- Ordinary products of the alternating reduced symmetry words. -/
def centeredSymmetryWordProducts (τ : P →ₗ[ℂ] ℂ) (D : StarSubalgebra ℂ P) (s : P) :
    Set P := {x | ∃ (side : Bool) (xs : List P), CenteredSymmetryWord τ D s side xs ∧
      x = xs.prod}

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

namespace TracialCornerGeometry

variable (G : TracialCornerGeometry P H) (A D S : StarSubalgebra ℂ P)

/-- Passage from the actual reduced words to their L² closure supplies the
word-algebra range hypothesis of the Fourier compression. -/
theorem expectation_span_of_symmetry_word_density
    (E : TracialExpectation G.trace A) (hfaithful : Function.Injective G.vector)
    (hτ : G.trace 1 = 1) (hfree : ScalarFree G.trace D A)
    (s : P) (hs : s ∈ A) (hs0 : G.trace s = 0)
    (hdense : ∀ x, x ∈ S → G.vector x ∈
      (Submodule.span ℂ (G.vector '' centeredSymmetryWordProducts G.trace D s)).topologicalClosure)
    (x : P) (hx : x ∈ S) :
    ∃ α β : ℂ, E.map x = α • (1 : P) + β • s := by
  apply G.expectation_span_of_word_closure A E hfaithful s
    (centeredSymmetryWordProducts G.trace D s) _ x (hdense x hx)
  rintro y ⟨side, xs, hw, rfl⟩
  exact hw.expectation_span E (G.trace_faithful hfaithful) hτ hfree hs hs0

end TracialCornerGeometry
end KadisonSimilarity

end

end OAI
