import OAI.Analysis.KadisonSimilarity.Tracial.TracialExpectations
import OAI.Analysis.KadisonSimilarity.FreeProduct.DihedralFourier

namespace OAI

/-! Identifying a tracial expectation whose range lies in the two-dimensional
algebra generated by a centered symmetry. The Fourier identities then require
only scalar trace moments, not operator-valued moment assumptions. -/

noncomputable section
namespace KadisonSimilarity

variable {P : Type*} [CStarAlgebra P] {τ : P →ₗ[ℂ] ℂ}
  {A : StarSubalgebra ℂ P}

namespace TracialExpectation

/-- Trace preservation and the trace pairing with s determine both
coefficients of the conditional expectation. -/
theorem map_eq_symmetryExpectation (E : TracialExpectation τ A)
    (hτ : τ 1 = 1) (s : P) (hsA : s ∈ A) (hs0 : τ s = 0) (hs2 : s * s = 1)
    (x : P) (hspan : ∃ α β : ℂ, E.map x = α • (1 : P) + β • s) :
    E.map x = symmetryExpectation τ s x := by
  obtain ⟨α, β, he⟩ := hspan
  have hα : τ x = α := by
    rw [← E.trace_map x, he, map_add, map_smul, map_smul, hτ, hs0]
    simp
  have hβ : τ (s * x) = β := by
    rw [← E.pairing x s hsA, he, mul_add, mul_smul_comm, mul_smul_comm,
      mul_one, hs2, map_add, map_smul, map_smul, hs0, hτ]
    simp
  rw [he, symmetryExpectation_apply, hα, hβ]

/-- The rotation and reflection expectation identities follow from scalar
Fourier moments once the free-word calculation puts these expectations in
span{1,s}. -/
theorem rotation_reflection_of_scalar_moments (E : TracialExpectation τ A)
    (hτ : τ 1 = 1) (htr : ∀ x y, τ (x * y) = τ (y * x))
    (s : P) (hsA : s ∈ A) (hs0 : τ s = 0) (hs2 : s * s = 1)
    (x : P) (γ : ℂ) (hcoef : τ x = γ) (hcoset : τ (s * x) = 0)
    (hspan : ∃ α β : ℂ, E.map x = α • (1 : P) + β • s)
    (hspan' : ∃ α β : ℂ, E.map (x * s) = α • (1 : P) + β • s) :
    E.map x = γ • (1 : P) ∧ E.map (x * s) = γ • s := by
  rw [E.map_eq_symmetryExpectation hτ s hsA hs0 hs2 x hspan,
    E.map_eq_symmetryExpectation hτ s hsA hs0 hs2 (x * s) hspan']
  simpa only [hcoef] using symmetryExpectation_mul_symmetry τ htr s x hs2 hcoset

/-- On the word algebra, a two-dimensional base expectation factors through
any intermediate algebra containing the symmetry. No global tower inclusion
of the entire base algebra is required. -/
theorem restricted_tower_of_symmetry_span (E : TracialExpectation τ A)
    {C S : StarSubalgebra ℂ P} (EC : TracialExpectation τ C) (hCS : C ≤ S)
    (hτ : τ 1 = 1) (s : P) (hsA : s ∈ A) (hsC : s ∈ C)
    (hs0 : τ s = 0) (hs2 : s * s = 1)
    (hspan : ∀ x, x ∈ S → ∃ α β : ℂ, E.map x = α • (1 : P) + β • s)
    (x : P) (hx : x ∈ S) : E.map (EC.map x) = E.map x := by
  rw [E.map_eq_symmetryExpectation hτ s hsA hs0 hs2 _ (hspan _ (hCS (EC.range x))),
    E.map_eq_symmetryExpectation hτ s hsA hs0 hs2 x (hspan x hx)]
  simp only [symmetryExpectation_apply, EC.trace_map, EC.pairing x s hsC]

/-- The dihedral Fourier entry with actual trace-pairing expectations.
Only scalar Fourier moments and the base word-range calculation remain;
bimodularity and the correctly restricted tower identity are derived. -/
theorem dihedral_entry_of_scalar_moments (E : TracialExpectation τ A)
    {C S : StarSubalgebra ℂ P} (EC : TracialExpectation τ C) (hCS : C ≤ S)
    (hfaithful : ∀ x, τ (star x * x) = 0 → x = 0)
    (hτ : τ 1 = 1) (htr : ∀ x y, τ (x * y) = τ (y * x))
    (w d : Pˣ) (hd : d * w = w⁻¹ * d)
    (hsA : (↑(w⁻¹ * d) : P) ∈ A) (hsC : (↑(w⁻¹ * d) : P) ∈ C)
    (hs0 : τ (↑(w⁻¹ * d) : P) = 0)
    (hs2 : (↑(w⁻¹ * d) : P) * (↑(w⁻¹ * d) : P) = 1)
    (hspan : ∀ x, x ∈ S → ∃ α β : ℂ,
      E.map x = α • (1 : P) + β • (↑(w⁻¹ * d) : P))
    (hpower : ∀ j : ℤ, (↑(w ^ j) : P) ∈ C)
    (f h : P) (hf : f ∈ C) (hh : h ∈ S) (u : ℂ) (γ : ℤ → ℂ)
    (hEC : EC.map h = u ^ 2 • (f * dihedralHalfProjection d))
    (hcomm : ∀ j : ℤ, (↑(w ^ j) : P) * f = f * (↑(w ^ j) : P))
    (hcoef : ∀ l : ℤ, τ (f * (↑(w ^ l) : P)) = γ l)
    (hcoset : ∀ l : ℤ, τ ((↑(w⁻¹ * d) : P) * (f * (↑(w ^ l) : P))) = 0)
    (j k : ℤ) :
    E.map ((↑(w ^ j) : P) * h * (↑(w ^ (-k)) : P)) =
      (u ^ 2 / 2) • (γ (j - k) • (1 : P) +
        γ (j + k + 1) • (↑(w⁻¹ * d) : P)) := by
  have hrotref (l : ℤ) := E.rotation_reflection_of_scalar_moments hτ htr
    (↑(w⁻¹ * d) : P) hsA hs0 hs2 (f * (↑(w ^ l) : P)) (γ l)
    (hcoef l) (hcoset l) (hspan _ (hCS (C.mul_mem hf (hpower l))))
    (hspan _ (hCS (C.mul_mem (C.mul_mem hf (hpower l)) hsC)))
  apply compressed_dihedral_fourier_entry w d hd f h EC.map E.map γ u hEC
  · intro j k
    exact EC.bimodule hfaithful htr _ _ h (hpower j) (hpower (-k))
  · intro j k
    exact E.restricted_tower_of_symmetry_span EC hCS hτ _ hsA hsC hs0 hs2 hspan _
      (S.mul_mem (S.mul_mem (hCS (hpower j)) hh) (hCS (hpower (-k))))
  · exact hcomm
  · exact fun l => (hrotref l).1
  · exact fun l => (hrotref l).2

end TracialExpectation
end KadisonSimilarity

end

end OAI
