import OAI.CategoryTheory.Thomason.Gray.GlobePastingDensity
import OAI.CategoryTheory.Thomason.Gray.PastingGlobeChains
import OAI.CategoryTheory.Thomason.Gray.TopologicalIntervalCylinder
import OAI.CategoryTheory.Thomason.Strict.StrictTerminalConeCategory
import OAI.CategoryTheory.Thomason.Transfer.PastingGlobeCylinderPushout

namespace OAI

section

/-! # The extended cylinder is composition-generated by its globe images -/

namespace Thomason.Construction.StrictOmegaCategory.GrayChainExtension

open CategoryTheory CategoryTheory.Limits

noncomputable section

def parameterLeg {C : StrictOmegaCategory.{0}} (i : GlobePasting.Shape)
    (f : GlobePasting.object i ⟶ C) : model.obj (GlobePasting.object i) ⟶ cylinder.obj C :=
  parameterIso.hom.app i ≫ cylinder.map f

def globeLeg {C : StrictOmegaCategory.{0}} (n : ℕ) (f : Globe.category n ⟶ C) :
    model.obj (Globe.category n) ⟶ cylinder.obj C := parameterLeg (.globe n) f

theorem parameterLeg_naturality {C : StrictOmegaCategory.{0}}
    {i j : GlobePasting.Shape} (u : i ⟶ j) (f : GlobePasting.object j ⟶ C) :
    model.map u ≫ parameterLeg j f = parameterLeg i (u ≫ f) := by
  let pi : model.obj (GlobePasting.object i) ⟶ cylinder.obj (GlobePasting.object i) :=
    parameterIso.hom.app i
  let pj : model.obj (GlobePasting.object j) ⟶ cylinder.obj (GlobePasting.object j) :=
    parameterIso.hom.app j
  have he : model.map u ≫ pj = pi ≫ cylinder.map u := parameterIso.hom.naturality u
  change model.map u ≫ (pj ≫ cylinder.map f) = pi ≫ cylinder.map (u ≫ f)
  exact (Category.assoc _ _ _).symm.trans
    ((congrArg (fun q => q ≫ cylinder.map f) he).trans
      ((Category.assoc _ _ _).trans
        (congrArg (fun q => pi ≫ q) (cylinder.map_comp u f).symm)))

theorem pair_image_generated {C : StrictOmegaCategory.{0}} {I : Type}
    (g : I → cylinder.obj C)
    (n k : ℕ) (hk : k < n) (f : PastingGlobe.category n n k ⟶ C)
    (hL : ∀ x, Nonempty (CompositionExpression (cylinder.obj C) g
      ((globeLeg n (PastingGlobe.left n n k ≫ f)).toFun x)))
    (hR : ∀ x, Nonempty (CompositionExpression (cylinder.obj C) g
      ((globeLeg n (PastingGlobe.right n n k ≫ f)).toFun x)))
    (x : model.obj (PastingGlobe.category n n k)) :
    Nonempty (CompositionExpression (cylinder.obj C) g ((parameterLeg (.pair n k hk) f).toFun x)) := by
  let e := PastingGlobe.CylinderSource.modelIso hk
  let L : model.obj (PastingGlobe.category n n k) ⟶ cylinder.obj C :=
    parameterLeg (.pair n k hk) f
  obtain ⟨t⟩ := PushoutGeneration.generated_by_pieces
    (model.map (Globe.faceMap true k n)) (model.map (Globe.faceMap false k n)) (e.inv.toFun x)
  have hl : pushout.inl (model.map (Globe.faceMap true k n))
      (model.map (Globe.faceMap false k n)) ≫ (e.hom ≫ L) =
      globeLeg n (PastingGlobe.left n n k ≫ f) := by
    change pushout.inl _ _ ≫ ((PastingGlobe.CylinderSource.modelIso hk).hom ≫ L) = _
    rw [PastingGlobe.CylinderSource.modelIso_hom, ← Category.assoc]
    change (PastingGlobe.CylinderSource.piece n k false ≫
      PastingGlobe.CylinderSource.comparison n k) ≫ L = _
    rw [PastingGlobe.CylinderSource.piece_comparison n k false]
    exact parameterLeg_naturality
      (show GlobePasting.Shape.globe n ⟶ .pair n k hk from PastingGlobe.left n n k) f
  have hr : pushout.inr (model.map (Globe.faceMap true k n))
      (model.map (Globe.faceMap false k n)) ≫ (e.hom ≫ L) =
      globeLeg n (PastingGlobe.right n n k ≫ f) := by
    change pushout.inr _ _ ≫ ((PastingGlobe.CylinderSource.modelIso hk).hom ≫ L) = _
    rw [PastingGlobe.CylinderSource.modelIso_hom, ← Category.assoc]
    change (PastingGlobe.CylinderSource.piece n k true ≫
      PastingGlobe.CylinderSource.comparison n k) ≫ L = _
    rw [PastingGlobe.CylinderSource.piece_comparison n k true]
    exact parameterLeg_naturality
      (show GlobePasting.Shape.globe n ⟶ .pair n k hk from PastingGlobe.right n n k) f
  have hh := t.substitute (e.hom ≫ L) (fun a => by
    cases a with
    | inl y =>
      change Nonempty (CompositionExpression _ _
        ((pushout.inl _ _ ≫ (e.hom ≫ L)).toFun y))
      rw [hl]
      exact hL y
    | inr y =>
      change Nonempty (CompositionExpression _ _
        ((pushout.inr _ _ ≫ (e.hom ≫ L)).toFun y))
      rw [hr]
      exact hR y)
  have he : e.hom.toFun (e.inv.toFun x) = x :=
    congrArg (fun q => q.toFun x) e.inv_hom_id
  change Nonempty (CompositionExpression _ _ (L.toFun (e.hom.toFun (e.inv.toFun x)))) at hh
  rw [he] at hh
  exact hh

/-- A generating family containing every globe image generates the actual
extended cylinder; binary parameters add only composites. -/
theorem generated_by_globe_images {C : StrictOmegaCategory.{0}} {I : Type}
    (g : I → cylinder.obj C)
    (h : ∀ n (f : Globe.category n ⟶ C) x,
      Nonempty (CompositionExpression (cylinder.obj C) g ((globeLeg n f).toFun x)))
    (x : cylinder.obj C) : Nonempty (CompositionExpression (cylinder.obj C) g x) := by
  have hp (i : GlobePasting.Shape) (f : GlobePasting.object i ⟶ C)
      (y : model.obj (GlobePasting.object i)) :
      Nonempty (CompositionExpression (cylinder.obj C) g ((parameterLeg i f).toFun y)) := by
    cases i with
    | globe n => exact h n f y
    | pair n k hk => exact pair_image_generated g n k hk f (h n _) (h n _) y
  obtain ⟨t⟩ := ColimitGeneration.generated_by_pieces
    (presentationCocone C) (presentationIsColimit C) x
  exact t.substitute (𝟙 (cylinder.obj C)) (fun a => by
    rcases a with ⟨j, y⟩
    change Nonempty (CompositionExpression (cylinder.obj C) g
      (((presentationCocone C).ι.app j).toFun y))
    rw [presentation_leg]
    change Nonempty (CompositionExpression (cylinder.obj C) g
      ((parameterLeg j.left j.hom).toFun y))
    exact hp j.left j.hom y)

end
end Thomason.Construction.StrictOmegaCategory.GrayChainExtension

end

section

/-! # Actual bounded lifts of the ordered chain-cylinder atoms -/

namespace Thomason.Construction.StrictOmegaCategory.GrayChainExtension

open CategoryTheory _root_.OAI.Thomason.Construction.DirectedComplex

noncomputable section

def comparisonToRealization (K : DirectedComplex.{0}) :
    cylinder.obj K.realization ⟶ (rightCylinder K).realization :=
  comparison.app K.realization ≫
    (RightCylinder.map (Abelianization.evaluateHom (𝟙 K.realization))).realization

theorem evaluation_globe {K : DirectedComplex.{0}} {n : ℕ}
    (f : Globe.category n ⟶ K.realization) :
    Abelianization.functor.map f ≫ Abelianization.evaluateHom (𝟙 K.realization) =
      (DirectedGlobeComplex.abelianizationIso n).hom ≫
        DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top) := by
  let a : Abelianization.functor.obj (Globe.category n) ⟶ K :=
    (DirectedGlobeComplex.abelianizationIso n).hom ≫
      DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top)
  let b : Abelianization.functor.obj K.realization ⟶ K :=
    Abelianization.evaluateHom (𝟙 K.realization)
  change Abelianization.functor.map f ≫ b = a
  apply (Abelianization.adjunction.homEquiv _ _).injective
  rw [Abelianization.adjunction.homEquiv_naturality_left]
  change f ≫ (Abelianization.unit _ ≫
      (Abelianization.evaluateHom (𝟙 K.realization)).realization) =
    (Abelianization.unit _ ≫
      (Abelianization.evaluateHom (DirectedGlobeComplex.fromGlobe n)).realization) ≫
        (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top)).realization
  have hK : Abelianization.unit K.realization ≫
      (Abelianization.evaluateHom (𝟙 K.realization)).realization = 𝟙 K.realization :=
    Abelianization.unit_evaluate _
  have hn : Abelianization.unit (Globe.category n) ≫
      (Abelianization.evaluateHom (DirectedGlobeComplex.fromGlobe n)).realization =
        DirectedGlobeComplex.fromGlobe n := Abelianization.unit_evaluate _
  rw [hK, hn, Category.comp_id]
  apply Globe.hom_ext
  exact (DirectedGlobeComplex.cellMap_top_of_bounded n _
    (f.dimensionLE (Globe.category_truncated n Globe.Cell.top))).symm

theorem globeLeg_comparison {K : DirectedComplex.{0}} {n : ℕ}
    (f : Globe.category n ⟶ K.realization) :
    globeLeg n f ≫ comparisonToRealization K = (modelGlobeIso n).hom ≫
      (RightCylinder.map (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top))).realization := by
  let pi : model.obj (Globe.category n) ⟶ cylinder.obj (Globe.category n) :=
    parameterIso.hom.app (.globe n)
  let cG : cylinder.obj (Globe.category n) ⟶ model.obj (Globe.category n) :=
    comparison.app (Globe.category n)
  let cK : cylinder.obj K.realization ⟶ model.obj K.realization :=
    comparison.app K.realization
  let fM : model.obj (Globe.category n) ⟶ model.obj K.realization := model.map f
  let fC : cylinder.obj (Globe.category n) ⟶ cylinder.obj K.realization := cylinder.map f
  have hn : pi ≫ cG = 𝟙 _ :=
    congrArg (fun q => q.app (.globe n)) parameter_comparison
  have hf : fC ≫ cK = cG ≫ fM := comparison.naturality f
  have he : globeLeg n f ≫ cK = fM := by
    change (pi ≫ fC) ≫ cK = fM
    calc
      _ = pi ≫ (fC ≫ cK) := Category.assoc _ _ _
      _ = pi ≫ (cG ≫ fM) := congrArg (fun q => pi ≫ q) hf
      _ = (pi ≫ cG) ≫ fM := (Category.assoc _ _ _).symm
      _ = fM := by rw [hn, Category.id_comp]
  let T := rightCylinderFunctor ⋙ realizationFunctor
  let b : Abelianization.functor.obj K.realization ⟶ K :=
    Abelianization.evaluateHom (𝟙 K.realization)
  change globeLeg n f ≫ (cK ≫ T.map b) = _
  refine (Category.assoc _ _ _).symm.trans
    ((congrArg (fun q => q ≫ T.map b) he).trans ?_)
  change T.map (Abelianization.functor.map f) ≫ T.map b = _
  exact (T.map_comp (Abelianization.functor.map f) b).symm.trans
    ((congrArg T.map (evaluation_globe f)).trans
      (T.map_comp (DirectedGlobeComplex.abelianizationIso n).hom
        (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top))))

theorem globeEndpoint_image {K : DirectedComplex.{0}} {n : ℕ}
    (f : Globe.category n ⟶ K.realization) (a : Bool) :
    (comparisonToRealization K).toFun ((globeLeg n f).toFun (endpointTop n a)) =
      Cell.map (RightCylinder.endpoint K a) (f.toFun Globe.Cell.top) := by
  have he := congrArg (fun q => q.toFun (endpointTop n a)) (globeLeg_comparison f)
  have hi := congrArg (fun q => q.toFun
    (Cell.map (RightCylinder.endpoint _ a) (DirectedGlobeComplex.topCell n)))
      (modelGlobeIso n).inv_hom_id
  have ht : Cell.map (RightCylinder.map (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top)))
      (Cell.map (RightCylinder.endpoint _ a) (DirectedGlobeComplex.topCell n)) =
        Cell.map (RightCylinder.endpoint K a) (f.toFun Globe.Cell.top) := by
    have hh : Cell.map (RightCylinder.map (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top)))
        (Cell.map (RightCylinder.endpoint _ a) (DirectedGlobeComplex.topCell n)) =
      Cell.map (RightCylinder.endpoint K a)
        (Cell.map (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top))
          (DirectedGlobeComplex.topCell n)) := by
      apply Cell.ext
      funext c p
      exact RightCylinder.map_endpoint (DirectedGlobeComplex.cellMap n _) a p _
    exact hh.trans (congrArg (Cell.map (RightCylinder.endpoint K a))
      (DirectedGlobeComplex.cellMap_top_of_bounded n _
        (f.dimensionLE (Globe.category_truncated n Globe.Cell.top))))
  exact he.trans ((congrArg
    (RightCylinder.map (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top))).realization.toFun hi).trans ht)

theorem globePrism_image {K : DirectedComplex.{0}} {n : ℕ}
    (f : Globe.category n ⟶ K.realization) :
    (comparisonToRealization K).toFun ((globeLeg n f).toFun (prismTop n)) =
      RightCylinder.prism (f.toFun Globe.Cell.top) := by
  have he := congrArg (fun q => q.toFun (prismTop n)) (globeLeg_comparison f)
  have hi := congrArg (fun q => q.toFun (RightCylinder.prism (DirectedGlobeComplex.topCell n)))
    (modelGlobeIso n).inv_hom_id
  exact he.trans ((congrArg
    (RightCylinder.map (DirectedGlobeComplex.cellMap n (f.toFun Globe.Cell.top))).realization.toFun hi).trans
      ((RightCylinder.prism_naturality (DirectedGlobeComplex.cellMap n _)
        (DirectedGlobeComplex.topCell n)).trans
          (congrArg RightCylinder.prism (DirectedGlobeComplex.cellMap_top_of_bounded n _
            (f.dimensionLE (Globe.category_truncated n Globe.Cell.top))))))

def atomLift {K : DirectedComplex.{0}} (B : OrderedAtomBasis K) :
    {p : ℕ} → B.CylinderIndex p → cylinder.obj K.realization
  | p, .endpoint a b => (globeLeg p (Globe.lift K.realization (B.atom p b) (B.atom_dimension p b))).toFun
      (endpointTop p a)
  | _, @RightCylinderBasis.Basis.mixed _ q b =>
    (globeLeg q (Globe.lift K.realization (B.atom q b) (B.atom_dimension q b))).toFun (prismTop q)

theorem atomLift_dimension {K : DirectedComplex.{0}} (B : OrderedAtomBasis K)
    {p : ℕ} (b : B.CylinderIndex p) :
    (cylinder.obj K.realization).DimensionLE p (atomLift B b) := by
  cases b with
  | endpoint a b => exact (globeLeg _ _).dimensionLE (endpointTop_dimension _ a)
  | mixed b => exact (globeLeg _ _).dimensionLE (prismTop_dimension _)

theorem atomLift_image {K : DirectedComplex.{0}} (B : OrderedAtomBasis K)
    {p : ℕ} (b : B.CylinderIndex p) :
    (comparisonToRealization K).toFun (atomLift B b) = B.cylinderAtom b := by
  cases b with
  | endpoint a b => exact globeEndpoint_image _ a
  | mixed b => exact globePrism_image _

end
end Thomason.Construction.StrictOmegaCategory.GrayChainExtension

end

section

/-! # Composition of bounded maps from actual globe cylinders

The proved cylinder pushout glues matching bounded maps. Restricting the
gluing to the universal composite gives the required mapping-cell
composition, with literal source, target, and postcomposition equations.
-/

namespace Thomason.Construction.StrictOmegaCategory.GrayMapping

open CategoryTheory CategoryTheory.Limits

noncomputable section

abbrev model := GrayChainExtension.model

/-- The universal composite, with its common finite bound made explicit. -/
def compositionGlobe (n k : ℕ) (hk : k < n) :
    Globe.category n ⟶ PastingGlobe.category n n k :=
  Globe.lift _ (PastingGlobe.composite n n k) (by
    simpa only [Nat.max_self] using PastingGlobe.composite_dimension n n k
      (show k < max n n by simpa only [Nat.max_self] using hk))

theorem compositionGlobe_source (n k : ℕ) (hk : k < n) :
    Globe.faceMap false k n ≫ compositionGlobe n k hk =
      Globe.faceMap false k n ≫ PastingGlobe.left n n k := by
  apply Globe.hom_ext
  exact ((compositionGlobe n k hk).map_face false k Globe.Cell.top).trans
    (((PastingGlobe.category n n k).source_comp k (PastingGlobe.leftCell n n k)
      (PastingGlobe.rightCell n n k) (PastingGlobe.matching n n k)).trans
        ((PastingGlobe.left n n k).map_face false k Globe.Cell.top).symm)

theorem compositionGlobe_target (n k : ℕ) (hk : k < n) :
    Globe.faceMap true k n ≫ compositionGlobe n k hk =
      Globe.faceMap true k n ≫ PastingGlobe.right n n k := by
  apply Globe.hom_ext
  exact ((compositionGlobe n k hk).map_face true k Globe.Cell.top).trans
    (((PastingGlobe.category n n k).target_comp k (PastingGlobe.leftCell n n k)
      (PastingGlobe.rightCell n n k) (PastingGlobe.matching n n k)).trans
        ((PastingGlobe.right n n k).map_face true k Globe.Cell.top).symm)

variable {D E : StrictOmegaCategory.{0}} {n k : ℕ}

/-- Glue the actual maps on the two cylinder pieces. -/
def glue (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    model.obj (PastingGlobe.category n n k) ⟶ D :=
  (PastingGlobe.CylinderSource.isPushout hk).desc f g h

@[reassoc (attr := simp)] theorem glue_left (hk : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    model.map (PastingGlobe.left n n k) ≫ glue hk f g h = f :=
  (PastingGlobe.CylinderSource.isPushout hk).inl_desc f g h

@[reassoc (attr := simp)] theorem glue_right (hk : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    model.map (PastingGlobe.right n n k) ≫ glue hk f g h = g :=
  (PastingGlobe.CylinderSource.isPushout hk).inr_desc f g h

/-- Composition in a fixed finite mapping level. -/
def composite (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) : model.obj (Globe.category n) ⟶ D :=
  model.map (compositionGlobe n k hk) ≫ glue hk f g h

theorem composite_source (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    model.map (Globe.faceMap false k n) ≫ composite hk f g h =
      model.map (Globe.faceMap false k n) ≫ f := by
  change model.map (Globe.faceMap false k n) ≫
    (model.map (compositionGlobe n k hk) ≫ glue hk f g h) = _
  rw [← Category.assoc, ← model.map_comp, compositionGlobe_source,
    model.map_comp, Category.assoc, glue_left]

theorem composite_target (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    model.map (Globe.faceMap true k n) ≫ composite hk f g h =
      model.map (Globe.faceMap true k n) ≫ g := by
  change model.map (Globe.faceMap true k n) ≫
    (model.map (compositionGlobe n k hk) ≫ glue hk f g h) = _
  rw [← Category.assoc, ← model.map_comp, compositionGlobe_target,
    model.map_comp, Category.assoc, glue_right]

theorem glue_postcompose (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) (u : D ⟶ E)
    (hu : model.map (Globe.faceMap true k n) ≫ (f ≫ u) =
      model.map (Globe.faceMap false k n) ≫ (g ≫ u)) :
    glue hk (f ≫ u) (g ≫ u) hu = glue hk f g h ≫ u := by
  apply (PastingGlobe.CylinderSource.isPushout hk).hom_ext
  · rw [glue_left, ← Category.assoc, glue_left]
  · rw [glue_right, ← Category.assoc, glue_right]

theorem composite_postcompose (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) (u : D ⟶ E)
    (hu : model.map (Globe.faceMap true k n) ≫ (f ≫ u) =
      model.map (Globe.faceMap false k n) ≫ (g ≫ u)) :
    composite hk (f ≫ u) (g ≫ u) hu = composite hk f g h ≫ u := by
  change model.map (compositionGlobe n k hk) ≫ glue hk (f ≫ u) (g ≫ u) hu = _
  rw [glue_postcompose, ← Category.assoc]
  rfl

/-- The glued composite has exactly the required source in the actual union. -/
theorem composite_cell_source (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    GlobeMappingCells.face model D false k (GlobeMappingCells.ι model D n (composite hk f g h)) =
      GlobeMappingCells.face model D false k (GlobeMappingCells.ι model D n f) := by
  simp only [GlobeMappingCells.face_ι, composite_source]

theorem composite_cell_target (hk : k < n) (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g) :
    GlobeMappingCells.face model D true k (GlobeMappingCells.ι model D n (composite hk f g h)) =
      GlobeMappingCells.face model D true k (GlobeMappingCells.ι model D n g) := by
  simp only [GlobeMappingCells.face_ι, composite_target]

end
end Thomason.Construction.StrictOmegaCategory.GrayMapping

end

section

/-! # Generation of cylinder images under bounds, faces and composition -/

namespace Thomason.Construction.StrictOmegaCategory.GrayChainExtension

open CategoryTheory _root_.OAI.Thomason.Construction.DirectedComplex

noncomputable section

variable {C : StrictOmegaCategory.{0}} {I : Type} (g : I → cylinder.obj C)

def CellImageGenerated (n : ℕ) (x : C) (hx : C.DimensionLE n x) : Prop :=
  ∀ z : model.obj (Globe.category n), Nonempty (CompositionExpression (cylinder.obj C) g
    ((globeLeg n (Globe.lift C x hx)).toFun z))

theorem cellImageGenerated_mono {n m : ℕ} (hnm : n ≤ m) (x : C)
    (hx : C.DimensionLE n x) (hm : C.DimensionLE m x)
    (h : CellImageGenerated g n x hx) : CellImageGenerated g m x hm := by
  intro z
  have hf : Globe.lower m n hnm ≫ Globe.lift C x hx = Globe.lift C x hm := by
    apply Globe.hom_ext
    rfl
  have he := parameterLeg_naturality
    (show GlobePasting.Shape.globe m ⟶ .globe n from Globe.lower m n hnm) (Globe.lift C x hx)
  change model.map (Globe.lower m n hnm) ≫ globeLeg n (Globe.lift C x hx) =
    globeLeg m (Globe.lower m n hnm ≫ Globe.lift C x hx) at he
  rw [hf] at he
  have hh := h ((model.map (Globe.lower m n hnm)).toFun z)
  exact (congrArg (fun f => f.toFun z) he) ▸ hh

theorem cellImageGenerated_comp {n k : ℕ} (hk : k < n) (x y : C)
    (hx : C.DimensionLE n x) (hy : C.DimensionLE n y)
    (hxy : C.target k x = C.source k y)
    (hc : C.DimensionLE n (C.comp k x y hxy))
    (hX : CellImageGenerated g n x hx) (hY : CellImageGenerated g n y hy) :
    CellImageGenerated g n (C.comp k x y hxy) hc := by
  intro z
  let f := PastingGlobe.desc C x y hx hy hxy
  have hL : PastingGlobe.left n n k ≫ f = Globe.lift C x hx := by
    apply Globe.hom_ext
    exact PastingGlobe.desc_left _ _ _ _ _ _
  have hR : PastingGlobe.right n n k ≫ f = Globe.lift C y hy := by
    apply Globe.hom_ext
    exact PastingGlobe.desc_right _ _ _ _ _ _
  have hC : GrayMapping.compositionGlobe n k hk ≫ f = Globe.lift C (C.comp k x y hxy) hc := by
    apply Globe.hom_ext
    exact PastingGlobe.desc_composite _ _ _ _ _ _
  have hh := pair_image_generated g n k hk f
    (by simpa only [hL, CellImageGenerated] using hX)
    (by simpa only [hR, CellImageGenerated] using hY)
    ((model.map (GrayMapping.compositionGlobe n k hk)).toFun z)
  have he := parameterLeg_naturality
    (show GlobePasting.Shape.globe n ⟶ .pair n k hk from GrayMapping.compositionGlobe n k hk) f
  change model.map (GrayMapping.compositionGlobe n k hk) ≫ parameterLeg (.pair n k hk) f =
    globeLeg n (GrayMapping.compositionGlobe n k hk ≫ f) at he
  rw [hC] at he
  exact (congrArg (fun f => f.toFun z) he) ▸ hh

private theorem ordered_expression {K : DirectedComplex.{0}} (B : OrderedAtomBasis K)
    (x : K.realization) : Nonempty (CompositionExpression K.realization B.atomCell x) := by
  apply B.generated (fun x => Nonempty (CompositionExpression K.realization B.atomCell x))
    (fun p b => ⟨CompositionExpression.generator (C := K.realization)
      (g := B.atomCell) ⟨p, b⟩⟩) _ x
  intro r u v huv hu hv
  obtain ⟨tu⟩ := hu
  obtain ⟨tv⟩ := hv
  exact ⟨CompositionExpression.comp r huv tu tv⟩

/-- At a fixed bound, the two top endpoints and the top prism suffice once
all lower-dimensional face images have been generated. -/
theorem cellImageGenerated_of_top {n : ℕ} (x : C) (hx : C.DimensionLE n x)
    (hsmall : ∀ p, p < n → ∀ a,
      CellImageGenerated g p (C.face a p x) (C.face_dimensionLE a p x))
    (he : ∀ a, Nonempty (CompositionExpression (cylinder.obj C) g
      ((globeLeg n (Globe.lift C x hx)).toFun (endpointTop n a))))
    (hp : Nonempty (CompositionExpression (cylinder.obj C) g
      ((globeLeg n (Globe.lift C x hx)).toFun (prismTop n)))) :
    CellImageGenerated g n x hx := by
  intro z
  let B := DirectedGlobeComplex.cylinderOrderedAtomBasis n
  let e := modelGlobeIso n
  let F := e.inv ≫ globeLeg n (Globe.lift C x hx)
  have hface {p : ℕ} (hpn : p < n) (a : Bool) (w : model.obj (Globe.category p)) :
      Nonempty (CompositionExpression (cylinder.obj C) g
        ((globeLeg n (Globe.lift C x hx)).toFun
          ((model.map (Globe.faceMap a p n)).toFun w))) := by
    have hn := parameterLeg_naturality
      (show GlobePasting.Shape.globe p ⟶ .globe n from Globe.faceMap a p n) (Globe.lift C x hx)
    change model.map (Globe.faceMap a p n) ≫ globeLeg n (Globe.lift C x hx) =
      globeLeg p (Globe.faceMap a p n ≫ Globe.lift C x hx) at hn
    rw [Globe.faceMap_lift] at hn
    exact (congrArg (fun q => q.toFun w) hn).symm ▸ hsmall p hpn a w
  have hatom (p : ℕ) (b : B.Index p) :
      Nonempty (CompositionExpression (cylinder.obj C) g (F.toFun (B.atom p b))) := by
    cases b with
    | endpoint a b =>
      have hbn : p ≤ n := by rcases b.property with h | ⟨h, _⟩ <;> omega
      have hb := endpointTop_modelAtom b a
      change (model.map (Globe.faceMap b.val p n)).toFun (endpointTop p a) =
        e.inv.toFun (B.atom p (.endpoint a b)) at hb
      change Nonempty (CompositionExpression (cylinder.obj C) g
        ((globeLeg n (Globe.lift C x hx)).toFun (e.inv.toFun (B.atom p (.endpoint a b)))))
      rw [← hb]
      by_cases hpn : p < n
      · exact hface hpn b.val _
      · have hpn' : p = n := by omega
        subst p
        rw [Globe.faceMap_self, model.map_id]
        exact he a
    | @mixed p b =>
      have hbn : p ≤ n := by rcases b.property with h | ⟨h, _⟩ <;> omega
      have hb := prismTop_modelAtom b
      change (model.map (Globe.faceMap b.val p n)).toFun (prismTop p) =
        e.inv.toFun (B.atom (p+1) (.mixed b)) at hb
      change Nonempty (CompositionExpression (cylinder.obj C) g
        ((globeLeg n (Globe.lift C x hx)).toFun (e.inv.toFun (B.atom (p+1) (.mixed b)))))
      rw [← hb]
      by_cases hpn : p < n
      · exact hface hpn b.val _
      · have hpn' : p = n := by omega
        subst p
        rw [Globe.faceMap_self, model.map_id]
        exact hp
  obtain ⟨t⟩ := ordered_expression B (e.hom.toFun z)
  have ht := t.substitute F (fun (a : B.AtomIndex) => hatom a.1 a.2)
  have hi : e.inv.toFun (e.hom.toFun z) = z :=
    congrArg (fun q => q.toFun z) e.hom_inv_id
  change Nonempty (CompositionExpression (cylinder.obj C) g
    ((globeLeg n (Globe.lift C x hx)).toFun (e.inv.toFun (e.hom.toFun z)))) at ht
  rw [hi] at ht
  exact ht

end
end Thomason.Construction.StrictOmegaCategory.GrayChainExtension

end

section

/-! # Ordered atoms generate the actual extended cylinder

The dimension induction uses lower globe faces and the actual binary
cylinder pushout. It is independent of any colimit-preservation claim
about positive-table realization.
-/

namespace Thomason.Construction.StrictOmegaCategory.GrayChainExtension

open CategoryTheory _root_.OAI.Thomason.Construction.DirectedComplex

noncomputable section

variable {K : DirectedComplex.{0}} (B : OrderedAtomBasis K)

def cylinderAtomLift (a : Σ p, B.CylinderIndex p) : cylinder.obj K.realization :=
  atomLift B a.2

theorem cellImageGenerated_from_atoms (n : ℕ) (x : K.realization)
    (hx : K.realization.DimensionLE n x) :
    CellImageGenerated (cylinderAtomLift B) n x hx := by
  induction n using Nat.strong_induction_on generalizing x with
  | h n ih =>
    apply B.generated (fun x => ∀ hx : K.realization.DimensionLE n x,
      CellImageGenerated (cylinderAtomLift B) n x hx) _ _ x hx
    · intro p b hp
      have hpn : p ≤ n := B.atom_degree_le b hp
      by_cases hlt : p < n
      · exact cellImageGenerated_mono (cylinderAtomLift B) hpn _ (B.atom_dimension p b) hp
          (ih p hlt _ (B.atom_dimension p b))
      · have heq : p = n := by omega
        subst p
        apply cellImageGenerated_of_top (cylinderAtomLift B) (B.atom n b) hp
        · intro q hqn a
          exact ih q hqn _ (K.realization.face_dimensionLE a q (B.atom n b))
        · intro a
          exact ⟨CompositionExpression.generator (C := cylinder.obj K.realization)
            (g := cylinderAtomLift B) ⟨n, .endpoint a b⟩⟩
        · exact ⟨CompositionExpression.generator (C := cylinder.obj K.realization)
            (g := cylinderAtomLift B) ⟨n+1, .mixed b⟩⟩
    · intro r u v huv hu hv hc
      have hf := Cell.dimensionLE_comp_factors B.positive_add_eq_zero huv hc
      by_cases hrn : r < n
      · exact cellImageGenerated_comp (cylinderAtomLift B) hrn u v hf.1 hf.2 huv hc
          (hu hf.1) (hv hf.2)
      · have hnr : n ≤ r := Nat.le_of_not_gt hrn
        have hu' := K.realization.dimensionLE_mono hnr hf.1
        have hc' := K.realization.dimensionLE_mono hnr hc
        have he : K.realization.comp r u v huv = u :=
          hc'.1.symm.trans ((K.realization.source_comp r u v huv).trans hu'.1)
        change Cell.comp u v r huv = u at he
        have huall : ∀ h : K.realization.DimensionLE n u,
            CellImageGenerated (cylinderAtomLift B) n u h := hu
        have ht : ∀ h : K.realization.DimensionLE n (Cell.comp u v r huv),
            CellImageGenerated (cylinderAtomLift B) n (Cell.comp u v r huv) h :=
          he.symm ▸ huall
        exact ht hc

theorem generated_from_atoms (x : cylinder.obj K.realization) :
    Nonempty (CompositionExpression (cylinder.obj K.realization) (cylinderAtomLift B) x) := by
  apply generated_by_globe_images (cylinderAtomLift B) _ x
  intro n f z
  have hx := f.dimensionLE (Globe.category_truncated n Globe.Cell.top)
  have hf : Globe.lift K.realization (f.toFun Globe.Cell.top) hx = f := by
    apply Globe.hom_ext
    rfl
  have h := cellImageGenerated_from_atoms B n (f.toFun Globe.Cell.top) hx z
  simpa only [hf] using h

end
end Thomason.Construction.StrictOmegaCategory.GrayChainExtension

end

section

/-! # Identity extension commutes with the actual mapping composition -/

namespace Thomason.Construction.StrictOmegaCategory.GrayMapping

open CategoryTheory

noncomputable section

/-- Lower the common dimension of the two universal composable cells. -/
def pastingLower {n m : ℕ} (hnm : n ≤ m) (k : ℕ) :
    PastingGlobe.category m m k ⟶ PastingGlobe.category n n k :=
  PastingGlobe.desc _ (PastingGlobe.leftCell n n k) (PastingGlobe.rightCell n n k)
    ((PastingGlobe.category n n k).dimensionLE_mono hnm
      ((PastingGlobe.left n n k).dimensionLE (Globe.category_truncated n Globe.Cell.top)))
    ((PastingGlobe.category n n k).dimensionLE_mono hnm
      ((PastingGlobe.right n n k).dimensionLE (Globe.category_truncated n Globe.Cell.top)))
    (PastingGlobe.matching n n k)

theorem pastingLower_left {n m : ℕ} (hnm : n ≤ m) (k : ℕ) :
    PastingGlobe.left m m k ≫ pastingLower hnm k =
      Globe.lower m n hnm ≫ PastingGlobe.left n n k := by
  apply Globe.hom_ext
  exact PastingGlobe.desc_left _ _ _ _ _ _

theorem pastingLower_right {n m : ℕ} (hnm : n ≤ m) (k : ℕ) :
    PastingGlobe.right m m k ≫ pastingLower hnm k =
      Globe.lower m n hnm ≫ PastingGlobe.right n n k := by
  apply Globe.hom_ext
  exact PastingGlobe.desc_right _ _ _ _ _ _

theorem compositionGlobe_lower {n m k : ℕ} (hnm : n ≤ m) (hkn : k < n) :
    compositionGlobe m k (hkn.trans_le hnm) ≫ pastingLower hnm k =
      Globe.lower m n hnm ≫ compositionGlobe n k hkn := by
  apply Globe.hom_ext
  exact PastingGlobe.desc_composite _ _ _ _ _ _

variable {D : StrictOmegaCategory.{0}} {n m k : ℕ}

/-- Gluing the two identity-extended maps is restriction of the original gluing. -/
theorem glue_lower (hnm : n ≤ m) (hkn : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g)
    (hm : model.map (Globe.faceMap true k m) ≫ (model.map (Globe.lower m n hnm) ≫ f) =
      model.map (Globe.faceMap false k m) ≫ (model.map (Globe.lower m n hnm) ≫ g)) :
    glue (hkn.trans_le hnm) (model.map (Globe.lower m n hnm) ≫ f)
      (model.map (Globe.lower m n hnm) ≫ g) hm =
      model.map (pastingLower hnm k) ≫ glue hkn f g h := by
  apply (PastingGlobe.CylinderSource.isPushout (hkn.trans_le hnm)).hom_ext
  · rw [glue_left, ← Category.assoc, ← model.map_comp, pastingLower_left,
      model.map_comp, Category.assoc, glue_left]
  · rw [glue_right, ← Category.assoc, ← model.map_comp, pastingLower_right,
      model.map_comp, Category.assoc, glue_right]

/-- Composition is unchanged by enlarging the finite bound. -/
theorem composite_lower (hnm : n ≤ m) (hkn : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g)
    (hm : model.map (Globe.faceMap true k m) ≫ (model.map (Globe.lower m n hnm) ≫ f) =
      model.map (Globe.faceMap false k m) ≫ (model.map (Globe.lower m n hnm) ≫ g)) :
    composite (hkn.trans_le hnm) (model.map (Globe.lower m n hnm) ≫ f)
      (model.map (Globe.lower m n hnm) ≫ g) hm =
      model.map (Globe.lower m n hnm) ≫ composite hkn f g h := by
  change model.map (compositionGlobe m k _) ≫ glue _ _ _ hm = _
  rw [glue_lower hnm hkn f g h hm, ← Category.assoc, ← model.map_comp,
    compositionGlobe_lower, model.map_comp, Category.assoc]
  rfl

/-- The enlarged finite representative denotes the same actual mapping cell. -/
theorem composite_cell_lower (hnm : n ≤ m) (hkn : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g)
    (hm : model.map (Globe.faceMap true k m) ≫ (model.map (Globe.lower m n hnm) ≫ f) =
      model.map (Globe.faceMap false k m) ≫ (model.map (Globe.lower m n hnm) ≫ g)) :
    GlobeMappingCells.ι model D m
      (composite (hkn.trans_le hnm) (model.map (Globe.lower m n hnm) ≫ f)
        (model.map (Globe.lower m n hnm) ≫ g) hm) =
      GlobeMappingCells.ι model D n (composite hkn f g h) := by
  rw [composite_lower hnm hkn f g h hm]
  exact GlobeMappingCells.ι_lower model D hnm _

end
end Thomason.Construction.StrictOmegaCategory.GrayMapping

end

section

/-! # Evaluating mapping composition in a strict parameter

Any map from the actual cylinder of a parameter evaluates its binary
pasting maps by the already constructed mapping composition. This bridge
transfers strict diagrams between finite parameters to equations of maps.
-/

namespace Thomason.Construction.StrictOmegaCategory.GrayMapping

open CategoryTheory CategoryTheory.Limits

noncomputable section

variable {C D : StrictOmegaCategory.{0}} {n k : ℕ}

theorem evaluation_matching (p : PastingGlobe.category n n k ⟶ C)
    (u : model.obj C ⟶ D) :
    model.map (Globe.faceMap true k n) ≫ (model.map (PastingGlobe.left n n k ≫ p) ≫ u) =
      model.map (Globe.faceMap false k n) ≫ (model.map (PastingGlobe.right n n k ≫ p) ≫ u) := by
  simp only [← Category.assoc, ← model.map_comp]
  exact congrArg (fun q => model.map (q ≫ p) ≫ u)
    (pushout.condition (f := Globe.faceMap true k n) (g := Globe.faceMap false k n))

theorem glue_evaluation (hk : k < n) (p : PastingGlobe.category n n k ⟶ C)
    (u : model.obj C ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫
        (model.map (PastingGlobe.left n n k ≫ p) ≫ u) =
      model.map (Globe.faceMap false k n) ≫
        (model.map (PastingGlobe.right n n k ≫ p) ≫ u)) :
    glue hk (model.map (PastingGlobe.left n n k ≫ p) ≫ u)
      (model.map (PastingGlobe.right n n k ≫ p) ≫ u) h = model.map p ≫ u := by
  apply (PastingGlobe.CylinderSource.isPushout hk).hom_ext
  · rw [glue_left, ← Category.assoc, ← model.map_comp]
  · rw [glue_right, ← Category.assoc, ← model.map_comp]

theorem composite_evaluation (hk : k < n) (p : PastingGlobe.category n n k ⟶ C)
    (u : model.obj C ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫
        (model.map (PastingGlobe.left n n k ≫ p) ≫ u) =
      model.map (Globe.faceMap false k n) ≫
        (model.map (PastingGlobe.right n n k ≫ p) ≫ u)) :
    composite hk (model.map (PastingGlobe.left n n k ≫ p) ≫ u)
      (model.map (PastingGlobe.right n n k ≫ p) ≫ u) h =
        model.map (compositionGlobe n k hk ≫ p) ≫ u := by
  change model.map (compositionGlobe n k hk) ≫ glue hk _ _ h = _
  rw [glue_evaluation, ← Category.assoc, ← model.map_comp]

end
end Thomason.Construction.StrictOmegaCategory.GrayMapping

end

section

/-! # Representation-independent composition of mapping cells

Every matching pair has finite representatives at a common dimension.
The actual cylinder gluing commutes with identity extension, so its
composite is independent of all representative choices.
-/

namespace Thomason.Construction.StrictOmegaCategory.GrayMapping

open CategoryTheory

noncomputable section

abbrev Cell (D : StrictOmegaCategory.{0}) := GlobeMappingCells.Carrier model D

structure Representative {D : StrictOmegaCategory.{0}} (k : ℕ) (x y : Cell D) where
  bound : ℕ
  lt_bound : k < bound
  first : model.obj (Globe.category bound) ⟶ D
  last : model.obj (Globe.category bound) ⟶ D
  first_eq : GlobeMappingCells.ι model D bound first = x
  last_eq : GlobeMappingCells.ι model D bound last = y
  matching : model.map (Globe.faceMap true k bound) ≫ first =
    model.map (Globe.faceMap false k bound) ≫ last

namespace Representative

variable {D : StrictOmegaCategory.{0}} {k : ℕ} {x y : Cell D}

def value (r : Representative k x y) : Cell D :=
  GlobeMappingCells.ι model D r.bound (composite r.lt_bound r.first r.last r.matching)

def raise (r : Representative k x y) (N : ℕ) (h : r.bound ≤ N) : Representative k x y where
  bound := N
  lt_bound := r.lt_bound.trans_le h
  first := model.map (Globe.lower N r.bound h) ≫ r.first
  last := model.map (Globe.lower N r.bound h) ≫ r.last
  first_eq := (GlobeMappingCells.ι_lower model D h r.first).trans r.first_eq
  last_eq := (GlobeMappingCells.ι_lower model D h r.last).trans r.last_eq
  matching := by
    rw [← Category.assoc, ← model.map_comp, Globe.faceMap_lower,
      ← Category.assoc, ← model.map_comp, Globe.faceMap_lower]
    exact r.matching

theorem raise_value (r : Representative k x y) (N : ℕ) (h : r.bound ≤ N) :
    (r.raise N h).value = r.value :=
  composite_cell_lower h r.lt_bound r.first r.last r.matching _

/-- Two different common finite presentations define the same composite. -/
theorem value_eq (r s : Representative k x y) : r.value = s.value := by
  let N := max r.bound s.bound
  let rr := r.raise N (Nat.le_max_left _ _)
  let ss := s.raise N (Nat.le_max_right _ _)
  have hf : rr.first = ss.first := (GlobeMappingCells.ι_injective model D N)
    (rr.first_eq.trans ss.first_eq.symm)
  have hg : rr.last = ss.last := (GlobeMappingCells.ι_injective model D N)
    (rr.last_eq.trans ss.last_eq.symm)
  have hv : rr.value = ss.value := by
    change GlobeMappingCells.ι model D N
      (composite rr.lt_bound rr.first rr.last rr.matching) =
      GlobeMappingCells.ι model D N
        (composite ss.lt_bound ss.first ss.last ss.matching)
    simp only [hf, hg]
  exact (r.raise_value N (Nat.le_max_left _ _)).symm.trans
    (hv.trans (s.raise_value N (Nat.le_max_right _ _)))

theorem value_source (r : Representative k x y) :
    GlobeMappingCells.face model D false k r.value = GlobeMappingCells.face model D false k x :=
  (composite_cell_source r.lt_bound r.first r.last r.matching).trans
    (congrArg (GlobeMappingCells.face model D false k) r.first_eq)

theorem value_target (r : Representative k x y) :
    GlobeMappingCells.face model D true k r.value = GlobeMappingCells.face model D true k y :=
  (composite_cell_target r.lt_bound r.first r.last r.matching).trans
    (congrArg (GlobeMappingCells.face model D true k) r.last_eq)

def map {E : StrictOmegaCategory.{0}} (r : Representative k x y) (u : D ⟶ E) :
    Representative k (GlobeMappingCells.map model u x) (GlobeMappingCells.map model u y) where
  bound := r.bound
  lt_bound := r.lt_bound
  first := r.first ≫ u
  last := r.last ≫ u
  first_eq := (GlobeMappingCells.map_ι model u r.bound r.first).symm.trans
    (congrArg (GlobeMappingCells.map model u) r.first_eq)
  last_eq := (GlobeMappingCells.map_ι model u r.bound r.last).symm.trans
    (congrArg (GlobeMappingCells.map model u) r.last_eq)
  matching := by
    rw [← Category.assoc, ← Category.assoc]
    exact congrArg (fun f => f ≫ u) r.matching

theorem map_value {E : StrictOmegaCategory.{0}} (r : Representative k x y) (u : D ⟶ E) :
    (r.map u).value = GlobeMappingCells.map model u r.value := by
  exact (congrArg (GlobeMappingCells.ι model E r.bound)
    (composite_postcompose r.lt_bound r.first r.last r.matching u (r.map u).matching)).trans
      (GlobeMappingCells.map_ι model u r.bound
        (composite r.lt_bound r.first r.last r.matching)).symm

end Representative

variable {D : StrictOmegaCategory.{0}}

theorem representative_exists (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y) :
    Nonempty (Representative k x y) := by
  obtain ⟨n, hn, f, g, hf, hg⟩ := GlobeMappingCells.exists_representatives₂_above model D x y (k+1)
  exact ⟨{
    bound := n
    lt_bound := Nat.lt_of_lt_of_le (Nat.lt_succ_self k) hn
    first := f
    last := g
    first_eq := hf
    last_eq := hg
    matching := GlobeMappingCells.matching_representatives model D x y h f g hf hg }⟩

/-- Actual composition on the mapping-family carrier. -/
def comp (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y) :
    Cell D :=
  (Classical.choice (representative_exists k x y h)).value

theorem comp_congr {k : ℕ} {x y x' y' : Cell D} (hx : x = x') (hy : y = y')
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y)
    (h' : GlobeMappingCells.face model D true k x' = GlobeMappingCells.face model D false k y') :
    comp k x y h = comp k x' y' h' := by
  subst x'
  subst y'
  rfl

theorem comp_eq (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y)
    (r : Representative k x y) : comp k x y h = r.value :=
  Representative.value_eq _ _

theorem comp_ι {n k : ℕ} (hk : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f =
      model.map (Globe.faceMap false k n) ≫ g)
    (h' : GlobeMappingCells.face model D true k (GlobeMappingCells.ι model D n f) =
      GlobeMappingCells.face model D false k (GlobeMappingCells.ι model D n g)) :
    comp k (GlobeMappingCells.ι model D n f) (GlobeMappingCells.ι model D n g) h' =
      GlobeMappingCells.ι model D n (composite hk f g h) :=
  comp_eq k _ _ h' {
    bound := n
    lt_bound := hk
    first := f
    last := g
    first_eq := rfl
    last_eq := rfl
    matching := h }

theorem source_comp (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y) :
    GlobeMappingCells.face model D false k (comp k x y h) =
      GlobeMappingCells.face model D false k x :=
  Representative.value_source _

theorem target_comp (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y) :
    GlobeMappingCells.face model D true k (comp k x y h) =
      GlobeMappingCells.face model D true k y :=
  Representative.value_target _

theorem map_comp {E : StrictOmegaCategory.{0}} (u : D ⟶ E) (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y)
    (h' : GlobeMappingCells.face model E true k (GlobeMappingCells.map model u x) =
      GlobeMappingCells.face model E false k (GlobeMappingCells.map model u y)) :
    GlobeMappingCells.map model u (comp k x y h) =
      comp k (GlobeMappingCells.map model u x) (GlobeMappingCells.map model u y) h' := by
  let r := Classical.choice (representative_exists k x y h)
  exact (congrArg (GlobeMappingCells.map model u) (comp_eq k x y h r)).trans
    ((r.map_value u).symm.trans (comp_eq k _ _ h' (r.map u)).symm)

end
end Thomason.Construction.StrictOmegaCategory.GrayMapping

end

section

/-! # Endpoint evaluation preserves actual mapping composition -/

namespace Thomason.Construction.StrictOmegaCategory.GrayMapping

open CategoryTheory

noncomputable section

variable (η : 𝟭 StrictOmegaCategory.{0} ⟶ model) {D : StrictOmegaCategory.{0}}

private theorem evaluate_parameter {n : ℕ} {C : StrictOmegaCategory.{0}}
    (s : Globe.category n ⟶ C) (u : model.obj C ⟶ D) :
    GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n (model.map s ≫ u)) =
      u.toFun ((η.app C).toFun (s.toFun Globe.Cell.top)) := by
  rw [GlobeMappingCells.naturalEvaluation_ι]
  exact congrArg u.toFun
    (congrArg (fun q : Globe.category n ⟶ model.obj C => q.toFun Globe.Cell.top)
      (η.naturality s)).symm

/-- Evaluation at either actual endpoint respects the finite gluing operation. -/
theorem naturalEvaluation_composite {n k : ℕ} (hk : k < n)
    (f g : model.obj (Globe.category n) ⟶ D)
    (h : model.map (Globe.faceMap true k n) ≫ f = model.map (Globe.faceMap false k n) ≫ g)
    (h' : D.target k (GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n f)) =
      D.source k (GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n g))) :
    GlobeMappingCells.naturalEvaluation η D
        (GlobeMappingCells.ι model D n (composite hk f g h)) =
      D.comp k (GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n f))
        (GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n g)) h' := by
  let u : PastingGlobe.category n n k ⟶ D := η.app _ ≫ glue hk f g h
  have hl : u.toFun (PastingGlobe.leftCell n n k) =
      GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n f) := by
    have he := evaluate_parameter η (PastingGlobe.left n n k) (glue hk f g h)
    rw [glue_left] at he
    exact he.symm
  have hr : u.toFun (PastingGlobe.rightCell n n k) =
      GlobeMappingCells.naturalEvaluation η D (GlobeMappingCells.ι model D n g) := by
    have he := evaluate_parameter η (PastingGlobe.right n n k) (glue hk f g h)
    rw [glue_right] at he
    exact he.symm
  have hm : D.target k (u.toFun (PastingGlobe.leftCell n n k)) =
      D.source k (u.toFun (PastingGlobe.rightCell n n k)) := by
    simpa only [hl, hr] using h'
  have he := evaluate_parameter η (compositionGlobe n k hk) (glue hk f g h)
  change GlobeMappingCells.naturalEvaluation η D
      (GlobeMappingCells.ι model D n (composite hk f g h)) =
    u.toFun (PastingGlobe.composite n n k) at he
  exact he.trans (by simpa only [PastingGlobe.composite, hl, hr] using
    (u.map_comp k (PastingGlobe.leftCell n n k) (PastingGlobe.rightCell n n k)
      (PastingGlobe.matching n n k) hm))

/-- Evaluation is a strict operation-preserving map on the entire carrier. -/
theorem naturalEvaluation_comp (k : ℕ) (x y : Cell D)
    (h : GlobeMappingCells.face model D true k x = GlobeMappingCells.face model D false k y)
    (h' : D.target k (GlobeMappingCells.naturalEvaluation η D x) =
      D.source k (GlobeMappingCells.naturalEvaluation η D y)) :
    GlobeMappingCells.naturalEvaluation η D (comp k x y h) =
      D.comp k (GlobeMappingCells.naturalEvaluation η D x)
        (GlobeMappingCells.naturalEvaluation η D y) h' := by
  let r := Classical.choice (representative_exists k x y h)
  have hm : D.target k (GlobeMappingCells.naturalEvaluation η D
        (GlobeMappingCells.ι model D r.bound r.first)) =
      D.source k (GlobeMappingCells.naturalEvaluation η D
        (GlobeMappingCells.ι model D r.bound r.last)) := by
    simpa only [r.first_eq, r.last_eq] using h'
  have he := naturalEvaluation_composite η r.lt_bound r.first r.last r.matching hm
  have hv := congrArg (GlobeMappingCells.naturalEvaluation η D) (comp_eq k x y h r)
  exact hv.trans (by simpa only [Representative.value, r.first_eq, r.last_eq] using he)

end
end Thomason.Construction.StrictOmegaCategory.GrayMapping

end

end OAI
