import OAI.MathematicalPhysics.ContinuumCoulomb.OneParticle.NumericalGridRounding
import OAI.MathematicalPhysics.ContinuumCoulomb.Programs.UnitCoulombProgram

namespace OAI

/-! The serialized unit-Coulomb instance has exactly the ground energy of
the rational array generated by the numerical node program. -/

noncomputable section
open scoped BigOperators Classical
namespace ContinuumCoulomb
open CappedKernelProgram (Triple position)

theorem unitData_attraction_list (d : UnitCoulomb) (hd : d.Valid) (y : Position) :
    Coulomb.attraction (d.toData hd).toNuclearData.toNuclei y =
      (d.nuclei.map (fun p => Coulomb.coulombKernel (y-realPosition p.value))).sum := by
  simp only [Coulomb.attraction,NuclearData.toNuclei,UnitNuclearData.toNuclearData,
    UnitCoulomb.toData,Nat.cast_one,one_mul,List.get_eq_getElem]
  exact Fin.sum_univ_fun_getElem d.nuclei (fun p => Coulomb.coulombKernel (y-realPosition p.value))

theorem program_ground_identity (rho U C K : ℕ) (x : UnitCoulombProgram.Input)
    (hx : (UnitCoulombProgram.value rho U C K x).Valid)
    {scale : ℝ} (hs : 0 < scale)
    (hfactor : (PhysicalNuclearProgram.factor rho x.1.1.1.2:ℝ)=scale⁻¹)
    (hq : Function.Injective (fun a : Fin (CenteredGaussLabels.labels x.1.2).length =>
      TransformedGauss.value rho U C K x.1.1.1.1 x.1.1.1.2 x.1.1.2.1.1 x.1.1.2.1.2 x.1.1.2.2
        ((CenteredGaussLabels.labels x.1.2).get a).1 ((CenteredGaussLabels.labels x.1.2).get a).2)) :
    unitGroundEnergy ((UnitCoulombProgram.value rho U C K x).toData hx) =
      formGroundEnergy (physicalRationalNuclei
        (by rw [CenteredGaussLabels.labels_length]; positivity) _ hq hs) x.2.1 := by
  change formGroundEnergy ((UnitCoulombProgram.value rho U C K x).toData hx).toNuclearData.toNuclei _ = _
  apply formGroundEnergy_eq_of_attraction
  intro y
  rw [unitData_attraction_list]
  change ((PhysicalNuclearProgram.nuclei rho U C K x.1).map
    (fun p => Coulomb.coulombKernel (y-realPosition p.value))).sum = _
  simp only [PhysicalNuclearProgram.nuclei,NuclearCoordinateOutput.positions,
    PhysicalNuclearProgram.triples,TransformedGauss.nodes,List.map_map,Function.comp_def,
    NuclearCoordinateOutput.real_position,PhysicalNuclearProgram.scale_position,hfactor]
  change ((CenteredGaussLabels.labels x.1.2).map (fun l =>
    Coulomb.coulombKernel (y-scale⁻¹ • position (TransformedGauss.value rho U C K
      x.1.1.1.1 x.1.1.1.2 x.1.1.2.1.1 x.1.1.2.1.2 x.1.1.2.2 l.1 l.2)))).sum = _
  simp only [Coulomb.attraction,physicalRationalNuclei,one_mul,List.get_eq_getElem]
  exact (Fin.sum_univ_fun_getElem (CenteredGaussLabels.labels x.1.2) (fun l =>
    Coulomb.coulombKernel (y-scale⁻¹ • position (TransformedGauss.value rho U C K
      x.1.1.1.1 x.1.1.1.2 x.1.1.2.1.1 x.1.1.2.1.2 x.1.1.2.2 l.1 l.2)))).symm

end ContinuumCoulomb

end

end OAI
