import OAI.Analysis.IrrationalRotation.Product.ProductScaleCocycleWindow
import OAI.Analysis.IrrationalRotation.Product.ProductCocycleWindow
import OAI.Analysis.IrrationalRotation.Rotation.CircleCocycleWindow
import OAI.Analysis.IrrationalRotation.Rotation.ProjectionCocycleWindow


