import OAI.Analysis.ModularTheory.LpTranslation
import OAI.Analysis.ModularTheory.LpFaithful

namespace OAI

/-! The concrete von Neumann algebra generated by the modular coefficient
representation and the regular translations. This defines the continuous
core representation and its universal containment property. Semifiniteness
and a trace on this algebra are not included as assumptions or assertions.

The representation is the one used in Anantharaman--Delaroche (1995),
Proposition 3.6, p.329. -/

noncomputable section
open MeasureTheory
open scoped Pointwise

namespace WeakPureInfiniteness

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (μ : Measure ℝ) [Measure.IsAddRightInvariant μ]
  (S : BoundedRecovery.StandardModularData H)

def modularCoreGenerators : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ) :=
  Set.range (fun a : S.M.toStarSubalgebra =>
    modularLpRepresentation μ S.D (a : H →L[ℂ] H)) ∪
  Set.range (fun t : ℝ => (modularLpTranslateEquiv (H := H) μ t :
    Lp H 2 μ →L[ℂ] Lp H 2 μ))

def algebraicModularCore : StarSubalgebra ℂ (Lp H 2 μ →L[ℂ] Lp H 2 μ) :=
  StarAlgebra.adjoin ℂ (modularCoreGenerators μ S)

omit [Measure.IsAddRightInvariant μ] in
private lemma starCentralizer_carrier
    (B : StarSubalgebra ℂ (Lp H 2 μ →L[ℂ] Lp H 2 μ)) :
    (StarSubalgebra.centralizer ℂ (B : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) :
      Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) =
        Set.centralizer (B : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) := by
  rw [StarSubalgebra.coe_centralizer, StarMemClass.star_coe_eq, Set.union_self]

def modularCrossedProduct : VonNeumannAlgebra (Lp H 2 μ) where
  toStarSubalgebra := StarSubalgebra.centralizer ℂ
    ((StarSubalgebra.centralizer ℂ
      (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) :
        Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))
  centralizer_centralizer' := by
    change Set.centralizer (Set.centralizer
      ((StarSubalgebra.centralizer ℂ
        ((StarSubalgebra.centralizer ℂ
          (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) :
            Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) :
              Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) = _
    rw [starCentralizer_carrier μ (StarSubalgebra.centralizer ℂ
      (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))),
      starCentralizer_carrier μ (algebraicModularCore μ S),
      Set.centralizer_centralizer_centralizer]
    change _ = (StarSubalgebra.centralizer ℂ
      (Set.centralizer (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) :
        Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))
    rw [← starCentralizer_carrier μ (algebraicModularCore μ S)]
    exact (starCentralizer_carrier μ (StarSubalgebra.centralizer ℂ
      (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)))).symm

lemma modularCrossedProduct_carrier :
    (modularCrossedProduct μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) =
      Set.centralizer (Set.centralizer
        (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) := by
  change ((StarSubalgebra.centralizer ℂ
    ((StarSubalgebra.centralizer ℂ
      (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) :
        Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))) :
          Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) = _
  rw [starCentralizer_carrier μ (StarSubalgebra.centralizer ℂ
    (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ))),
    starCentralizer_carrier μ (algebraicModularCore μ S)]

lemma algebraicModularCore_le :
    (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) ⊆
      modularCrossedProduct μ S := by
  rw [modularCrossedProduct_carrier]
  exact Set.subset_centralizer_centralizer

lemma modularCrossedProduct_coeff (a : S.M.toStarSubalgebra) :
    modularLpRepresentation μ S.D (a : H →L[ℂ] H) ∈ modularCrossedProduct μ S :=
  algebraicModularCore_le μ S (StarAlgebra.subset_adjoin ℂ _ (Or.inl ⟨a, rfl⟩))

lemma modularCrossedProduct_translate (t : ℝ) :
    (modularLpTranslateEquiv (H := H) μ t : Lp H 2 μ →L[ℂ] Lp H 2 μ) ∈
      modularCrossedProduct μ S :=
  algebraicModularCore_le μ S (StarAlgebra.subset_adjoin ℂ _ (Or.inr ⟨t, rfl⟩))

def modularCoreEmbedding : S.M.toStarSubalgebra →⋆ₐ[ℂ]
    (modularCrossedProduct μ S).toStarSubalgebra :=
  ((modularLpRepresentation μ S.D).comp S.M.toStarSubalgebra.subtype).codRestrict
    (modularCrossedProduct μ S).toStarSubalgebra (modularCrossedProduct_coeff μ S)

theorem modularCoreEmbedding_injective :
    Function.Injective (modularCoreEmbedding (volume : Measure ℝ) S) := by
  intro a b hab
  apply Subtype.ext
  apply modularLpRepresentation_injective S.D
  exact congrArg Subtype.val hab

lemma modularCrossedProduct_le (N : VonNeumannAlgebra (Lp H 2 μ))
    (hcoeff : ∀ a : S.M.toStarSubalgebra,
      modularLpRepresentation μ S.D (a : H →L[ℂ] H) ∈ N)
    (htranslate : ∀ t : ℝ,
      (modularLpTranslateEquiv (H := H) μ t : Lp H 2 μ →L[ℂ] Lp H 2 μ) ∈ N) :
    modularCrossedProduct μ S ≤ N := by
  have hgen : modularCoreGenerators μ S ⊆ N := by
    rintro T (⟨a, rfl⟩ | ⟨t, rfl⟩)
    · exact hcoeff a
    · exact htranslate t
  have halg : (algebraicModularCore μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) ⊆ N :=
    StarAlgebra.adjoin_le hgen
  change (modularCrossedProduct μ S : Set (Lp H 2 μ →L[ℂ] Lp H 2 μ)) ⊆ N
  rw [modularCrossedProduct_carrier]
  have hcc := Set.centralizer_subset (Set.centralizer_subset halg)
  simpa only [N.centralizer_centralizer] using hcc

end WeakPureInfiniteness

end

end OAI
