import OAI.Combinatorics.ContingencyTables.Machines.MatrixCodeEquality

namespace OAI

/-! # Binary row and column checks for original-table candidates -/

namespace ContingencyTables.ProfilePrograms
open MatchingFPRAS MatchingFPRAS.TreeTyped DensePrograms Polynomial

abbrev OriginalCheckInput := (List ℕ×List ℕ)×MatrixCode

def originalColumnTotals (z : OriginalCheckInput) : List ℕ :=
  (List.range z.1.2.length).map (fun j => columnTotal (z.2,j))

def originalColumnTotalsRealizer : Realizer originalColumnTotals :=
  composition (pair second (composition
    (composition (composition first second) listLength) range)) (mapWith columnTotalRealizer)

lemma polynomial_originalColumnTotals : PolynomialTime originalColumnTotalsRealizer := by
  unfold originalColumnTotalsRealizer
  apply polynomial_composition _ (polynomial_mapWith polynomial_columnTotal)
  apply polynomial_pair polynomial_second
  apply polynomial_boundedRange
    (polynomial_composition (polynomial_composition polynomial_first polynomial_second)
      polynomial_listLength) X
  intro z
  simpa only [Function.comp_apply,Polynomial.eval_X] using
    (list_length_le_weight z.1.2).trans ((weight_snd z.1).trans (weight_fst z))

/-- Applied to the fixed rectangular shape generated by the enumerator. -/
def originalTableTest (z : OriginalCheckInput) : Bool :=
  decide (z.2.map List.sum=z.1.1) && decide (originalColumnTotals z=z.1.2)

def originalTableTestRealizer : Realizer originalTableTest :=
  composition (pair
    (composition (pair (composition second (map listSum)) (composition first first)) listNatEqual)
    (composition (pair originalColumnTotalsRealizer (composition first second)) listNatEqual)) boolAnd

lemma polynomial_originalTableTest : PolynomialTime originalTableTestRealizer :=
  polynomial_composition (polynomial_pair
    (polynomial_composition (polynomial_pair
      (polynomial_composition polynomial_second (polynomial_map polynomial_listSum))
      (polynomial_composition polynomial_first polynomial_first)) polynomial_listNatEqual)
    (polynomial_composition (polynomial_pair polynomial_originalColumnTotals
      (polynomial_composition polynomial_first polynomial_second)) polynomial_listNatEqual)) polynomial_boolAnd

lemma originalColumnTotals_code {m n : ℕ} (r : Fin m → ℕ) (c : Fin n → ℕ)
    (X : Fin m → Fin n → ℕ) :
    originalColumnTotals ((List.ofFn r,List.ofFn c),matrixCode X)=
      List.ofFn (fun j => ∑ i,X i j) := by
  unfold originalColumnTotals
  rw [List.length_ofFn]
  apply List.ext_getElem
  · simp
  · intro j hj hj'
    have hjn : j<n := by simpa using hj'
    simp only [List.getElem_map,List.getElem_range,List.getElem_ofFn]
    exact columnTotal_code X ⟨j,hjn⟩

lemma originalTableTest_code {m n : ℕ} (r : Fin m → ℕ) (c : Fin n → ℕ)
    (X : Fin m → Fin n → ℕ) :
    originalTableTest ((List.ofFn r,List.ofFn c),matrixCode X)=true ↔ HasMargins X r c := by
  unfold originalTableTest
  rw [originalColumnTotals_code]
  simp only [Bool.and_eq_true,decide_eq_true_eq,matrixCode,List.map_ofFn,Function.comp_def,List.sum_ofFn]
  constructor
  · rintro ⟨hr,hc⟩
    exact ⟨congrFun (List.ofFn_injective hr),congrFun (List.ofFn_injective hc)⟩
  · rintro ⟨hr,hc⟩
    exact ⟨congrArg List.ofFn (by funext i; exact hr i),congrArg List.ofFn (by funext j; exact hc j)⟩

end ContingencyTables.ProfilePrograms

end OAI
