import OAI.Combinatorics.LowSpaceSubsetSum.Storage.StoredArrayCells
import OAI.Combinatorics.LowSpaceSubsetSum.Representation.RepresentationSortCells

namespace OAI

/-! # Live storage of the complete stored-array preparation

The left array remains available while the right array is generated and
sorted. Both returned arrays are the actual arrays captured by the reader
initializer; no leaf family is regenerated by this wrapper.
-/

namespace LowSpaceSubsetSum.StoredPreparationCells

variable {n : ℕ}

def prepare (D : RepresentationParentData n) (F ones zeros : IndexedMask n) (j : Fin 2) :
    ((Array (LeafRecord n) × Array (LeafRecord n)) × ℕ) × ℕ :=
  let dl := IndexedMask.measuredDomain (D.pair j).left.top
  let dr := IndexedMask.measuredDomain (D.pair j).right.top
  let l := StoredArrayCells.array (D.pair j).left ones zeros dl.1
  let r := StoredArrayCells.array (D.pair j).right ones zeros dr.1
  let s := RepresentationSortCells.sort D.input F D.lowModulus D.modulus r.1.1
  (((l.1.1, s.1.1), dl.2+dr.2+l.1.2+r.1.2+s.1.2),
    l.2+r.2+s.2+(6*n+12)*(l.1.1.size+r.1.1.size+1)+32*(n+1))

theorem prepare_value (D : RepresentationParentData n) (F ones zeros : IndexedMask n) (j : Fin 2) :
    (prepare D F ones zeros j).1 = RepresentationStoredArrays.prepare D F ones zeros j := by
  simp only [prepare, StoredArrayCells.array_value, RepresentationSortCells.sort_value,
    RepresentationStoredArrays.prepare]

private theorem scale (n u C a b s L R : ℕ) (hn : 10000 ≤ n) (hu : n+2 ≤ u)
    (ha : a ≤ u^6*(C+1)) (hb : b ≤ u^6*(C+1))
    (hs : s ≤ u^5*(C+1)) (hL : L ≤ C) (hR : R ≤ C) :
    a+b+s+(6*n+12)*(L+R+1)+32*(n+1) ≤ u^8*(C+1) := by
  have hu0 : 10000 ≤ u := by omega
  have h65 : u^5 ≤ u^6 := Nat.pow_le_pow_right (by omega) (by decide)
  have hs' := hs.trans (Nat.mul_le_mul_right (C+1) h65)
  have hlinear : (6*n+12)*(L+R+1)+32*(n+1) ≤ 44*u*(C+1) := by
    have h := Nat.mul_le_mul (show 6*n+12 ≤ 6*u by omega)
      (show L+R+1 ≤ 2*(C+1) by omega)
    have h' := Nat.mul_le_mul_left (32*u) (show 1 ≤ C+1 by omega)
    nlinarith only [h, h', hu]
  have hsmall : 44*u ≤ u^6 := by
    have hp : 44 ≤ u^5 := by
      have h := Nat.pow_le_pow_left hu0 5
      omega
    calc
      _ ≤ u^5*u := Nat.mul_le_mul_right u hp
      _ = _ := by rw [← pow_succ]
  have hminor := hlinear.trans (Nat.mul_le_mul_right (C+1) hsmall)
  have hlast : 4*u^6 ≤ u^8 := by
    have hp : 4 ≤ u^2 := by nlinarith
    calc
      _ ≤ u^2*u^6 := Nat.mul_le_mul_right _ hp
      _ = _ := by rw [← pow_add]
  have hfinal := Nat.mul_le_mul_right (C+1) hlast
  simp only [Nat.mul_assoc] at hfinal
  omega

theorem prepare_cells (D : RepresentationParentData n) (F ones zeros : IndexedMask n)
    (j : Fin 2) (C : ℕ) (hn : 10000 ≤ n)
    (hL : (D.pair j).left.occurrences.card ≤ C)
    (hR : (D.pair j).right.occurrences.card ≤ C) (hC : C ≤ 2^n) :
    (prepare D F ones zeros j).2 ≤ inputScale D.input^8*(C+1) := by
  let dl := (IndexedMask.measuredDomain (D.pair j).left.top).1
  let dr := (IndexedMask.measuredDomain (D.pair j).right.top).1
  let l := StoredArrayCells.array (D.pair j).left ones zeros dl
  let r := StoredArrayCells.array (D.pair j).right ones zeros dr
  have hl := StoredArrayCells.array_cells D.input (D.pair j).left ones zeros dl hn
  have hr := StoredArrayCells.array_cells D.input (D.pair j).right ones zeros dr hn
  have hls : l.1.1.size ≤ C := by
    dsimp only [l]
    rw [StoredArrayCells.array_value]
    exact ((D.pair j).left.measuredStoredArray_size ones zeros dl).trans hL
  have hrs : r.1.1.size ≤ C := by
    dsimp only [r]
    rw [StoredArrayCells.array_value]
    exact ((D.pair j).right.measuredStoredArray_size ones zeros dr).trans hR
  have hs := RepresentationSortCells.sort_cells D.input F D.lowModulus D.modulus r.1.1 C hn hrs hC
  have hl' := hl.trans (Nat.mul_le_mul_left _ (Nat.add_le_add_right hL 1))
  have hr' := hr.trans (Nat.mul_le_mul_left _ (Nat.add_le_add_right hR 1))
  exact scale n (inputScale D.input) C l.2 r.2 _ l.1.1.size r.1.1.size hn
    (by unfold inputScale; omega) hl' hr' hs hls hrs

end LowSpaceSubsetSum.StoredPreparationCells

end OAI
