import OAI.Analysis.CircleDomains.Topology.ClosedHitSplit
import OAI.Analysis.CircleDomains.Probability.ClosedFusionScheme

namespace OAI

/-! The actual nested tree of nonsmall closed candidates. Every vertex carries
its finite probability split, and every infinite address has a continuous limit
inside every ancestor. -/

open Set MeasureTheory
open scoped Topology

noncomputable section

namespace CircleDomainRigidity

variable {X Z : Type*} [MetricSpace X] [SecondCountableTopology X]
  [MeasurableSpace X] [BorelSpace X]
  [MeasurableSpace C(PathTime, X)] [BorelSpace C(PathTime, X)]
  [MetricSpace Z] [SecondCountableTopology Z]
  (law : Z → ProbabilityMeasure C(PathTime, X)) (C : ℝ)

structure ClosedHitCandidate where
  carrier : Set Z
  closed : IsClosed carrier
  nonsmall : ¬HitTestSmall law C carrier

namespace ClosedHitCandidate

variable {law C}

omit [SecondCountableTopology X] [BorelSpace X]
    [BorelSpace C(PathTime, X)] [SecondCountableTopology Z] in
theorem nonempty (A : ClosedHitCandidate law C) : A.carrier.Nonempty := by
  by_contra h
  exact A.nonsmall ((not_nonempty_iff_eq_empty.mp h).symm ▸ hitTestSmall_empty law C)

end ClosedHitCandidate

structure HitFusionSplit (A : ClosedHitCandidate law C) (n : ℕ) (r ε η : ℝ) where
  count : ℕ
  count_pos : 0 < count
  weight : Fin count → ℝ
  weight_nonneg : ∀ i, 0 ≤ weight i
  weight_sum : (∑ i, weight i) = 1
  child : Fin count → ClosedHitCandidate law C
  child_subset : ∀ i, (child i).carrier ⊆ A.carrier
  child_dist : ∀ i, ∀ x ∈ (child i).carrier, ∀ y ∈ (child i).carrier, dist x y ≤ η
  bound : ∀ z : Fin count → Z, (∀ i, z i ∈ (child i).carrier) →
    ∀ p : HitConfiguration X n r,
      ∑ i, weight i * weightedConfigurationHits law (z i) p < C + ε

variable {law C}

theorem nonempty_hitFusionSplit [CompactSpace X]
    (hlaw : Continuous law) (hC : 0 ≤ C) (A : ClosedHitCandidate law C)
    (n : ℕ) {r ε η : ℝ} (hr : 0 < r) (hε : 0 < ε) (hη : 0 < η) :
    Nonempty (HitFusionSplit law C A n r ε η) := by
  obtain ⟨k, w, D, hw, hw1, hD, hb⟩ := exists_closed_nonsmall_hit_split_all law hlaw
    A.closed hC hε hη hr n A.nonsmall
  have hk : 0 < k := by
    by_contra h
    have hk0 : k = 0 := Nat.eq_zero_of_not_pos h
    subst k
    simp at hw1
  exact ⟨⟨k, hk, w, hw, hw1, fun i => ⟨D i, (hD i).1, (hD i).2.2.1⟩,
    fun i => (hD i).2.1, fun i => (hD i).2.2.2, hb⟩⟩

namespace HitFusionSplit

variable {A : ClosedHitCandidate law C} {n : ℕ} {r ε η : ℝ}

/-- All natural-number addresses are valid; only the first `count` receive mass. -/
def index (S : HitFusionSplit law C A n r ε η) (a : ℕ) : Fin S.count :=
  ⟨a % S.count, Nat.mod_lt a S.count_pos⟩

omit [SecondCountableTopology X] [BorelSpace X]
    [BorelSpace C(PathTime, X)] [SecondCountableTopology Z] in
@[simp] theorem index_val (S : HitFusionSplit law C A n r ε η) (i : Fin S.count) :
    S.index i.val = i := by
  apply Fin.ext
  exact Nat.mod_eq_of_lt i.isLt

end HitFusionSplit

variable (ns : ℕ → ℕ) (rs : ℕ → ℝ) (ε : ℝ)
  (split : ∀ d (A : ClosedHitCandidate law C),
    HitFusionSplit law C A (ns d) (rs d) ε (1 / ((d : ℝ) + 1)))
  (root : ClosedHitCandidate law C)

def hitFusionNode : List ℕ → ClosedHitCandidate law C
  | [] => root
  | a :: l => (split l.length (hitFusionNode l)).child
      ((split l.length (hitFusionNode l)).index a)

def hitFusionScheme : ClosedFusionScheme Z where
  carrier l := (hitFusionNode ns rs ε split root l).carrier
  closed l := (hitFusionNode ns rs ε split root l).closed
  nonempty l := (hitFusionNode ns rs ε split root l).nonempty
  child_subset l _a := (split l.length (hitFusionNode ns rs ε split root l)).child_subset _
  child_dist l _a := (split l.length (hitFusionNode ns rs ε split root l)).child_dist _

/-- The data generated by the proved finite splitting construction. -/
structure HitFusionData where
  sizes : ℕ → ℕ
  separations : ℕ → ℝ
  error : ℝ
  initial : ClosedHitCandidate law C
  split : ∀ d (A : ClosedHitCandidate law C),
    HitFusionSplit law C A (sizes d) (separations d) error (1 / ((d : ℝ) + 1))

namespace HitFusionData

variable (T : HitFusionData (law := law) (C := C))

def node (l : List ℕ) : ClosedHitCandidate law C :=
  hitFusionNode T.sizes T.separations T.error T.split T.initial l

def scheme : ClosedFusionScheme Z :=
  hitFusionScheme T.sizes T.separations T.error T.split T.initial

def splitAt (l : List ℕ) := T.split l.length (T.node l)

omit [SecondCountableTopology X] [BorelSpace X]
    [BorelSpace C(PathTime, X)] [SecondCountableTopology Z] in
@[simp] theorem node_cons (a : ℕ) (l : List ℕ) :
    T.node (a :: l) = (T.splitAt l).child ((T.splitAt l).index a) := rfl

end HitFusionData

end CircleDomainRigidity

end

end OAI
