import OAI.AlgebraicGeometry.SurfaceCones.TensorLineCoherent

namespace OAI

private local instance schemeSectionModule (X : AlgebraicGeometry.Scheme.{0})
    (M : X.Modules) (U : X.Opensᵒᵖ) :
    Module (X.sheaf.obj.obj U) (M.val.obj U) :=
  (M.val.obj U).isModule

private local instance schemeGammaModule (X : AlgebraicGeometry.Scheme.{0})
    (M : X.Modules) (U : X.Opens) :
    Module (X.presheaf.obj (Opposite.op U)) (M.val.obj (Opposite.op U)) :=
  (M.val.obj (Opposite.op U)).isModule

private local instance tensorSectionModule (X : AlgebraicGeometry.Scheme.{0})
    (M : SheafOfModules (ActualSheafTensor.ringSheaf X.sheaf)) (U : X.Opensᵒᵖ) :
    Module (X.sheaf.obj.obj U) (M.val.obj U) :=
  (M.val.obj U).isModule

private local instance tensorGammaModule (X : AlgebraicGeometry.Scheme.{0})
    (M : SheafOfModules (ActualSheafTensor.ringSheaf X.sheaf)) (U : X.Opens) :
    Module (X.presheaf.obj (Opposite.op U)) (M.val.obj (Opposite.op U)) :=
  (M.val.obj (Opposite.op U)).isModule

private noncomputable local instance unitSectionModule (X : AlgebraicGeometry.Scheme.{0}) (U : X.Opens) :
    Module (X.presheaf.obj (Opposite.op U))
      ((SheafOfModules.unit X.ringCatSheaf).val.obj (Opposite.op U)) :=
  ((SheafOfModules.unit X.ringCatSheaf).val.obj (Opposite.op U)).isModule

private local instance finiteQuasicoherent (X : AlgebraicGeometry.Scheme.{0})
    (M : X.Modules) [M.IsFinitePresentation] : M.IsQuasicoherent :=
  (SheafOfModules.IsFinitePresentation.exists_quasicoherentData M).choose.isQuasicoherent

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace ActualCartier
open Scheme.Modules ActualSheafTensor

private theorem kernelMono {C : Type*} [Category C] [HasZeroMorphisms C]
    {A B : C} (g : A ⟶ B) [HasKernel g] : Mono (kernel.ι g) :=
  equalizer.ι_mono

variable {X Y : Scheme.{0}} (f : X ⟶ Y) (U : Y.Opens)

/-- A trivialization of the section module of the ideal. -/
abbrev SectionTrivialization :=
  (idealSheaf f).val.obj (op U) ≃ₗ[Γ(Y, U)] Γ(Y, U)

variable (e : SectionTrivialization f U)

def equation : Γ(Y, U) := ((idealι f).val.app (op U)) (e.symm 1)

lemma equation_mem_kernel : equation f U e ∈ RingHom.ker (f.app U).hom := by
  have hz := congrArg (fun g => (g : idealSheaf f ⟶
    (pushforward f).obj (SheafOfModules.unit _)).val.app (op U))
    (kernel.condition (structureMap f))
  exact ConcreteCategory.congr_hom hz (e.symm 1)

lemma equation_regular : IsSMulRegular Γ(Y, U) (equation f U e) := by
  have hmono : Mono (idealι f) :=
    kernelMono (C := SheafOfModules Y.ringCatSheaf) (structureMap f)
  have : Mono ((SheafOfModules.evaluation Y.ringCatSheaf (op U)).map (idealι f)) :=
    @Functor.map_mono _ _ _ _ (SheafOfModules.evaluation Y.ringCatSheaf (op U))
      _ _ _ (idealι f) hmono
  have hi : Function.Injective ((idealι f).val.app (op U)) :=
    (ModuleCat.mono_iff_injective _).mp this
  have he : Function.Injective e.symm := e.symm.injective
  intro a b hab
  apply he
  apply hi
  have ha : ((idealι f).val.app (op U)) (e.symm a) = a * equation f U e := by
    have h := (e.symm).map_smul a (1 : Γ(Y, U))
    simp only [smul_eq_mul, mul_one] at h
    rw [h, _root_.map_smul]
    rfl
  have hb : ((idealι f).val.app (op U)) (e.symm b) = b * equation f U e := by
    have h := (e.symm).map_smul b (1 : Γ(Y, U))
    simp only [smul_eq_mul, mul_one] at h
    rw [h, _root_.map_smul]
    rfl
  rw [ha, hb]
  exact (mul_comm _ _).trans (hab.trans (mul_comm _ _))

/-- The closed ideal is generated by the regular local equation extracted from its trivialization.
Neither principality nor regularity is an extra hypothesis about the section-ring map. -/
lemma kernel_eq_span_equation :
    RingHom.ker (f.app U).hom = Ideal.span ({equation f U e} : Set Γ(Y, U)) := by
  apply le_antisymm
  · intro r hr
    obtain ⟨l, hl⟩ := ideal_section_lift f U r hr
    rw [Ideal.mem_span_singleton]
    refine ⟨e l, ?_⟩
    have he : e.symm (e l) = l := e.symm_apply_apply l
    have ha := e.symm.map_smul (e l) (1 : Γ(Y, U))
    simp only [smul_eq_mul, mul_one, he] at ha
    have hm : ((idealι f).val.app (op U)) l = (e l) * equation f U e := by
      conv_lhs => rw [ha]
      rw [_root_.map_smul]
      rfl
    exact hl.symm.trans (hm.trans (mul_comm (e l) (equation f U e)))
  · apply Ideal.span_le.mpr
    intro r hr
    obtain rfl := Set.mem_singleton_iff.mp hr
    exact equation_mem_kernel f U e

/-- Slice-site line trivializations induce section-module trivializations on Cartier charts. -/
def lineSectionTrivialization (d : LineTrivialization Y.sheaf (idealSheaf f)) (i : d.I) :
    SectionTrivialization f (d.obj i) :=
  CategoryTheory.Iso.toLinearEquiv
    ((SheafOfModules.evaluation _ (op (Over.mk (𝟙 (d.obj i))))).mapIso (d.iso i))
end ActualCartier

end

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace SheafTorsion
open ActualSheafTensor

/-- Torsion freedom of sections on an integral scheme is local on an arbitrary open cover. Empty
intersections are included, via the zero section ring. -/
lemma of_cover {X : Scheme.{0}} [IsIntegral X] (M : X.Modules)
    {ι : Type*} (U : ι → X.Opens) (hU : (⨆ i, U i) = ⊤)
    (hM : ∀ i (V : X.Opens), V ≤ U i →
      Module.IsTorsionFree Γ(X, V) (M.val.obj (op V)))
    (W : X.Opens) : Module.IsTorsionFree Γ(X, W) (M.val.obj (op W)) where
  isSMulRegular r hr := by
    intro x y hxy
    let Q : TopCat.Sheaf AddCommGrpCat X := (SheafOfModules.toSheaf X.ringCatSheaf).obj M
    apply Q.eq_of_locally_eq' (fun i => W ⊓ U i) W (fun _ => homOfLE inf_le_left)
      (by rw [← inf_iSup_eq, hU, inf_top_eq])
    intro i
    let V := W ⊓ U i
    by_cases hV : Nonempty V
    · let := hV
      have : Nonempty W := by
        obtain ⟨v⟩ := hV
        exact ⟨⟨v.1, v.2.1⟩⟩
      let g : V ⟶ W := homOfLE inf_le_left
      let s : Γ(X, V) := X.presheaf.map g.op r
      have hr0 : r ≠ 0 := isRegular_iff_ne_zero.mp hr
      have hs : s ≠ 0 := by
        intro hs0
        exact hr0 (map_injective_of_isIntegral X g (by simpa [s] using hs0))
      have : Module.IsTorsionFree Γ(X, V) (M.val.obj (op V)) := hM i V inf_le_right
      change M.val.map g.op x = M.val.map g.op y
      apply (isRegular_iff_ne_zero.mpr hs).isSMulRegular (M := M.val.obj (op V))
      have hh := congrArg (M.val.map g.op) hxy
      change M.val.map g.op (r • x) = M.val.map g.op (r • y) at hh
      exact (M.val.map_smul g.op r x).symm.trans
        (hh.trans (M.val.map_smul g.op r y))
    · have hz : V = ⊥ := by
        ext v
        exact ⟨fun hv => (hV ⟨⟨v, hv⟩⟩).elim, False.elim⟩
      have : Subsingleton Γ(X, V) :=
        CommRingCat.subsingleton_of_isTerminal (X.sheaf.isTerminalOfEqEmpty hz)
      have := Module.subsingleton Γ(X, V) (M.val.obj (op V))
      exact Subsingleton.elim (α := M.val.obj (op V)) _ _

/-- Twisting a torsion-free module sheaf by a line bundle preserves torsion freedom. No formal
'twist' operation is assumed. -/
lemma tensor_line {X : Scheme.{0}} [IsIntegral X] (L N : X.Modules)
    (d : LineTrivialization X.sheaf L)
    (hN : ∀ U, Module.IsTorsionFree (X.sheaf.obj.obj U) (N.val.obj U))
    (U : X.Opensᵒᵖ) :
    Module.IsTorsionFree (X.sheaf.obj.obj U) ((tensor X.sheaf L N).val.obj U) := by
  apply of_cover (tensor X.sheaf L N) d.obj ((Opens.coversTop_iff X _).mp d.cover)
  intro i V hV
  let e : (tensor X.sheaf L N).over (d.obj i) ≅ N.over (d.obj i) :=
    tensorOverIso X.sheaf (d.obj i) L N ≪≫
      (tensorLeftIso (X.sheaf.over (d.obj i)) (d.iso i)).app (N.over (d.obj i)) ≪≫
      (tensorUnitLeftIso (X.sheaf.over (d.obj i))).app (N.over (d.obj i))
  let W := op (Over.mk (homOfLE hV))
  let t : (tensor X.sheaf L N).val.obj (op V) ≃ₗ[Γ(X, V)] N.val.obj (op V) :=
    CategoryTheory.Iso.toLinearEquiv
      ((SheafOfModules.evaluation (X.ringCatSheaf.over (d.obj i)) W).mapIso e)
  have : Module.IsTorsionFree Γ(X, V) (N.val.obj (op V)) := hN (op V)
  exact t.injective.moduleIsTorsionFree t.toLinearMap t.map_smul
end SheafTorsion

end

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace SheafTorsion
open Scheme.Modules

lemma regular_ringEquiv {R S : Type*} [CommRing R] [CommRing S]
    (e : R ≃+* S) {r : R} (hr : IsRegular r) : IsRegular (e r) := by
  constructor
  · intro x y hxy
    apply e.symm.injective
    apply hr.1
    simpa only [map_mul, RingEquiv.symm_apply_apply] using congrArg e.symm hxy
  · intro x y hxy
    apply e.symm.injective
    apply hr.2
    simpa only [map_mul, RingEquiv.symm_apply_apply] using congrArg e.symm hxy

/-- Sectionwise torsion freedom survives open-scheme restriction, including the coefficient-ring
isomorphism in that restriction. -/
lemma restrict {X Y : Scheme.{0}} (f : X ⟶ Y) [IsOpenImmersion f]
    (M : Y.Modules)
    (hM : ∀ U, Module.IsTorsionFree (Y.sheaf.obj.obj U) (M.val.obj U))
    (U : X.Opensᵒᵖ) : Module.IsTorsionFree (X.sheaf.obj.obj U)
      (((restrictFunctor f).obj M).val.obj U) := by
  let e := (f.appIso U.unop).commRingCatIsoToRingEquiv
  have : Module.IsTorsionFree Γ(Y, f ''ᵁ U.unop) (M.val.obj (op (f ''ᵁ U.unop))) := hM _
  constructor
  intro r hr x y hxy
  apply (regular_ringEquiv e.symm hr).isSMulRegular
    (M := M.val.obj (op (f ''ᵁ U.unop)))
  exact hxy

/-- Conversely, torsion freedom of restricted sections gives torsion freedom over the original
coefficient ring on the image open. -/
lemma of_restrict {X Y : Scheme.{0}} (f : X ⟶ Y) [IsOpenImmersion f]
    (M : Y.Modules) (U : X.Opens)
    [Module.IsTorsionFree Γ(X, U) (((restrictFunctor f).obj M).val.obj (op U))] :
    Module.IsTorsionFree Γ(Y, f ''ᵁ U) (M.val.obj (op (f ''ᵁ U))) := by
  let e := (f.appIso U).commRingCatIsoToRingEquiv
  constructor
  intro r hr x y hxy
  apply (regular_ringEquiv e hr).isSMulRegular
    (M := ((restrictFunctor f).obj M).val.obj (op U))
  change (f.appIso U).inv ((f.appIso U).hom r) • x =
    (f.appIso U).inv ((f.appIso U).hom r) • y
  simpa only [CommRingCat.inv_hom_apply] using hxy

/-- Local torsion freedom on an open immersion cover is a global property of the sheaf, without
identifying non-definitional section rings. -/
lemma of_restrict_cover {X : Scheme.{0}} [IsIntegral X] (M : X.Modules)
    {ι : Type*} (U : ι → X.Opens) (hU : (⨆ i, U i) = ⊤)
    (hM : ∀ i V, Module.IsTorsionFree ((U i).toScheme.sheaf.obj.obj V)
      (((restrictFunctor (U i).ι).obj M).val.obj V))
    (W : X.Opens) : Module.IsTorsionFree Γ(X, W) (M.val.obj (op W)) := by
  apply of_cover M U hU
  intro i V hV
  let T := (U i).ι ⁻¹ᵁ V
  have : Module.IsTorsionFree Γ((U i).toScheme, T)
      (((restrictFunctor (U i).ι).obj M).val.obj (op T)) := hM i (op T)
  have h := of_restrict (U i).ι M T
  have heq : (U i).ι ''ᵁ T = V := by
    rw [Scheme.Hom.image_preimage_eq_opensRange_inf]
    rw [Scheme.Opens.opensRange_ι]
    exact inf_eq_right.mpr hV
  rwa [heq] at h
end SheafTorsion

end

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace SheafTorsion
open Scheme.Modules

/-- Torsion freedom can be reflected through an scheme isomorphism, without treating the two
structure sheaves as definitionally equal. -/
lemma of_restrict_iso {X Y : Scheme.{0}} (f : X ⟶ Y) [IsIso f] (M : Y.Modules)
    (hM : ∀ U, Module.IsTorsionFree (X.sheaf.obj.obj U)
      (((restrictFunctor f).obj M).val.obj U))
    (V : Y.Opensᵒᵖ) : Module.IsTorsionFree (Y.sheaf.obj.obj V) (M.val.obj V) := by
  let U := f ⁻¹ᵁ V.unop
  have : Module.IsTorsionFree Γ(X, U) (((restrictFunctor f).obj M).val.obj (op U)) :=
    hM (op U)
  have h := of_restrict f M U
  have hi : f ''ᵁ U = V.unop := by
    rw [Scheme.Hom.image_preimage_eq_opensRange_inf, Scheme.Hom.opensRange_of_isIso, top_inf_eq]
  change Module.IsTorsionFree Γ(Y, V.unop) (M.val.obj (op V.unop))
  rw [hi] at h
  exact h
end SheafTorsion

end

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace CoherentDual
open Scheme.Modules
variable {X Y : Scheme.{0}} [IsAffine X] [IsAffine Y] (f : X ⟶ Y)

/-- Pullback comparison for the affine identifications of source and target, retaining the map of
global section rings. -/
def pullbackIsoSpec (N : Y.Modules) :
    (restrictFunctor X.isoSpec.inv).obj ((Scheme.Modules.pullback f).obj N) ≅
      (Scheme.Modules.pullback (Spec.map f.appTop)).obj
        ((restrictFunctor Y.isoSpec.inv).obj N) :=
  (restrictFunctorIsoPullback X.isoSpec.inv).app _ ≪≫
    (pullbackComp X.isoSpec.inv f).app N ≪≫
    (pullbackCongr (Scheme.isoSpec_inv_naturality f).symm).app N ≪≫
    ((pullbackComp (Spec.map f.appTop) Y.isoSpec.inv).app N).symm ≪≫
    (Scheme.Modules.pullback (Spec.map f.appTop)).mapIso
      ((restrictFunctorIsoPullback Y.isoSpec.inv).app N).symm

/-- Dual restriction to a closed integral Cartier subscheme of an affine scheme is torsion-free. Its
regular defining equation is derived from the given trivialization of the kernel ideal, not
added as a hypothesis. -/
lemma affineSchemeDual_restriction_torsionFree
    [IsLocallyNoetherian Y] [IsIntegral X] [IsClosedImmersion f]
    (e : ActualCartier.SectionTrivialization f ⊤)
    (M : Y.Modules) [M.IsFinitePresentation]
    (U : X.Opensᵒᵖ) : Module.IsTorsionFree (X.sheaf.obj.obj U)
      (((Scheme.Modules.pullback f).obj
        (homSheaf Y.sheaf M (SheafOfModules.unit _))).val.obj U) := by
  have : IsNoetherianRing Γ(Y, ⊤) :=
    IsLocallyNoetherian.component_noetherian ⟨⊤, isAffineOpen_top Y⟩
  have : IsNoetherianRing Γ(X, ⊤) :=
    isNoetherianRing_of_surjective Γ(Y, ⊤) Γ(X, ⊤) f.appTop.hom
      (f.app_surjective ⊤ (isAffineOpen_top Y))
  have : IsDomain Γ(X, ⊤) := inferInstance
  let N := (restrictFunctor Y.isoSpec.inv).obj M
  have : N.IsFinitePresentation := CoherentGlobal.coherent_restrict _ M
  let t := ActualCartier.equation f ⊤ e
  have ht := ActualCartier.equation_regular f ⊤ e
  have hk := ActualCartier.kernel_eq_span_equation f ⊤ e
  let z := pullbackIsoSpec f (homSheaf Y.sheaf M (SheafOfModules.unit _)) ≪≫
    (Scheme.Modules.pullback (Spec.map f.appTop)).mapIso
      (dualSchemeRestrictionIso Y.isoSpec.inv M)
  apply SheafTorsion.of_restrict_iso X.isoSpec.inv
  intro V
  exact SheafTorsion.subobject z.hom
    (fun W => affineDual_algebra_restriction_torsionFree f.appTop N
      (f.app_surjective ⊤ (isAffineOpen_top Y)) t ht hk W) V
end CoherentDual

end

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace ActualCartier
open Scheme.Modules
variable {X Y : Scheme.{0}} (f : X ⟶ Y) (U : Y.Opens)

/-- The pushed-forward structure sheaf has the canonical open base-change identification. -/
def structureTargetRestrictIso :
    (restrictFunctor U.ι).obj ((pushforward f).obj (SheafOfModules.unit _)) ≅
      (pushforward (f ∣_ U)).obj (SheafOfModules.unit _) :=
  CoherentBaseChange.pushforwardRestrictIso f U (SheafOfModules.unit _) ≪≫
    (pushforward (f ∣_ U)).mapIso (restrictUnitIso (f ⁻¹ᵁ U).ι)

lemma structureMap_restrict :
    (restrictFunctor U.ι).map (structureMap f) ≫ (structureTargetRestrictIso f U).hom =
      (restrictUnitIso U.ι).hom ≫ structureMap (f ∣_ U) := by
  apply Scheme.Modules.hom_ext
  intro V
  apply AddCommGrpCat.ext
  intro r
  change (((f ⁻¹ᵁ U).ι.appIso ((f ∣_ U) ⁻¹ᵁ V)).hom
    (X.presheaf.map (eqToHom (image_morphismRestrict_preimage f U V)).op
      (f.app (U.ι ''ᵁ V) r))) =
    (f ∣_ U).app V ((U.ι.appIso V).hom r)
  simp only [Scheme.Opens.ι_appIso, Iso.refl_hom]
  rw [morphismRestrict_app]
  rfl

/-- The kernel ideal of the closed morphism commutes with actual restriction, by preservation of
kernels and the structure-map square. -/
def idealRestrictionIso :
    (restrictFunctor U.ι).obj (idealSheaf f) ≅ idealSheaf (f ∣_ U) :=
  PreservesKernel.iso (restrictFunctor U.ι) (structureMap f) ≪≫
    kernel.mapIso ((restrictFunctor U.ι).map (structureMap f))
      (structureMap (f ∣_ U)) (restrictUnitIso U.ι) (structureTargetRestrictIso f U)
      (structureMap_restrict f U)
end ActualCartier

end

noncomputable section
open CategoryTheory CategoryTheory.Limits _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry Opposite
namespace CoherentDual
open Scheme.Modules ActualSheafTensor
variable {X Y : Scheme.{0}} (f : X ⟶ Y)

/-- Dual pullback restricted to an open of the target. -/
def dualPullbackRestrictIso (V : Y.Opens) (M : Y.Modules) :
    (restrictFunctor (f ⁻¹ᵁ V).ι).obj
      ((Scheme.Modules.pullback f).obj (homSheaf Y.sheaf M (SheafOfModules.unit _))) ≅
    (Scheme.Modules.pullback (f ∣_ V)).obj
      (homSheaf V.toScheme.sheaf ((restrictFunctor V.ι).obj M) (SheafOfModules.unit _)) :=
  ((CoherentBaseChange.pullbackRestrictNatIso f V).app _).symm ≪≫
    (Scheme.Modules.pullback (f ∣_ V)).mapIso (dualSchemeRestrictionIso V.ι M)

lemma torsionFree_of_empty_scheme {Z : Scheme.{0}} [IsEmpty Z] (M : Z.Modules)
    (U : Z.Opensᵒᵖ) : Module.IsTorsionFree (Z.sheaf.obj.obj U) (M.val.obj U) := by
  have hz : U.unop = ⊥ := by ext x; exact isEmptyElim x
  have : Subsingleton Γ(Z, U.unop) :=
    CommRingCat.subsingleton_of_isTerminal (Z.sheaf.isTerminalOfEqEmpty hz)
  let : Module Γ(Z, U.unop) (M.val.obj U) := (M.val.obj U).isModule
  have : Subsingleton (M.val.obj U) := Module.subsingleton Γ(Z, U.unop) (M.val.obj U)
  exact ⟨fun _ _ _ _ _ => Subsingleton.elim _ _⟩

/-- If the closed ideal is trivial, the dual restriction is torsion-free on every open of an
integral divisor. Affine equations are derived from that ideal, and empty preimages in the
affine cover are treated separately. -/
lemma dual_restriction_torsionFree_of_trivial_ideal
    [IsLocallyNoetherian Y] [IsIntegral X] [IsClosedImmersion f]
    (e : ActualCartier.idealSheaf f ≅ SheafOfModules.unit Y.ringCatSheaf)
    (M : Y.Modules) [M.IsFinitePresentation] (U : X.Opensᵒᵖ) :
    Module.IsTorsionFree (X.sheaf.obj.obj U)
      (((Scheme.Modules.pullback f).obj
        (homSheaf Y.sheaf M (SheafOfModules.unit _))).val.obj U) := by
  apply SheafTorsion.of_restrict_cover _ (fun V : Y.affineOpens => f ⁻¹ᵁ V.1)
    (CoherentGlobal.preimage_cover f _ (iSup_affineOpens_eq_top Y))
  intro V W
  by_cases hV : Nonempty (f ⁻¹ᵁ V.1).toScheme
  · let := hV
    have : IsIntegral (f ⁻¹ᵁ V.1).toScheme :=
      isIntegral_of_isOpenImmersion (f ⁻¹ᵁ V.1).ι
    have : IsAffine V.1.toScheme := V.2
    have : IsAffine (f ⁻¹ᵁ V.1).toScheme := V.2.preimage f
    let z := (ActualCartier.idealRestrictionIso f V.1).symm ≪≫
      (restrictFunctor V.1.ι).mapIso e ≪≫ restrictUnitIso V.1.ι
    let t : ActualCartier.SectionTrivialization (f ∣_ V.1) ⊤ :=
      CategoryTheory.Iso.toLinearEquiv
        ((SheafOfModules.evaluation _ (op ⊤)).mapIso z)
    have : ((restrictFunctor V.1.ι).obj M).IsFinitePresentation :=
      CoherentGlobal.coherent_restrict _ M
    exact SheafTorsion.subobject (dualPullbackRestrictIso f V.1 M).hom
      (fun T => affineSchemeDual_restriction_torsionFree (f ∣_ V.1) t
        ((restrictFunctor V.1.ι).obj M) T) W
  · have : IsEmpty (f ⁻¹ᵁ V.1).toScheme := not_nonempty_iff.mp hV
    exact torsionFree_of_empty_scheme _ W

/-- Restriction of a coherent dual to an integral effective Cartier divisor is torsion-free; this
applies in particular to the model double dual. -/
lemma dual_restriction_torsionFree
    [IsLocallyNoetherian Y] [IsIntegral X] [IsClosedImmersion f]
    (d : LineTrivialization Y.sheaf (ActualCartier.idealSheaf f))
    (M : Y.Modules) [M.IsFinitePresentation] (U : X.Opensᵒᵖ) :
    Module.IsTorsionFree (X.sheaf.obj.obj U)
      (((Scheme.Modules.pullback f).obj
        (homSheaf Y.sheaf M (SheafOfModules.unit _))).val.obj U) := by
  apply SheafTorsion.of_restrict_cover _ (fun i => f ⁻¹ᵁ d.obj i)
    (CoherentGlobal.preimage_cover f _ ((Opens.coversTop_iff Y _).mp d.cover))
  intro i W
  by_cases hi : Nonempty (f ⁻¹ᵁ d.obj i).toScheme
  · let := hi
    have : IsIntegral (f ⁻¹ᵁ d.obj i).toScheme :=
      isIntegral_of_isOpenImmersion (f ⁻¹ᵁ d.obj i).ι
    let e := (ActualCartier.idealRestrictionIso f (d.obj i)).symm ≪≫ d.schemeIso (ActualCartier.idealSheaf f) i
    have : ((restrictFunctor (Scheme.Opens.ι (d.obj i))).obj M).IsFinitePresentation :=
      CoherentGlobal.coherent_restrict _ M
    exact SheafTorsion.subobject (dualPullbackRestrictIso f (d.obj i) M).hom
      (fun T => dual_restriction_torsionFree_of_trivial_ideal (f ∣_ d.obj i) e
        ((restrictFunctor (Scheme.Opens.ι (d.obj i))).obj M) T) W
  · have : IsEmpty (f ⁻¹ᵁ d.obj i).toScheme := not_nonempty_iff.mp hi
    exact torsionFree_of_empty_scheme _ W
end CoherentDual

end


/-! From regular affine equations to trivializations of the actual kernel ideal sheaf. This is
needed to construct the source Cartier data. -/
noncomputable section
open _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry CategoryTheory CategoryTheory.Limits Opposite
namespace ActualCartier
open Scheme.Modules
variable {X Y : Scheme.{0}} (f : X ⟶ Y)

lemma ideal_section_mem_kernel (U : Y.Opens) (l : (idealSheaf f).val.obj (op U)) :
    (idealι f).val.app (op U) l ∈ RingHom.ker (f.app U).hom := by
  have hz := congrArg (fun g => (g : idealSheaf f ⟶
    (pushforward f).obj (SheafOfModules.unit _)).val.app (op U))
    (kernel.condition (structureMap f))
  exact ConcreteCategory.congr_hom hz l

def sectionToKernel (U : Y.Opens) :
    (idealSheaf f).val.obj (op U) →ₗ[Γ(Y,U)] RingHom.ker (f.app U).hom :=
  ((idealι f).val.app (op U)).hom.codRestrict _ (ideal_section_mem_kernel f U)

lemma sectionToKernel_bijective (U : Y.Opens) : Function.Bijective (sectionToKernel f U) := by
  constructor
  · intro a b h
    have hmono : Mono (idealι f) :=
      kernelMono (C := SheafOfModules Y.ringCatSheaf) (structureMap f)
    have : Mono ((SheafOfModules.evaluation Y.ringCatSheaf (op U)).map (idealι f)) :=
      @Functor.map_mono _ _ _ _ (SheafOfModules.evaluation Y.ringCatSheaf (op U))
      _ _ _ (idealι f) hmono
    apply (ModuleCat.mono_iff_injective _).mp this
    exact congrArg Subtype.val h
  · intro r
    obtain ⟨l,hl⟩ := ideal_section_lift f U r.val r.property
    exact ⟨l, Subtype.ext hl⟩

def sectionKernelEquiv (U : Y.Opens) :
    (idealSheaf f).val.obj (op U) ≃ₗ[Γ(Y,U)] RingHom.ker (f.app U).hom :=
  LinearEquiv.ofBijective (sectionToKernel f U) (sectionToKernel_bijective f U)

lemma idealSheaf_coherent [IsLocallyNoetherian Y] [IsClosedImmersion f] :
    (idealSheaf f).IsFinitePresentation := by
  have : (SheafOfModules.unit X.ringCatSheaf).IsFinitePresentation :=
    CoherentLocality.finitePresentation_unit _
  have : ((pushforward f).obj (SheafOfModules.unit _)).IsFinitePresentation :=
    CoherentGlobal.coherent_pushforward f _
  have : (SheafOfModules.unit Y.ringCatSheaf).IsFinitePresentation :=
    CoherentLocality.finitePresentation_unit _
  exact CoherentGlobal.coherent_kernel (structureMap f)

/-- On an affine target, a section-module trivialization produces a sheaf trivialization by the
proved coherent affine equivalence. -/
def affineIdealUnitIso {A : CommRingCat.{0}} [IsNoetherianRing A]
    (f : X ⟶ Spec A) [IsClosedImmersion f] (e : SectionTrivialization f ⊤) :
    idealSheaf f ≅ SheafOfModules.unit (Spec A).ringCatSheaf := by
  have := idealSheaf_coherent f
  have : (SheafOfModules.unit (Spec A).ringCatSheaf).IsFinitePresentation :=
    CoherentLocality.finitePresentation_unit _
  have hIdeal : IsIso (fromTildeΓ (idealSheaf f)) := isIso_fromTildeΓ_of_isQuasicoherent _
  have hUnit : IsIso (fromTildeΓ (SheafOfModules.unit (Spec A).ringCatSheaf)) :=
    isIso_fromTildeΓ_of_isQuasicoherent _
  let e' := (ModuleCat.restrictScalars (Scheme.ΓSpecIso A).inv.hom).mapIso e.toModuleIso
  exact (@asIso _ _ _ _ (fromTildeΓ (idealSheaf f)) hIdeal).symm ≪≫
    (tilde.functor A).mapIso e' ≪≫ @asIso _ _ _ _ (fromTildeΓ (SheafOfModules.unit (Spec A).ringCatSheaf)) hUnit

end ActualCartier

end


/-! Affine Cartier ideal trivialization from a regular principal coordinate kernel. Used for the
source exceptional immersion. -/
noncomputable section
open _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry CategoryTheory CategoryTheory.Limits Opposite
namespace ActualCartier
open Scheme.Modules

def principalIdealEquiv {R : Type*} [CommRing R] (I : Ideal R) (t : R)
    (ht : IsSMulRegular R t) (hI : I = Ideal.span {t}) : I ≃ₗ[R] R := by
  let m : R →ₗ[R] I := (LinearMap.mulLeft R t).codRestrict I (by
    intro r
    rw [hI, Ideal.mem_span_singleton]
    exact dvd_mul_right t r)
  have hm : Function.Bijective m := by
    constructor
    · intro a b h
      apply ht
      exact congrArg Subtype.val h
    · intro x
      have hx : t ∣ (x : R) := Ideal.mem_span_singleton.mp (by
        simpa only [hI] using x.property)
      obtain ⟨r,hr⟩ := hx
      exact ⟨r, Subtype.ext hr.symm⟩
  exact (LinearEquiv.ofBijective m hm).symm

def equationSectionTrivialization {X Y : Scheme.{0}} (f : X ⟶ Y) (U : Y.Opens)
    (t : Γ(Y,U)) (ht : IsSMulRegular Γ(Y,U) t)
    (hker : RingHom.ker (f.app U).hom = Ideal.span {t}) : SectionTrivialization f U :=
  (sectionKernelEquiv f U).trans (principalIdealEquiv _ t ht hker)

lemma specMap_app_kernel {A B : CommRingCat.{0}} (q : A ⟶ B) (t : A)
    (hker : RingHom.ker q.hom = Ideal.span {t}) :
    RingHom.ker ((Spec.map q).app ⊤).hom =
      Ideal.span {((Scheme.ΓSpecIso A).inv.hom t)} := by
  let e := (Scheme.ΓSpecIso A).commRingCatIsoToRingEquiv
  let eB := (Scheme.ΓSpecIso B).commRingCatIsoToRingEquiv
  ext r
  have he : eB ((Spec.map q).appTop r) = q (e r) :=
    ConcreteCategory.congr_hom (Scheme.ΓSpecIso_naturality q) r
  rw [RingHom.mem_ker, Ideal.mem_span_singleton]
  change (Spec.map q).appTop r = 0 ↔ e.symm t ∣ r
  rw [← eB.injective.eq_iff, map_zero, he]
  rw [← RingHom.mem_ker, hker, Ideal.mem_span_singleton]
  simpa only [RingEquiv.apply_symm_apply] using
    (map_dvd_iff e : e (e.symm t) ∣ e r ↔ e.symm t ∣ r)

lemma specInverse_regular {A : CommRingCat.{0}} (t : A) (ht : IsSMulRegular A t) :
    IsSMulRegular Γ(Spec A, ⊤) ((Scheme.ΓSpecIso A).inv.hom t) := by
  let e := (Scheme.ΓSpecIso A).commRingCatIsoToRingEquiv
  intro a b h
  apply e.injective
  apply ht
  change t * e a = t * e b
  have hh := congrArg e h
  change e (e.symm t * a) = e (e.symm t * b) at hh
  simpa only [map_mul, RingEquiv.apply_symm_apply] using hh

def affinePrincipalIdealUnitIso {A B : CommRingCat.{0}} [IsNoetherianRing A]
    (q : A ⟶ B) (hq : Function.Surjective q) (t : A)
    (ht : IsSMulRegular A t) (hker : RingHom.ker q.hom = Ideal.span {t}) :
    idealSheaf (Spec.map q) ≅ SheafOfModules.unit (Spec A).ringCatSheaf := by
  have : IsClosedImmersion (Spec.map q) := IsClosedImmersion.spec_of_surjective q hq
  exact affineIdealUnitIso (Spec.map q)
    (equationSectionTrivialization (Spec.map q) ⊤ ((Scheme.ΓSpecIso A).inv.hom t)
      (specInverse_regular t ht) (specMap_app_kernel q t hker))

end ActualCartier

end


/-! The ideal sheaf on an open chart of a closed immersion. -/
noncomputable section
open _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry CategoryTheory CategoryTheory.Limits Opposite
namespace ActualCartier
open Scheme.Modules
variable {X Y X' Y' : Scheme.{0}} (f : X ⟶ Y) (g : X' ⟶ Y')
  (k : X' ⟶ X) (j : Y' ⟶ Y) [IsOpenImmersion k] [IsOpenImmersion j]
  (hw : k ≫ f = g ≫ j) (hp : k ''ᵁ ⊤ = f ⁻¹ᵁ (j ''ᵁ ⊤))

def chartSourceSectionsIso : Γ(X, f ⁻¹ᵁ (j ''ᵁ ⊤)) ≅ Γ(X', ⊤) :=
  X.presheaf.mapIso (eqToIso hp).op ≪≫ k.appIso ⊤

include hw in
lemma chart_section_square :
    f.app (j ''ᵁ ⊤) ≫ (chartSourceSectionsIso f k j hp).hom =
      (j.appIso ⊤).hom ≫ g.appTop := by
  simp only [chartSourceSectionsIso, Iso.trans_hom, Functor.mapIso_hom, Iso.op_hom,
    Scheme.Hom.appIso_hom']
  rw [Scheme.Hom.map_appLE]
  change _ = (j.appLE _ _ _) ≫ (g.app ⊤)
  rw [f.app_eq_appLE, g.app_eq_appLE, Scheme.Hom.appLE_comp_appLE,
    Scheme.Hom.appLE_comp_appLE]
  simp only [hw, Scheme.Hom.preimage_top]

/-- The kernel ideal on the chart, in its coefficient module. -/
def chartIdealSectionMap :
    ((restrictFunctor j).obj (idealSheaf f)).val.obj (op ⊤) →ₗ[Γ(Y', ⊤)]
      Γ(Y', ⊤) := by
  let a : ((restrictFunctor j).obj (SheafOfModules.unit Y.ringCatSheaf)).val.obj (op ⊤) →ₗ[Γ(Y', ⊤)]
      Γ(Y', ⊤) := ((restrictUnitIso j).hom.val.app (op ⊤)).hom
  let b : ((restrictFunctor j).obj (idealSheaf f)).val.obj (op ⊤) →ₗ[Γ(Y', ⊤)]
      ((restrictFunctor j).obj (SheafOfModules.unit Y.ringCatSheaf)).val.obj (op ⊤) :=
    (((restrictFunctor j).map (idealι f)).val.app (op ⊤)).hom
  exact a.comp b

lemma chartIdealSectionMap_apply
    (x : ((restrictFunctor j).obj (idealSheaf f)).val.obj (op ⊤)) :
    chartIdealSectionMap f j x = (j.appIso ⊤).hom ((idealι f).val.app (op (j ''ᵁ ⊤)) x) := rfl

lemma chartIdealSectionMap_injective : Function.Injective (chartIdealSectionMap f j) := by
  intro a b h
  have hh := (j.appIso ⊤).commRingCatIsoToRingEquiv.injective h
  apply (sectionToKernel_bijective f (j ''ᵁ ⊤)).1
  exact Subtype.ext hh

include hw hp in
lemma chartIdealSectionMap_mem (x : ((restrictFunctor j).obj (idealSheaf f)).val.obj (op ⊤)) :
    chartIdealSectionMap f j x ∈ RingHom.ker g.appTop.hom := by
  have hsq := ConcreteCategory.congr_hom (chart_section_square f g k j hw hp)
    ((idealι f).val.app (op (j ''ᵁ ⊤)) x)
  change (chartSourceSectionsIso f k j hp).hom
      (f.app (j ''ᵁ ⊤) ((idealι f).val.app (op (j ''ᵁ ⊤)) x)) =
    g.appTop ((j.appIso ⊤).hom ((idealι f).val.app (op (j ''ᵁ ⊤)) x)) at hsq
  have hx := ideal_section_mem_kernel f (j ''ᵁ ⊤) x
  change (f.app (j ''ᵁ ⊤)) ((idealι f).val.app (op (j ''ᵁ ⊤)) x) = 0 at hx
  change g.appTop ((j.appIso ⊤).hom ((idealι f).val.app (op (j ''ᵁ ⊤)) x)) = 0
  rw [← hsq, hx, map_zero]


def chartIdealSectionToKernel :
    ((restrictFunctor j).obj (idealSheaf f)).val.obj (op ⊤) →ₗ[Γ(Y', ⊤)]
      RingHom.ker g.appTop.hom :=
  (chartIdealSectionMap f j).codRestrict _ (chartIdealSectionMap_mem f g k j hw hp)

lemma chartIdealSectionToKernel_bijective :
    Function.Bijective (chartIdealSectionToKernel f g k j hw hp) := by
  constructor
  · intro a b h
    apply chartIdealSectionMap_injective f j
    exact congrArg Subtype.val h
  · intro r
    let a := (j.appIso ⊤).inv r.val
    have ha : f.app (j ''ᵁ ⊤) a = 0 := by
      apply (chartSourceSectionsIso f k j hp).commRingCatIsoToRingEquiv.injective
      change (chartSourceSectionsIso f k j hp).hom (f.app (j ''ᵁ ⊤) a) =
        (chartSourceSectionsIso f k j hp).hom 0
      have hr : g.appTop r.val = 0 := r.property
      have hsq := ConcreteCategory.congr_hom (chart_section_square f g k j hw hp) a
      simpa only [CommRingCat.comp_apply, a, Iso.inv_hom_id_apply, hr,
        map_zero] using hsq
    obtain ⟨l,hl⟩ := ideal_section_lift f (j ''ᵁ ⊤) a ha
    refine ⟨l, Subtype.ext ?_⟩
    change (j.appIso ⊤).hom ((idealι f).val.app (op (j ''ᵁ ⊤)) l) = r.val
    rw [hl]
    exact Iso.inv_hom_id_apply _ _

def chartIdealSectionsEquiv :
    ((restrictFunctor j).obj (idealSheaf f)).val.obj (op ⊤) ≃ₗ[Γ(Y', ⊤)]
      RingHom.ker g.appTop.hom :=
  LinearEquiv.ofBijective (chartIdealSectionToKernel f g k j hw hp)
    (chartIdealSectionToKernel_bijective f g k j hw hp)

def affineUnitIsoOfSections {A : CommRingCat.{0}} (N : (Spec A).Modules)
    [N.IsFinitePresentation]
    (e : N.val.obj (op ⊤) ≃ₗ[Γ(Spec A, ⊤)] Γ(Spec A, ⊤)) :
    N ≅ SheafOfModules.unit (Spec A).ringCatSheaf := by
  have : (SheafOfModules.unit (Spec A).ringCatSheaf).IsFinitePresentation :=
    CoherentLocality.finitePresentation_unit _
  have hN : IsIso (fromTildeΓ N) := isIso_fromTildeΓ_of_isQuasicoherent _
  have hUnit : IsIso (fromTildeΓ (SheafOfModules.unit (Spec A).ringCatSheaf)) :=
    isIso_fromTildeΓ_of_isQuasicoherent _
  let e' := (ModuleCat.restrictScalars (Scheme.ΓSpecIso A).inv.hom).mapIso e.toModuleIso
  exact (@asIso _ _ _ _ (fromTildeΓ N) hN).symm ≪≫
    (tilde.functor A).mapIso e' ≪≫ @asIso _ _ _ _ (fromTildeΓ (SheafOfModules.unit (Spec A).ringCatSheaf)) hUnit


def chartAffinePrincipalIdealUnitIso {A B : CommRingCat.{0}}
    {X Y : Scheme.{0}} [IsLocallyNoetherian Y]
    (f : X ⟶ Y) [IsClosedImmersion f]
    (q : A ⟶ B) (k : Spec B ⟶ X) (j : Spec A ⟶ Y)
    [IsOpenImmersion k] [IsOpenImmersion j]
    (hw : k ≫ f = Spec.map q ≫ j) (hp : k ''ᵁ ⊤ = f ⁻¹ᵁ (j ''ᵁ ⊤))
    (t : A) (ht : IsSMulRegular A t) (hker : RingHom.ker q.hom = Ideal.span {t}) :
    (restrictFunctor j).obj (idealSheaf f) ≅ SheafOfModules.unit (Spec A).ringCatSheaf := by
  have := idealSheaf_coherent f
  have : ((restrictFunctor j).obj (idealSheaf f)).IsFinitePresentation :=
    CoherentGlobal.coherent_restrict _ _
  exact affineUnitIsoOfSections _ ((chartIdealSectionsEquiv f (Spec.map q) k j hw hp).trans
    (principalIdealEquiv _ _ (specInverse_regular t ht) (specMap_app_kernel q t hker)))

end ActualCartier

namespace ActualSheafTensor
open Scheme.Modules

def lineTrivializationOfCharts {Y : Scheme.{0}} (L : Y.Modules)
    {I : Type} (Z : I → Scheme.{0}) (j : ∀ i, Z i ⟶ Y)
    [∀ i, IsOpenImmersion (j i)] (hc : (⨆ i, (j i).opensRange) = ⊤)
    (e : ∀ i, (restrictFunctor (j i)).obj L ≅ SheafOfModules.unit (Z i).ringCatSheaf) :
    LineTrivialization Y.sheaf L where
  I := I
  obj i := (j i).opensRange
  cover := (Opens.coversTop_iff Y _).mpr hc
  iso i := by
    let U := (j i).opensRange
    let h := (j i).isoOpensRange.inv
    let ei : (restrictFunctor U.ι).obj L ≅ SheafOfModules.unit U.toScheme.ringCatSheaf :=
      ((restrictFunctorCongr (Scheme.Hom.isoOpensRange_inv_comp (j i))).app L).symm ≪≫
      (restrictFunctorComp h (j i)).app L ≪≫
      (restrictFunctor h).mapIso (e i) ≪≫ restrictUnitIso h
    exact (overEquiv U).functor.preimageIso
      ((overFunctorEquiv U).app L ≪≫ ei ≪≫ (restrictUnitIso U.ι).symm ≪≫
        ((overFunctorEquiv U).app (SheafOfModules.unit Y.ringCatSheaf)).symm)

end ActualSheafTensor


end


/-! Torsion freedom of the exceptional restriction of `E = (p* M)⁎⁎`, using the Cartier equations on
the source charts. -/
noncomputable section
open _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry CategoryTheory CategoryTheory.Limits Opposite
attribute [local instance] MvPolynomial.gradedAlgebra
namespace SourceExceptionalRestriction
open KummerSourceModel SourcePullbackChart SourceZeroSections CoherentDual Scheme.Modules
attribute [local instance] integralSurfaceCommRing integralSurfaceSemiring
  integralPullbackCommRing integralPullbackSemiring pullbackBaseAlgebra surfaceOriginAlgebra
  completedPullbackModule completedPullbackAction completedPullbackSMul completedPullbackTower
  completedSurfaceModule completedSeriesModule completedSourceChartCommRing completedSourceChartSemiring
  completedSourceAlgebra

/-- Functoriality connects the global sheaf pullback with the actual regular quotient on each
surface affine chart. -/
def chartIso (N : W.Modules) (i : Fin 3) :
    (restrictFunctor (surfaceIota i)).obj
      ((Scheme.Modules.pullback completedSourceZero).obj
        (homSheaf W.sheaf N (SheafOfModules.unit _))) ≅
    (Scheme.Modules.pullback (completedZeroChart i)).obj
      (homSheaf (Spec (.of (completedSourceChart i))).sheaf
        ((restrictFunctor (completedIota i)).obj N) (SheafOfModules.unit _)) :=
  (restrictFunctorIsoPullback (surfaceIota i)).app _ ≪≫
    (pullbackComp (surfaceIota i) completedSourceZero).app _ ≪≫
    (pullbackCongr (surfaceIota_completedSourceZero i)).app _ ≪≫
    ((pullbackComp (completedZeroChart i) (completedIota i)).app _).symm ≪≫
    (Scheme.Modules.pullback (completedZeroChart i)).mapIso
      (((restrictFunctorIsoPullback (completedIota i)).app _).symm ≪≫
        dualSchemeRestrictionIso (completedIota i) N)

lemma chart_torsionFree (N : W.Modules) [N.IsFinitePresentation] (i : Fin 3)
    (T : (Spec (.of (surfaceChart i))).Opensᵒᵖ) :
    Module.IsTorsionFree ((Spec (.of (surfaceChart i))).sheaf.obj.obj T)
      (((restrictFunctor (surfaceIota i)).obj
        ((Scheme.Modules.pullback completedSourceZero).obj
          (homSheaf W.sheaf N (SheafOfModules.unit _)))).val.obj T) := by
  have : IsNoetherianRing (surfaceChart i) :=
    isNoetherianRing_of_surjective (completedSourceChart i) (surfaceChart i)
      (completedZeroEvaluation i) (completedZeroEvaluation_surjective i)
  have : ((restrictFunctor (completedIota i)).obj N).IsFinitePresentation :=
    CoherentGlobal.coherent_restrict _ N
  exact SheafTorsion.subobject (chartIso N i).hom
    (fun U => affineDual_algebra_restriction_torsionFree
      (CommRingCat.ofHom (completedZeroEvaluation i)) ((restrictFunctor (completedIota i)).obj N)
      (completedZeroEvaluation_surjective i) (completedFiberParameter i)
      (completedFiberParameter_regular i) (completedZeroEvaluation_kernel i) U) T

/-- The global section modules of the exceptional restriction of any coherent dual are torsion-free
over the integral surface. -/
lemma dual_restriction_torsionFree (N : W.Modules) [N.IsFinitePresentation]
    (U : ExplicitCone.projectiveSurface.Opens) :
    Module.IsTorsionFree Γ(ExplicitCone.projectiveSurface, U)
      (((Scheme.Modules.pullback completedSourceZero).obj
        (homSheaf W.sheaf N (SheafOfModules.unit _))).val.obj (op U)) := by
  let Q := (Scheme.Modules.pullback completedSourceZero).obj
    (homSheaf W.sheaf N (SheafOfModules.unit _))
  apply SheafTorsion.of_cover Q (fun i => (surfaceIota i).opensRange) surfaceIota_cover
  intro i V hV
  let T := (surfaceIota i) ⁻¹ᵁ V
  have : Module.IsTorsionFree Γ(Spec (.of (surfaceChart i)), T)
      (((restrictFunctor (surfaceIota i)).obj Q).val.obj (op T)) :=
    chart_torsionFree N i (op T)
  have hh := SheafTorsion.of_restrict (surfaceIota i) Q T
  have heq : (surfaceIota i) ''ᵁ T = V := by
    rw [Scheme.Hom.image_preimage_eq_opensRange_inf]
    exact inf_eq_right.mpr hV
  rwa [heq] at hh

abbrev P (M : ModuleCat ExplicitCone.completedRing) : ExplicitCone.projectiveSurface.Modules :=
  (Scheme.Modules.pullback completedSourceZero).obj (SourceConeMorphism.E M)

lemma P_torsionFree (M : ModuleCat ExplicitCone.completedRing)
    [Module.Finite ExplicitCone.completedRing M] (U : ExplicitCone.projectiveSurface.Opens) :
    Module.IsTorsionFree Γ(ExplicitCone.projectiveSurface, U) ((P M).val.obj (op U)) := by
  let := ExplicitCone.actualCompletion_noetherian
  obtain ⟨F,hF⟩ := CoherentPullback.exists_presentation_pullback_tilde SourceConeMorphism.p M
  let := hF
  have : ((Scheme.Modules.pullback SourceConeMorphism.p).obj (tilde M)).IsFinitePresentation :=
    CoherentLocality.finitePresentation_of_presentation F
  have hN := coherent_dual ((Scheme.Modules.pullback SourceConeMorphism.p).obj (tilde M))
  exact dual_restriction_torsionFree _ U

end SourceExceptionalRestriction

end


/-! Coherence of the exceptional restriction, descended from finite presentations on the affine
cover. -/
noncomputable section
open _root_.AlgebraicGeometry _root_.OAI.AlgebraicGeometry CategoryTheory CategoryTheory.Limits Opposite
namespace CoherentPullback
open Scheme.Modules
lemma coherent_from_affine {A : CommRingCat.{0}} [IsNoetherianRing A]
    {X : Scheme.{0}} (f : X ⟶ Spec A) (N : (Spec A).Modules)
    [N.IsFinitePresentation] : ((Scheme.Modules.pullback f).obj N).IsFinitePresentation := by
  let M := moduleSpecΓFunctor.obj N
  have : Module.Finite A M := CoherentGlobal.finiteGamma_of_coherent N
  have hN : IsIso (Scheme.Modules.fromTildeΓ N) := isIso_fromTildeΓ_of_isQuasicoherent N
  obtain ⟨P, hP⟩ := exists_presentation_pullback_tilde f M
  let := hP
  have h := CoherentLocality.finitePresentation_of_presentation P
  exact (SheafOfModules.isFinitePresentation X.ringCatSheaf).prop_of_iso
    ((Scheme.Modules.pullback f).mapIso (@asIso _ _ _ _ (Scheme.Modules.fromTildeΓ N) hN)) h
end CoherentPullback
namespace CoherentGlobal
open Scheme.Modules

lemma weakSheafify_over (X : Scheme.{0}) :
    ∀ U : X.Opens, HasWeakSheafify ((Opens.grothendieckTopology X).over U) AddCommGrpCat.{0} :=
  fun _ => inferInstance

lemma wEqualsLocallyBijective_over (X : Scheme.{0}) :
    ∀ U : X.Opens, ((Opens.grothendieckTopology X).over U).WEqualsLocallyBijective
      AddCommGrpCat.{0} :=
  fun _ => inferInstance

/-- Finite presentation is invariant under an isomorphism of module sheaves. -/
lemma coherent_of_iso {X : Scheme.{0}} {M N : X.Modules} (e : M ≅ N)
    (hM : M.IsFinitePresentation) : N.IsFinitePresentation :=
  (SheafOfModules.isFinitePresentation X.ringCatSheaf).prop_of_iso e hM

/-- Coherence descends along a covering family of open immersions. -/
lemma coherent_of_open_immersions {X : Scheme.{0}} {I : Type}
    {Y : I → Scheme.{0}} (f : ∀ i, Y i ⟶ X) [∀ i, IsOpenImmersion (f i)]
    (hcover : (⨆ i, (f i).opensRange) = ⊤) (M : X.Modules)
    (hM : ∀ i, ((restrictFunctor (f i)).obj M).IsFinitePresentation) :
    M.IsFinitePresentation := by
  apply coherent_of_open_cover (fun i => (f i).opensRange) hcover
  intro i
  have := hM i
  have h := coherent_restrict (f i).isoOpensRange.inv ((restrictFunctor (f i)).obj M)
  let e := ((restrictFunctorComp (f i).isoOpensRange.inv (f i)).app M).symm ≪≫
    (restrictFunctorCongr (Scheme.Hom.isoOpensRange_inv_comp (f i))).app M
  exact coherent_of_iso e h
end CoherentGlobal

namespace SourceExceptionalRestriction
open KummerSourceModel SourcePullbackChart SourceZeroSections Scheme.Modules
attribute [local instance] integralSurfaceCommRing integralSurfaceSemiring
  integralPullbackCommRing integralPullbackSemiring pullbackBaseAlgebra surfaceOriginAlgebra
  completedPullbackModule completedPullbackAction completedPullbackSMul completedPullbackTower
  completedSurfaceModule completedSeriesModule completedSourceChartCommRing completedSourceChartSemiring
  completedSourceAlgebra

local instance (i : Fin 3) :
    ∀ U : (Spec (.of (surfaceChart i))).Opens,
      HasWeakSheafify ((Opens.grothendieckTopology (Spec (.of (surfaceChart i)))).over U)
        AddCommGrpCat.{0} :=
  CoherentGlobal.weakSheafify_over _

local instance (i : Fin 3) :
    ∀ U : (surfaceIota i).opensRange.toScheme.Opens,
      HasWeakSheafify ((Opens.grothendieckTopology (surfaceIota i).opensRange.toScheme).over U)
        AddCommGrpCat.{0} :=
  CoherentGlobal.weakSheafify_over _

local instance (i : Fin 3) :
    ∀ U : (Spec (.of (surfaceChart i))).Opens,
      ((Opens.grothendieckTopology (Spec (.of (surfaceChart i)))).over U).WEqualsLocallyBijective
        AddCommGrpCat.{0} :=
  CoherentGlobal.wEqualsLocallyBijective_over _

local instance (i : Fin 3) :
    ∀ U : (surfaceIota i).opensRange.toScheme.Opens,
      ((Opens.grothendieckTopology (surfaceIota i).opensRange.toScheme).over U).WEqualsLocallyBijective
        AddCommGrpCat.{0} :=
  CoherentGlobal.wEqualsLocallyBijective_over _

def chartPullbackIso (N : W.Modules) (i : Fin 3) :
    (restrictFunctor (surfaceIota i)).obj ((Scheme.Modules.pullback completedSourceZero).obj N) ≅
      (Scheme.Modules.pullback (completedZeroChart i)).obj
        ((restrictFunctor (completedIota i)).obj N) :=
  (restrictFunctorIsoPullback (surfaceIota i)).app _ ≪≫
    (pullbackComp (surfaceIota i) completedSourceZero).app _ ≪≫
    (pullbackCongr (surfaceIota_completedSourceZero i)).app _ ≪≫
    ((pullbackComp (completedZeroChart i) (completedIota i)).app _).symm ≪≫
    (Scheme.Modules.pullback (completedZeroChart i)).mapIso
      ((restrictFunctorIsoPullback (completedIota i)).app _).symm

lemma chart_pullback_coherent (N : W.Modules) [N.IsFinitePresentation] (i : Fin 3) :
    ((restrictFunctor (surfaceIota i)).obj
      ((Scheme.Modules.pullback completedSourceZero).obj N)).IsFinitePresentation := by
  have : ((restrictFunctor (completedIota i)).obj N).IsFinitePresentation :=
    CoherentGlobal.coherent_restrict _ N
  exact CoherentGlobal.coherent_of_iso (chartPullbackIso N i).symm
    (CoherentPullback.coherent_from_affine _ _)

lemma pullback_coherent (N : W.Modules) [N.IsFinitePresentation] :
    ((Scheme.Modules.pullback completedSourceZero).obj N).IsFinitePresentation := by
  exact CoherentGlobal.coherent_of_open_immersions surfaceIota surfaceIota_cover _
    (fun i => chart_pullback_coherent N i)

lemma P_coherent (M : ModuleCat ExplicitCone.completedRing)
    [Module.Finite ExplicitCone.completedRing M] : (P M).IsFinitePresentation := by
  have := SourceConeMorphism.E_coherent M
  exact pullback_coherent _

end SourceExceptionalRestriction

end

end OAI
