import OAI.Analysis.RCDHeat.DimensionalCompactWeightedGradient
import OAI.Analysis.RCDHeat.FiniteDimensionalBochnerTarget
import OAI.Analysis.RCDHeat.LastTimeBins
import OAI.Analysis.RCDHeat.MidpointEndpoint
import OAI.Analysis.RCDHeat.VariableRadialSecant
import OAI.Analysis.RCDHeat.WeightedMidpointEndpoint
