import Mathlib
import OAI.SetTheory.PartitionConsistency.Construction.CellTowers

namespace OAI

/-! ## CellCut -/

/-! The selected subconstruction at every original cut. Closing the retained
words under their dependencies supplies actual restricted cells. -/
namespace PartitionConsistency.MonoidPushout.IsPushout
universe u
noncomputable section
variable {A B C D E : Type u} [Monoid A] [Monoid B] [Monoid C] [Monoid D] [Monoid E]

/-- Replacing the upper-right corner by an isomorphic monoid does not
change a presentation pushout. -/
theorem change_left {f : A →* B} {g : A →* C} {i : B →* D} {j : C →* D}
    (h : IsPushout f g i j) (e : B ≃* E) :
    IsPushout (e.toMonoidHom.comp f) g (i.comp e.symm.toMonoidHom) j where
  comm := by ext x; simpa using DFunLike.congr_fun h.comm x
  universal b c hc := by
    let b' := b.comp e.toMonoidHom
    have hc' : b'.comp f = c.comp g := by simpa only [b',MonoidHom.comp_assoc] using hc
    let t := h.lift b' c hc'
    have ht : t.comp i = b' := h.lift_comp_left _ _ _
    have ht' : t.comp j = c := h.lift_comp_right _ _ _
    have he : t.comp (i.comp e.symm.toMonoidHom) = b := by
      ext x
      have hh := DFunLike.congr_fun ht (e.symm x)
      simpa only [MonoidHom.comp_apply,MulEquiv.coe_toMonoidHom,e.apply_symm_apply,b'] using hh
    refine ⟨t,⟨he,ht'⟩,?_⟩
    intro s hs
    apply h.hom_ext
    · ext x
      have hh := DFunLike.congr_fun hs.1 (e x)
      have hh' := DFunLike.congr_fun he (e x)
      simpa only [MonoidHom.comp_apply,MulEquiv.coe_toMonoidHom,e.symm_apply_apply]
        using hh.trans hh'.symm
    · exact hs.2.trans ht'.symm
end
end PartitionConsistency.MonoidPushout.IsPushout

namespace PartitionConsistency.ConservativeMonoids
universe u
open CategoryTheory DiagramOrder MonoidPushout
noncomputable section
open scoped Classical

namespace Cell
variable {M N : Object.{u}}

@[simp] theorem simulation_old (d : Cell M) (f : M ⟶ N) (x : M) :
    d.simulation f (d.inclusion x) = (d.map f).inclusion (f x) := by cases d <;> rfl

theorem simulation_generator_range (d : Cell M) (f : M ⟶ N) :
    Set.range (fun i => d.simulation f (d.generator i)) = Set.range (d.map f).generator := by
  cases d with
  | inl d => exact congrArg Set.range (funext (d.simulation_generator f))
  | inr d => exact congrArg Set.range (funext (d.simulation_generator f))
end Cell

namespace CellTower
variable {T : Object.{u}} {J : Type u} [LinearOrder J] [OrderBot J] [OrderTop J]
  [SuccOrder J] (D : CellTower T J) (S : Subobject T)

def Closed : Prop := ∀ x ∈ S.submonoid, D.dependencies x ⊆ S.submonoid

def selected (i : J) : Prop := ∃ x ∈ S.submonoid, D.NewAt i x

def restrict (i : J) : Subobject T := S.inf (D.stage i)

omit [OrderBot J] in
theorem restrict_le (i : J) : (D.restrict S i).submonoid ≤ (D.stage i).submonoid := fun _ h => h.2

omit [OrderBot J] in
theorem restrict_mono : Monotone (fun i => (D.restrict S i).submonoid) :=
  fun _ _ h _ hx => ⟨hx.1,D.mono h hx.2⟩

omit [OrderBot J] in
theorem restrict_omitted {i : J} (h : ¬ D.selected S i) :
    (D.restrict S i).submonoid = (D.restrict S (Order.succ i)).submonoid := by
  apply le_antisymm (D.restrict_mono S (Order.le_succ i))
  intro x hx
  exact ⟨hx.1,by by_contra hh; exact h ⟨x,hx.1,hx.2,hh⟩⟩

theorem selected_countable (hS : (S.submonoid : Set T).Countable) :
    {i | D.selected S i}.Countable := by
  apply (hS.image D.newIndex).mono
  rintro i ⟨x,hx,hi⟩
  exact ⟨x,hx,D.newIndex_eq hi⟩

/-- All the parameters and all the countably many generators are retained
as soon as one new word of this cell is retained. -/
theorem selected_dependencies (hS : D.Closed S) {i : J} (hi : D.selected S i) :
    ∃ h : (D.stage i).submonoid ≠ (D.stage (Order.succ i)).submonoid,
      (D.stepCell i h).parameters ⊆ S.submonoid ∧
        Set.range (D.stepCell i h).generator ⊆ S.submonoid := by
  obtain ⟨x,hx,hin⟩ := hi
  refine ⟨hin.neq D,?_,?_⟩
  all_goals
    have hh := hS x hx
    rw [D.dependencies_at hin] at hh
  · exact fun _ hm => hh (Or.inl (Or.inl hm))
  · exact fun _ hm => hh (Or.inl (Or.inr hm))

/-- Every retained new word is still generated by retained old coefficients
and the generators of this very same cell. -/
theorem selected_word (hS : D.Closed S) {i : J}
    (h : (D.stage i).submonoid ≠ (D.stage (Order.succ i)).submonoid)
    {x : T} (hx : x ∈ S.submonoid) (hi : D.NewAt i x) :
    x ∈ Submonoid.closure ((D.restrict S i).submonoid ∪
      Set.range (D.stepCell i h).generator) := by
  let c := D.coefficients i h ⟨x,hi.1⟩
  have hc : (D.stage i).inclusion '' (c : Set (D.stage i).object) ⊆ S.submonoid := by
    have hh := hS x hx
    rw [D.dependencies_at hi] at hh
    exact fun _ hm => hh (Or.inr hm)
  have hc' : (D.stage i).inclusion '' (c : Set (D.stage i).object) ⊆
      (D.restrict S i).submonoid := by
    rintro z ⟨y,hy,rfl⟩
    exact ⟨hc ⟨y,hy,rfl⟩,y.property⟩
  exact (Submonoid.closure_mono (Set.union_subset_union hc' Set.Subset.rfl))
    ((D.stepCell i h).finite_coefficients ⟨x,hi.1⟩).choose_spec

/-- A selected successor really is the operation restricted to the retained
base. Its inclusion into the original successor is the conservative cell
simulation. This theorem includes the full presentation pushout. -/
theorem restrict_selected (hS : D.Closed S) {i : J} (hi : D.selected S i) :
    Nonempty (Attachment (D.restrict S i) (D.restrict S (Order.succ i))) ∧
    IsPushout (Subobject.hom (D.restrict_mono S (Order.le_succ i))).toMonoidHom
      (Subobject.hom (D.restrict_le S i)).toMonoidHom
      (Subobject.hom (D.restrict_le S (Order.succ i))).toMonoidHom
      (Subobject.hom (D.mono (Order.le_succ i))).toMonoidHom := by
  obtain ⟨h,hp,hg⟩ := D.selected_dependencies S hS hi
  let d := D.stepCell i h
  let f := Subobject.hom (D.restrict_le S i)
  have hp' : d.cell.parameters ⊆ Set.range f := by
    intro x hx
    exact ⟨⟨x.val,hp ⟨x,hx,rfl⟩,x.property⟩,Subtype.ext rfl⟩
  obtain ⟨c,hc⟩ := d.cell.exists_preimage f hp'
  have work (c : Cell (D.restrict S i).object)
      (cell : Cell (D.stage i).object) (hc : c.map f = cell)
      (e : cell.extension ≃* (D.stage (Order.succ i)).object)
      (he : ∀ x : (D.stage i).object, (e (cell.inclusion x)).val = x.val)
      (hgen : Set.range (fun k => (e (cell.generator k)).val) ⊆ S.submonoid)
      (hwords : ∀ x ∈ S.submonoid, D.NewAt i x →
        x ∈ Submonoid.closure ((D.restrict S i).submonoid ∪
          Set.range (fun k => (e (cell.generator k)).val))) :
      Nonempty (Attachment (D.restrict S i) (D.restrict S (Order.succ i))) ∧
      IsPushout (Subobject.hom (D.restrict_mono S (Order.le_succ i))).toMonoidHom
        f.toMonoidHom (Subobject.hom (D.restrict_le S (Order.succ i))).toMonoidHom
        (Subobject.hom (D.mono (Order.le_succ i))).toMonoidHom := by
    subst cell
    let m := (D.stage (Order.succ i)).inclusion.comp
      ((ofMulEquiv e).comp (c.simulation f))
    have mo (x : (D.restrict S i).object) : m (c.inclusion x) = x.val := by
      change (e (c.simulation f (c.inclusion x))).val = x.val
      rw [c.simulation_old]
      exact he (f x)
    have mg : Set.range (fun k => m (c.generator k)) =
        Set.range (fun k => (e ((c.map f).generator k)).val) := by
      have hh := congrArg (fun s => (fun y => (e y).val) '' s)
        (c.simulation_generator_range f)
      rw [← Set.range_comp,← Set.range_comp] at hh
      exact hh
    have sm : ∀ x : c.extension, m x ∈ S.submonoid := by
      let Q := S.submonoid.comap m.toMonoidHom
      have hQ : Q = ⊤ := c.generated Q
        (fun x => by change m (c.inclusion x) ∈ S.submonoid; rw [mo]; exact x.property.1)
        (fun k => hgen (mg ▸ Set.mem_range_self k))
      intro x
      exact (show x ∈ Q from hQ ▸ Submonoid.mem_top x)
    have rm : ∀ x : c.extension, m x ∈ (D.restrict S (Order.succ i)).submonoid :=
      fun x => ⟨sm x,(e (c.simulation f x)).property⟩
    let m' : c.extension →* (D.restrict S (Order.succ i)).object :=
      { toFun := fun x => ⟨m x,rm x⟩
        map_one' := Subtype.ext m.map_one
        map_mul' x y := Subtype.ext (m.map_mul x y) }
    have hm : Function.Bijective m' := by
      refine ⟨?_,?_⟩
      · intro x y hh
        apply m.injective
        exact congrArg (fun z : (D.restrict S (Order.succ i)).object => z.val) hh
      · intro x
        have hl : (D.restrict S i).submonoid ≤ MonoidHom.mrange m.toMonoidHom := by
          intro y hy
          exact ⟨c.inclusion ⟨y,hy⟩,mo ⟨y,hy⟩⟩
        have hn : Set.range (fun k => (e ((c.map f).generator k)).val) ⊆
            MonoidHom.mrange m.toMonoidHom := by
          rw [← mg]
          rintro _ ⟨k,rfl⟩
          exact ⟨c.generator k,rfl⟩
        have hh : x.val ∈ MonoidHom.mrange m.toMonoidHom := by
          by_cases ho : x.val ∈ (D.stage i).submonoid
          · exact hl ⟨x.property.1,ho⟩
          · exact (Submonoid.closure_le.mpr (Set.union_subset hl hn))
              (hwords x.val x.property.1 ⟨x.property.2,ho⟩)
        obtain ⟨z,hz⟩ := hh
        exact ⟨z,Subtype.ext hz⟩
    let e' := MulEquiv.ofBijective m' hm
    have hpo := ((c.pushout f).map_apex e).change_left e'
    have h₁ : e'.toMonoidHom.comp c.inclusion.toMonoidHom =
        (Subobject.hom (D.restrict_mono S (Order.le_succ i))).toMonoidHom := by
      ext x; apply Subtype.ext; exact mo x
    have h₂ : (e.toMonoidHom.comp (c.simulation f).toMonoidHom).comp e'.symm.toMonoidHom =
        (Subobject.hom (D.restrict_le S (Order.succ i))).toMonoidHom := by
      ext x
      apply Subtype.ext
      exact congrArg (fun z : (D.restrict S (Order.succ i)).object => z.val) (e'.apply_symm_apply x)
    have h₃ : e.toMonoidHom.comp (c.map f).inclusion.toMonoidHom =
        (Subobject.hom (D.mono (Order.le_succ i))).toMonoidHom := by
      ext x; apply Subtype.ext; exact he x
    rw [h₁,h₂,h₃] at hpo
    exact ⟨⟨⟨c,e',mo⟩⟩,hpo⟩
  have hh : ∀ x ∈ S.submonoid, D.NewAt i x →
      x ∈ Submonoid.closure ((D.restrict S i).submonoid ∪ Set.range d.generator) :=
    fun _ hx hin => D.selected_word S hS h hx hin
  exact work c d.cell hc d.equiv d.old hg hh

end CellTower
end
end PartitionConsistency.ConservativeMonoids


/-! ## CellFunctor -/

/-! Functoriality of the actual presentations. A redundant natural-number
list of generators avoids changing index types during base change. -/
namespace PartitionConsistency.ConservativeMonoids.Cell
universe u
open CategoryTheory DiagramOrder DiagramForcing
noncomputable section
open scoped Classical
variable {M N P : Object.{u}}

def naturalGenerator : (d : Cell M) → ℕ → d.extension
  | .inl d,i => d.generator i
  | .inr d,i => if h : i < d.n then d.generator ⟨i,h⟩ else 1

theorem hom_ext {R : Type u} [Monoid R] (d : Cell M) {f g : d.extension →* R}
    (ho : ∀ x, f (d.inclusion x) = g (d.inclusion x))
    (hn : ∀ i, f (d.naturalGenerator i) = g (d.naturalGenerator i)) : f = g := by
  cases d with
  | inl d => exact d.path.presentedHom_ext d.e_ne_one d.b d.b_ne_one f g ho hn
  | inr d =>
    apply d.prescription.presentedHom_ext d.valid f g ho
    rintro ⟨i,hi⟩
    have hh := hn i
    dsimp only [naturalGenerator] at hh
    erw [dite_eq_left hi] at hh
    exact hh

@[simp] theorem simulation_naturalGenerator (d : Cell M) (f : M ⟶ N) (i : ℕ) :
    d.simulation f (d.naturalGenerator i) = (d.map f).naturalGenerator i := by
  cases d with
  | inl d => exact d.simulation_generator f i
  | inr d =>
    dsimp only [map,naturalGenerator,simulation,Merger.map]
    by_cases hi : i < d.n
    · erw [dite_eq_left hi, dite_eq_left hi]
      exact d.simulation_generator f _
    · erw [dite_eq_right hi, dite_eq_right hi]
      exact (d.simulation f).map_one

def cast {c d : Cell M} (h : c = d) : c.extension ≃* d.extension := h ▸ MulEquiv.refl _

@[simp] theorem cast_old {c d : Cell M} (h : c = d) (x : M) :
    cast h (c.inclusion x) = d.inclusion x := by subst d; rfl

@[simp] theorem cast_naturalGenerator {c d : Cell M} (h : c = d) (i : ℕ) :
    cast h (c.naturalGenerator i) = d.naturalGenerator i := by subst d; rfl

theorem map_comp (d : Cell M) (f : M ⟶ N) (g : N ⟶ P) :
    (d.map f).map g = d.map (g.comp f) := by
  cases d with
  | inl d =>
    apply congrArg Sum.inl
    exact Probe.ext rfl rfl rfl rfl
  | inr d =>
    apply congrArg Sum.inr
    have hh : (d.prescription.map f.toMonoidHom).map g.toMonoidHom =
        d.prescription.map (g.comp f).toMonoidHom := by
      have hst : ((d.prescription.map f.toMonoidHom).map g.toMonoidHom).start =
          (d.prescription.map (g.comp f).toMonoidHom).start := by
        funext i j
        dsimp only [OverlapPrescription.map]
        cases d.prescription.start i j <;> rfl
      exact congrArg OverlapPrescription.mk hst
    change Merger.mk _ _ _ = Merger.mk _ _ _
    congr 1

/-- Simulating along two conservative maps is the literal simulation along
the composite, after the presentation-theoretic identification. -/
theorem simulation_comp (d : Cell M) (f : M ⟶ N) (g : N ⟶ P) :
    (cast (d.map_comp f g)).toMonoidHom.comp
      (((d.map f).simulation g).toMonoidHom.comp (d.simulation f).toMonoidHom) =
      (d.simulation (g.comp f)).toMonoidHom := by
  apply d.hom_ext
  · intro x
    change cast _ ((d.map f).simulation g (d.simulation f (d.inclusion x))) =
      d.simulation (g.comp f) (d.inclusion x)
    simp only [simulation_old,cast_old,Hom.comp_apply]
  · intro i
    change cast _ ((d.map f).simulation g (d.simulation f (d.naturalGenerator i))) =
      d.simulation (g.comp f) (d.naturalGenerator i)
    simp only [simulation_naturalGenerator,cast_naturalGenerator]

end
end PartitionConsistency.ConservativeMonoids.Cell


/-! ## CellBaseChange -/

/-! A selected cell can be simulated over any conservative intermediate
base. Full monoid pushouts identify the presentations, while explicit cell
simulations prove that the intermediate presentation embeds conservatively. -/
namespace PartitionConsistency.MonoidPushout.IsPushout
universe u
noncomputable section
variable {A B C D : Type u} [Monoid A] [Monoid B] [Monoid C] [Monoid D]
variable {f : A →* B} {g : A →* C} {i : B →* D} {j : C →* D}

theorem generated (h : IsPushout f g i j) (S : Submonoid D)
    (hb : ∀ x, i x ∈ S) (hc : ∀ x, j x ∈ S) : S = ⊤ := by
  let b : B →* S :=
    { toFun := fun x => ⟨i x,hb x⟩
      map_one' := Subtype.ext i.map_one
      map_mul' x y := Subtype.ext (i.map_mul x y) }
  let c : C →* S :=
    { toFun := fun x => ⟨j x,hc x⟩
      map_one' := Subtype.ext j.map_one
      map_mul' x y := Subtype.ext (j.map_mul x y) }
  have hbc : b.comp f = c.comp g := by
    ext x
    exact congrArg (fun m : A →* D => m x) h.comm
  let l := h.lift b c hbc
  have hl : S.subtype.comp l = MonoidHom.id D := by
    apply h.hom_ext
    · rw [MonoidHom.comp_assoc,h.lift_comp_left,MonoidHom.id_comp]; rfl
    · rw [MonoidHom.comp_assoc,h.lift_comp_right,MonoidHom.id_comp]; rfl
  apply top_unique
  intro x _
  have hh := (l x).property
  rwa [show (l x).val = x from DFunLike.congr_fun hl x] at hh
end
end PartitionConsistency.MonoidPushout.IsPushout

namespace PartitionConsistency.ConservativeMonoids
universe u
open CategoryTheory DiagramOrder MonoidPushout
noncomputable section
open scoped Classical

namespace Subobject
variable {T : Object.{u}}

/-- A commutative square of actual inclusions which is a pushout among all
monoids, not merely among conservative maps. -/
structure Square (A B C D : Subobject T) : Prop where
  ab : A.submonoid ≤ B.submonoid
  ac : A.submonoid ≤ C.submonoid
  bd : B.submonoid ≤ D.submonoid
  cd : C.submonoid ≤ D.submonoid
  pushout : IsPushout (hom ab).toMonoidHom (hom ac).toMonoidHom
    (hom bd).toMonoidHom (hom cd).toMonoidHom

namespace Square
variable {A B C D : Subobject T} (h : Square A B C D)

include h in
theorem apex_eq_sup : D.submonoid = B.submonoid ⊔ C.submonoid := by
  apply le_antisymm ?_ (sup_le h.bd h.cd)
  let Q := (B.submonoid ⊔ C.submonoid).comap D.inclusion.toMonoidHom
  have hQ := h.pushout.generated Q
    (fun x => (show B.submonoid ≤ B.submonoid ⊔ C.submonoid from le_sup_left) x.property)
    (fun x => (show C.submonoid ≤ B.submonoid ⊔ C.submonoid from le_sup_right) x.property)
  intro x hx
  exact (show (⟨x,hx⟩ : D.object) ∈ Q from hQ ▸ Submonoid.mem_top _)

include h in
theorem flip : Square A C B D := ⟨h.ac,h.ab,h.cd,h.bd,h.pushout.flip⟩

theorem presentationPushout (d : Attachment A B) :
    IsPushout d.cell.inclusion.toMonoidHom (hom h.ac).toMonoidHom
      ((hom h.bd).toMonoidHom.comp d.equiv.toMonoidHom) (hom h.cd).toMonoidHom := by
  have hp := h.pushout.change_left d.equiv.symm
  have h₁ : d.equiv.symm.toMonoidHom.comp (hom h.ab).toMonoidHom =
      d.cell.inclusion.toMonoidHom := by
    ext x
    apply d.equiv.injective
    simpa only [MonoidHom.comp_apply,MulEquiv.coe_toMonoidHom,d.equiv.apply_symm_apply]
      using! (Subtype.ext (d.old x)).symm
  rw [h₁] at hp
  exact hp

/-- The canonical cell base-change is identified with the given apex by
its universal property. -/
def realization (d : Attachment A B) :
    (d.cell.map (hom h.ac)).extension ≃* D.object :=
  (d.cell.pushout (hom h.ac)).equiv (h.presentationPushout d)

@[simp] theorem realization_old (d : Attachment A B) (x : C.object) :
    (h.realization d ((d.cell.map (hom h.ac)).inclusion x)).val = x.val :=
  congrArg (fun z : D.object => z.val)
    (DFunLike.congr_fun ((d.cell.pushout (hom h.ac)).equiv_comp_right (h.presentationPushout d)) x)

@[simp] theorem realization_new (d : Attachment A B) (x : d.cell.extension) :
    (h.realization d (d.cell.simulation (hom h.ac) x)).val = (d.equiv x).val :=
  congrArg (fun z : D.object => z.val)
    (DFunLike.congr_fun ((d.cell.pushout (hom h.ac)).equiv_comp_left (h.presentationPushout d)) x)

def attachment (d : Attachment A B) : Attachment C D :=
  ⟨d.cell.map (hom h.ac),h.realization d,h.realization_old d⟩

end Square
end Subobject

namespace Hom
variable {M N : Object.{u}} (f : M ⟶ N)

/-- A conservative embedding identifies its domain with its actual range. -/
def rangeEquiv : M ≃* (Subobject.range f).object := by
  let m : M →* (Subobject.range f).object :=
    { toFun := fun x => ⟨f x,⟨x,rfl⟩⟩
      map_one' := Subtype.ext f.map_one
      map_mul' x y := Subtype.ext (f.map_mul x y) }
  exact MulEquiv.ofBijective m
    ⟨fun _ _ h => f.injective (congrArg Subtype.val h),by
      rintro ⟨x,y,hy⟩
      exact ⟨y,Subtype.ext hy⟩⟩

@[simp] theorem rangeEquiv_val (x : M) : (f.rangeEquiv x).val = f x := rfl
end Hom

namespace Subobject.Square
variable {T : Object.{u}} {A B C D E : Subobject T}

/-- Intermediate base change stays inside the original successor. Its
carrier is exactly the submonoid generated by the intermediate base and
the retained successor, not an enlarged conservative hull. -/
theorem intermediate (h : Square A B C D) (d : Attachment A B)
    (ha : A.submonoid ≤ E.submonoid) (hc : E.submonoid ≤ C.submonoid) :
    ∃ F : Subobject T, F.submonoid = B.submonoid ⊔ E.submonoid ∧
      F.submonoid ≤ D.submonoid ∧ Nonempty (Attachment E F) ∧ Square A B E F := by
  let f := hom ha
  let g := hom hc
  have hcomp : g.comp f = hom h.ac := by ext x; rfl
  have heq : (d.cell.map f).map g = d.cell.map (hom h.ac) :=
    (d.cell.map_comp f g).trans (congrArg d.cell.map hcomp)
  let e := h.realization d
  let m := D.inclusion.comp ((ofMulEquiv e).comp
    ((ofMulEquiv (Cell.cast heq)).comp ((d.cell.map f).simulation g)))
  have mo (x : E.object) : m ((d.cell.map f).inclusion x) = x.val := by
    change (e (Cell.cast heq ((d.cell.map f).simulation g ((d.cell.map f).inclusion x)))).val = x.val
    rw [Cell.simulation_old,Cell.cast_old]
    exact h.realization_old d (g x)
  have mn (x : d.cell.extension) : m (d.cell.simulation f x) = (d.equiv x).val := by
    have hn : Cell.cast heq ((d.cell.map f).simulation g (d.cell.simulation f x)) =
        d.cell.simulation (hom h.ac) x := by
      have hh := DFunLike.congr_fun (d.cell.simulation_comp f g) x
      cases hcomp
      exact hh
    change (e (Cell.cast heq ((d.cell.map f).simulation g (d.cell.simulation f x)))).val = _
    rw [hn]
    exact h.realization_new d x
  let F := Subobject.range m
  have hEF : E.submonoid ≤ F.submonoid := by
    intro x hx
    exact ⟨(d.cell.map f).inclusion ⟨x,hx⟩,mo ⟨x,hx⟩⟩
  have hBF : B.submonoid ≤ F.submonoid := by
    intro x hx
    refine ⟨d.cell.simulation f (d.equiv.symm ⟨x,hx⟩),?_⟩
    erw [mn,d.equiv.apply_symm_apply]
  let e' := m.rangeEquiv
  have hp := ((d.cell.pushout f).map_apex e').change_left d.equiv
  have h₁ : d.equiv.toMonoidHom.comp d.cell.inclusion.toMonoidHom =
      (hom h.ab).toMonoidHom := by ext x; apply Subtype.ext; exact d.old x
  have h₂ : (e'.toMonoidHom.comp (d.cell.simulation f).toMonoidHom).comp
      d.equiv.symm.toMonoidHom = (hom hBF).toMonoidHom := by
    ext x
    apply Subtype.ext
    exact (mn (d.equiv.symm x)).trans (congrArg (fun z : B.object => z.val) (d.equiv.apply_symm_apply x))
  have h₃ : e'.toMonoidHom.comp (d.cell.map f).inclusion.toMonoidHom =
      (hom hEF).toMonoidHom := by ext x; apply Subtype.ext; exact mo x
  rw [h₁,h₂,h₃] at hp
  let hs : Square A B E F := ⟨h.ab,ha,hBF,hEF,hp⟩
  refine ⟨F,hs.apex_eq_sup,?_,⟨⟨d.cell.map f,e',mo⟩⟩,hs⟩
  rintro x ⟨y,rfl⟩
  exact (e (Cell.cast heq ((d.cell.map f).simulation g y))).property

end Subobject.Square
end
end PartitionConsistency.ConservativeMonoids

end OAI
