import OAI.Analysis.KadisonSimilarity.Representation.Amplification
import Mathlib.Analysis.Normed.Operator.Extend
import Mathlib.Analysis.InnerProductSpace.Projection.Basic

namespace OAI

/-!
# Cyclic column factorization from equality of vector functionals

Equality of quadratic forms yields an intertwining column contraction.
Existence of a realizing vector is a consequence of standard form.
-/

noncomputable section
namespace KadisonSimilarity

variable {K : Type*} [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]

/-- Equality of the quadratic forms represented by one vector and by a finite
family of vectors, tested on an operator star subalgebra. -/
def VectorQuadraticFormsAgree (N : StarSubalgebra ℂ (K →L[ℂ] K))
    {n : ℕ} (ξ : HilbertCopies K n) (ζ : K) : Prop :=
  ∀ a : N, ‖(a : K →L[ℂ] K) ζ‖ ^ 2 =
    ∑ i : Fin n, ‖(a : K →L[ℂ] K) (ξ i)‖ ^ 2

/-- The linear orbit map at the vector realizing the positive functional. -/
def orbitLinearMap (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K) : N →ₗ[ℂ] K where
  toFun a := (a : K →L[ℂ] K) ζ
  map_add' a b := by simp
  map_smul' c a := by simp

@[simp] theorem orbitLinearMap_apply (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K) (a : N) :
    orbitLinearMap N ζ a = (a : K →L[ℂ] K) ζ := rfl

/-- The corresponding orbit map of the finite family. -/
def columnOrbitLinearMap (N : StarSubalgebra ℂ (K →L[ℂ] K))
    {n : ℕ} (ξ : HilbertCopies K n) : N →ₗ[ℂ] HilbertCopies K n where
  toFun a := amplify (a : K →L[ℂ] K) n ξ
  map_add' a b := by
    apply PiLp.ext
    intro i
    simp
  map_smul' c a := by
    apply PiLp.ext
    intro i
    simp

@[simp] theorem columnOrbitLinearMap_apply (N : StarSubalgebra ℂ (K →L[ℂ] K))
    {n : ℕ} (ξ : HilbertCopies K n) (a : N) (i : Fin n) :
    columnOrbitLinearMap N ξ a i = (a : K →L[ℂ] K) (ξ i) := by
  simp [columnOrbitLinearMap]

/-- The closed cyclic subspace generated by the realizing vector. -/
def orbitClosure (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K) : ClosedSubmodule ℂ K :=
  (LinearMap.range (orbitLinearMap N ζ)).closure

/-- The orbit map with codomain restricted to the closed cyclic subspace. -/
def orbitIntoClosure (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K) :
    N →ₗ[ℂ] orbitClosure N ζ :=
  (orbitLinearMap N ζ).codRestrict (orbitClosure N ζ).toSubmodule fun a =>
    (LinearMap.range (orbitLinearMap N ζ)).le_topologicalClosure ⟨a, rfl⟩

@[simp] theorem orbitIntoClosure_coe (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K) (a : N) :
    (orbitIntoClosure N ζ a : K) = (a : K →L[ℂ] K) ζ := rfl

/-- The algebraic orbit is dense in its closed cyclic subspace. -/
theorem orbitIntoClosure_dense (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K) :
    DenseRange (orbitIntoClosure N ζ) := by
  change Dense (Set.range (orbitIntoClosure N ζ))
  rw [Subtype.dense_iff, ← Set.range_comp]
  change closure (Set.range (orbitLinearMap N ζ)) ⊆
    closure (Set.range (orbitLinearMap N ζ))
  exact Set.Subset.rfl

/-- The closed orbit is invariant under the star subalgebra. -/
theorem orbitClosure_invariant (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K)
    (a : N) (x : K) (hx : x ∈ orbitClosure N ζ) :
    (a : K →L[ℂ] K) x ∈ orbitClosure N ζ := by
  have hmap : Set.MapsTo (a : K →L[ℂ] K)
      (LinearMap.range (orbitLinearMap N ζ) : Set K)
      (LinearMap.range (orbitLinearMap N ζ) : Set K) := by
    rintro y ⟨b, rfl⟩
    refine ⟨a * b, ?_⟩
    simp [mul_apply_eq_comp]
  exact hmap.closure (a : K →L[ℂ] K).continuous hx

/-- The orthogonal projection onto the cyclic subspace commutes with the
star subalgebra. -/
theorem orbitClosure_projection_commutes (N : StarSubalgebra ℂ (K →L[ℂ] K)) (ζ : K)
    (a : N) : Commute (orbitClosure N ζ).toSubmodule.starProjection (a : K →L[ℂ] K) := by
  let M := orbitClosure N ζ
  change M.toSubmodule.starProjection * (a : K →L[ℂ] K) =
    (a : K →L[ℂ] K) * M.toSubmodule.starProjection
  ext x
  apply Submodule.eq_starProjection_of_mem_of_inner_eq_zero
  · exact orbitClosure_invariant N ζ a _ (Submodule.starProjection_apply_mem _ _)
  · intro w hw
    simp only [mul_apply_eq_comp]
    have hadj : (a : K →L[ℂ] K).adjoint = ((star a : N) : K →L[ℂ] K) := rfl
    have hzero : inner ℂ ((a : K →L[ℂ] K) (x - M.toSubmodule.starProjection x)) w = 0 := by
      rw [← ContinuousLinearMap.adjoint_inner_right, hadj]
      exact M.toSubmodule.starProjection_inner_eq_zero x _
        (orbitClosure_invariant N ζ (star a) w hw)
    simpa only [map_sub, ContinuousLinearMap.coe_coe] using hzero

/-- Equality of quadratic forms makes the two orbit maps isometric. -/
theorem columnOrbit_norm_eq (N : StarSubalgebra ℂ (K →L[ℂ] K))
    {n : ℕ} (ξ : HilbertCopies K n) (ζ : K)
    (hforms : VectorQuadraticFormsAgree N ξ ζ) (a : N) :
    ‖columnOrbitLinearMap N ξ a‖ = ‖orbitIntoClosure N ζ a‖ := by
  apply (sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)).mp
  change ‖columnOrbitLinearMap N ξ a‖ ^ 2 = ‖(a : K →L[ℂ] K) ζ‖ ^ 2
  rw [PiLp.norm_sq_eq_of_L2]
  simp only [columnOrbitLinearMap_apply]
  exact (hforms a).symm

/-- Testing the identity gives equality of the norms of the realizing vector
and the finite vector family. -/
theorem norm_eq_of_vectorQuadraticFormsAgree
    (N : StarSubalgebra ℂ (K →L[ℂ] K)) {n : ℕ}
    (ξ : HilbertCopies K n) (ζ : K) (hforms : VectorQuadraticFormsAgree N ξ ζ) :
    ‖ξ‖ = ‖ζ‖ := by
  apply (sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)).mp
  rw [PiLp.norm_sq_eq_of_L2]
  simpa using (hforms 1).symm

/-- Construction of the column contraction from a vector realizing the
finite sum of vector functionals. It vanishes on the orthogonal complement
of the closed orbit of that vector. -/
theorem exists_intertwining_column_contraction
    (N : StarSubalgebra ℂ (K →L[ℂ] K)) {n : ℕ}
    (ξ : HilbertCopies K n) (ζ : K) (hforms : VectorQuadraticFormsAgree N ξ ζ) :
    ∃ V : K →L[ℂ] HilbertCopies K n,
      ‖V‖ ≤ 1 ∧ V ζ = ξ ∧
      (∀ a : N, V.comp (a : K →L[ℂ] K) = (amplify (a : K →L[ℂ] K) n).comp V) ∧
      (∀ x ∈ (orbitClosure N ζ).toSubmodule.orthogonal, V x = 0) := by
  let M := orbitClosure N ζ
  let e := orbitIntoClosure N ζ
  let f := columnOrbitLinearMap N ξ
  have he : DenseRange e := orbitIntoClosure_dense N ζ
  have hn : ∀ a : N, ‖f a‖ = ‖e a‖ := columnOrbit_norm_eq N ξ ζ hforms
  let J : M →ₗᵢ[ℂ] HilbertCopies K n := f.extendOfIsometry he hn
  have hJe (a : N) : J (e a) = f a := LinearMap.extendOfIsometry_eq f he hn a
  let P := M.toSubmodule.orthogonalProjectionOnto
  let V : K →L[ℂ] HilbertCopies K n := J.toContinuousLinearMap.comp P
  have hPe (a : N) : P ((a : K →L[ℂ] K) ζ) = e a := by
    apply Subtype.ext
    change M.toSubmodule.starProjection ((a : K →L[ℂ] K) ζ) =
      (a : K →L[ℂ] K) ζ
    exact Submodule.starProjection_eq_self_iff.mpr (e a).property
  have hJinter (a : N) (x : M) :
      J ⟨(a : K →L[ℂ] K) x, orbitClosure_invariant N ζ a x x.property⟩ =
        amplify (a : K →L[ℂ] K) n (J x) := by
    let R : M →L[ℂ] M := (a : K →L[ℂ] K).restrict (orbitClosure_invariant N ζ a)
    change J (R x) = amplify (a : K →L[ℂ] K) n (J x)
    refine he.induction ?_ (isClosed_eq (J.continuous.comp R.continuous)
      ((amplify (a : K →L[ℂ] K) n).continuous.comp J.continuous)) x
    rintro y ⟨b, rfl⟩
    have hRe : R (e b) = e (a * b) := by
      apply Subtype.ext
      rfl
    rw [hRe, hJe, hJe]
    apply PiLp.ext
    intro i
    simp [f, mul_apply_eq_comp]
  refine ⟨V, ?_, ?_, ?_, ?_⟩
  · apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
    intro x
    change ‖J (P x)‖ ≤ 1 * ‖x‖
    rw [J.norm_map, one_mul]
    exact M.toSubmodule.norm_orthogonalProjectionOnto_apply_le x
  · have hPone : P ζ = e 1 := by simpa using hPe 1
    change J (P ζ) = ξ
    rw [hPone, hJe]
    apply PiLp.ext
    intro i
    simp [f]
  · intro a
    apply ContinuousLinearMap.ext
    intro x
    have hPinter : P ((a : K →L[ℂ] K) x) =
        ⟨(a : K →L[ℂ] K) (P x), orbitClosure_invariant N ζ a _ (P x).property⟩ := by
      apply Subtype.ext
      have h := congrArg (fun T : K →L[ℂ] K => T x)
        (orbitClosure_projection_commutes N ζ a).eq
      change M.toSubmodule.starProjection ((a : K →L[ℂ] K) x) =
        (a : K →L[ℂ] K) (M.toSubmodule.starProjection x)
      simpa only [mul_apply_eq_comp] using h
    change J (P ((a : K →L[ℂ] K) x)) = amplify (a : K →L[ℂ] K) n (J (P x))
    rw [hPinter]
    exact hJinter a (P x)
  · intro x hx
    change J (P x) = 0
    rw [show P x = 0 from M.toSubmodule.orthogonalProjectionOnto_apply_of_mem_orthogonal hx]
    exact map_zero J

/-- The coordinates of a bounded column operator. -/
def columnEntry {n : ℕ} (V : K →L[ℂ] HilbertCopies K n) (i : Fin n) : K →L[ℂ] K :=
  (PiLp.proj 2 (fun _ : Fin n => K) i).comp V

omit [CompleteSpace K] in
@[simp] theorem columnEntry_apply {n : ℕ}
    (V : K →L[ℂ] HilbertCopies K n) (i : Fin n) (x : K) :
    columnEntry V i x = V x i := rfl

/-- Intertwining the diagonal action puts each column entry in the commutant. -/
theorem columnEntry_commutes {n : ℕ} (N : StarSubalgebra ℂ (K →L[ℂ] K))
    (V : K →L[ℂ] HilbertCopies K n)
    (hV : ∀ a : N, V.comp (a : K →L[ℂ] K) = (amplify (a : K →L[ℂ] K) n).comp V)
    (i : Fin n) (a : N) : Commute (columnEntry V i) (a : K →L[ℂ] K) := by
  change columnEntry V i * (a : K →L[ℂ] K) = (a : K →L[ℂ] K) * columnEntry V i
  ext x
  have h := congrArg (fun T : K →L[ℂ] HilbertCopies K n => T x i) (hV a)
  simpa only [mul_apply_eq_comp, columnEntry_apply, ContinuousLinearMap.comp_apply,
    amplify_apply] using h

/-- The column factorization needed in the manuscript once the realizing
vector for the commutant has been supplied. -/
theorem exists_column_factorization_of_vector_realization
    (P : VonNeumannAlgebra K) {n : ℕ} (ξ : HilbertCopies K n) (ζ : K)
    (hforms : VectorQuadraticFormsAgree P.commutant.toStarSubalgebra ξ ζ) :
    ∃ V : K →L[ℂ] HilbertCopies K n,
      ‖V‖ ≤ 1 ∧ V ζ = ξ ∧ ∀ i : Fin n, columnEntry V i ∈ P := by
  obtain ⟨V, hnorm, hζ, hV, _⟩ :=
    exists_intertwining_column_contraction P.commutant.toStarSubalgebra ξ ζ hforms
  refine ⟨V, hnorm, hζ, ?_⟩
  intro i
  rw [← P.commutant_commutant, VonNeumannAlgebra.mem_commutant_iff]
  intro a ha
  exact (columnEntry_commutes P.commutant.toStarSubalgebra V hV i ⟨a, ha⟩).symm.eq

end KadisonSimilarity

end

end OAI
