import OAI.Analysis.KadisonSimilarity.Similarity.SimilarityMetric
import OAI.Analysis.KadisonSimilarity.Derivation.Derivations

namespace OAI

/-! # The reducing space generated by a homomorphism factorization

Only the vectors generated by the right factor are needed. Multiplicativity
makes the left factor an intertwiner on this closed span. Its kernel is then
a reducing subspace, which is the geometric input to invertible similarity.
-/

noncomputable section
namespace KadisonSimilarity
open ContinuousLinearMap

variable {A H K : Type*} [CStarAlgebra A]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]

/-- The closed cyclic span of the range of the right factor. -/
def factorizationSpace (σ : A →⋆ₐ[ℂ] (K →L[ℂ] K)) (W : H →L[ℂ] K) :
    ClosedSubmodule ℂ K :=
  (Submodule.span ℂ (Set.range fun p : A × H => σ p.1 (W p.2))).closure

theorem right_mem_factorizationSpace (σ : A →⋆ₐ[ℂ] (K →L[ℂ] K))
    (W : H →L[ℂ] K) (x : H) : W x ∈ factorizationSpace σ W := by
  apply (Submodule.span ℂ _).le_topologicalClosure
  apply Submodule.subset_span
  exact ⟨(1, x), by simp⟩

/-- The generating space is invariant under the whole star representation. -/
theorem factorizationSpace_invariant (σ : A →⋆ₐ[ℂ] (K →L[ℂ] K))
    (W : H →L[ℂ] K) (a : A) (x : K) (hx : x ∈ factorizationSpace σ W) :
    σ a x ∈ factorizationSpace σ W := by
  let N := Submodule.span ℂ (Set.range fun p : A × H => σ p.1 (W p.2))
  have hi : N ≤ N.comap (σ a).toLinearMap := by
    apply Submodule.span_le.mpr
    rintro _ ⟨⟨b, y⟩, rfl⟩
    apply Submodule.subset_span
    exact ⟨(a * b, y), by simp only [map_mul, mul_apply_eq_comp]; rfl⟩
  have hm : Set.MapsTo (σ a) (N : Set K) (N : Set K) := fun _ hy => hi hy
  exact hm.closure (σ a).continuous hx

/-- The left factor intertwines on the closed cyclic span, by continuity
from the algebraic generators and multiplicativity of the homomorphism. -/
theorem left_intertwines_factorizationSpace (π : BoundedUnitalHom A H)
    (σ : A →⋆ₐ[ℂ] (K →L[ℂ] K)) (W : H →L[ℂ] K) (L : K →L[ℂ] H)
    (hf : ∀ a, L.comp ((σ a).comp W) = π.1 a)
    (a : A) (x : K) (hx : x ∈ factorizationSpace σ W) :
    L (σ a x) = π.1 a (L x) := by
  let D := L.comp (σ a) - (π.1 a).comp L
  have hs : Submodule.span ℂ (Set.range fun p : A × H => σ p.1 (W p.2)) ≤
      D.ker := by
    apply Submodule.span_le.mpr
    rintro _ ⟨⟨b, y⟩, rfl⟩
    change L (σ a (σ b (W y))) - π.1 a (L (σ b (W y))) = 0
    have hab := congrArg (fun T : H →L[ℂ] H => T y) (hf (a * b))
    have hb := congrArg (fun T : H →L[ℂ] H => T y) (hf b)
    simp only [map_mul, comp_apply, mul_apply_eq_comp] at hab hb
    rw [hab, hb]
    exact sub_self _
  have hc : closure (Submodule.span ℂ
      (Set.range fun p : A × H => σ p.1 (W p.2)) : Set K) ⊆ (D.ker : Set K) :=
    closure_minimal hs D.isClosed_ker
  exact sub_eq_zero.mp (hc hx)

end KadisonSimilarity

end

end OAI
