import OAI.GroupTheory.FiniteLattice.CorePreimage
import OAI.GroupTheory.FiniteLattice.GeneratedNormality

namespace OAI

namespace FiniteLattice.CommonCore
variable {K H : Type*} [Group K] [Group H]

/-- Normality inside a subgroup gives ambient normalization by that subgroup. -/
theorem normal_image_normalized (U : Subgroup K) (B : Subgroup U) [B.Normal] :
    U ≤ Subgroup.normalizer ((B.map U.subtype) : Set K) := by
  apply Subgroup.le_normalizer_iff.mpr
  intro u hu b hb
  obtain ⟨b, hb, rfl⟩ := hb
  exact ⟨(⟨u, hu⟩ : U) * b * (⟨u, hu⟩ : U)⁻¹,
    (inferInstance : B.Normal).conj_mem b hb ⟨u, hu⟩, rfl⟩

theorem normal_of_image_normalized (A : Subgroup K) (C : Subgroup A)
    (h : A ≤ Subgroup.normalizer ((C.map A.subtype) : Set K)) : C.Normal := by
  refine ⟨?_⟩
  intro c hc a
  have ht := Subgroup.le_normalizer_iff.mp h a.val a.property c.val
    (show c.val ∈ C.map A.subtype from ⟨c, hc, rfl⟩)
  obtain ⟨b, hb, he⟩ := ht
  have he' : b = a * c * a⁻¹ := Subtype.val_injective he
  exact he' ▸ hb

/-- The core of `A` in `U`, pulled back to a subgroup of `A`. -/
def relativeCore (A U : Subgroup K) : Subgroup A :=
  ((A.subgroupOf U).normalCore.map U.subtype).comap A.subtype

theorem relativeCore_image (A U : Subgroup K) :
    (relativeCore A U).map A.subtype = (A.subgroupOf U).normalCore.map U.subtype := by
  apply le_antisymm
  · rintro _ ⟨a, ha, rfl⟩
    exact ha
  · rintro _ ⟨u, hu, rfl⟩
    have hua : (u : K) ∈ A := (A.subgroupOf U).normalCore_le hu
    exact ⟨⟨u, hua⟩, ⟨u, hu, rfl⟩, rfl⟩

theorem relativeCore_normalized (A U : Subgroup K) :
    U ≤ Subgroup.normalizer (((relativeCore A U).map A.subtype) : Set K) := by
  rw [relativeCore_image]
  exact normal_image_normalized U (A.subgroupOf U).normalCore

theorem relativeCore_normal (A U : Subgroup K) (hAU : A ≤ U) :
    (relativeCore A U).Normal :=
  normal_of_image_normalized A _ (hAU.trans (relativeCore_normalized A U))

/-- Restriction of a homomorphism determines its conjugation equation on `A`. -/
theorem restriction_conjugation (A U : Subgroup K) (hAU : A ≤ U)
    (f : A →* H) (beta : U →* H)
    (hext : ∀ a : A, beta (Subgroup.inclusion hAU a) = f a)
    (u : U) (a b : A) (hb : (b : K) = u * (a : K) * (u : K)⁻¹) :
    f b = beta u * f a * (beta u)⁻¹ := by
  have he : Subgroup.inclusion hAU b =
      u * Subgroup.inclusion hAU a * u⁻¹ := Subtype.ext hb
  rw [← hext b, he, map_mul, map_mul, map_inv, hext a]

/-- The least normal preimage is normalized by each extension domain whose relative core
maps over the prescribed perfect subgroup. -/
theorem canonical_preimage_normalized_by_local
    (A U : Subgroup K) [Finite A] (hAU : A ≤ U)
    (f : A →* H) (beta : U →* H)
    (hext : ∀ a : A, beta (Subgroup.inclusion hAU a) = f a)
    (J : Subgroup H) [J.Normal] [Group.IsPerfect J]
    (Q : Subgroup A) [Q.Normal] (hQ : Q.map f = J)
    (hminQ : ∀ B : Subgroup A, B.Normal → J ≤ B.map f → Q ≤ B)
    (hcore : J ≤ (relativeCore A U).map f) :
    U ≤ Subgroup.normalizer ((Q.map A.subtype) : Set K) := by
  let C := relativeCore A U
  let : C.Normal := relativeCore_normal A U hAU
  have hrange : J ≤ (f.comp C.subtype).range := by
    intro y hy
    obtain ⟨x, hx, hxy⟩ := hcore hy
    exact ⟨⟨x, hx⟩, hxy⟩
  obtain ⟨B, hBN, hB, hminB⟩ :=
    FiniteLattice.exists_least_normal_perfect_preimage (f.comp C.subtype) J hrange
  let : B.Normal := hBN
  have hBQ : B.map C.subtype = Q :=
    least_image_inside_normal_eq f J Q hQ hminQ C hcore B hB hminB
  apply Subgroup.le_normalizer_iff.mpr
  intro u hu q hq
  obtain ⟨q, hq, rfl⟩ := hq
  rw [← hBQ] at hq
  obtain ⟨b, hb, rfl⟩ := hq
  let a : C ≃* C := FiniteLattice.RetainedCore.embeddedConj C A.subtype
    Subtype.val_injective u (relativeCore_normalized A U hu)
  have ha (z : C) : A.subtype (a z : A) =
      u * A.subtype (z : A) * u⁻¹ :=
    FiniteLattice.RetainedCore.embeddedConj_val C A.subtype
      Subtype.val_injective u _ z
  have hc : ∀ z : C, (f.comp C.subtype) (a z) =
      MulAut.conj (beta ⟨u, hu⟩) ((f.comp C.subtype) z) := by
    intro z
    exact restriction_conjugation A U hAU f beta hext ⟨u, hu⟩ z (a z) (ha z)
  have hj : ∀ y ∈ J, MulAut.conj (beta ⟨u, hu⟩) y ∈ J :=
    fun y hy => (inferInstance : J.Normal).conj_mem y hy (beta ⟨u, hu⟩)
  have hab : a b ∈ B := least_image_stable (f.comp C.subtype) J B hB hminB
    a (MulAut.conj (beta ⟨u, hu⟩)) hj hc b hb
  refine ⟨(a b : A), ?_, ha b⟩
  rw [← hBQ]
  exact ⟨a b, hab, rfl⟩

/-- The common least preimage and its intersection with the kernel are normal
in the group generated by the extension domains. -/
theorem exists_common_normal_preimage [Finite K] {ι : Type*} [Nonempty ι]
    (A : Subgroup K) (U : ι → Subgroup K) (hAU : ∀ i, A ≤ U i)
    (hgen : (⨆ i, U i) = ⊤) (f : A →* H) (beta : ∀ i, U i →* H)
    (hext : ∀ i, ∀ a : A, beta i (Subgroup.inclusion (hAU i) a) = f a)
    (J : Subgroup H) [J.Normal] [Group.IsPerfect J]
    (hcore : ∀ i, J ≤ (relativeCore A (U i)).map f) :
    ∃ Q : Subgroup A, Q.Normal ∧ Q.map f = J ∧
      (Q.map A.subtype).Normal ∧ ((Q ⊓ f.ker).map A.subtype).Normal ∧
      (∀ i, U i ≤ Subgroup.normalizer ((Q.map A.subtype) : Set K)) := by
  classical
  obtain ⟨i⟩ := ‹Nonempty ι›
  have hrange : J ≤ f.range := by
    intro y hy
    obtain ⟨a, _, ha⟩ := hcore i hy
    exact ⟨a, ha⟩
  obtain ⟨Q, hQN, hQ, hminQ⟩ :=
    FiniteLattice.exists_least_normal_perfect_preimage f J hrange
  let : Q.Normal := hQN
  have hnorm (j : ι) : U j ≤ Subgroup.normalizer ((Q.map A.subtype) : Set K) :=
    canonical_preimage_normalized_by_local A (U j) (hAU j) f (beta j)
      (hext j) J Q hQ hminQ (hcore j)
  have hQKN := GeneratedNormality.normal_of_generating_family U hgen _ hnorm
  have hLnorm (j : ι) : U j ≤ Subgroup.normalizer (((Q ⊓ f.ker).map A.subtype) : Set K) := by
    apply Subgroup.le_normalizer_iff.mpr
    intro u hu x hx
    obtain ⟨a, ha, rfl⟩ := hx
    have ht := Subgroup.le_normalizer_iff.mp (hnorm j) u hu a.val
      (show a.val ∈ Q.map A.subtype from ⟨a, ha.1, rfl⟩)
    obtain ⟨b, hb, hbe⟩ := ht
    refine ⟨b, ⟨hb, ?_⟩, hbe⟩
    change f b = 1
    rw [restriction_conjugation A (U j) (hAU j) f (beta j) (hext j)
      ⟨u, hu⟩ a b hbe]
    have hfa : f a = 1 := ha.2
    rw [hfa, mul_one, mul_inv_cancel]
  exact ⟨Q, hQN, hQ, hQKN,
    GeneratedNormality.normal_of_generating_family U hgen _ hLnorm, hnorm⟩

end FiniteLattice.CommonCore

end OAI
