import Mathlib
import OAI.Computability.QuantumFactoring.RationalTemplateEmission

namespace OAI



section
namespace ExactQuantumFactoring.NetworkEmission
open BitStackProgram BitStackProgram.Emits Emits
variable {α v : Type} {ea : α→List Bool} {ev : v→List Bool}
/-- A fixed polynomial syntax skeleton transports literal coefficient emitters
through substitution. The outer polynomial's depth is fixed; input coefficients
are generated by the supplied charged Boolean-stack procedures. -/
def PolyEmits (ea : α→List Bool) (ev : v→List Bool) (f : α→PolyExpr v) : Prop:=
  ∀(g : α→PolyExpr v), (∀k,BitStackProgram.Emits ea (ratExprCode ev) (fun x=>(g x).coeff k))→
    ∀k,BitStackProgram.Emits ea (ratExprCode ev) (fun x=>((f x).comp (g x)).coeff k)
namespace PolyEmits
lemma C {f : α→RatExpr v} (hf : BitStackProgram.Emits ea (ratExprCode ev) f) :
    PolyEmits ea ev (fun x=>PolyExpr.C (f x)):=by
  intro g hg k;change BitStackProgram.Emits _ _ (fun x=>if k=0 then f x else RatExpr.const 0)
  by_cases h:k=0
  · simpa only [ite_eq_left h] using hf
  · simpa only [ite_eq_right h] using (const ea (ratExprCode ev) (RatExpr.const 0))
lemma X : PolyEmits ea ev (fun _=>PolyExpr.X):=by intro g hg k;exact hg k
lemma add {f g : α→PolyExpr v} (hf : PolyEmits ea ev f) (hg : PolyEmits ea ev g) :
    PolyEmits ea ev (fun x=>PolyExpr.add (f x) (g x)):=by
  intro b hb k;exact rAdd (hf b hb k) (hg b hb k)
lemma neg {f : α→PolyExpr v} (hf : PolyEmits ea ev f) :
    PolyEmits ea ev (fun x=>PolyExpr.negation (f x)):=by
  intro b hb k;exact rNeg (hf b hb k)
lemma sub {f g : α→PolyExpr v} (hf : PolyEmits ea ev f) (hg : PolyEmits ea ev g) :
    PolyEmits ea ev (fun x=>PolyExpr.sub (f x) (g x)):=hf.add hg.neg
lemma mul {f g : α→PolyExpr v} (hf : PolyEmits ea ev f) (hg : PolyEmits ea ev g) :
    PolyEmits ea ev (fun x=>PolyExpr.mul (f x) (g x)):=by
  intro b hb k;exact rSum (fun i=>rMul (hf b hb i) (hg b hb (k-i))) (k+1)
lemma constant (q : ℚ) : PolyEmits ea ev (fun _=>PolyExpr.const q):=C (const _ _ (RatExpr.const q))
lemma pow {f : α→PolyExpr v} (hf : PolyEmits ea ev f) (k : ℕ) :
    PolyEmits ea ev (fun x=>PolyExpr.pow (f x) k):=by
  induction k with
  | zero=>exact constant 1
  | succ k ih=>exact ih.mul hf
lemma literal (p : PolyExpr v) : PolyEmits ea ev (fun _=>p):=by
  induction p with
  | C r=>exact C (const _ _ r)
  | X=>exact X
  | add a b ha hb=>exact ha.add hb
  | negation a ha=>exact ha.neg
  | mul a b ha hb=>exact ha.mul hb
lemma comp_comp (a b c : PolyExpr v) : (a.comp b).comp c=a.comp (b.comp c):=by
  induction a with
  | C r=>rfl
  | X=>rfl
  | add a b ha hb=>simp only [PolyExpr.comp,ha,hb]
  | negation a ha=>simp only [PolyExpr.comp,ha]
  | mul a b ha hb=>simp only [PolyExpr.comp,ha,hb]
lemma comp {f g : α→PolyExpr v} (hf : PolyEmits ea ev f) (hg : PolyEmits ea ev g) :
    PolyEmits ea ev (fun x=>(f x).comp (g x)):=by
  intro b hb k
  exact (hf (fun x=>(g x).comp (b x)) (hg b hb) k).congr (by intro x;rw [comp_comp])
lemma comp_X (a : PolyExpr v) : a.comp .X=a:=by
  induction a with
  | C r=>rfl
  | X=>rfl
  | add a b ha hb=>simp only [PolyExpr.comp,ha,hb]
  | negation a ha=>simp only [PolyExpr.comp,ha]
  | mul a b ha hb=>simp only [PolyExpr.comp,ha,hb]
lemma coeff {f : α→PolyExpr v} (hf : PolyEmits ea ev f) (k : ℕ) :
    BitStackProgram.Emits ea (ratExprCode ev) (fun x=>(f x).coeff k):=
  (hf (fun _=>.X) (fun i=>const _ _ (PolyExpr.coeff .X i)) k).congr (by intro x;rw [comp_X])
end PolyEmits
end ExactQuantumFactoring.NetworkEmission
namespace ExactQuantumFactoring
syntax "poly_emit" : tactic
macro_rules
  | `(tactic| poly_emit) => `(tactic|
    with_reducible_and_instances first
    | assumption
    | exact NetworkEmission.PolyEmits.X
    | exact NetworkEmission.PolyEmits.constant _
    | (apply NetworkEmission.PolyEmits.add <;> poly_emit)
    | (apply NetworkEmission.PolyEmits.sub <;> poly_emit)
    | (apply NetworkEmission.PolyEmits.mul <;> poly_emit)
    | (apply NetworkEmission.PolyEmits.neg;poly_emit)
    | (apply NetworkEmission.PolyEmits.pow;poly_emit)
    | (apply NetworkEmission.PolyEmits.comp <;> poly_emit)
    | (apply NetworkEmission.PolyEmits.C;rat_emit))
end ExactQuantumFactoring

end


end OAI
