import OAI.NumberTheory.DukePrimeDegree.Arithmetic.CyclicAverages
import OAI.NumberTheory.DukePrimeDegree.Arithmetic.StarkOddDegree

namespace OAI

/-!
# Gluing the real characters selected by a simple zeta zero

A zero-order function on subgroups determines each cyclic restriction by
its values on the subgroups generated by single elements. Conjugacy of
these orders then gives precisely the class function used in odd-degree
descent. No global irreducible-character decomposition is needed.
-/

noncomputable section
open scoped BigOperators Classical

namespace DukePrimeDegree

variable {G : Type*} [Group G] [Finite G]

/-- The sign detected by the zero order of the cyclic fixed field. -/
def cyclicZeroSign (m : Subgroup G → ℤ) (g : G) : ℝˣ :=
  if m (Subgroup.zpowers g) = 1 then 1 else -1

theorem cyclicZeroSign_eq_character
    (m : Subgroup G → ℤ) (C : Subgroup G) (χ : C →* ℝˣ)
    (hχ : ∀ x : C, m (Subgroup.zpowers (x : G)) = if χ x = 1 then 1 else 0)
    (x : C) : cyclicZeroSign m (x : G) = χ x := by
  unfold cyclicZeroSign
  rw [hχ]
  by_cases hx : χ x = 1
  · simp [hx]
  · have hv := PrimeDegreePackets.realFiniteCharacter_values χ x
    rcases hv with hv | hv
    · exact False.elim (hx hv)
    · simp only [hx, ite_false, zero_ne_one]
      exact hv.symm

theorem cyclicZeroSign_cyclic_restriction
    (m : Subgroup G → ℤ)
    (hcyclic : ∀ C : Subgroup G, IsCyclic C → ∃ χ : C →* ℝˣ,
      ∀ x : C, m (Subgroup.zpowers (x : G)) = if χ x = 1 then 1 else 0)
    (g : G) : ∃ χ : Subgroup.zpowers g →* ℝˣ,
      ∀ x : Subgroup.zpowers g, χ x = cyclicZeroSign m (x : G) := by
  obtain ⟨χ, hχ⟩ := hcyclic (Subgroup.zpowers g) inferInstance
  exact ⟨χ, fun x => (cyclicZeroSign_eq_character m _ χ hχ x).symm⟩

omit [Finite G] in
theorem cyclicZeroSign_conjugate
    (m : Subgroup G → ℤ)
    (hconj : ∀ (C : Subgroup G) (a : G), m (C.map (MulAut.conj a).toMonoidHom) = m C)
    (a g : G) : cyclicZeroSign m (a * g * a⁻¹) = cyclicZeroSign m g := by
  have hmap : (Subgroup.zpowers g).map (MulAut.conj a).toMonoidHom =
      Subgroup.zpowers (a * g * a⁻¹) := by
    rw [MonoidHom.map_zpowers]
    rfl
  unfold cyclicZeroSign
  rw [← hmap, hconj]

/-- The average of a finite real character detects its being principal. -/
theorem sum_realLinearCharacter {C : Type*} [Group C] [Fintype C]
    (χ : C →* ℝˣ) :
    (∑ g, (χ g : ℝ)) = if χ = 1 then (Fintype.card C : ℝ) else 0 := by
  by_cases hχ : χ = 1
  · simp [hχ]
  · simp only [hχ, ite_false]
    obtain ⟨a, ha⟩ : ∃ a, χ a ≠ 1 := by
      by_contra! h
      apply hχ
      exact MonoidHom.ext (fun a => by simpa using h a)
    have hval : (χ a : ℝ) ≠ 1 := fun h => ha (Units.ext h)
    have hs : (χ a : ℝ) * (∑ g, (χ g : ℝ)) = ∑ g, (χ g : ℝ) := by
      simp only [Finset.mul_sum, ← Units.val_mul, ← map_mul]
      exact Fintype.sum_equiv (Equiv.mulLeft a) _ _ (fun _ => rfl)
    by_contra hs0
    exact hval ((mul_eq_right₀ hs0).mp hs)

theorem sum_cyclicZeroSign
    (m : Subgroup G → ℤ) (C : Subgroup G) [Fintype C] (χ : C →* ℝˣ)
    (hχ : ∀ x : C, m (Subgroup.zpowers (x : G)) = if χ x = 1 then 1 else 0)
    (hC : m C = if χ = 1 then 1 else 0) :
    (∑ g : C, (cyclicZeroSign m (g : G) : ℝ)) = Fintype.card C * (m C : ℝ) := by
  simp_rw [cyclicZeroSign_eq_character m C χ hχ]
  rw [sum_realLinearCharacter, hC]
  split_ifs <;> simp

/-- The scalar form of cyclic indicator inversion for real observables. -/
theorem sum_real_eq_cyclic_sums
    {G : Type*} [Group G] [Fintype G]
    (a : CyclicSubgroups G → ℤ)
    (ha : ∀ g : G, (∑ C, if g ∈ C.val then a C else 0) = 1)
    (f : G → ℝ) :
    (∑ g, f g) = ∑ C : CyclicSubgroups G, (a C : ℝ) * ∑ g : C.val, f g := by
  have hcast (g : G) : (∑ C : CyclicSubgroups G,
      if g ∈ C.val then (a C : ℝ) else 0) = 1 := by
    exact_mod_cast ha g
  calc
    (∑ g, f g) = ∑ g, f g *
        (∑ C : CyclicSubgroups G, if g ∈ C.val then (a C : ℝ) else 0) := by
      simp only [hcast, mul_one]
    _ = ∑ C : CyclicSubgroups G, (a C : ℝ) *
        ∑ g : G, if g ∈ C.val then f g else 0 := by
      simp only [Finset.mul_sum]
      rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro C _
      apply Finset.sum_congr rfl
      intro g _
      split_ifs <;> simp [mul_comm]
    _ = _ := by
      apply Finset.sum_congr rfl
      intro C _
      congr 1
      rw [← Finset.sum_filter]
      exact Finset.sum_subtype _ (by simp) f

/-- Once the cyclic averages recover the subgroup order, odd-index descent
forces all signs to be principal. -/
theorem cyclicZeroSign_trivial_of_odd_average
    (m : Subgroup G → ℤ)
    (hconj : ∀ (C : Subgroup G) (a : G), m (C.map (MulAut.conj a).toMonoidHom) = m C)
    (hcyclic : ∀ C : Subgroup G, IsCyclic C → ∃ χ : C →* ℝˣ,
      ∀ x : C, m (Subgroup.zpowers (x : G)) = if χ x = 1 then 1 else 0)
    (H : Subgroup G) [Fintype H] (hodd : Odd H.index)
    (havg : ∑ h : H, (cyclicZeroSign m (h : G) : ℝ) = Fintype.card H) :
    ∀ g, cyclicZeroSign m g = 1 :=
  cyclic_real_classFunction_trivial_of_odd_average _
    (cyclicZeroSign_conjugate m hconj)
    (cyclicZeroSign_cyclic_restriction m hcyclic) H hodd havg

end DukePrimeDegree

end

end OAI
