import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Algebra.BigOperators.Group.List.Basic
import Mathlib.Topology.MetricSpace.Basic

namespace OAI

/-!
# Packing estimates and intrinsic word balls

This is the finite counting step in Lemma `height-kernel-growth` of
*Quasi-isometric recognition of virtually polycyclic groups*. A metric cover of
orbit points and a bound on the number of source points in a small target ball
give a cardinal bound on the original finite set. Applying this to intrinsic
word balls does not require the subgroup to be undistorted in an ambient group.
-/

namespace PolycyclicRecognition

universe u v

section Packing

variable {H : Type u} {X : Type v} [PseudoMetricSpace X]

/-- Count a finite set using a finite metric-ball cover and bounds on each fiber
of the cover. The balls may overlap. -/
theorem card_le_cover_mul [DecidableEq H] [DecidableEq X]
    (S : Finset H) (f : H → X) (centers : Finset X) (radius : ℝ) (M : ℕ)
    (hcover : ∀ h ∈ S, ∃ c ∈ centers, dist (f h) c ≤ radius)
    (hfiber : ∀ c ∈ centers, (S.filter fun h => dist (f h) c ≤ radius).card ≤ M) :
    S.card ≤ centers.card * M := by
  classical
  have hsubset : S ⊆ centers.biUnion (fun c => S.filter fun h => dist (f h) c ≤ radius) := by
    intro h hh
    obtain ⟨c, hc, hdist⟩ := hcover h hh
    exact Finset.mem_biUnion.mpr ⟨c, hc, Finset.mem_filter.mpr ⟨hh, hdist⟩⟩
  exact (Finset.card_le_card hsubset).trans
    (Finset.card_biUnion_le_card_mul centers _ M hfiber)

/-- A uniform bound on all finite subsets lying over a target ball can be used
for every finite source set. -/
theorem card_le_cover_mul_of_bounded_multiplicity [DecidableEq H] [DecidableEq X]
    (S : Finset H) (f : H → X) (centers : Finset X) (radius : ℝ) (M : ℕ)
    (hcover : ∀ h ∈ S, ∃ c ∈ centers, dist (f h) c ≤ radius)
    (hmultiplicity : ∀ (c : X) (A : Finset H),
      (∀ h ∈ A, dist (f h) c ≤ radius) → A.card ≤ M) :
    S.card ≤ centers.card * M := by
  apply card_le_cover_mul S f centers radius M hcover
  intro c _
  apply hmultiplicity c
  intro h hh
  exact (Finset.mem_filter.mp hh).2

/-- Passing to an injectively embedded subgroup preserves the same multiplicity
bound, independently of distortion of word metrics. -/
theorem boundedMultiplicity_comp_of_injective {J : Type*}
    [DecidableEq J] [DecidableEq H]
    (embedding : J → H) (hinjective : Function.Injective embedding)
    (f : H → X) (radius : ℝ) (M : ℕ)
    (hmultiplicity : ∀ (c : X) (A : Finset H),
      (∀ h ∈ A, dist (f h) c ≤ radius) → A.card ≤ M) :
    ∀ (c : X) (A : Finset J),
      (∀ j ∈ A, dist (f (embedding j)) c ≤ radius) → A.card ≤ M := by
  intro c A hA
  have hbound := hmultiplicity c (A.image embedding) (fun h hh => by
    obtain ⟨j, hj, rfl⟩ := Finset.mem_image.mp hh
    exact hA j hj)
  simpa only [Finset.card_image_of_injective A hinjective] using hbound

end Packing

section WordBalls

variable {H : Type u} [Monoid H] [DecidableEq H]

/-- Products of at most `n` letters from `T`. Choosing `T` symmetric gives the
usual intrinsic word ball of radius `n` in the subgroup generated by `T`. -/
def wordBall (T : Finset H) : ℕ → Finset H
  | 0 => {1}
  | n + 1 => wordBall T n ∪ T.biUnion (fun t => (wordBall T n).image (t * ·))

@[simp]
theorem wordBall_zero (T : Finset H) : wordBall T 0 = {1} := rfl

/-- The identity is represented by the empty word at every radius. -/
theorem one_mem_wordBall (T : Finset H) (n : ℕ) : 1 ∈ wordBall T n := by
  induction n with
  | zero => simp [wordBall]
  | succ n ih => exact Finset.mem_union_left _ ih

/-- This explicit list characterization identifies the recursive finite sets
with intrinsic word balls, rather than with ambient metric balls. -/
theorem mem_wordBall_iff (T : Finset H) (n : ℕ) (h : H) :
    h ∈ wordBall T n ↔ ∃ l : List H,
      l.length ≤ n ∧ (∀ t ∈ l, t ∈ T) ∧ l.prod = h := by
  induction n generalizing h with
  | zero =>
      constructor
      · intro hh
        have hh1 : h = 1 := Finset.mem_singleton.mp hh
        exact ⟨[], by simp, by simp, by simpa using hh1.symm⟩
      · rintro ⟨l, hl, _, hprod⟩
        have hl0 : l = [] := List.length_eq_zero_iff.mp (Nat.eq_zero_of_le_zero hl)
        subst l
        simpa only [List.prod_nil, wordBall_zero, Finset.mem_singleton] using hprod.symm
  | succ n ih =>
      constructor
      · intro hh
        rcases Finset.mem_union.mp hh with hh | hh
        · obtain ⟨l, hl, hletters, hprod⟩ := (ih h).mp hh
          exact ⟨l, hl.trans (Nat.le_succ n), hletters, hprod⟩
        · obtain ⟨t, ht, hrest⟩ := Finset.mem_biUnion.mp hh
          obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hrest
          obtain ⟨l, hl, hletters, hprod⟩ := (ih k).mp hk
          refine ⟨t :: l, by simpa using Nat.succ_le_succ hl, ?_, ?_⟩
          · intro a ha
            rcases List.mem_cons.mp ha with rfl | ha
            · exact ht
            · exact hletters a ha
          · simp only [List.prod_cons, hprod]
      · rintro ⟨l, hl, hletters, hprod⟩
        cases l with
        | nil =>
            have hh1 : h = 1 := hprod.symm
            subst h
            exact one_mem_wordBall T (n + 1)
        | cons t l =>
            have hl' : l.length ≤ n := by simpa using hl
            have ht : t ∈ T := hletters t (List.mem_cons_self ..)
            have hletters' : ∀ a ∈ l, a ∈ T :=
              fun a ha => hletters a (List.mem_cons_of_mem t ha)
            have htail : l.prod ∈ wordBall T n := (ih l.prod).mpr ⟨l, hl', hletters', rfl⟩
            apply Finset.mem_union_right
            apply Finset.mem_biUnion.mpr
            refine ⟨t, ht, Finset.mem_image.mpr ⟨l.prod, htail, ?_⟩⟩
            simpa only [List.prod_cons] using hprod

/-- Every shorter intrinsic word ball is contained in the next one. -/
theorem wordBall_subset_succ (T : Finset H) (n : ℕ) :
    wordBall T n ⊆ wordBall T (n + 1) :=
  Finset.subset_union_left

variable {X : Type v} [PseudoMetricSpace X] [DecidableEq X]

/-- A cover of an intrinsic word ball bounds its cardinality with no hypothesis
relating intrinsic word length to an ambient word length. -/
theorem wordBall_card_le_cover_mul (T : Finset H) (f : H → X) (n : ℕ)
    (centers : Finset X) (M : ℕ)
    (hcover : ∀ h ∈ wordBall T n, ∃ c ∈ centers, dist (f h) c ≤ 1)
    (hmultiplicity : ∀ (c : X) (A : Finset H),
      (∀ h ∈ A, dist (f h) c ≤ 1) → A.card ≤ M) :
    (wordBall T n).card ≤ centers.card * M :=
  card_le_cover_mul_of_bounded_multiplicity (wordBall T n) f centers 1 M hcover hmultiplicity

/-- Polynomially many covering balls and bounded multiplicity give polynomial
intrinsic word growth. All constants are independent of the word radius. -/
theorem wordBall_polynomial_card_bound (T : Finset H) (f : H → X)
    (C b M : ℕ) (centers : ℕ → Finset X)
    (hcenters : ∀ n, (centers n).card ≤ C * (1 + n) ^ b)
    (hcover : ∀ n h, h ∈ wordBall T n → ∃ c ∈ centers n, dist (f h) c ≤ 1)
    (hmultiplicity : ∀ (c : X) (A : Finset H),
      (∀ h ∈ A, dist (f h) c ≤ 1) → A.card ≤ M) :
    ∀ n, (wordBall T n).card ≤ (C * M) * (1 + n) ^ b := by
  intro n
  calc
    (wordBall T n).card ≤ (centers n).card * M :=
      wordBall_card_le_cover_mul T f n (centers n) M (hcover n) hmultiplicity
    _ ≤ (C * (1 + n) ^ b) * M := Nat.mul_le_mul_right M (hcenters n)
    _ = (C * M) * (1 + n) ^ b := by ac_rfl

end WordBalls

end PolycyclicRecognition

end OAI
